### ISSUE TITLE
Example for using Node_redis library to push Data in Tile38 DB

### ISSUE THREAD

**Issue by shailesh17mar** [tidwall/tile38#100]
Hi, I am trying to test out tile38 for my new project and due to lack of documentation I am facing trouble about how to go about pushing a sample dataset in DB.
It would be awesome if you could provide a Node_redis library example.
I also could not find the documentation needed about providing timestamp with new entries. 

Any help is appreciated.

**Comment by tidwall** [comment]
Hi @shailesh17mar,

Node_redis is supported. The trick is to call the `client.send_command(name, args, callback)` function in order to use Tile38 commands.

```javascript
var redis = require("redis")
var client = redis.createClient(9851, "localhost")

client.send_command(
	"SET", ["fleet", "truck1", "POINT", "33", "-115"], 
	function(err, reply){
		if (err){
			// ERROR
		}else{
			console.log(reply)
			// OK
		}
	}
)

client.send_command(
	"GET", ["fleet", "truck1"],
	function(err, reply){
		if (err){
			// ERROR
		}else{
			console.log(reply)
			// {"type":"Point","coordinates":[-115,33]}
		}
	}
)
```

**Comment by tidwall** [comment]
I also added a link to the Tile38 wiki site. https://github.com/tidwall/tile38/wiki/node_redis-example

I agree with you that there should be more documentation. 

Thanks for the suggestion and for trying out Tile38.

**Comment by shailesh17mar** [comment]
I will be trying out Tile38 with a large location db. Will tell you about my experience.

**Comment by tidwall** [comment]
Sounds good. I look forward to the feedback.
