### ISSUE TITLE
Add example code for each major client library

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#101]
We should have example code documented for each recommended [client library](https://github.com/tidwall/tile38#client-libraries)

At the moment only the node_redis library has an [example](https://github.com/tidwall/tile38/wiki/node_redis-example) of how to use the client library.

**What to do for each client library**

- Create an example code wiki page that executes the following commands:
```
SET fleet truck1 POINT 33 -115
GET fleet truck1
NEARBY fleet POINT 33 -115 1000
```
Use the [node_redis example](https://github.com/tidwall/tile38/wiki/node_redis-example) as a template.

- Add a link next to the name of the library in the [client library](https://github.com/tidwall/tile38#client-libraries) list.
- Add a link to the [wiki homepage](https://github.com/tidwall/tile38/wiki)

Recommended #100

**Comment by beyoung** [comment]
hi @tidwall, i cloned https://github.com/tidwall/tile38.wiki.git , and writed a simple python and golang example, but when i push my example to github, it reports 
```
Permission to tidwall/tile38.wiki.git denied to beyoung
```
so , what should i do ?

**Comment by beyoung** [comment]
i  create a [new repo](https://github.com/beyoung/tile38_wiki).  H_H

**Comment by beyoung** [comment]
@tidwall  No problem.     it's a pleasure for me to make tile38 more  reachable. (and tile38 is great , it makes LBS application much simple . Thanks for your work. )  #_# .

**Comment by enc** [comment]
I added a ruby version
https://github.com/enc/tile38/wiki

**Comment by tidwall** [comment]
@enc Thanks a bunch. I'll merge it asap.

**Comment by enc** [comment]
Here is a golang version for redigo too.

I prefer this library since it ignores the redis semantics which is handy for our usecase.

```
package main

import (
	"fmt"
	"log"
	"github.com/garyburd/redigo/redis"
)

func main() {
	c, err := redis.Dial("tcp", ":9851")
	if err != nil {
		log.Fatalf("Could not connect: %v\n", err)
	}
	defer c.Close()

	ret, _ := c.Do("SET","fleet", "truck1", "POINT", "33", "-115")
	fmt.Printf("%s\n", ret)

	ret, _ = c.Do("GET","fleet", "truck1")
	fmt.Printf("%s\n", ret)

}
```

**Comment by tidwall** [comment]
@beyoung and @enc, I just updated the [client libraries](https://github.com/tidwall/tile38#client-libraries) section in the README and the [wiki](https://github.com/tidwall/tile38/wiki) to include the new examples.
Thanks for these!

**Comment by phulst** [comment]
it would be great if you could link to my node library in your docs as well!
https://github.com/phulst/node-tile38

**Comment by tidwall** [comment]
@phulst Absolutely. I just added it to the README. If you have basic example code, I can add it to the [Wiki](https://github.com/tidwall/tile38/wiki) too.

**Comment by phulst** [comment]
thanks. There are a bunch of examples in the readme, but I will also be adding some examples as runnable code here: 
https://github.com/phulst/node-tile38/tree/master/examples
Feel free to copy that to the Wiki, or refer back to my repo.

**Comment by Lars-Meijer** [comment]
I've written an example for Java using lettuce. I hope this helps people as it took some time to figure out how to use lettuce for tile38.

You can find it here:
https://github.com/lars-meijer/tile38/wiki/

**Comment by tidwall** [comment]
@Lars-Meijer Thanks for the code examples. I think it'll help a lot.

**Comment by tidwall** [comment]
@phulst I added some example code the `node-tile38` library. I pulled it from the examples/ directory. I didn't test it. Let me know if it needs any fixing. Thanks!

**Comment by phulst** [comment]
looks great, thanks for adding this to your docs.

**Comment by phulst** [comment]
btw you may want to make mention of the node-tile38 library here too: http://tile38.com/clients/

**Comment by tidwall** [comment]
@phulst will do. Thanks for reminding me.

**Comment by Lars-Meijer** [comment]
I just noticed my sample code is missing an import, you can add this line after the second import to fix it:

import com.lambdaworks.redis.api.sync.RedisCommands;

**Comment by tidwall** [comment]
@Lars-Meijer fixed. 👍

**Comment by tidwall** [comment]
I recommend including one NEARBY command to each example. This will ensure that the client supports custom commands and complex responses.

#190

**Comment by skz363** [comment]
can't get the code for nearby and scan commands for java can please anyone help !!

**Comment by s32x** [comment]
Here is a golang version for go-redis which automatically supports connection pooling.

```go
package main

import "github.com/go-redis/redis"

func main() {
	c := redis.NewClient(&redis.Options{
		Addr: ":9851",
		OnConnect: func(c *redis.Conn) error {
			// Set the output to JSON for every connection that is created
			return c.Do("OUTPUT", "json").Err()
		},
		ReadTimeout:  -1,
		WriteTimeout: -1,
	})

	res, _ := c.Do("SET", "fleet", "truck1", "POINT", 33, -115).String()
	println(res)

	res, _ = c.Do("GET", "fleet", "truck1").String()
	println(res)
}
```

Output:
```json
{"ok":true,"elapsed":"9.036µs"}
{"ok":true,"object":{"type":"Point","coordinates":[-115,33]},"elapsed":"4.579µs"}
```

**Comment by tidwall** [comment]
Thanks for everyone's help with putting together the examples. I think we have enough to get most new users started with using Tile38 in their favorite language.
