### ISSUE TITLE
Is there any way to import data into tile38 from csv/tsv file?

### ISSUE THREAD

**Issue by shailesh17mar** [tidwall/tile38#102]

**Comment by amorskoy** [comment]
I am using Scala for this - with the Spark for csv read (spark.read.csv) --> scalaj.http for http post into Tile38 port

It could be simplier - like python for csv read --> python curl post

The bad news here is insertion performance, as massinsert is under development, as i see in @tidwall master branch

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if needed. 

Thank you!

**Comment by stefanocudini** [comment]
@tidwall ```massinsert``` will be a new command?
