### ISSUE TITLE
Del Command

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#104]
Hi,
I want to take the match when using del command.
For example,
1.set fleet t:1 point 1 1
2.set fleet t:2 point 2 2
Then,I want to delete begin with t id directly.
But I don't want to delete one by one.Excuse me how should I do

**Comment by tidwall** [comment]
This is currently not available. Perhaps I could add a `PDEL key pattern` command.

**Comment by GameFreedom** [comment]
That's pretty? Thanks a lot
