### ISSUE TITLE
Add Kafka as SETHOOK endpoint

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#109]
It seems to be natural extention for scalable architecures.

Currently my flow looks like:
GeospatialPointsProducer  --->  Tile38 [Hook, http endpoint] ----> Python HTTP server --->  push to Kafka <---- Spark Streaming

We could achieve:
GeospatialPointsProducer  --->  Tile38 [Hook, kafka endpoint] ----> push to Kafka <---- Spark Streaming

So python http botlleneck removed

**Comment by tidwall** [comment]
I think that this may be possible. There's an [controller/endpoint](https://github.com/tidwall/tile38/tree/master/controller/endpoint) package that provides and interface for adding hook protocols. Right now Tile38 supports HTTP, gRPC, and Disque. 

I don't have any hands-on experience with Kafka but as long as there's a TCP endpoint to connect to then support should be possible.

**Comment by amorskoy** [comment]
When I feel more comfortable with Go - will try to make pull request as well

**Comment by amorskoy** [comment]
@tidwall  after short searching I have found this implementation mature and progressive enought: https://github.com/Shopify/sarama

I do not know benchmarking for it yet, but it seems to be good feet

**Comment by tidwall** [comment]
Good find. Sarama looks mature and feature rich. I agree that this may be the best option to start with.

I'm hoping that the `controller/endpoint` package is self explanatory, but if you have any question along the way, don't hesitate to ask.

**Comment by kcech** [comment]
Useful feature indeed. +1!

**Comment by m1ome** [comment]
I can try to implement this on next week.

**Comment by marinoaldi** [comment]
That sounds good! +1

**Comment by fgt-opentrends** [comment]
Waiting Anxiously! +1

**Comment by m1ome** [comment]
Tomorrow I will start working on this issue. 
Sorry guys, was sick for a week. FeelsBadMan.

Try to implement this one ASAP.
Using Sarama.

**Comment by m1ome** [comment]
Guys, can you please dive into issue and say if it fit's your requirements?
I don't work with Kafka a lot, and i need your help if this PR contains all stuff you need?

**Comment by tidwall** [comment]
Kafka endpoints are now supported in the master branch! 🎉

@m1ome Thanks a ton for your help!

**Comment by m1ome** [comment]
@tidwall hooray!
![happy](https://media.giphy.com/media/l46CkATpdyLwLI7vi/giphy.gif)

**Comment by m1ome** [comment]
@tidwall maybe we can close this one?
