### ISSUE TITLE
Cannot unzip zipped file for Mac OS X

### ISSUE THREAD

**Issue by JosephShering** [tidwall/tile38#111]
````
unzip tile38-1.7.0-darwin-amd64.zip
Archive:  tile38-1.7.0-darwin-amd64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of tile38-1.7.0-darwin-amd64.zip or
        tile38-1.7.0-darwin-amd64.zip.zip, and cannot find tile38-1.7.0-darwin-amd64.zip.ZIP, period.
```

**Comment by tidwall** [comment]
I just tested on my side and unzipped ok. Perhaps the file was corrupted on transit?

The MD5 is `354de5253f92a91041e29c4d9a8c5b1b`.

```
$ md5 tile38-1.7.0-darwin-amd64.zip
```

Alternatively you can install using Homebrew `brew install tile38`

**Comment by tidwall** [comment]
Hi @JosephShering,

Checking to see if were you able to get Tile38 installed and if there's anything else I can assist with.

**Comment by m1ome** [comment]
@JosephShering just checked on my MPB, all fine.

BTW you can install last version from `brew`.
It's much more easy way to do it.

**Comment by m1ome** [comment]
@tidwall maybe we should close this?
