### ISSUE TITLE
TTL not returning anything

### ISSUE THREAD

**Issue by phulst** [tidwall/tile38#116]
```
127.0.0.1:9851> SET my ufo POINT 33.5123 -112.2693
{"ok":true,"elapsed":"18.71µs"}
127.0.0.1:9851> expire my ufo 100
{"ok":true,"elapsed":"9.599µs"}
127.0.0.1:9851> GET my ufo
{"ok":true,"object":{"type":"Point","coordinates":[-112.2693,33.5123]},"elapsed":"49.92µs"}
127.0.0.1:9851> TTL my ufo
{"ok":true,"elapsed":"5.57µs"}
```

I was expecting the TTL command to return 100 (or something close to 100), but it doesn't return a TTL value at all. Is this a bug? The expiration does appear to work, 100 seconds after calling expire the object is removed.

**Comment by tidwall** [comment]
Thanks for finding this. It appears that with the `tile38-cli` utility, the TTL command does not return the TTL value as you described. I fixed this and pushed to the master branch.

On a side note you can use a Redis client or type in `OUTPUT resp` to switch `tile38-cli` to output as a redis formatted response.

```
127.0.0.1:9851> SET my ufo POINT 33.5123 -112.2693
{"ok":true,"elapsed":"18.71µs"}
127.0.0.1:9851> OUTPUT resp
OK
127.0.0.1:9851> expire my ufo 100
(integer) 1
127.0.0.1:9851> GET my ufo
"{"type":"Point","coordinates":[-112.2693,33.5123]}"
127.0.0.1:9851> TTL my ufo
(integer) 3
```

**Comment by phulst** [comment]
thanks Josh. I intentionally set the output format to json because I'm working on a Node driver for Tile38 (essentially a wrapper around node-redis). Working with JSON is more convenient than the redis response format in javascript code... 
https://github.com/phulst/node-tile38

**Comment by tidwall** [comment]
I fixed this issue and pushed the update to the master branch. I'll bump a public release by the end of the week. 

Your project looks great. 

I was working with the node redis library the other day, which is pretty good, and I found a minor limitation with creating [live geofences](http://tile38.com/topics/geofencing)... rather I couldn't find a way to use the FENCE keyword and read continuous messages from the stream.

I'm a little rusty on my node skills, so perhaps I was missing something. FWIW in case you might want this functionality for your client, I wrote a hackish workaround: https://gist.github.com/tidwall/0e7fe116351fb7a9a16c0cbd3e2fb79a

**Comment by phulst** [comment]
Thanks, that might be very helpful. As I'm sure you noticed I hadn't implemented support for live geofences yet but I'll take a look. Perhaps if node-redis does not support continuous messages well, [ioredis](https://github.com/luin/ioredis) might.
