### ISSUE TITLE
NEARBY fleet FENCE DETECT enter COMMAND ... invalid argument 'COMMAND'

### ISSUE THREAD

**Issue by juanpabloaj** [tidwall/tile38#117]
When I try this command of the documentation

    NEARBY fleet FENCE DETECT enter COMMAND set POINT 0 0 1000 

I get this error message 

    (error) invalid argument 'COMMAND'

I use the version 1.7.0

**Comment by tidwall** [comment]
Sorry about that. It's a typo in the documentation. The keyword is `COMMANDS` with an S. 

I just fixed the docs moments ago.

Thanks a ton for discovering the error.

**Comment by phulst** [comment]
the INTERSECTS and WITHIN doc pages also specify COMMAND instead of COMMANDS
