### ISSUE TITLE
Remove "[ERRO] unexpected EOF" message

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#118]
Too many `[ERRO] unexpected EOF` messages when disconnecting from Websockets when a `.close()` is called from Javascript application.

The Tile38 should recognized that the connection was closed and gracefully end the stream without errors.

#115

**Comment by m1ome** [comment]
@tidwall if you wanna to, i can research and fix it.

**Comment by tidwall** [comment]
@m1ome That would awesome. Thanks! 👍

**Comment by m1ome** [comment]
@tidwall ok i will to it tomorrow 👍

**Comment by tidwall** [comment]
@m1ome Thanks for your help with this bug
