### ISSUE TITLE
HTTP webhook content-type header missing

### ISSUE THREAD

**Issue by UriHendler** [tidwall/tile38#124]
When I use HTTP webhooks, it seems that Tile38 is not sending the Content-Type header (which should be application/json according to the docs).

I'm using v1.7.0 on Windows.

Here's an example webhook request:
```
POST /api/routeMonitoring/hooks/tile38 HTTP/1.1
Host: a1234567.ngrok.io
User-Agent: Go-http-client/1.1
Content-Length: 237
Accept-Encoding: gzip
X-Forwarded-For: (My IP here)

{"command":"set","group":"5875e3122c9d463190d70c7e","detect":"inside","hook":"deliveriesVehicle12","key":"customerVehicles3","time":"2017-01-11T09:47:30.5686894+02:00","id":"12","object":{"type":"Point","coordinates":[28.0029,-26.2154]}}
```

I assume `req.Header.Set("Content-Type", "application/json")`
should be added before this line: https://github.com/tidwall/tile38/blob/master/controller/endpoint/http.go#L66

**Comment by m1ome** [comment]
@UriHendler nice catch, submitted PR for this.
