### ISSUE TITLE
what is the META parameter used for in SETHOOK?

### ISSUE THREAD

**Issue by phulst** [tidwall/tile38#129]
A few questions: 
1. When I submit a command like this: 

SETHOOK testhook http://httpbin.org/post META field val1 NEARBY fleet FENCE POINT 33.637276 -84.434006 500

it happily accepts it, but I'm not sure what META actually does, and can't find any description of it in your docs. The webhooks documentation page suggests that META may accept multiple name/value pairs, but if I try this: 

SETHOOK testhook http://httpbin.org/post META field val1 field2 val2 NEARBY fleet FENCE POINT 33.637276 -84.434006 500

I get an error "invalid argument 'field2'"

2. I'm assuming that SETHOOK supports all of POINT, GET, BOUNDS, OBJECT, TILE, QUADKEY, HASH, is that correct?  Which of these can a radius be specified with... Just POINT or all others as well? 
Just want to make sure my node driver can support all the options....
thanks

**Comment by damariei** [comment]
1. 
The META are just any key/value pairs you would like to be returned in the callback as additional data. The reason why you second example fails is you must use the `META` keyword in front of each pair, like so: `META field val1 META field2 val2`
2. 
Only POINT and ROAM have the radius option, see the documentation here:
http://tile38.com/commands/nearby/

**Comment by phulst** [comment]
thanks for the clarification
