### ISSUE TITLE
how to query using geojson object

### ISSUE THREAD

**Issue by ray93** [tidwall/tile38#13]
hi，i met a problem about query. 
When i query using geojson object, such as 
'within city object OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
it always returns error 'invalid argument object'.
can you help me solve the problem,thank you!

**Comment by tidwall** [comment]
Hi @ray93 
It looks like this is an issue with Tile38. I found the root of the problem. I'll post a fix right away.

**Comment by tidwall** [comment]
I posted a fix, try this query

```
within city object {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
```

**Comment by ray93** [comment]
it does work well for me, it did miss object key,thank for your help!
And i have another two problems.
one is how to add data using set command by batch, and can set command use websocket protocol?.
And the other is how to log in the background when the server starts.
can you give me some advice,thank u!

**Comment by tidwall** [comment]
I'm glad to hear that your query is working.

For batches I recommend using one of the [clients](http://tile38.com/clients), not HTTP or websockets. HTTP is more for system administration such as running from a bash script with curl. The websocket protocol is really only useful when connecting to [Geofences](http://tile38.com/topics/geofencing/) and live searches.

After choosing a client, make a single connection to the Tile38 server. Then do multiple SET commands for each object in the batch. Finally close the connection. 

As for logging in the background you should use upstart, systemd, launchd, daemontools, supervisord, or runit. Which ever is best suited for your Linux environment.

Is hope this is helpful. Please let me know if you have any further questions. Thanks!
