### ISSUE TITLE
TTL no longer working on v1.7.5

### ISSUE THREAD

**Issue by damariei** [tidwall/tile38#131]
It seems TTLs stopped working on the latest version of Tile38.

**Comment by tidwall** [comment]
I'm not seeing the issue from my end. 

A simple test I just tried:

```
> SET fleet hello EX 10 POINT 33 -115
{"ok":true,"elapsed":"21.152µs"} 
> TTL fleet hello
{"ok":true,"ttl":8.472180651,"elapsed":"10.575µs"}
> TTL fleet hello
{"ok":true,"ttl":4.224236963,"elapsed":"5.479µs"}
> TTL fleet hello
{"ok":true,"ttl":1.536149794,"elapsed":"23.728µs"}
> TTL fleet hello
(error) id not found
```

What are you seeing on your side?

**Comment by tidwall** [comment]
@damariei Are you still running into issues with TTL?

**Comment by tidwall** [comment]
I'm closing this for now. Please reopen if this is still an issue. Thanks.
