### ISSUE TITLE
Hook queue is slow

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#132]
I am pushing messages into Tile38 using Telnet. Input rate is around `100` inserts/sec - SET - simple point objects into `people` collection with EX 10 seconds

Static part is `pois` collection, ~ 73000 objects, simple points as well.

There is just 1 hook
127.0.0.1:9852> hooks *
`{"ok":true,"hooks":[{"name":"poi_hook","key":"people","endpoints":["http://localhost:9999/"],"command":["NEARBY","people","FENCE","COMMANDS","set","ROAM","pois","*","300"]}],"elapsed":"64.541µs"}`

The problem is that HTTP endpoint  call rate is very poor - just 10 messages per second (so hook message queue rising).

Endpoint is Python's `BaseHTTPServer.BaseHTTPRequestHandler`,  which can  handle thousands of requests per second

**Comment by tidwall** [comment]
Hi @amorskoy, 

That is slow. 
Which version of Tile38 are you running?

If you do a generic fence in Telnet, does the rate keep up?

```
$ telnet localhost 9852
Trying ::1...
Connected to localhost.
Escape character is '^]'.
NEARBY people FENCE COMMANDS set ROAM pois * 300
+OK
```

You may also want to delete the current webhook first.

I'm wondering if the problem is in ROAM logic or the http delivery.

**Comment by amorskoy** [comment]
Hi @tidwall . It is fresh checkout from master.
Yes, it is already telnet - and this rate is high enough - (~100 messages per second)
Problem is about outgoing rate (hook endpoint HTTP call - ~10 per secon

I have debugged a little bit - seems that controlooer/endpoint/http.go, line 68 goes slow - seems to be a reason:
`resp, err := conn.client.Do(req)`

**Comment by tidwall** [comment]
That should be a very fast operation.

What's suppose to be happening is that the first webhook notification to an endpoint will open an HTTP/2 connection using the default Go `net/http` client. Then all of the following Do() commands to that endpoint should share the same connection. If more that 30 seconds elapse between two notifications, the connection is closed. It then gets reopened when a new notification is sent.

At least that's what is intended. Clearly something gone haywire.

**Comment by amorskoy** [comment]
I will try to check one idea - my python scripts, besides fast TCP recv, does Kafka push as well. I want to check if it possible that this operation is don synchronously. In this case it may be a reason in theory.

**Comment by amorskoy** [comment]
@tidwall  definetely it is Sync nature of Kafka python producer. Let me play a little bit with the tests today before closing the issue

**Comment by amorskoy** [comment]
Yes, it was definetely 2 factors on HTTP endpoint side
1. slow python's SimpleHTTP server - replaced with gunicorn + falcon
2. slow kafka producer - will work on it

**Comment by tidwall** [comment]
Thanks for looking into this and letting me know.

**Comment by amorskoy** [comment]
I was able to easely produce ~1000 http hooks/sec (with input SET rate 1000 msg/sec). Looks fantastic.
I will try to increase the things as I am finishing with Python Kafka producers test

**Comment by tidwall** [comment]
👍 Very good to hear.
