### ISSUE TITLE
Send fields with webhook notification

### ISSUE THREAD

**Issue by UriHendler** [tidwall/tile38#134]
Here's a suggestion, may be of use to others also.

Is it possible to allow the values of fields to be sent with the webhook?

I need a way to identify the message that caused the hook to fire. I can set the MessageID as a field when updating, e.g.:
`SET fleet truck1 FIELD messageId 354524 FIELD lastUpdatedAt 28758279 POINT 33.5123 -112.2693`
but when the hook fires, I have no way to know the value of the messageId field. I could query the field, but by the time I do that, it could have been updated.

Here's my suggestion:
```
SETHOOK name endpoint [META name value ...] [FIELDS which] NEARBY|WITHIN|INTERSECTS key FENCE [DETECT what] [COMMANDS which] param [param ...]
OR
SETHOOK name endpoint [META name value ...] [FIELD name...] NEARBY|WITHIN|INTERSECTS key FENCE [DETECT what] [COMMANDS which] param [param ...]

SETHOOK testhook http://localhost:9999 META routeId 123 FIELDS messageId, lastUpdatedAt NEARBY fleet FENCE POINT 33.5123 -112.2693 500
```

When the hook fires, it will look like:
```
{
    "command": "set",
    "detect": "enter",
    "hook": "testhook",
    "time": "2017-01-15T09:37:49.567854293+01:00",
    "key": "fleet",
    "id": "truck2",
    "meta": {
        "routeId": "123"
    },
    "fields": {
        "messageId": 354524,
        "lastUpdatedAt": 28758279
    },
    "object": {
        "type": "Point",
        "coordinates": [-112.2693, 33.5123]
    }
}
```

**Comment by tidwall** [comment]
Hi Uri,

Fields should always be sent with each notification. I just tested on my side to verify. 

I used this hook:
```
SETHOOK testhook http://localhost:9999 META routeId 123 NEARBY fleet FENCE POINT 33.5123 -112.2693 500
```

then I sent this command:
```
SET fleet truck1 FIELD messageId 354524 FIELD lastUpdatedAt 28758279 POINT 33.5123 -112.2693
```

which produces this notification:
```json
{
  "command":"set",
  "group":"587f84f1d5eefd5073ea852b",
  "detect":"inside",
  "hook":"testhook",
  "meta":{
    "routeId":"123"
  },
  "key":"fleet",
  "time":"2017-01-18T08:09:06.264344724-07:00",
  "id":"truck1",
  "object":{
    "type":"Point",
    "coordinates":[-112.2693,33.5123]
  },
  "fields":{
    "messageId":354524,
    "lastUpdatedAt":28758279
  }
}
```

Perhaps there's something going haywire with a specific field name, value... could you attach an example of what you're receiving

**Comment by UriHendler** [comment]
Thanks, let me test again.

I must have missed that last time I tried it. :flushed:

**Comment by tidwall** [comment]
Hi @UriHendler, Did you have a chance to test?

**Comment by UriHendler** [comment]
Working fine now.

I must have been half asleep the last time I tested.

**Comment by tidwall** [comment]
👍 Great to hear.
