### ISSUE TITLE
KNN for nearby command

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#136]
It's been often requested to allow for a NEARBY request to order the results by the distance to the target point and to limit by a count rather than a radius.

Including the `LIMIT` and `DISTANCES` keyword, and excluding the radius (meters) parameter, Tile38 will guarantee:
- The results will be order by the distance nearest to the target point.
- Each resulting object will include the distance to the target point in meters.
- The number of objects returned will not exceed the value of `LIMIT`

For example:
```
NEARBY fleet LIMIT 10 DISTANCES POINT 33.374 -115.829
```
This will return up to, but not exceeding, 10 objects which are ordered by their distance to the target point `33.374 -115.829`.

It may be worth noting that the CURSOR keyword is not compatible with this feature, at least not for the initial release.

**Comment by m1ome** [comment]
@tidwall i think we can implement right now in a hacky-way, just adding mix of `DISTANCE` and `LIMIT` command, and then measure speed. After merge or cancel we can improve it with KKN algo. Sound good?

**Comment by tidwall** [comment]
@m1ome Yes, that sounds like a good start.

**Comment by m1ome** [comment]
@tidwall submitted PR #138
