### ISSUE TITLE
Support redis CLIENT commands

### ISSUE THREAD

**Issue by UriHendler** [tidwall/tile38#139]
I'm trying to debug an issue where I'm getting frequent network receive timeouts on open connections to tile38 (running v1.7.5).

The debug log shows when connections are opened/closed/dropped, but I'm not finding any pattern there.

Tile38 is running on a Ubuntu VM in Azure. The apps that are talking to tile38 are in the same Azure region, so the network latency should be very low. CPU usage is usually not more than 5%.

I'm sending at most 100-200 commands per second, mostly SET commands.

I'm currently using the [ServiceStack.Redis](https://github.com/ServiceStack/ServiceStack.Redis) client, which supports connection pooling.

Is support for the redis CLIENT commands on the roadmap?

At least the CLIENT LIST command would be helpful, with the `id` and `addr` fields (`name`, `age` and `idle` would be a nice addition.)

**Comment by tidwall** [comment]
@UriHendler I added the CLIENTS command to the master branch. Let me know how it goes.

**Comment by UriHendler** [comment]
@tidwall Great, thanks!
