### ISSUE TITLE
Geofence on GeoJSON not working 

### ISSUE THREAD

**Issue by ywadi** [tidwall/tile38#144]
I am facing what seems to be a bug 
I am not able to geofence on an OBJECT 

`NEARBY fleet FENCE OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
`
I get (error) invalid argument 'OBJECT'
It seems like a bug, or I might be missing something as I cant find anything like it in documentation

**Comment by ywadi** [comment]
Bounds seem to cause the same issue

**Comment by tidwall** [comment]
The NEARBY command is only valid for the POINT type. Alternatively you can use the WITHIN or INTERSECTS.

**Comment by ywadi** [comment]
Ok I think the documentation needs update then, as it says 

> geofence is a virtual boundary that can detect when an object enters or exits the area. This boundary can be a radius or any search area format, such as a bounding box, GeoJSON object, etc. Tile38 can turn any standard search into a geofence monitor by adding the FENCE keyword to the search.

**Comment by tidwall** [comment]
The standard search commands are [NEARBY](http://tile38.com/commands/nearby), [WITHIN](http://tile38.com/commands/within), or [INTERSECTS](http://tile38.com/commands/intersects).

NEARBY is for points with a radius in meters, and WITHIN/INTERSECTS are for objects and boundaries. 

The FENCE keyword can be added to a standard search to turn it into a geofence.

For example,
```
NEARBY fleet POINT 33 -115 1000
```
will return all objects in the fleet collection that are inside the 1km radius of the target point.
```
NEARBY fleet FENCE POINT 33 -115 1000
```
will create a geofence around the point and send notifications.

For the OBJECT types:
```
WITHIN fleet OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
```
can be turned into a geofence:
```
WITHIN fleet FENCE OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
```

**Comment by ywadi** [comment]
Got it, I guess just got confused around this. Thanks for the clarification

**Comment by tidwall** [comment]
👍  The commands are confusing and I agree that a clearer description would be helpful.
