### ISSUE TITLE
Max memory setting

### ISSUE THREAD

**Issue by jrots** [tidwall/tile38#15]
When quickly looking at the code I don't see any option or setting to define max memory tile38 can use up - are there plans to add this?
Just would rather have errors returned from tile38 that max memory has been reached than an OOM killer killing the whole process.

**Comment by tidwall** [comment]
Hi @jrots, Great suggestion and it should be trivial to implement since Tile38 tracks total memory usage for the server stats command.

**Comment by tidwall** [comment]
To set the max memory use something like
```
config set maxmemory 100mb
config rewrite
```

**Comment by jrots** [comment]
cool !! very nice 👍
