### ISSUE TITLE
within live fence with detect=inside doesn't trigger event for new object

### ISSUE THREAD

**Issue by phulst** [tidwall/tile38#150]
open one CLI and start a live fence: 
```
WITHIN users FENCE DETECT inside POINTS BOUNDS 33.618824 -84.457973 33.654359 -84.399859
```

now send a coordinate within the given bounds from a second CLI:
```
SET users 200 POINT 33.642301 -84.43118
```

The live fence doesn't trigger an event. If you send the same SET command a second time, the live fence does receive an event. 
Note that if I use detect=enter, the event does trigger immediately with the first SET command for a new object. 

This only appears to be an issue when using detect=inside and when the object isn't already in the database.

**Comment by phulst** [comment]
also note that when I use "detect enter,inside"  in the above example, I do get a event for both inside and enter, even when the object did not previously exist. When testing with just 'detect inside', I get nothing for the first SET.

**Comment by tidwall** [comment]
I can confirm that this is happening for me too. Thanks for reporting.
