### ISSUE TITLE
JSET issue

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#151]
Hello,
First.I follow the orders,`localhost:9851/jset+a+b+1+1`
Then,I follow the orders again,`localhost:9851/jget+a+b`
Returned the following results：`{"ok":true,"value":"{\"1\":\"1\"}","elapsed":"0s"}`.
Among them, the backslash escapes is much more at a time？

**Comment by m1ome** [comment]
@GameFreedom JSON you provided is a valid. Could you provide additional information about issue you have?

**Comment by m1ome** [comment]
And BTW http endpoint is deprecated right now and will be disabled by default in future releases.

**Comment by tidwall** [comment]
@GameFreedom This is the correct behavior. 

The "JSET a b 1 1" command will create the JSON document: 

    {"1":"1"}

In order to store this value as a string in Tile38, it must be escaped:

    "{\"1\":\"1\"}"

You must then retrieve this value as an unescaped string using the JSON library for your programming language.

**Comment by tidwall** [comment]
@GameFreedom I'm closing this issue for now, but feel free to reopen if you have further questions on the output format.
