### ISSUE TITLE
Question: What is the RESP endpoint returning (or maybe just how) ?

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/tile38#153]
It's entirely possible that I am just glossing over something obvious but for the life of me I can't figure out what's being returned when I send a `INTERSECTS` command over the RESP endpoint using the `redigo` package:

https://github.com/whosonfirst/go-whosonfirst-tile38/blob/bboxd-resp/client/resp.go#L81-L94

Specifically I am getting back a `[]interface{}` response but I am not sure what its type is or how to work with it. Marshaling it in to JSON returns a whole lot of stuff like this:

```
2017/03/04 16:12:54 [100,[["MTEwODgxNDcxMSNkeGxhYnM=",["LTMzLjg4NTc0ODIwNjE4","MTUxLjI0NDE1MDQyMDUz"],["d29mOmlk","MTEwODgxNDcxMQ==","d29mOnBhcmVudF9pZA==","LTE=","d29mOnBsYWNldHlwZV9pZA==","MTAyMzEyMzE5"]],["MTEwODgyMzAyNSNkeGxhYnM=",["LTMzLjg3OTY5NDQ1NDE0MzQ1","MTUxLjIzNTk3NzE3MTMyNQ=="],["d29mOmlk","MTEwODgyMzAyNQ==","d29mOnBhcmVudF9pZA==","LTE=","d29mOnBsYWNldHlwZV9pZA==","MTAyMzEyMzE5"]],["MTEwODgxNDk3NyNkeGxhYnM=",["LTMzLjg5Mjk5MjgyMjkzNTc5Ng==","MTUxLjI1MDI3MDM5ODQ1"],["d29mOmlk","MTEwODgxNDk3Nw==","d29mOnBhcmVudF9pZA==","LTE=","d29mOnBsYWNldHlwZV9pZA==","MTAyMzEyMzE5"]] ... and so on
```

Ideally I would like to be able to take whatever the RESP endpoint returns and convert it in to the same JSON response that comes back from the HTTP endpoint.

Thoughts?

**Comment by tidwall** [comment]
The output is a bit convoluted and redigo stores the response as a combination of []interface{} and strings. I'll put a little effort into documenting it.

But if what you are looking for is a JSON document, then I recommend sending the server the `OUTPUT json` command immediately after connecting. 

Something like this:

```go
pool := &redis.Pool{
	MaxActive: 1000,
	Dial: func() (redis.Conn, error) {
		c, err := redis.Dial("tcp", t38_endpoint)
		if err != nil {
			return nil, err
		}
		json, err := redis.String(c.Do("OUTPUT", "json"))
		if err != nil {
			return nil, err
		}
		if (!gjson.Get(json, "ok").Bool()){
			return nil, errors.New(gjson.Get(json, "err").String())
		}
		return c, err
	},
}
```

```go
func (cl *RESPClient) Do(t38_cmd string, t38_args ...interface{}) (string, error) {
	conn := cl.pool.Get()
	defer conn.Close()

	json, err := redis.String(conn.Do(t38_cmd, t38_args...))
	if err != nil {
		return nil, err
	}
	if (!gjson.Get(json, "ok").Bool()){
		return nil, errors.New(gjson.Get(json, "err").String())
	}
	return json, nil
}
```

Now everything the server returns will be a JSON response.

**Comment by thisisaaronland** [comment]
Perfect, thanks!
