### ISSUE TITLE
Setting multiple (small) fields, big size overhead

### ISSUE THREAD

**Issue by jrots** [tidwall/tile38#16]
Hi, 
you can set multiple fields, but internally it's always stored as a float64..which take up 8 bytes, 
I have a lot of boolean values/ small integer values < 255 that could fit in one byte, 
would be nice if there was an option to define the size during set.. 
maybe some prefix b:  f.e. SET FIELD b:somefield 5

Regards 
Jayme

**Comment by tidwall** [comment]
Good idea. We could probably detect the minimum size of the value when SET FIELD is called. So the server would recognize that `SET FIELD somefield 5` can fit in one byte and choose to store it efficiently. This way one syntax could handle float64, byte, or other sizes in the future. What do you think?

**Comment by jrots** [comment]
Sure, or change low level storage in collection.go from
```
type itemT struct {
	ID     string
	Object geojson.Object
	Fields []float64
}
```
to : 
```
type itemT struct {
	ID     string
	Object geojson.Object
	Fields [][]byte
}
```
storing a byte array? 
```
 []byte(strconv.Itoa(<someinteger>))
```
You can convert back to float64 when fetching, would require minimal code changes imho

**Comment by tidwall** [comment]
Something like what you suggest should work. Though the overhead of a byte array in Go can be quite large. Perhaps we can pack up to 8 individual bytes in a float64. Then the collection structure can know which field indexes are used for packed bytes or float64. Then we can use the `math.Float64bits` function for translating.

For example, the collection could dedicate the second float64 as 8-8bit values, and we could retrieve the 2nd byte like such. 
```go
b := byte((math.Float64bits(item.Fields[1])>>1)&0xFF)
```
