### ISSUE TITLE
How to store XYZ tiles in tile38?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#160]
Hi, @tidwall 
The official website says support for XYZ tiles.
How to store and get XYZ tiles in tile38 ,Can you give an example ?

**Comment by m1ome** [comment]
@icewukong you should probably use "Z coordinate" for a such things as altitude and something like that. Look here: [SET COMMAND](http://tile38.com/commands/set/).

You can also use **Z** coordinate in queries, such as NEARBY, WITHIN and e.t.c.

**Comment by Lars-Meijer** [comment]
> The official website says support for XYZ tiles.
> How to store and get XYZ tiles in tile38 ,Can you give an example ?

As far as I know you cannot "store" XYZ tiles, you can only search within XYZ tiles.
"All object types except for XYZ Tiles and QuadKeys can be stored in a collection. XYZ Tiles and QuadKeys are reserved for the SEARCH keyword only."
See documentation: http://tile38.com/topics/object-types/

> How to store and get XYZ tiles in tile38 ,Can you give an example ?
If you want to search within a xyz tile you can use the following commands:
Firstly, set a point (this one is located in the Netherlands)
SET fleet truck POINT 52.313010 5.775904

Then search the tile (16, 10) at zoom level 5, which is also The Netherlands:
INTERSECTS fleet TILE 16 10 5

**Comment by tidwall** [comment]
@Lars-Meijer 

> It might be a good idea to document the fact that Google tiling is used.

I agree and thanks for the suggestion.

**Comment by icewukong** [comment]
@tidwall ,@m1ome ,@Lars-Meijer 
I know that and try it, thank you!

**Comment by m1ome** [comment]
@icewukong you are welcome.
