### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by younisshah** [tidwall/tile38#163]
Hi, this is a tremendous piece of work! You made our lives much easier! Thank you so very kindly for the work!

However, I'd one question regarding the **scalability** and **"production-ready**" status of the project. We are currently developing an "Uber-like app" for which I need to use the **Geofencing** and **NEARBY** queries of tile38 server. We have a tremendous amount of location traffic which means a lot of geofences and NEARBY **queries/second**. 

Is title38 server capable of "Uber-like" location and geofence queries/ second?

**Comment by tidwall** [comment]
Thanks for your kind words and I'm happy to hear that you're considering Tile38 for your project.

Tile38 is production ready and it's possible to create Uber-like apps with it. Though a single instance of Tile38 wouldn't be able to handle the amount of traffic that Uber does. You would likely need to distribute many instances.

You can test the overall queries/second with the recently added [tile38-benchmark](https://github.com/tidwall/tile38/issues/54#issuecomment-290550810) tool. It's not a part of an official release yet, so you'll need to manually compile a build from the master branch. 
```go
$ tile38-benchmark
```
This will give you the ops/sec for GET,SET,NEARBY.

I hope this info helps. Let me know if you have any further questions.

**Comment by younisshah** [comment]
I'm really glad to know that tile38 is production ready! 

So the leader-follower replication should be enough? 
Plus what should be the ideal leader-follower ratio of instances for Uber-like apps? 

Off topic questions: 

In Geofencing, how can I setup a WebSocket connection for real-time updates from tile38 server? Is there any documentation for that?

Are there any hooks for Deepstream integration?

**Comment by tidwall** [comment]
> So the leader-follower replication should be enough?
> Plus what should be the ideal leader-follower ratio of instances for Uber-like apps?

The leader-follower setup is good for [replication](http://tile38.com/topics/replication/) and the followers can also be used to increase performance for read-only commands like GET and NEARBY. 

Basically you send all SET commands to the leader and distribute the GET and NEARBY commands between the leader and followers.

While this alone may take you far, it's likely that you need many leaders to handle the necessary write throughput to handle the type of traffic that Uber does. It depends quite a bit on how many SET commands you app will be sending to the server. 



I wish I had an straight forward answer. It also depends on the complexity of the objects, such as points and polygons. 2D points are the fastest and smallest object type. Also the size of the NEARBY radius can make a difference in performance, 1 kilometer will be much quicker than 10 kilometers. Also the frequency of location updates from a single user/driver ap makes a big difference, for example 5 second intervals will generate a lot less traffic and be much more performant than 1 second intervals.

> In Geofencing, how can I setup a WebSocket connection for real-time updates from tile38 server? Is there any documentation for that?

I don't have any formal documentation, but a simple example:

```javascript
var socket = new WebSocket("ws://localhost:9851/NEARBY+fleet+FENCE+POINT+33.462+-112.268+6000");
socket.onmessage = function(event) {
  console.log(event.data);
};
```

The first message will be:

```json
{"ok":true,"live":true}
```

Then the rest of the messages are the geofence notifications.

**Comment by younisshah** [comment]
Ahh! That answers my questions. Except the Deepstream part! 
What about SET, GET and NEARBY query performance for GeoJSON feature objects? What is the time complexity of these queries?

Much appreciated!

**Comment by tidwall** [comment]
It depends on the feature's geometry. There's a little overhead for parsing the json and a little more memory used than from storing the geometry directly. But it should be nominal. 

A feature with a lot of "properties" and an "id" member, and is a complex multipolygon geometry will take longer to parse and index, and it will take up more memory than a simple geometry like a Point.

For complex geometries it helps to have a "bbox" member.

A simple feature like `{"type":"Feature","geometry":{"type":"Point","coordinates":[-115.123,33.393]}}` will be pretty fast. Though I would recommend just using `{"type":"Point","coordinates":[-115.123,33.393]}`, or better yet avoid GeoJSON and `SET fleet driver1 POINT 33.393 -115.123`.

**Comment by younisshah** [comment]
Thank you so much for answering my question really comprehensively! Much oblidged! 

I just need one property in the GeoJSON like this 

`
{"type": "Feature", "geometry" : {"type" : "Point", "coordinates": [-115.123,33.393]}, "properties"{"canAcceptJobs" : true}}
`

How would you suggest I should store this in tile38? A POINT with FIELD? Plus how efficient is the Roaming Geofence for Uber like apps?

**Comment by tidwall** [comment]
> How would you suggest I should store this in tile38? A POINT with FIELD?

A POINT with FIELD will work well in this case. You can query on it, and it'll probably be faster too.

> Plus how efficient is the Roaming Geofence for Uber like apps?

It depends on the number of SETs per second. In the case of:
```
NEARBY people FENCE ROAM people * 5000
```
The geofence algorithm performs a NEARBY query following every SET command. So all points in the 5km radius of an update point will be broadcasted as a geofence notification. This may be costly if you have a ton of points in the vicinity.

I recommend mocking up some tests to see what your servers and network can handle.

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if you have further questions. Thanks!

**Comment by Kilowhisky** [comment]
> 
> While this alone may take you far, it's likely that you need **_many leaders_** to handle the necessary write throughput to handle the type of traffic that Uber does. It depends quite a bit on how many SET commands you app will be sending to the server.
> 

Emphasis mine. 

Are you suggesting there is a configuration where multiple leaders can be arranged in a cluster? Or are you suggesting that you will need to fragment the data to multiple leaders based on some sort of key?

**Comment by iwpnd** [comment]
There is no way to have many leaders unless you shard your data. There's ways to use sentinel with leader election for fault tolerance, but in the end only one leader will ever receive set commands. 
You can however redundantly store data and hooks on multiple leaders, but would have to take care of deduplication (in case of hooks and events) yourself.
