### ISSUE TITLE
Any plans for adding more types of indexes?

### ISSUE THREAD

**Issue by PayasR** [tidwall/tile38#165]
Also, the current documentation is a little sparse on the details of the working of B-Tree and R-Tree in tandem. Can this please be fixed?

**Comment by tidwall** [comment]
We don't currently have any plans for more types of indexes at this time. Perhaps in the future.

The btree is primarily used to order the objects inside a collection. It's also used for string-only objects. The rtree is used for the spatial index. Both are required by a collection.

I hope this information help, let me know if you have any further questions. Thanks!
