### ISSUE TITLE
http hooks leave sockets behind

### ISSUE THREAD

**Issue by spamatica** [tidwall/tile38#166]
Hi and thanks for tile38, it's working splendidly for us keeping track of our moving units entering, exiting different areas.

We did however find an issue with using http hooks. It seems that the REST connection has a time to live which is checked with func (conn *HTTPEndpointConn) Expired(), if it has expired the connection is nil:ed (and subsequently recreated). The issue here is that the socket used is actually not closed, after running for a longer duration we hit the roof for open file descriptors as listed by lsof. I tried to find a way in this context to call some Close() method but didn't succeed.
We did solve it on our end by hijacking the http connection and closing down the tcp connection from our receiver, but probably the Close should be done on the server, maybe you have an idea on what can be done.

Thanks again

**Comment by m1ome** [comment]
`Expired()` don't check anything in HTTPENpointConn, instead we have:

```go
	return &HTTPEndpointConn{
		ep: ep,
		client: &http.Client{
			Transport: &http.Transport{
				MaxIdleConnsPerHost: httpMaxIdleConnections,
				IdleConnTimeout:     httpExpiresAfter,
			},
			Timeout: httpRequestTimeout,
		},
	}
```

But seems i need a check this issue, maybe it's related to client stuff.

**Comment by m1ome** [comment]
Can you paste some example how you hadle connections ?

**Comment by spamatica** [comment]
Ah, sorry, seems I didn't do my homework.
I thought I checked the git sources but apparently not. In the last release (which is what we are using), Expired() does: conn.client = nil. It seems to me that the checkin 0617593 from feb 10 probably fixes the problem we were seeing.
I can confirm that later but I think it is safe to close this issue as already fixed.

**Comment by m1ome** [comment]
You can close it and feel free to open if you have some issues.

**Comment by tidwall** [comment]
Hi @spamatica, This was fixed in the latest release. The new implementation should gracefully handle closed/expired connections, and also supports HTTP2 endpoints.

@m1ome Thanks for looking into this issue.
