### ISSUE TITLE
Update front page with version info

### ISSUE THREAD

**Issue by spamatica** [tidwall/tile38#167]
As a result of the already fixed bug I filed on Thursday I just became aware that the homepage is lagging.

On the http://tile38.com/ page there are some easy to copy examples on how to install tile38. Until now I was under the impression that the version listed in these examples, 1.7.5, was the latest as there was no other info on the front page (there is the link to the github release page but no version info)

Please, either keep these copy&paste links up to date or put a generic version string e.g tile38-<version.number.string>.tar.gz so it is clear that these are just examples.

**Comment by tidwall** [comment]
Thanks for pointing this out. I wasn't aware that the homepage was lagging. The page now has the corrected version.
