### ISSUE TITLE
How to find all polygons that a point can be contained?

### ISSUE THREAD

**Issue by FX-HAO** [tidwall/tile38#168]
Let's say we have the following polygons: 

    SET areas center_1 OBJECT {"type":"Polygon","coordinates":[[[-80.19,25.774],[-66.118,18.466],[-64.757,32.321],[-78.123,40.123],[-80.19,25.774]]]}
    SET areas center_2 OBJECT {"type":"Polygon","coordinates":[[-80.19,15.774],[-66.118,8.466],[-64.757,22.321],[-78.123,30.123],[-80.19,15.774]]}
    SET areas center_3 OBJECT {"type":"Polygon","coordinates":[[[-90.19,25.774],[-76.118,18.466],[-74.757,32.321],[-88.123,40.123],[-90.19,25.774]]]}
    SET areas center_4 OBJECT {"type":"Polygon","coordinates":[[[-80.19,35.774],[-66.118,28.466],[-64.757,42.321],[-78.123,50.123],[-80.19,35.774]]]}

The point:
    
    SET users 1 POINT -80.2828473 25.7666943

How to find all polygons that the point is within? IMO, it's somewhat similar to geofence, but what i want is just the polygons without monitors. Is it possible to do that?

**Comment by m1ome** [comment]
You should use `INTERSECTS`, but it's working with a `BBOX`.

But you can use `GeoJSON` to solve this:
```
INTERSECTS areas OBJECT {"type":"Feature","geometry":{"type":"Point","coordinates":[-80.2828473, 25.7666943]}}
```

Something like this would solve a problem.

**Comment by FX-HAO** [comment]
It seems to work, thanks a lot.

**Comment by m1ome** [comment]
@FX-HAO you are welcome.
