### ISSUE TITLE
Tile38 2.0 progress

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#171]
Tile38 2.0 is in the works and I wanted to share some (very early pre-alpha) benchmarks.

The big internal changes are:

- R-tree data structure is entirely rewritten. It's now a customized R-star like tree with support for 2 and 3 dimensions.
- All Key/value objects have a [new format](https://github.com/tidwall/pair) which take up much less memory per item.
- I finally got around to adding [Redcon](https://github.com/tidwall/redcon) for network IO.

I want to emphasis that this is a very early pre-alpha and I expect that the results will vary when the public preview is released. Though I do expect huge gains across the board.

I hope to have a public preview by end of summer.

```
benchmark             requests    1.9 req/sec    2.0 req/sec     delta
----------------------------------------------------------------------
PING                    100000         229041        4963646    +2067%
PING                    500000         226056        5208402    +2204%
PING                   1000000         214641        5286097    +2363%
SET (point)             100000          41615         147430     +254%
SET (point)             500000          39740         136593     +244%
SET (point)            1000000          36335         132156     +264%
SET (rect)              100000          33259         121971     +267%
SET (rect)              500000          31378         112224     +258%
SET (rect)             1000000          31095         106933     +244%
SET (string)            100000          42239         231126     +447%
SET (string)            500000          38949         213475     +448%
SET (string)           1000000          39883         199476     +400%
GET (point)             100000          57738        1000617    +1633%
GET (point)             500000          55711        1157387    +1977%
GET (point)            1000000          56683         970985    +1613%
GET (rect)              100000          56994         790618    +1287%
GET (rect)              500000          50442         731005    +1349%
GET (rect)             1000000          47233         630950    +1236%
GET (string)            100000          69011        1875410    +2618%
GET (string)            500000          66053        1736211    +2529%
GET (string)           1000000          59194         133974    +2163%
SEARCH (nearby 1km)     100000          29343         536865    +1730%
SEARCH (nearby 1km)     500000          10977         324025    +2852%
SEARCH (nearby 1km)    1000000           5835         177724    +2946%
SEARCH (nearby 10km)    100000          20183         416399    +1963%
SEARCH (nearby 10km)    500000           6395         169021    +2543%
SEARCH (nearby 10km)   1000000           3160          81508    +2479%
SEARCH (nearby 100km)   100000           2875          79229    +2656%
SEARCH (nearby 100km)   500000            576          14754    +2461%
SEARCH (nearby 100km)  1000000            280           6775    +2320%

benchmark             requests         1.9 MB         2.0 MB    delta
---------------------------------------------------------------------
MEMORY USAGE            100000            148             88     -41%
MEMORY USAGE            500000            720            418     -42%
MEMORY USAGE           1000000           1443            839     -42%
```

*Running locally on a MacBook Pro 15" 2.8 GHz Intel Core i7 using Go 1.7*

Commands:

```
tile38-benchmark -p 9851 -q -n 100000 -c 50 -P 64
tile38-benchmark -p 9851 -q -n 500000 -c 50 -P 64
tile38-benchmark -p 9851 -q -n 1000000 -c 50 -P 64
```

**Comment by thisisaaronland** [comment]
We (Who's On First) would be happy to test it on our dev servers. Is there a branch or build somewhere we can try?

**Comment by tidwall** [comment]
@thisisaaronland That's great to hear. I would love any feedback you can provide.

As it stands right now Tile38 2.0 is missing a lot of components such as geofencing, replication, configuration, etc. It only has the PING,GET,SET,NEARBY commands. Maybe I can get a rough alpha branch within the next few week for you to try.

**Comment by m1ome** [comment]
@tidwall 🏆

**Comment by umpc** [comment]
@tidwall Awesome! Thank you for your dedication towards improving this. Looking forward to testing the new tree structure.

**Comment by Lars-Meijer** [comment]
> Maybe I can get a rough alpha branch within the next few week for you to try.

:+1: I would also like this :smile: 


> Running locally on a MacBook Pro 15" 2.8 GHz Intel Core i7 using Go 1.7

The benchmarks where run on the same machine? Any idea of the impact of the new network IO on a test over network? 

> R-tree data structure is entirely rewritten. It's now a customized R-star like tree with support for 2 and 3 dimensions.

Is it mostly threading that has improved, or will it still be beneficial to run a multiple instances on a single core? In other words does a single Tile38 instance on a single thread also see a (major) performance increase?

**Comment by tidwall** [comment]
@Lars-Meijer 👍 I'll let you know asap.

> The benchmarks where run on the same machine? Any idea of the impact of the new network IO on a test over network?

These were run on the same machine. The base network library is Redcon, here's some benchmarks that were done a few months back. https://simongui.github.io/2016/10/24/benchmarking-go-redis-server-libraries.html

> Is it mostly threading that has improved, or will it still be beneficial to run 4 tile instances on 4 cores? In other words does a single Tile38 instance on a single thread also see a (major) performance increase?

Yes, a single threaded server will see the same improvements. The underlying data structure is that much better. Also, a single threaded server will likely be even a little faster for SET than multithreaded in 2.0 because Tile38 will avoid all locking when only one CPU is being used (GOMAXPROCS=1).

Of course with `--appendonly no` it's even more performant.

Overall I expect SETs to be around 1.5x - 3.0x faster in 2.0 (single or multi threaded). 
GETs will be around 5x - 10x faster in single threaded.

**Comment by Lars-Meijer** [comment]
> Of course with --appendonly no it's even more performant.

Will this be an official feature in 2.0?

> Yes, a single threaded server will see the same improvements. The underlying data structure is that much better. Also, a single threaded server will likely be even a little faster for SET than multithreaded in 2.0 because Tile38 will avoid all locking when only one CPU is being used (GOMAXPROCS=1

Thanks for all the work, looking forward to the results and testing with the new version.

**Comment by abelyansky** [comment]
Hello, version 2.0 sounds awesome. Any update as to when it may become available?

**Comment by tidwall** [comment]
@abelyansky 2.0 is still a work in progress. No definite date is set, but I'm hopeful for this year. And yes, it's gonna pretty awesome. :)

**Comment by abelyansky** [comment]
@tidwall - thanks for the update and the hard work involved! am excited to see the alpha version once it's ready.

**Comment by tidwall** [comment]
So I've rolled many of the features and optimization that I planned for v2 into recent v1 releases, including  `--appendonly no`,  `Redcon`, and rtree optimizations. 

I plan on continuing to improve v1 until we need breaking changes that require version 2.

I'm closing this issue for now. Thanks to everyone for all the feedback.
