### ISSUE TITLE
Hooks without appendonly

### ISSUE THREAD

**Issue by Lars-Meijer** [tidwall/tile38#174]
I know it is not an officially supported feature, but is there anyway to make hooks work when the append only file is off? It makes a massive performance difference for me, but if it is too much work please let me know.

Currently I get the following error:
```
goroutine 14 [running]:
github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*Tx).lock(0xc420158600)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:1057 +0x2d
github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*DB).begin(0x0, 0xc420147501, 0x46e604, 0xc420218280, 0xa27140)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:1039 +0x82
github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*DB).managed(0x0, 0x1, 0xc42023cf50, 0x0, 0x0)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:912 +0x53
github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*DB).Update(0x0, 0xc420147750, 0xc420218280, 0xc420147678)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:957 +0x3a
github.com/tidwall/tile38/controller.(*Hook).proc(0xc4202125a0, 0xc42020e620)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/controller/hooks.go:478 +0x143
github.com/tidwall/tile38/controller.(*Hook).manager(0xc4202125a0)
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/controller/hooks.go:427 +0x4a
created by github.com/tidwall/tile38/controller.(*Hook).Open
	/tmp/tile38.r1is/src/github.com/tidwall/tile38/controller/hooks.go:395 +0x13f

```
When executing this command:
SETHOOK kafka kafka://127.0.0.1/tile NEARBY fleet FENCE POINT 0 0 50000

Other hooks have the same behavior and the master branch does not have this problem.

**Comment by tidwall** [comment]
Just to be clear, the error is occurring with the `memoptz` branch and with `--appendonly no` flag?

**Comment by Lars-Meijer** [comment]
> Just to be clear, the error is occurring with the memoptz branch and with --appendonly no flag?

As far as I am aware, yes

**Comment by tidwall** [comment]
At the moment webhooks and replication rely on the AOF pipeline. The `memoptz` `appendonly no` hack breaks that. 

I'm guessing that we can probably fix the problem with some modifications, but I'm not sure how much work it'll take just yet.

In the meantime is it possible to try a workaround (it may be a stretch)  by creating a symbolic link of `/dev/null` -> `data/appendonly.aof`?

Using the 1.9.0 release:

```bash
$ mkdir -p data
$ ln -s /dev/null data/appendonly.aof
$ tile38-server
```

**Comment by Lars-Meijer** [comment]
> In the meantime is it possible to try a workaround (it may be a stretch) by creating a symbolic link of /dev/null -> data/appendonly.aof?

Looks possible, will look into this tomorrow.

**Comment by Lars-Meijer** [comment]
There seems to be still quite an impact on performance, from about 25.1k sets per second to 21.8k sets per second, tho it is better than with the aof enabled, about 19k sets per second.

**Comment by tidwall** [comment]
25k->21k vs 19k doesn't seem like much. 
Regarding the error above, would it be possible to include the full panic report? I'm wondering if the crash is unrelated to turning off appendonly.

**Comment by Lars-Meijer** [comment]
> 25k->21k vs 19k doesn't seem like much.

The difference between 25k/s (no append) and 21k/s (/dev/null) is almost 20%, for now we decided on a different approach for the wanted functionality.   

> Regarding the error above, would it be possible to include the full panic report?

How would one acquire this report? :smile:

**Comment by tidwall** [comment]
Great, that's all I need. Thanks!

**Comment by tidwall** [comment]
This issue has been fixed when we added the "--appendonly no" options a few weeks ago.
