### ISSUE TITLE
Only use JSON output format in 2.0

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#175]
Right now there are two output formats, RESP and JSON. I'm planning to drop the RESP format in 2.0 and only output JSON. IMO this will hugely simplify documentation and also make it much easier to maintain client libraries. It's also makes a lot more sense for users new to Tile38.

Tile38 will still support the Redis protocol as the default, but all responses will be Bulk Strings containing the JSON payload.

I'm looking for feedback so please let me know if anyone objects or has other thoughts.

ping: @phulst, @m1ome, @Lars-Meijer, @amorskoy, @umpc, @beyoung, @mitghi

**Comment by umpc** [comment]
That makes sense to me.

I think that this would work well because it still supports Redis client libraries, and allows a choice for deserialization.

I think that it should be stated clearly in the ```README.md``` though, as the split input/output encoding might be confusing for current Redis users who are new to Tile38.

One thing to consider though: this will break Redis dashboards and RESP output-based tools.

Overall, I think that having less to maintain makes this worth it.

**Comment by m1ome** [comment]
Please use emoji to vote-up and leave your comment.

**Comment by Lars-Meijer** [comment]
Is there any sort of timeline for version 2.0? Are we talking about weeks, months, a year or longer?   

I am not sure how this will impact the my current implementation with Lettuce, I don't think it will have a huge impact, except for maybe the usage of current cursors.

**Comment by tidwall** [comment]
> this will break Redis dashboards and RESP output-based tools.

Good point, system calls such as AUTH, SERVER, PING we'll likely want to keep as RESP. I guess the real issue I'm seeing is with the RESP output of geo object from commands like GET, NEARBY, SCAN, etc.

**Comment by tidwall** [comment]
> Is there any sort of timeline for version 2.0?

It's too early to make promises, but I targeting:

- mid May to push a public 2.0 branch. Won't include geofencing, replication, and system commands.
- mid July for feature completeness
- end of summer for merge with master branch and 2.0 release.

**Comment by m1ome** [comment]
@tidwall need any help from me?

**Comment by tidwall** [comment]
@m1ome 👍 I'll ping you when I push the branch.

**Comment by phulst** [comment]
works for me. I think this should only involve changing a few lines of code. When you have a branch, I can branch the node client as well for testing against your code.

**Comment by tidwall** [comment]
I'll likely do this when I get to v2.0. I'm closing this issue to reduce clutter. Thanks!
