### ISSUE TITLE
Order of arguments

### ISSUE THREAD

**Issue by Lars-Meijer** [tidwall/tile38#177]
While writing documentation for my system I noticed that the following command:
SET fleet truck POINT 1 2

Will result in the following GeoJSON output:
{"type":"Point","coordinates":[2,1]}

Now, the GeoJSON specification specifies a point as "Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, latitude for geographic coordinates)", so the output is complaint. 

Is there any reason that commands have the order lat lon instead of lon lat?

**Comment by tidwall** [comment]
This was a design decision that I made early in development. The lat lon order is very common in geolocation web and mobile APIs such as [Android LocationManager](https://developer.android.com/reference/android/location/LocationManager.html), [iOS CoreLocation](https://developer.apple.com/reference/corelocation/CLLocationCoordinate2D), and Google Maps. These are some of the tech that I've been integrating with for years, and at the time I thought it would be best to align Tile38 with these APIs.

I regret this decision, and I wish everything was XY ordered. 

But the damage is done, at least for 1.X. I've thought about ripping the bandaid off in 2.0, but I haven't decided yet. I'm worried it may be confusing for existing users.

**Comment by Lars-Meijer** [comment]
> This was a design decision that I made early in development. The lat lon order is very common in geolocation web and mobile APIs such as Android LocationManager, iOS CoreLocation, and Google Maps. These are some of the tech that I've been integrating with for years, and at the time I thought it would be best to align Tile38 with these APIs.

ISO 6709 also specifies the yx format while the GeoJSON spec suggests xy, so even standards don't really agree.

> But the damage is done, at least for 1.X. I've thought about ripping the bandaid off in 2.0, but I haven't decided yet. I'm worried it may be confusing for existing users.

For me xy seems more logical since that's is the way axis work in maths. I think if you do decide to change this, it will be more logical for new users, but existing users need to be very aware of the impact of a change to the command structure. 

I don't think it is a huge deal either way, as long as users are aware of it. For now, this issue can be closed.

**Comment by tidwall** [comment]
Thanks for sharing your thoughts.
