### ISSUE TITLE
Getting the geofence an object belongs to

### ISSUE THREAD

**Issue by younisshah** [tidwall/tile38#179]
I have this specific use-case wherein I need to identify in which geofence an object (say a driver or customer) falls in. How would I do it in T38? Also, is there a way to assign an `id` or a `name` to a geofence when it's opened?

**Comment by tidwall** [comment]
Hi @younisshah,

A [webhook](http://tile38.com/commands/sethook/) may be the way to go. You assign a webhook a name and that name is sent to the endpoint along with the geofence event. 

For example, the following hook is named "warehouse".

```
SETHOOK warehouse http://10.0.20.78/endpoint NEARBY fleet FENCE POINT 33.5123 -112.2693 500
```

All events will then include the name, such as:

```json
{
    "command": "set",
    "detect": "enter",
    "hook": "warehouse",
    "time": "2016-03-20T09:37:49.567854293-07:00",
    "key": "fleet",
    "id": "truck02",
    "object": {
        "type": "Point",
        "coordinates": [-112.2695, 33.4626]
    }
}
```

**Comment by younisshah** [comment]
Hi @tidwall,

Thanks for the reply! I'm gonna try this tomorrow! Currently, I'm working on using **PushPin** with **T38**. PushPin sits in front of T38 (leader), clients make WebSocket connections (for GeoFences) with the PushPin which proxies them to T38. I wanted to know if there is a way to delete the GeoFence when the client closes the WS connection.

Appreciated!

**Comment by tidwall** [comment]
You're welcome. :)

**Comment by younisshah** [comment]
Just to confirm: If I delete a hook, is the associated fence also deleted?

**Comment by tidwall** [comment]
> If I delete a hook, is the associated fence also deleted?

Yes
