### ISSUE TITLE
Any plans to get this to work on ARM devices?

### ISSUE THREAD

**Issue by deathg0d** [tidwall/tile38#180]
I am trying to get this to work on an arm device (devices like raspberry pi, odroid). Tile38 looks useful in portable applications. Any plans to support these architectures?

**Comment by tidwall** [comment]
Official releases are x64 Linux, Mac, FreeBSD, and Windows. 

Unofficially Tile38 can be built for:

OS: `android, darwin, freebsd, linux, nacl, netbsd, openbsd, plan9, windows`
Arch: `386, amd64, arm, arm64, mips, mips64`

I'm not sure about Raspberry PI specifically, but perhaps one of these will work:

```
$ GOOS=linux GOARCH=arm make
$ GOOS=linux GOARCH=arm GOARM=6 make
````

**Comment by deathg0d** [comment]
Thanks @tidwall ! Yes it seems to work. I tried this on Odroid xu4. I was missing the correct version of Go and hence was getting few errors. Here's what worked.

Check the architecture. Mine was ARMv7. So first I installed Go accordingly.

```
wget https://github.com/hypriot/golang-armbuilds/releases/download/v1.7.3/go1.7.3.linux-armv7.tar.gz
sudo tar -C /usr/local -xzf go1.7.3.linux-armv7.tar.gz
export PATH=$PATH:/usr/local/go/bin/
```

Then I went to where I had downloaded and extracted tile38 and used the following code as you suggested:
```
GOOS=linux GOARCH=arm make
```

It's working fine so far. Thanks for your help. Will let you know if I find any other issues.

**Comment by tidwall** [comment]
You're welcome and good luck with your project.

**Comment by deathg0d** [comment]
Thanks @tidwall, just one question though. How do I run tile38 on a server as a service? With my limited knowledge I am guessing with `./tile38-server`, the server closes if the terminal closes? I want tile38 to run continuously so that I can connect through a node application.

**Comment by Lars-Meijer** [comment]
> How do I run tile38 on a server as a service?

As far as I know, there is no option to daemonize tile38 build in, so you will need to use either nohup (http://linux.101hacks.com/unix/nohup-command/), which allows programs to ignore the signal for a closing terminal or screen https://help.ubuntu.com/community/Screen which allows you to create virtual terminals.

There are other methods but I prefer the screen method.

**Comment by tidwall** [comment]
Also if you want to have Tile38 load at boot, you can add a command to the /etc/rc.local script like:

```
/path/to/tile38-server &
```

This will launch Tile38 in the background with the system boots up. Make sure to the change the `/path/to` prefix to the root directory of the `tile38-server` executable.

https://www.raspberrypi.org/documentation/linux/usage/rc-local.md

**Comment by deathg0d** [comment]
Thanks @Lars-Meijer and @tidwall. I will give these options a go. I will let you know if I run into issues.
