### ISSUE TITLE
Deploying in Google App Engine

### ISSUE THREAD

**Issue by Drugantibus** [tidwall/tile38#188]
Hi, 

I'm having trouble deploying tile38 to the Google App Engine. I can start the server just fine, but can't connect directly to it. I admittedly have to experience working in neither GAE or other similar services (AWS, Digital Ocean, etc.). I have looked at Google's documentation, but it really isn't helpful (at least for Go). 

This is the error returned from running `gcloud app deploy`:

```
failed analyzing /home/***/tile38-source: could not get package for dir "/home/***/tile38-source": no buildable Go source files in /home/***/tile38-source
GOPATH: /home/***/gopath:/google/gopath
```

Am I simply doing something wrong or isn't it possible to deploy tile38 in this kind of environment?

**Comment by tidwall** [comment]
Unfortunately, I don't have any experience with GAE and I was hoping that someone who does might chime in. I'm closing this issue for now but if anyone out there has a solution, please feel free to reopen. Thanks.
