### ISSUE TITLE
WITHIN OBJECT command with WHERE z?

### ISSUE THREAD

**Issue by mmcloughlin** [tidwall/tile38#192]
I was hoping the last `WITHIN` command here would return the point `inside2`. It actually returns nothing.

```
$ tile38-cli
127.0.0.1:9851> FLUSHDB
{"ok":true,"elapsed":"4.37µs"}
127.0.0.1:9851>
127.0.0.1:9851> SET test outside1 POINT 15.20 52.58 1
{"ok":true,"elapsed":"18.225µs"}
127.0.0.1:9851> SET test outside2 POINT 15.20 52.58 2
{"ok":true,"elapsed":"6.091µs"}
127.0.0.1:9851>
127.0.0.1:9851> SET test inside1 POINT 46.49 52.37 1
{"ok":true,"elapsed":"5.861µs"}
127.0.0.1:9851> SET test inside2 POINT 46.49 52.37 2
{"ok":true,"elapsed":"4.784µs"}
127.0.0.1:9851>
127.0.0.1:9851> WITHIN test OBJECTS OBJECT '{"type":"Polygon","coordinates":[[[33.75,43.45],[59.32,43.45],[59.32,59.17],[33.75,59.17],[33.75,43.45]]]}'
{"ok":true,"objects":[{"id":"inside1","object":{"type":"Point","coordinates":[52.37,46.49,1]}},{"id":"inside2","object":{"type":"Point","coordinates":[52.37,46.49,2]}}],"count":2,"cursor":0,"elapsed":"82.687µs"}
127.0.0.1:9851> WITHIN test WHERE z 1.5 2.5 OBJECTS OBJECT '{"type":"Polygon","coordinates":[[[33.75,43.45],[59.32,43.45],[59.32,59.17],[33.75,59.17],[33.75,43.45]]]}'
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"35.083µs"}
```

What is the correct way to perform this query? Or is this unsupported, or even a bug?

**Comment by tidwall** [comment]
I'll have to do a little more digging but this may be a bug (or at least a quirk). Currently GeoJSON polygons are limited to 2D. The Z where clause puts the query engine into 3D mode so the polygon is being ignored. 

It's possible that this could be corrected, but in the meantime you can use `BOUNDS` instead:

```
127.0.0.1:9851> WITHIN test WHERE z 1.5 2.5 OBJECTS BOUNDS 43.45 33.75 59.17 59.32
{"ok":true,"objects":[{"id":"inside2","object":{"type":"Point","coordinates":[52.37,46.49,2]}}],"count":1,"cursor":0,"elapsed":"34.078µs"}
```

This would likely be a more efficient operation in the long run.

**Comment by mmcloughlin** [comment]
Thanks for the quick response. Given the internals you described the behavior makes sense. If the fix isn't easy, I'd suggest documenting this.

I used a box in the test case for simplicity, but my use case requires complex polygons so `BOUNDS` won't work.

I think I'll use a named field instead of `z`. Performance is worse but it should still be fine for our application.

**Comment by tidwall** [comment]
For a future release, I think it's possible that the system might be able detect that polygon is 2D and do a BOUNDS with Z under the hood. The process the WITHIN on the results. 

Thanks for filing this issue.

**Comment by tidwall** [comment]
FYI, I just pushed an update that happens to address this issue. There's nothing tricky being done, it just queries over 2D and then filters the results on Z.
