### ISSUE TITLE
JSET issue

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#193]
Hi,
I enter commond "http://localhost:9852/jset+a+c+properties.object+{"type": "PointString","coordinates": [112.125249675955,31.0669205188914]}",then,the commond "http://localhost:9852/scan+a" was used,
But i got an undesired result "{"ok":true,"objects":[{"id":"c","object":"{\"properties\":{\"object\":\"{\\\"type\\\": \\\"PointString\\\",\\\"coordinates\\\"[112.125249675955,31.0669205188914]}\"}}"}],"count":2,"cursor":0,"elapsed":"0s"}".
Obviously, the innermost layer is not parsed, because there is an extra layer of quotation marks outside {}.
Is this a bug? Looking forward to your reply

**Comment by GameFreedom** [comment]
Looking forward to your reply

**Comment by m1ome** [comment]
The thing you wanna to achive is:

```
SET a c OBJECT {"type":"Point","coordinates": [112.125249675955,31.0669205188914]}
> {"ok":true,"elapsed":"8.177499ms"}
```

And then:

```
SCAN a
> {"ok":true,"objects":[{"id":"c","object":{"type":"Point","coordinates":[112.125249675955,31.0669205188914]}}],"count":1,"cursor":0,"elapsed":"8.374809ms"}
```

Why do you use **JSET** for setting object coordinates?
In GeoJSON specification there is no . such thing as `PointString` according to RFC.

In your case 

```
JSET a d properties.object {"type":"PointString","coordinates": [112.125249675955,31.0669205188914]}
```

And retrieving:
```
SCAN a
> {"ok":true,"objects":[{"id":"c","object":{"type":"Point","coordinates":[112.125249675955,31.0669205188914]}},{"id":"d","object":"{\"properties\":{\"object\":\"{\\\"type\\\":\\\"PointString\\\",\\\"coordinates\\\": [112.125249675955,31.0669205188914]}\"}}"}],"count":2,"cursor":0,"elapsed":"6.1471ms"}
```

And this is seems like a good/valid JSON. You just need to strip-slashes.
