### ISSUE TITLE
Delete a Geofence

### ISSUE THREAD

**Issue by younisshah** [tidwall/tile38#194]
Hey Josh, 

I am struggling with a problem. I have to delete a geofence which I created using the `NEARBY` command without setting a webhook for it. 

Is there a way to delete such geofences?

**Comment by tidwall** [comment]
Hi Younis,

You can close a live geofeonce by issuing a `QUIT` command from the client that initiated the fence. It's also safe to just close the client connection altogether. 

The client connection that opened a live geofence is the only one that can close it.

**Comment by younisshah** [comment]
Hey Josh,

Thanks for the reply. I will give it a spin!

**Comment by tidwall** [comment]
You're welcome!
