### ISSUE TITLE
Ability to specify the pidfile via args in FreeBSD

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#20]
Currently the pidfile must be managed outside the application. Adding an arg to the startup process will streamline this process. See #19.

**Comment by tidwall** [comment]
@olevole I was thinking I would add a parameter named `--pidfile`. When provided the process would daemonize. Does this seem like a reasonable approach?

**Comment by olevole** [comment]
@tidwall Absolutely! Currenlty, i've made rc.d script for FreeBSD:

http://pastebin.com/jPmpqrwx

where i got pid from daemon(8). It is necessary for correct stop command; with --pidfile tile38 would be self-sufficient for rc.d subsystem.

**Comment by tidwall** [comment]
@olevole Apparently daemonizing a Go app is a little more challenging that I expected. I was hoping for a simple solution by just forking and rerouting logging and such. But fork and posix threads don't always play well with Goroutines. It sometimes works, but isn't totally stable.

There's a whole long discussion about it dating back to 2009. https://github.com/golang/go/issues/227

There may still be a way yet, but it may take more tinkering on my side. Sorry for the delay on this. I'll keep you posted when I find a stable solution.

**Comment by olevole** [comment]
Thank you very much!

**Comment by tidwall** [comment]
You're welcome and sorry about the delay.
