### ISSUE TITLE
StackExchange of C# cannot connect successfully

### ISSUE THREAD

**Issue by yorkxiao** [tidwall/tile38#201]
Great job!
I'm in trouble When connecting to the server using StackExchange client. When connecting, the server output the message 'An existing connection was forcibly closed by the remote host.'
Can you help me? thx! 
Here is my code snippet:

```
using (ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("127.0.0.1:9851"))
{
	IDatabase db = redis.GetDatabase();
	var result = db.Execute("NEARBY", "fleet POINT 33.462 -112.268 6000".Split(' '));
	Console.WriteLine(result);
}
```

**Comment by yorkxiao** [comment]
It is ok when I using redis-cli.
![qq 20170726233435](https://user-images.githubusercontent.com/12769474/28629844-24f5df36-725b-11e7-9125-5ce75dcb8fc5.png)

**Comment by tidwall** [comment]
According to this [article](http://blog.marcgravell.com/2017/04/stackexchangeredis-and-redis-40-modules.html) you may want to separate the params individually.

```
db.Execute("NEARBY", "fleet", "POINT", "33.462", "-112.268", "6000");
```

**Comment by yorkxiao** [comment]
Hi, @tidwall , Thank you for your reply. But the error happens on the method "ConnectionMultiplexer.Connect". The error message is :  

> It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketClosed on PING

If I use ServiceStack.Redis library, the error will be "No master found".

**Comment by tidwall** [comment]
I just pushed an update to the master branch that fixes the exception with `StackExchange.Redis`.

The problem was that the StackExchange client sent an `ECHO` command while establishing a new connection, and Tile38 didn't know that command so it responded with `-ERR unknown command`. 

I added the `ECHO` command to Tile38 and now it appears to work better.

**Comment by yorkxiao** [comment]
That is great! Thanks!

**Comment by tidwall** [comment]
You're welcome. 😊
