### ISSUE TITLE
Nearby not working with two dimension MultiPolygon

### ISSUE THREAD

**Issue by francescguiuturmo** [tidwall/tile38#204]
Hello tidwall,

We are using Nearby command with MultiPolygon geometries. We realised that Tile38 is not working fine when we use two dimensions MultiPolygon and the point that we test is close to the second position of the coordinates array.

Some testing data:

- MultiPolygon insertion: **SET TEST 1 OBJECT {"type":"Feature","id":"1","geometry":{"type":"MultiPolygon","coordinates":[[[[2.103906,41.342235],[2.103612,41.342708],[2.103716,41.343225],[2.105384,41.344511],[2.105904,41.345144],[2.107149,41.345884],[2.10792,41.345917],[2.108514,41.345647],[2.108949,41.345056],[2.108824,41.344483],[2.10801,41.343509],[2.107,41.342711],[2.105998,41.342046],[2.105206,41.341745],[2.104519,41.341824],[2.103906,41.342235]],[[2.09764,41.342292],[2.098168,41.343],[2.099051,41.343179],[2.100168,41.342839],[2.100534,41.342395],[2.100565,41.342044],[2.100048,41.341314],[2.098689,41.341038],[2.097802,41.341407],[2.097558,41.341896],[2.09764,41.342292]]]]}}**

- SUCCESS TEST: **NEARBY TEST LIMIT 10 NOFIELDS DISTANCE POINT 41.342946605207004 2.10662841796875 1**

- FAIL TEST: **NEARBY TEST LIMIT 10 NOFIELDS DISTANCE POINT 41.34173030699962 2.1000301837921143 1**

We really appreciate any help you can provide.

**Comment by tidwall** [comment]
Hi Francesc,

I think your geojson may be the problem. The geometry that you specified is basically a single polygon with an outer and inner ring.

![image](https://user-images.githubusercontent.com/1156077/28834447-1afb05b6-7697-11e7-8105-7cb6b6444553.png)

But I'm guessing that what you are wanting is a geometry where each ring is an independent polygon instead. Here's a modified version that passes your tests.

```json
{
  "type":"Feature",
  "geometry": {
    "type":"MultiPolygon",
    "coordinates": [
      [
        [
          [2.103906,41.342235],[2.103612,41.342708],
          [2.103716,41.343225],[2.105384,41.344511],
          [2.105904,41.345144],[2.107149,41.345884],
          [2.10792,41.345917],[2.108514,41.345647],
          [2.108949,41.345056],[2.108824,41.344483],
          [2.10801,41.343509],[2.107,41.342711],
          [2.105998,41.342046],[2.105206,41.341745],
          [2.104519,41.341824],[2.103906,41.342235]
        ]
      ],
      [
        [
          [2.09764,41.342292],[2.098168,41.343],
          [2.099051,41.343179],[2.100168,41.342839],
          [2.100534,41.342395],[2.100565,41.342044],
          [2.100048,41.341314],[2.098689,41.341038],
          [2.097802,41.341407],[2.097558,41.341896],
          [2.09764,41.342292]
        ]
      ]
    ]
  },
  "id":"1"
}
```

Let me know if this helps.

**Comment by francescguiuturmo** [comment]
Hi tidwall,

You're right. After I opened the issue we were discussing the format of the coordinates.

My apologies for taking your time and thank you very much!
