### ISSUE TITLE
Intersects throws an exception when the key not found 

### ISSUE THREAD

**Issue by FX-HAO** [tidwall/tile38#207]
By now, `intersects` will throw an exception if the key isn't set (as well as empty), does it make sense to throw an exception instead of returning an empty result? it crashed my program and i don't know how to catch it (in golang). And I found that `nearby` returns an empty result when the key was not found, why it doesn't throw an exception as same as `intersects`.

**Comment by tidwall** [comment]
Hi FX-HAO,

I'm not seeing the same problem, I just tried:

```
127.0.0.1:9851> INTERSECTS test BOUNDS 33 -115 34 -114
(error) key not found
```

Could you provide an example of the `INTERSECTS` command causing the error?

**Comment by FX-HAO** [comment]
```
tile38:9851> scan test
1) (integer) 0
2) (empty list or set)
tile38:9851> nearby test point 12 34 1000
1) (integer) 0
2) (empty list or set)
tile38:9851> INTERSECTS test BOUNDS 33 -115 34 -114
(error) ERR key not found
```

```go
vals, err := redis.Values(conn.Do("INTERSECTS", "test", "BOUNDS", 33, -115, 34, -114))
if err != nil { 
        // this will be called if the key is empty
	log.Panicf("could not INTERSECTS: %v\n", err) 
}
...
```

**Comment by tidwall** [comment]
The panic is being caused by your client code, not the Tile38 server.

Changing the line in your code from:

```go
log.Panicf("could not INTERSECTS: %v\n", err); 
```

to

```go
log.Printf("could not INTERSECTS: %v\n", err);
```

will stop the panic.

**Comment by FX-HAO** [comment]
But i got the error from redis connection, so i should just ignore it? Why `intersects` does not return an empty result like what `nearby` did.

**Comment by tidwall** [comment]
:) I see what you're saying now and I agree that this is a valid issue. I agree that NEARBY/INTERSECTS/SEARCH/SCAN should return empty result when a key is not found.

I just pushed an update to the master branch that fixes this problem.   

Thanks for reporting this issue!
