### ISSUE TITLE
Please document the DETECT option intruduced in version 1.1.0

### ISSUE THREAD

**Issue by mozinator** [tidwall/tile38#21]

**Comment by tidwall** [comment]
Thanks for letting me know. I just updated the online documentation on the commands/intersects and topics/geofencing pages.

http://tile38.com/commands/intersects
http://tile38.com/topics/geofencing

**Comment by tidwall** [comment]
@mozinator I'm closing this issue for now. If you think that there's anything I should add to the docs, feel free to reopen this issue. Thanks again.

**Comment by mozinator** [comment]
Looks good, thank you !
