### ISSUE TITLE
After the aofshrink command is executed, the service crashes

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#211]
When the aofshrink command is executed through the browser
`http://localhost:8801/aofshrink`

A file named "shrink" is generated under the service directory, and then the service crashes  after a few seconds.
Using the tile38 client to perform the aofshrink operation, the same result occurs.

Is that the design?

Is there a setting to automatically execute aofshrink? If so, how do I open and close this setting?

**Comment by tidwall** [comment]
That's not by design. Did a panic message happen to print to the console?

**Comment by icewukong** [comment]
The program has exited since this error occurred.
Running in IDE, error is as follows: 
`2017/08/11 08:50:41 [FATA] shink backup fatal operation: rename data/appendonly.aof data/appendonly.bak: The process cannot access the file because it is being used by another process.`

**Comment by tidwall** [comment]
Which OS are you running?

**Comment by icewukong** [comment]
windows 7 64bit

**Comment by icewukong** [comment]
No problems occurred after execution on centos7

**Comment by tidwall** [comment]
I just pushed a fix to the master branch. The shrink process atomically renames a file while it's currently in use. This is normally OK for Linux, BSD, and Mac, but not for Windows.
