### ISSUE TITLE
Tile38 load Test

### ISSUE THREAD

**Issue by fmr683** [tidwall/tile38#212]
Let say I'm using following tile38 command:

let query = client.intersectsQuery('fleet').bounds(33.462, -112.268, 33.491, -112.245);
query.execute(function(results).then(results => {
    console.dir(results);  // results is an object.
}).catch(err => {
    console.error("something went wrong! " + err);
)};

And performing a load test with 500 request per second (with 10 concurrent users). Will this execute one by one? or will it execute all at once with no time at all? 

In case if it's executing one by one, how can I improve it make it faster? OR would it be ideal to use the directly use the https://github.com/NodeRedis/node_redis for large number request use/accept applications?

**Comment by tidwall** [comment]
Hi @fmr683,

> Will this execute one by one? or will it execute all at once with no time at all?

I'm not sure. Are you using the https://github.com/phulst/node-tile38 library? 

> In case if it's executing one by one, how can I improve it make it faster? OR would it be ideal to use the directly use the https://github.com/NodeRedis/node_redis for large number request use/accept applications?

I think node-tile38 uses https://github.com/NodeRedis/node_redis under the hood. The node_redis library is very well tuned for high throughput. I think it's a good idea to try both libraries and compare the results. 

Ultimately performance is going to come down to the search area size and how many objects overlap that area. 

There's also the `tile38-benchmark` tool, which comes installed alongside `tile38-server`. It tests the performance of the server by adding a bunch of random objects to a collection and running a few queries of varying area sizes. The results are generally better than 500 ops/sec.
