### ISSUE TITLE
WHEREIN clause has no effects on command SCAN

### ISSUE THREAD

**Issue by yorkxiao** [tidwall/tile38#217]
Hi, @tidwall , **WHEREIN** is a so useful clause for me, so I try it right away. And I found that it works correctly on command **NEAYBY**, but it has no effects on **SCAN** .

**Comment by tidwall** [comment]
hi @yorkxiao,

I'm not seeing a problem with SCAN and WHEREIN from my side. 
Could you provide an example of the issue?

**Comment by yorkxiao** [comment]
hi, @tidwall , thanks for you reply.
I'm sorry, I should provide an the exact case.
This problem will happen when SCAN command excute with WHEREIN and COUNT options. Here is a sample:
```
10.88.6.61:9851> SCAN lwlk.vehicle.loc.now wherein hangyeid 1 11 count
(integer) 313685
10.88.6.61:9851> nearby lwlk.vehicle.loc.now wherein hangyeid 1 11 count point 11 111 99999999999999
(integer) 19668
10.88.6.61:9851> SCAN lwlk.vehicle.loc.now wherein hangyeid 1 12 count
(integer) 313689
10.88.6.61:9851> nearby lwlk.vehicle.loc.now wherein hangyeid 1 12 count point 11 111 99999999999999
(integer) 5867
```
The problem maybe is a bug with the issue #203, I think.

**Comment by tidwall** [comment]
Yes this looks like a a bug.

**Comment by tidwall** [comment]
I just pushed an update to the master branch that fixes this issue. Let me know if you see further problems around this issue.  Thanks!
