### ISSUE TITLE
How do get more TILE38 running logs?

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#218]
@tidwall ,
i sometimes experience service down. the log at the exception of the time point, only " hangup " information.
 i have used the -vv parameter 

thanks!

tile38 server log: 
   _______ _______
  |       |       |
  |____   |   _   |   Tile38 1.9.1 (9cdbea1) 64 bit (amd64/linux)
  |       |       |   Port: 7851, PID: 10287
  |____   |   _   | 
  |       |       |   tile38.com
  |_______|_______| 

2017/08/31 17:20:18 [36m[INFO][0m Server started, Tile38 version 1.9.1, git 9cdbea1
2017/08/31 17:20:18 [36m[INFO][0m AOF loaded 4 commands: 0.00s, 15662/s, 8 MB/s
2017/08/31 17:20:18 [36m[INFO][0m The server is now ready to accept connections on port 7851
2017/08/31 17:22:17 [35m[DEBU][0m opened connection: 127.0.0.1:54783
2017/08/31 17:22:17 [36m[INFO][0m aof shrink ended 11.300735ms
2017/08/31 17:22:51 [35m[DEBU][0m opened connection: 127.0.0.1:55275
2017/08/31 17:22:58 [35m[DEBU][0m closed connection: 127.0.0.1:55275
2017/08/31 17:26:33 [35m[DEBU][0m opened connection: 127.0.0.1:57193
2017/08/31 17:26:52 [35m[DEBU][0m closed connection: 127.0.0.1:57193
2017/08/31 17:27:08 [35m[DEBU][0m opened connection: 127.0.0.1:57569
2017/08/31 18:22:17 [36m[INFO][0m aof shrink ended 12.002162ms
2017/08/31 19:22:17 [36m[INFO][0m aof shrink ended 10.895258ms
2017/08/31 19:46:08 [33m[WARN][0m signal: hangup
2017/08/31 19:46:08 [35m[DEBU][0m closed connection: 127.0.0.1:57569

:)

**Comment by tidwall** [comment]
Does the server stop after the "signal: hangup" message?

**Comment by huangpeizhi** [comment]
i did not take the initiative to shut down the tile38 system, the service is to quit, but the log is only this line.
I started the service using the nohup server& mode.

**Comment by huangpeizhi** [comment]
I don't know how to collect information to determine where the problem is.

**Comment by huangpeizhi** [comment]
such as github.com/google/gops
:)

**Comment by tidwall** [comment]
Cool tool. Do you think it might help to find the problem?

**Comment by huangpeizhi** [comment]
yes.

**Comment by huangpeizhi** [comment]
Hi, @tidwall,
sometimes TILE38 suddenly DOWN, I don't know what caused it(self or OS?). 
i also recommended that you have the option to turn off AOFSHRINK.

**Comment by tidwall** [comment]
Are you seeing the problem during the AOFSHRINK operation? Do you see the problem elsewhere?

**Comment by huangpeizhi** [comment]
I've had a AOFSHRINK pause before.
Recently, several tile38 services startup at the same time, and at the same time this batch of simultaneous down phenomena occurred.
Still checking what causes it.

**Comment by huangpeizhi** [comment]
These days have been running stable, I close the issue.
