### ISSUE TITLE
tile38 drops properties

### ISSUE THREAD

**Issue by Yugloocamai** [tidwall/tile38#219]
tile38 SET command will not store GeoJSON properties.

`
SET fleet test OBJECT {
   "features":[
      {
         "geometry":{
            "coordinates":[
               [
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ],
                  [
                     -117.97119140625,
                     33.815666308702774
                  ],
                  [
                     -117.70751953125,
                     34.05265942137599
                  ],
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ]
               ]
            ],
            "type":"Polygon"
         },
         "properties":{},
         "type":"Feature"
      }
   ],
   "properties":{
      "cityName":"shooby",
      "continent":"North America",
      "country":"USA",
      "subdivisions":"shoob county"
   },
   "type":"FeatureCollection"
}
`

I would expect to **GET fleet test** to be:

`
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ],
                  [
                     -117.97119140625,
                     33.815666308702774
                  ],
                  [
                     -117.70751953125,
                     34.05265942137599
                  ],
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ]
               ]
            ]
         },
         "properties":{
           "cityName":"shooby",
           "continent":"North America",
           "country":"USA",
           "subdivisions":"shoob county"
         }
      }
   ]
}
`

But instead I get: 

`
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ],
                  [
                     -117.97119140625,
                     33.815666308702774
                  ],
                  [
                     -117.70751953125,
                     34.05265942137599
                  ],
                  [
                     -118.27880859375001,
                     33.779147331286474
                  ]
               ]
            ]
         },
         "properties":{}
      }
   ]
}
`

The properties object is empty.  The home page of [GeoJSON.org](http://geojson.org/) shows an example of "properties" as a valid GeoJSON property, and if you read the spec you'll see it being used:

`
{
       "type": "Feature",
       "id": "f1",
       "geometry": {...},
       "properties": {...},
       "title": "Example Feature"
}
`

I think tile38 should save "properties" as an arbitrary JSON object.

**Comment by tidwall** [comment]
A FeatureCollection should only have the `type` and `features` members. A Feature is the only type that allows for the `properties` and `id` fields.

[RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.2)

Unfortunately as it stands right now Tile38 drops all non-conforming GeoJSON members.

If you need the properties at the top-level perhaps you can wrap the FeaturesCollection inside a Feature object like this:

```json
{
    "type": "Feature",
    "geometry":{
        "type": "FeatureCollection",
        "features": [
            {
                "type":"Feature",
                "geometry": {
                    "type":"Polygon",
                    "coordinates": [[
                        [-118.27880859375001,33.779147331286474],
                        [-117.97119140625,33.815666308702774],
                        [-117.70751953125,34.05265942137599],
                        [-118.27880859375001,33.779147331286474]
                    ]]
                },
                "properties":{}
            }
        ]
    },
    "properties":{
        "cityName": "shooby",
        "continent": "North America",
        "country": "USA",
        "subdivisions": "shoob county"
   }
}
```

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if needed. 

Thank you!
