### ISSUE TITLE
Disable AOF

### ISSUE THREAD

**Issue by sign0** [tidwall/tile38#220]
Hello everyone,

Is it possible to disable AOF on a Tile38 instance?
I do not have a SSD, and I think that my intensive writes are at the origin of a bottleneck...

Thank you

**Comment by tidwall** [comment]
Hi @sign0,

There's isn't an explicit option to disable AOF at the moment.

But it's possible to symlink the AOF file to `/dev/null`

```bash
$ cd data
$ ln -s /dev/null appendonly.aof
```

Also avoid the `AOFSHRINK` command when using a symlink.

I hope to add an `--appendonly no` flag in the future.

**Comment by sign0** [comment]
Thanks for your advice !

This is really problematic for me, because in 4 days of use, the file already weighs 570GB, to store only data with TTL ...

Moreover, I feel like having another bug (EPIPE) after a few days of intensive use (dozens of inserts containing hundreds of big dots via the redis protocol). But I'm not sure that the bug comes from you, although I directly pipe the data into nodeJS via spawn and redis-cli --pipe (I believe that is the case because the problem occurs after several days). And the problem persists as long as I do not have "hard flush" Tile38.

`events.js:160`
`      throw er; // Unhandled 'error' event`
`      ^`

`Error: write EPIPE`
`    at exports._errnoException (util.js:1020:11)`
`    at WriteWrap.afterWrite (net.js:800:14)`

Anyway, I'm really a fan of tile38, I really looked for months before finding you! :)
