### ISSUE TITLE
How to disable appendonly.aof file in tile38 ?

### ISSUE THREAD

**Issue by fmr683** [tidwall/tile38#223]
Hi all,

Can we disable the Append Only File (AOF) in the tile38 (data/appendonly.aof) ? As it increase the disk space. 

May I know what's the purpose of that file? and by disabling it will there be any affect?

Thanks,
Fazlul

**Comment by umpc** [comment]
It can be disabled, though there is not yet an option to do so from within Tile38.

Please see issue #220 for the workaround and a potential pitfall, as this issue is a duplicate.

**Comment by tidwall** [comment]
I just pushed an update to the master branch that allows for disabling the AOF file.
