### ISSUE TITLE
calculate distance

### ISSUE THREAD

**Issue by tjgillies** [tidwall/tile38#233]
Is there a way to get distance between two objects?

**Comment by tidwall** [comment]
Sorry. There's isn't a command that just returns the distance two object. You'll need to pull down the objects and perform the calculation on your side.  Though it would seem like a useful builtin function.

**Comment by abhit011** [comment]
Haversine is what you need to use ... 

Abhi
!wq

**Comment by abhit011** [comment]
@kirantpatil 
Haversine is the arial Distance and its going to return you line of arc distance , because of shape of earth. 
Now if you have to calculate the ROAD Distance depending upon the mode <Driving|cycling|walking> ,you need to use google distance api 

:wq

**Comment by kirantpatil** [comment]
Got it. Thanks a lot.
