### ISSUE TITLE
consistent NEARBY sorting across servers

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/tile38#236]
I'm thinking maybe the issue I am seeing was addressed here, but I'm not certain:

https://github.com/tidwall/tile38/issues/195#issuecomment-316474297

We have two separate T38 instances each with the same data that return the same results for a given query, but in different orders. For example:

```
# tl-1

127.0.0.1:9851> NEARBY whosonfirst WHERE wof:placetype_id 102312319 102312319 LIMIT 100 IDS POINT 37.766633 -122.417693 1
{"ok":true,"ids":["85887443#whosonfirst-data","85834637#whosonfirst-data"],"count":2,"cursor":0,"elapsed":"112.50519ms"}

# tl-2

NEARBY whosonfirst WHERE wof:placetype_id 102312319 102312319 LIMIT 100 IDS POINT 37.766633 -122.417693 1
{"ok":true,"ids":["85834637#whosonfirst-data","85887443#whosonfirst-data"],"count":2,"cursor":0,"elapsed":"111.925704ms"}
```

As best I can tell the two servers are basically the same:

```
# tl-1

127.0.0.1:9851> server
{"ok":true,"stats":{"aof_size":34552183312,"avg_item_size":80,"heap_released":16371761152,"heap_size":21725549552,"http_transport":true,"id":"744703bb896f3db3425d50cb8ad302da","in_memory_size":10339992111,"max_heap_size":0,"mem_alloc":21725549552,"num_collections":1,"num_hooks":0,"num_objects":48715936,"num_points":268600322,"num_strings":24357968,"pid":12977,"pointer_size":8,"read_only":false},"elapsed":"138.417µs"}

# tl-2

127.0.0.1:9851> server
{"ok":true,"stats":{"aof_size":34552183312,"avg_item_size":80,"heap_released":15087968256,"heap_size":21697922416,"http_transport":true,"id":"9d9164e197a0ba503cc12ac743e8bc72","in_memory_size":10339992111,"max_heap_size":0,"mem_alloc":21697922416,"num_collections":1,"num_hooks":0,"num_objects":48715936,"num_points":268600322,"num_strings":24357968,"pid":12975,"pointer_size":8,"read_only":false},"elapsed":"111.65µs"}
```

Each server appears to return the same individual ordering consistently but not with its complimentary server. Is this a known-known ?

**Comment by tidwall** [comment]
That sounds like a bug. Which version are you running? There's been a few updates around the kNN logic over the past month or so that are sitting in the master branch.

**Comment by thisisaaronland** [comment]
We are running `1.9.1`

**Comment by tidwall** [comment]
Is there a WOF dataset that I can publicly download that will reproduce what you are seeing?

**Comment by thisisaaronland** [comment]
Yes, you can test with this:

https://github.com/whosonfirst-data/whosonfirst-data

We index T38 using this:

https://github.com/whosonfirst/go-whosonfirst-tile38/blob/master/cmd/wof-tile38-index.go

For example:

```
./bin/wof-tile38-index --tile38-collection whosonfirst --mode repo /path/to/whosonfirst-data
```

**Comment by tidwall** [comment]
Thanks. I'll keep you posted

**Comment by tidwall** [comment]
I noticed that your query is asking for up to 100 IDs that are within 1 meter of 37.766633,-122.417693 where wof:placetype_id is 102312319. 

In your NEARBY query, is the value of "1" for the meters param intentional?

If so, then Tile38 is working as expected, because the order of the results will be undefined for NEARBY searches that include the meters param. This is not a kNN search, but rather a regular within radius search.

If you exclude the meters param then it will be a kNN search and the order will be nearest to farthest.

**Comment by s32x** [comment]
Hey @thisisaaronland, It's been a while since we've heard back from you on this issue. Since it sounds like the system was working as expected and a solution was given we hope that has solved your issue. If not feel free to re-open this issue!
