### ISSUE TITLE
How many keys supported?

### ISSUE THREAD

**Issue by masagatech** [tidwall/tile38#238]
Hi, 
What is key limitation & what is impact on performance if has many(50000) keys?

My project model is 
 Truck1 > 50 POINTS
 Truck2 > 100 POINTS
 ....
What would be the approach?
Thanks in advance.

**Comment by tidwall** [comment]
The keys are stored in a btree (so the performance is O(log n)) and there's no limit to the number of keys.

**Comment by masagatech** [comment]
Thanks @tidwall
