### ISSUE TITLE
How to query the maximum and minimum of a field in a set ?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#239]
Hi @tidwall 
I haven't been here for a long time to ask for advice :)

My requirement like this:
I have a set named "fleet" and it has a field named "age",  I want to find the objects that  have maximum or minimum of the field "age" in the "fleet" without traversal.

The command would be like: scan fleet where age MINVALUE, and return the object.

Because field has been indexed, I think it should be easy to implement. Or you have any good suggestion.

**Comment by tidwall** [comment]
Hi @icewukong,

Unfortunately I don't think this possible at this time because there's no way to sort by a field value. 

As a workaround, you could add the separate STRING value which is alphabetically sorted.

```
> SET fleet truck1 POINT 33.45 -115.45
> SET fleet:age truck1 STRING 25
> SET fleet truck2 POINT 32.46 -114.46
> SET fleet:age truck2 STRING 24
> SET fleet truck3 POINT 31.47 -113.47
> SET fleet:age truck3 STRING 31
```
```
> SEARCH fleet:age LIMIT 1
```

**Comment by icewukong** [comment]
OK, is this feature possible to be implemented in 2.x ?

**Comment by tidwall** [comment]
I'll certainly consider it. The challenging part is around making the operation fast. I wouldn't want the operation to be O(1). I would need to create an index for each field. A collection with a lot of fields could be a big cost in terms of memory.

Perhaps we can have a special command(s) that is specifically made to index fields, and search on field.

**Comment by icewukong** [comment]
That's true. 
It's up on you whether it is necessary to close this issue.

**Comment by tidwall** [comment]
I'm closing this issue for now, but I may return to it in the future. Thanks

**Comment by kirantpatil** [comment]
Hi @tidwall 

It doesn't holds good in scenario where I am trying to get the fleet with less travelled in kms as below. You can clearly see that I have three fleets having run 19, 193 and 20 kms. I want to list the least run trucks and it shows 19 and 193 instead of 19 and 20

```
127.0.0.1:9851> SET fleet:kms truck1 STRING 19
{"ok":true,"elapsed":"34.039µs"}
127.0.0.1:9851> 
127.0.0.1:9851> SET fleet:kms truck2 STRING 193
{"ok":true,"elapsed":"29.639µs"}
127.0.0.1:9851> 
127.0.0.1:9851> SET fleet:kms truck3 STRING 20
{"ok":true,"elapsed":"28.136µs"}

127.0.0.1:9851> search fleet:kms limit 2
{"ok":true,"objects":[{"id":"truck1","object":"19"},{"id":"truck2","object":"193"}],"count":2,"cursor":2,"elapsed":"59.58µs"}



```

**Comment by tidwall** [comment]
Adding zero prefixes should make them numerically sortable.

```
> SET fleet:kms truck1 STRING 0019
> SET fleet:kms truck2 STRING 0193
> SET fleet:kms truck3 STRING 0020
```

**Comment by kirantpatil** [comment]
Yeah, but I came to know that search is not using point and distance as that of nearby. So that I can get nearby fleet.

**Comment by tidwall** [comment]
That’s correct. Search is for string data.
