### ISSUE TITLE
ResponseError: Position must have two or more numbers

### ISSUE THREAD

**Issue by poojawiserion** [tidwall/tile38#240]
Hi,

Hitting this query SETHOOK Transfer_Stations_GTS_-_KABITKHEDI http://127.0.0.1:8000/app/test WITHIN T1 FENCE OBJECT {"type":"Polygon","coordinates":[[[75.87183609671243, 22.77004717242172], [75.87189541726976, 22.76993067239999], [75.87239056012884, 22.76979717369646], [75.87262660398993, 22.77054446542436], [75.87204797386504, 22.77072245295209], [75.87183609671243, 22.77004717242172]]]}
with cli works fine but return an responseError while excecuting it with python code-
import redis
client = redis.Redis(host='127.0.0.1', port=9851)
query = 'SETHOOK Transfer_Stations_GTS_-_KABITKHEDI http://127.0.0.1:8000/app/test WITHIN T1 FENCE OBJECT {"type":"Polygon","coordinates":[[[75.87183609671243, 22.77004717242172], [75.87189541726976, 22.76993067239999], [75.87239056012884, 22.76979717369646], [75.87262660398993, 22.77054446542436], [75.87204797386504, 22.77072245295209], [75.87183609671243, 22.77004717242172]]]}'

result = client.execute_command(query)

Error:- ResponseError: Position must have two or more numbers
Any help would be great.
Thanks in advance

**Comment by tidwall** [comment]
Hi, 

I think for the Python redis-py client you need to execute commands with each keyword as a separate argument.

```python
client.execute_command('SETHOOK', 'Transfer_Stations_GTS-_KABITKHEDI', 'http://127.0.0.1:8000/app/test', 'WITHIN', 'T1', 'FENCE', 'OBJECT', '{"type":"Polygon","coordinates":[[[75.87183609671243, 22.77004717242172], [75.87189541726976, 22.76993067239999], [75.87239056012884, 22.76979717369646], [75.87262660398993, 22.77054446542436], [75.87204797386504, 22.77072245295209], [75.87183609671243, 22.77004717242172]]]}')
```

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if needed.

Thank you!
