### ISSUE TITLE
INTERSECTS not working with Polygon inner bounds 

### ISSUE THREAD

**Issue by genesor** [tidwall/tile38#241]
Hey, 

We are currently facing an issue with Tile and the INTERSECTS command and inner bounds of a polygon.

When using `INTERSECTS` Tile doesn't seem to be taking the inner bounds into account and still returns a polygon even if the point isn't intersecting with the polygon as it is in the "hole" defined by the inner bounds.

![image](https://user-images.githubusercontent.com/1420159/33994153-b9dc4706-e0d9-11e7-9262-a84ef4a57a9a.png)

Here is a GeoJSON gist with some example data https://gist.github.com/anonymous/2b2b3f68f7debdb32f7333e04d8b7265#file-map-geojson

Here is the command used: 
This one shouldn't match but it is 🙈 
```
INTERSECTS cities OBJECT {"type":"Point","coordinates":[2.253119945526123,48.841404318083505]}
```

This one should match and it is.
```
INTERSECTS cities OBJECT {"type":"Point","coordinates":[2.2564244270324703,48.83788774899389]}
```

Maybe I'm not using Tile38 as I should and this is intended but it seems weird. 

Thanks !

**Comment by tidwall** [comment]
That looks like a bug. I'll do some investigating. Thanks for the descriptive example.

**Comment by tidwall** [comment]
I found the issue and pushed the fix. Thanks for reporting!
