### ISSUE TITLE
https://api.tile38.com

### ISSUE THREAD

**Issue by LCD344** [tidwall/tile38#242]
Hi,

My name is Nur bar, I'm one of the creators of barrioball. And I would like to understand why your api subdomain seems to be mirroring our site? 
https://api.tile38.com

I'm hoping to get your response asap.
Thanks, 
Nur

**Comment by tidwall** [comment]
Hi,

A dig on api.tile38.com show that the A record is pointing to 138.68.228.111. It appears that there's a website called Barrio-Ball on that IP address. It's not mirroring, just pointing to that IP address.

```
$ dig api.tile38.com

; <<>> DiG 9.9.7-P3 <<>> api.tile38.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42726
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;api.tile38.com.			IN	A

;; ANSWER SECTION:
api.tile38.com.		165	IN	A	138.68.228.111

;; Query time: 56 msec
;; SERVER: 192.168.86.1#53(192.168.86.1)
;; WHEN: Thu Jan 04 11:51:32 MST 2018
;; MSG SIZE  rcvd: 59
```
I'm closing this issue because it's not related the Tile38 project.
