### ISSUE TITLE
FENCE query is not working with node JS

### ISSUE THREAD

**Issue by fazlul3003** [tidwall/tile38#244]
I think this is related to https://github.com/tidwall/tile38/issues/144 issue. I'm trying to execute the below fence query via the function which given in the https://gist.github.com/tidwall/0e7fe116351fb7a9a16c0cbd3e2fb79a
```
openFence(9851, "localhost", 
'WITHIN fleet FENCE OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}',
function(message){
    console.log("heklo")
    console.log(message)
}, 
function(err){
    console.log(err)
}, 
function(){
    console.log("closed")
}
)

```
but I'm getting every time "closed" . 

Any idea what casing the error?

**Comment by tidwall** [comment]
The input command that you are sending the server is invalid. 

This is the error on the server side:

```
2018/01/05 11:25:11 [ERRO] Protocol error: unbalanced quotes in request
```

The example code was created to demonstrate the simplest way to create a geofence connection in node JS. Unfortunately it breaks on more complex inputs that contain strings with unbalanced quotes, such as geojson. 

I just updated the example code so that it now accepts an array and serializes the command to [RESP](https://redis.io/topics/protocol). https://gist.github.com/tidwall/0e7fe116351fb7a9a16c0cbd3e2fb79a.

Then try this on your side.

```js
openFence(9851, "localhost",
	["WITHIN","fleet","FENCE","OBJECT",'{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}'],
	function(message){
		console.log(message)
	}, 
	function(err){
		console.log(err)
	}, 
	function(err){
		console.log("closed", err)
	}
)
```

**Comment by fazlul3003** [comment]
thanks man, working like a charm now. 
FYI: I think you need to update the function "openFence" variable **args** -> **command**

**Comment by fazlul3003** [comment]
Hi tidwall,

I think the function you updated, only to accept OBJECT data types. However, if tried with OBJECT geojson data. I'm getting  **ERR Type member is invalid. Expecting a string**

Here is the data I'm trying:
```

openFence(9851, "localhost",
["WITHIN","fleet","FENCE","OBJECT","{'type':'Feature','geometry':{'type':'Polygon','coordinates':[[[[79.8512351859432,6.96091024801032],[79.8512900703478,6.9608396823473],[79.8508327003097,6.96059139575517],[79.8505870272607,6.96043458317067],[79.8503413542116,6.96023595389697],[79.8501740874548,6.96005823296788],[79.8500486373872,6.95991710164183],[79.8489692440972,6.95829409139226],[79.8492828692662,6.95808500794627],[79.849241052577,6.95802750999862],[79.8489431086665,6.95823659344461],[79.8485380094899,6.95763286499429],[79.8479891654441,6.9568069853826],[79.8469960190756,6.95530158457141],[79.8470221545064,6.95524931370991],[79.8470169274202,6.95521272410686],[79.846975110731,6.95518136158996],[79.8469176127834,6.95517090741766],[79.8468862502665,6.95519704284841],[79.8468862502665,6.95524931370991],[79.8469332940418,6.95535908251906],[79.8474586161999,6.95617189441538],[79.8483602885608,6.9575074149267],[79.8489640170111,6.95841954145986],[79.8496775142705,6.95949893474983],[79.8499911394395,6.95995369124488],[79.8502420395747,6.96024640806927],[79.8504824855376,6.96045549151527],[79.8508222461374,6.96066980204742],[79.8512351859432,6.96091024801032]]],[[[79.8422777451086,6.92999198050479],[79.8420055803085,6.93065052211949],[79.8417446406412,6.93144915564653],[79.8416418462268,6.93184451877873],[79.8414520719234,6.93229918638076],[79.841127874155,6.93304246906929],[79.8410013579527,6.93375412270725],[79.8409618216395,6.93382924170237],[79.8408511199625,6.93391622159145],[79.8408036763866,6.93401901600582],[79.8408194909119,6.93419297578399],[79.8408432126998,6.93447368360785],[79.8407166964975,6.93508254283144],[79.8404794786182,6.93577838194411],[79.8402106316883,6.9361183942378],[79.8401473735871,6.9362607249654],[79.8402501680015,6.9364584065315],[79.8403213333653,6.93660864452173],[79.8405664585073,6.9367114389361],[79.8408511199625,6.93696447134071],[79.841017172478,6.93734401994762],[79.8410646160538,6.93791334285799],[79.8413334629837,6.93863290375859],[79.8414520719234,6.93919036577499],[79.8415311445498,6.93977550321065],[79.8416181244389,6.94051483226786],[79.8417999914797,6.9410604333903],[79.8419739512579,6.94150324009836],[79.8420530238843,6.9415823127248],[79.8422190763999,6.94166929261388],[79.8425353669056,6.94194604680642],[79.8427251412091,6.94207651664005],[79.842732201265,6.94206380853938],[79.8428753791993,6.94220698647368],[79.843816343454,6.94780928205694],[79.8441879847982,6.95005889827916],[79.8443303155258,6.95099590890247],[79.8443303155258,6.95129638488294],[79.8444489244655,6.95360135194366],[79.8445596261425,6.95593399442364],[79.8445912551931,6.9559814379995],[79.8447019568701,6.95597353073686],[79.8448126585471,6.95586282905984],[79.8448126585471,6.95576794190812],[79.8446782350822,6.95579166369605],[79.8444884607787,6.95200013125826],[79.8445200898293,6.95197640947032],[79.8446070697184,6.95202385304619],[79.8448838239109,6.9525299178554],[79.8448917311735,6.95264061953242],[79.8449312674868,6.95271969215886],[79.8450340619011,6.95281457931059],[79.8451842998914,6.95295691003818],[79.8452791870431,6.95315459160428],[79.8454452395586,6.95326529328129],[79.8455243121851,6.95338390222095],[79.8455954775489,6.95339971674624],[79.8456903647006,6.95336808769567],[79.8457536228017,6.95332855138245],[79.8457457155391,6.95325738601865],[79.8456824574379,6.95321784970543],[79.8455796630236,6.95320994244279],[79.8455322194477,6.9531941279175],[79.845326630619,6.95291737372496],[79.8449075456988,6.95226107092551],[79.8446545132942,6.95170756254043],[79.8446386987689,6.95159290723209],[79.8447810294965,6.95133987482748],[79.8448838239109,6.95076264465447],[79.8448680093856,6.95066380387142],[79.8453977959827,6.95056891671969],[79.8449866183253,6.94799510272908],[79.8446307915063,6.94599851891147],[79.8445200898293,6.94515639543988],[79.8446070697184,6.94512476638931],[79.8447652149712,6.94499034292436],[79.8450103401132,6.94481638314619],[79.8451052272649,6.94468986694389],[79.8450735982144,6.94450799990308],[79.8449628965373,6.94434194738755],[79.8448996384362,6.94429845744301],[79.8449233602241,6.94413240492749],[79.8448838239109,6.9440454250384],[79.844860102123,6.9439189088361],[79.8448126585471,6.94370541274471],[79.8448442875977,6.94367378369414],[79.8448521948603,6.94358680380505],[79.8447889367592,6.94353145296654],[79.8447335859207,6.94346028760275],[79.844725678658,6.94336540045102],[79.8447335859207,6.94331795687516],[79.8447889367592,6.94331004961251],[79.8448126585471,6.94317562614757],[79.8448205658098,6.94308073899584],[79.8448284730724,6.9430016663694],[79.8450656909517,6.9429660836875],[79.8450261546385,6.9426972367576],[79.8449312674868,6.94216745016046],[79.8445991624557,6.94097345350121],[79.8443777591017,6.94102089707708],[79.8442196138488,6.94090624176874],[79.8442749646873,6.94087461271817],[79.8443619445764,6.94044762053539],[79.8442117065862,6.94046343506068],[79.8441089121718,6.94089042724345],[79.8438637870298,6.94090624176874],[79.8438242507166,6.94090624176874],[79.8437451780902,6.94028947528251],[79.8435316819988,6.94011551550434],[79.8434288875844,6.94022621718136],[79.8433340004327,6.94035273338366],[79.8430967825533,6.940234124444],[79.8429307300378,6.94013133002963],[79.842859564674,6.93999690656468],[79.8430809680281,6.93955409985662],[79.8433814440085,6.93974387416007],[79.843436794847,6.9396410797457],[79.8431363188666,6.93946711996754],[79.84332609317,6.93913501493649],[79.8436344764131,6.93955805348794],[79.8437768071407,6.93946316633621],[79.843571218312,6.93919431940632],[79.8442433356367,6.93900454510286],[79.844369851839,6.9395501462253],[79.8444884607787,6.93950270264943],[79.8443540373137,6.93898082331493],[79.8447494004459,6.93885430711263],[79.8448521948603,6.93933665013391],[79.8450419691638,6.93928920655805],[79.8449233602241,6.93883058532469],[79.8452633725178,6.93872779091032],[79.8462201512977,6.9422821054688],[79.847390426169,6.94195000043775],[79.8463308529747,6.93827707693962],[79.8464020183385,6.9382375406264],[79.8471769300777,6.93804776632294],[79.8474338981732,6.9381096290126],[79.8479856941419,6.93295535303188],[79.8478658996983,6.93294280313779],[79.8468352337866,6.93265421668252],[79.8465878739678,6.93256742376364],[79.8464099484841,6.93236780005022],[79.8462927780436,6.93215515739897],[79.8462103247707,6.93184270289101],[79.8461951360099,6.9316192111249],[79.8462298531774,6.93132845484666],[79.8463643822017,6.9307990180415],[79.8459862488141,6.93066359352596],[79.8458287410864,6.93059570226399],[79.8448848369507,6.93030477290711],[79.8435918175868,6.93017547097072],[79.8426996342258,6.93005909922797],[79.8422777451086,6.92999198050479]]]]}}"],
function(message){
	console.log(message)
}, 
function(err){
	console.log(err)
}, 
function(err){
	console.log("closed", err)
}
)

```

**Comment by fazlul3003** [comment]
Update:
If I remove the parent array from the coordinates parameter the code is working without any issues, but the result is always return as "outside", even If I set the point inside the polygon. Here is the code I'm now trying:

`SET fleet truck1 POINT 79.8512351859432 6.96091024801032`

`
openFence(9851, "localhost",
["WITHIN","fleet","FENCE","OBJECT",'{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[79.8512351859432,6.96091024801032],[79.8512900703478,6.9608396823473],[79.8508327003097,6.96059139575517],[79.8505870272607,6.96043458317067],[79.8503413542116,6.96023595389697],[79.8501740874548,6.96005823296788],[79.8500486373872,6.95991710164183],[79.8489692440972,6.95829409139226],[79.8492828692662,6.95808500794627],[79.849241052577,6.95802750999862],[79.8489431086665,6.95823659344461],[79.8485380094899,6.95763286499429],[79.8479891654441,6.9568069853826],[79.8469960190756,6.95530158457141],[79.8470221545064,6.95524931370991],[79.8470169274202,6.95521272410686],[79.846975110731,6.95518136158996],[79.8469176127834,6.95517090741766],[79.8468862502665,6.95519704284841],[79.8468862502665,6.95524931370991],[79.8469332940418,6.95535908251906],[79.8474586161999,6.95617189441538],[79.8483602885608,6.9575074149267],[79.8489640170111,6.95841954145986],[79.8496775142705,6.95949893474983],[79.8499911394395,6.95995369124488],[79.8502420395747,6.96024640806927],[79.8504824855376,6.96045549151527],[79.8508222461374,6.96066980204742],[79.8512351859432,6.96091024801032]]],[[[79.8422777451086,6.92999198050479],[79.8420055803085,6.93065052211949],[79.8417446406412,6.93144915564653],[79.8416418462268,6.93184451877873],[79.8414520719234,6.93229918638076],[79.841127874155,6.93304246906929],[79.8410013579527,6.93375412270725],[79.8409618216395,6.93382924170237],[79.8408511199625,6.93391622159145],[79.8408036763866,6.93401901600582],[79.8408194909119,6.93419297578399],[79.8408432126998,6.93447368360785],[79.8407166964975,6.93508254283144],[79.8404794786182,6.93577838194411],[79.8402106316883,6.9361183942378],[79.8401473735871,6.9362607249654],[79.8402501680015,6.9364584065315],[79.8403213333653,6.93660864452173],[79.8405664585073,6.9367114389361],[79.8408511199625,6.93696447134071],[79.841017172478,6.93734401994762],[79.8410646160538,6.93791334285799],[79.8413334629837,6.93863290375859],[79.8414520719234,6.93919036577499],[79.8415311445498,6.93977550321065],[79.8416181244389,6.94051483226786],[79.8417999914797,6.9410604333903],[79.8419739512579,6.94150324009836],[79.8420530238843,6.9415823127248],[79.8422190763999,6.94166929261388],[79.8425353669056,6.94194604680642],[79.8427251412091,6.94207651664005],[79.842732201265,6.94206380853938],[79.8428753791993,6.94220698647368],[79.843816343454,6.94780928205694],[79.8441879847982,6.95005889827916],[79.8443303155258,6.95099590890247],[79.8443303155258,6.95129638488294],[79.8444489244655,6.95360135194366],[79.8445596261425,6.95593399442364],[79.8445912551931,6.9559814379995],[79.8447019568701,6.95597353073686],[79.8448126585471,6.95586282905984],[79.8448126585471,6.95576794190812],[79.8446782350822,6.95579166369605],[79.8444884607787,6.95200013125826],[79.8445200898293,6.95197640947032],[79.8446070697184,6.95202385304619],[79.8448838239109,6.9525299178554],[79.8448917311735,6.95264061953242],[79.8449312674868,6.95271969215886],[79.8450340619011,6.95281457931059],[79.8451842998914,6.95295691003818],[79.8452791870431,6.95315459160428],[79.8454452395586,6.95326529328129],[79.8455243121851,6.95338390222095],[79.8455954775489,6.95339971674624],[79.8456903647006,6.95336808769567],[79.8457536228017,6.95332855138245],[79.8457457155391,6.95325738601865],[79.8456824574379,6.95321784970543],[79.8455796630236,6.95320994244279],[79.8455322194477,6.9531941279175],[79.845326630619,6.95291737372496],[79.8449075456988,6.95226107092551],[79.8446545132942,6.95170756254043],[79.8446386987689,6.95159290723209],[79.8447810294965,6.95133987482748],[79.8448838239109,6.95076264465447],[79.8448680093856,6.95066380387142],[79.8453977959827,6.95056891671969],[79.8449866183253,6.94799510272908],[79.8446307915063,6.94599851891147],[79.8445200898293,6.94515639543988],[79.8446070697184,6.94512476638931],[79.8447652149712,6.94499034292436],[79.8450103401132,6.94481638314619],[79.8451052272649,6.94468986694389],[79.8450735982144,6.94450799990308],[79.8449628965373,6.94434194738755],[79.8448996384362,6.94429845744301],[79.8449233602241,6.94413240492749],[79.8448838239109,6.9440454250384],[79.844860102123,6.9439189088361],[79.8448126585471,6.94370541274471],[79.8448442875977,6.94367378369414],[79.8448521948603,6.94358680380505],[79.8447889367592,6.94353145296654],[79.8447335859207,6.94346028760275],[79.844725678658,6.94336540045102],[79.8447335859207,6.94331795687516],[79.8447889367592,6.94331004961251],[79.8448126585471,6.94317562614757],[79.8448205658098,6.94308073899584],[79.8448284730724,6.9430016663694],[79.8450656909517,6.9429660836875],[79.8450261546385,6.9426972367576],[79.8449312674868,6.94216745016046],[79.8445991624557,6.94097345350121],[79.8443777591017,6.94102089707708],[79.8442196138488,6.94090624176874],[79.8442749646873,6.94087461271817],[79.8443619445764,6.94044762053539],[79.8442117065862,6.94046343506068],[79.8441089121718,6.94089042724345],[79.8438637870298,6.94090624176874],[79.8438242507166,6.94090624176874],[79.8437451780902,6.94028947528251],[79.8435316819988,6.94011551550434],[79.8434288875844,6.94022621718136],[79.8433340004327,6.94035273338366],[79.8430967825533,6.940234124444],[79.8429307300378,6.94013133002963],[79.842859564674,6.93999690656468],[79.8430809680281,6.93955409985662],[79.8433814440085,6.93974387416007],[79.843436794847,6.9396410797457],[79.8431363188666,6.93946711996754],[79.84332609317,6.93913501493649],[79.8436344764131,6.93955805348794],[79.8437768071407,6.93946316633621],[79.843571218312,6.93919431940632],[79.8442433356367,6.93900454510286],[79.844369851839,6.9395501462253],[79.8444884607787,6.93950270264943],[79.8443540373137,6.93898082331493],[79.8447494004459,6.93885430711263],[79.8448521948603,6.93933665013391],[79.8450419691638,6.93928920655805],[79.8449233602241,6.93883058532469],[79.8452633725178,6.93872779091032],[79.8462201512977,6.9422821054688],[79.847390426169,6.94195000043775],[79.8463308529747,6.93827707693962],[79.8464020183385,6.9382375406264],[79.8471769300777,6.93804776632294],[79.8474338981732,6.9381096290126],[79.8479856941419,6.93295535303188],[79.8478658996983,6.93294280313779],[79.8468352337866,6.93265421668252],[79.8465878739678,6.93256742376364],[79.8464099484841,6.93236780005022],[79.8462927780436,6.93215515739897],[79.8462103247707,6.93184270289101],[79.8461951360099,6.9316192111249],[79.8462298531774,6.93132845484666],[79.8463643822017,6.9307990180415],[79.8459862488141,6.93066359352596],[79.8458287410864,6.93059570226399],[79.8448848369507,6.93030477290711],[79.8435918175868,6.93017547097072],[79.8426996342258,6.93005909922797],[79.8422777451086,6.92999198050479]]]}}'],
function(message){
	console.log(message)
}, 
function(err){
	console.log(err)
}, 
function(err){
	console.log("closed", err)
}
)
`

**Comment by tidwall** [comment]
The JSON is invalid when I test it in [jsonlint.com](https://jsonlint.com). I think you may have some unbalanced array brackets.

Also a polygon can only have one exterior ring, which is the first array of points. The next rings are interior rings which act as holes, and should be within the bounds of the exterior ring.

https://tools.ietf.org/html/rfc7946#section-3.1.6

You're polygon has one exterior ring, which is correctly handling the geofence event, and an interior ring, which is completely on the outside of the exterior. 

I'm guessing that what you want are two polygons that work as a single object. 

If so, you should try the MultiPolygon object. Or a FeatureCollection with two Polygon features. 

I would recommend a FeatureCollection because MultiPolygon JSON can get a little messy because of all bracket soup.

**Comment by fazlul3003** [comment]
Hi tidwall,

Thanks for your quick response and I humbly appreciate on your comments. However, still I'm having the problem.

Looking at the MultiPolygon and FeatureCollection objects, I think it's easy for me to go with MultiPolygon.  Here is my updated code:

```
openFence(9851, "localhost",
["WITHIN","fleet","FENCE","OBJECT",`{
	"type": "MultiPolygon",
	"coordinates": [
		[[[79.8512351859432,6.96091024801032],[79.8512900703478,6.9608396823473],[79.8508327003097,6.96059139575517],[79.8505870272607,6.96043458317067],[79.8503413542116,6.96023595389697],[79.8501740874548,6.96005823296788],[79.8500486373872,6.95991710164183],[79.8489692440972,6.95829409139226],[79.8492828692662,6.95808500794627],[79.849241052577,6.95802750999862],[79.8489431086665,6.95823659344461],[79.8485380094899,6.95763286499429],[79.8479891654441,6.9568069853826],[79.8469960190756,6.95530158457141],[79.8470221545064,6.95524931370991],[79.8470169274202,6.95521272410686],[79.846975110731,6.95518136158996],[79.8469176127834,6.95517090741766],[79.8468862502665,6.95519704284841],[79.8468862502665,6.95524931370991],[79.8469332940418,6.95535908251906],[79.8474586161999,6.95617189441538],[79.8483602885608,6.9575074149267],[79.8489640170111,6.95841954145986],[79.8496775142705,6.95949893474983],[79.8499911394395,6.95995369124488],[79.8502420395747,6.96024640806927],[79.8504824855376,6.96045549151527],[79.8508222461374,6.96066980204742],[79.8512351859432,6.96091024801032]]],
		[[[79.8422777451086,6.92999198050479],[79.8420055803085,6.93065052211949],[79.8417446406412,6.93144915564653],[79.8416418462268,6.93184451877873],[79.8414520719234,6.93229918638076],[79.841127874155,6.93304246906929],[79.8410013579527,6.93375412270725],[79.8409618216395,6.93382924170237],[79.8408511199625,6.93391622159145],[79.8408036763866,6.93401901600582],[79.8408194909119,6.93419297578399],[79.8408432126998,6.93447368360785],[79.8407166964975,6.93508254283144],[79.8404794786182,6.93577838194411],[79.8402106316883,6.9361183942378],[79.8401473735871,6.9362607249654],[79.8402501680015,6.9364584065315],[79.8403213333653,6.93660864452173],[79.8405664585073,6.9367114389361],[79.8408511199625,6.93696447134071],[79.841017172478,6.93734401994762],[79.8410646160538,6.93791334285799],[79.8413334629837,6.93863290375859],[79.8414520719234,6.93919036577499],[79.8415311445498,6.93977550321065],[79.8416181244389,6.94051483226786],[79.8417999914797,6.9410604333903],[79.8419739512579,6.94150324009836],[79.8420530238843,6.9415823127248],[79.8422190763999,6.94166929261388],[79.8425353669056,6.94194604680642],[79.8427251412091,6.94207651664005],[79.842732201265,6.94206380853938],[79.8428753791993,6.94220698647368],[79.843816343454,6.94780928205694],[79.8441879847982,6.95005889827916],[79.8443303155258,6.95099590890247],[79.8443303155258,6.95129638488294],[79.8444489244655,6.95360135194366],[79.8445596261425,6.95593399442364],[79.8445912551931,6.9559814379995],[79.8447019568701,6.95597353073686],[79.8448126585471,6.95586282905984],[79.8448126585471,6.95576794190812],[79.8446782350822,6.95579166369605],[79.8444884607787,6.95200013125826],[79.8445200898293,6.95197640947032],[79.8446070697184,6.95202385304619],[79.8448838239109,6.9525299178554],[79.8448917311735,6.95264061953242],[79.8449312674868,6.95271969215886],[79.8450340619011,6.95281457931059],[79.8451842998914,6.95295691003818],[79.8452791870431,6.95315459160428],[79.8454452395586,6.95326529328129],[79.8455243121851,6.95338390222095],[79.8455954775489,6.95339971674624],[79.8456903647006,6.95336808769567],[79.8457536228017,6.95332855138245],[79.8457457155391,6.95325738601865],[79.8456824574379,6.95321784970543],[79.8455796630236,6.95320994244279],[79.8455322194477,6.9531941279175],[79.845326630619,6.95291737372496],[79.8449075456988,6.95226107092551],[79.8446545132942,6.95170756254043],[79.8446386987689,6.95159290723209],[79.8447810294965,6.95133987482748],[79.8448838239109,6.95076264465447],[79.8448680093856,6.95066380387142],[79.8453977959827,6.95056891671969],[79.8449866183253,6.94799510272908],[79.8446307915063,6.94599851891147],[79.8445200898293,6.94515639543988],[79.8446070697184,6.94512476638931],[79.8447652149712,6.94499034292436],[79.8450103401132,6.94481638314619],[79.8451052272649,6.94468986694389],[79.8450735982144,6.94450799990308],[79.8449628965373,6.94434194738755],[79.8448996384362,6.94429845744301],[79.8449233602241,6.94413240492749],[79.8448838239109,6.9440454250384],[79.844860102123,6.9439189088361],[79.8448126585471,6.94370541274471],[79.8448442875977,6.94367378369414],[79.8448521948603,6.94358680380505],[79.8447889367592,6.94353145296654],[79.8447335859207,6.94346028760275],[79.844725678658,6.94336540045102],[79.8447335859207,6.94331795687516],[79.8447889367592,6.94331004961251],[79.8448126585471,6.94317562614757],[79.8448205658098,6.94308073899584],[79.8448284730724,6.9430016663694],[79.8450656909517,6.9429660836875],[79.8450261546385,6.9426972367576],[79.8449312674868,6.94216745016046],[79.8445991624557,6.94097345350121],[79.8443777591017,6.94102089707708],[79.8442196138488,6.94090624176874],[79.8442749646873,6.94087461271817],[79.8443619445764,6.94044762053539],[79.8442117065862,6.94046343506068],[79.8441089121718,6.94089042724345],[79.8438637870298,6.94090624176874],[79.8438242507166,6.94090624176874],[79.8437451780902,6.94028947528251],[79.8435316819988,6.94011551550434],[79.8434288875844,6.94022621718136],[79.8433340004327,6.94035273338366],[79.8430967825533,6.940234124444],[79.8429307300378,6.94013133002963],[79.842859564674,6.93999690656468],[79.8430809680281,6.93955409985662],[79.8433814440085,6.93974387416007],[79.843436794847,6.9396410797457],[79.8431363188666,6.93946711996754],[79.84332609317,6.93913501493649],[79.8436344764131,6.93955805348794],[79.8437768071407,6.93946316633621],[79.843571218312,6.93919431940632],[79.8442433356367,6.93900454510286],[79.844369851839,6.9395501462253],[79.8444884607787,6.93950270264943],[79.8443540373137,6.93898082331493],[79.8447494004459,6.93885430711263],[79.8448521948603,6.93933665013391],[79.8450419691638,6.93928920655805],[79.8449233602241,6.93883058532469],[79.8452633725178,6.93872779091032],[79.8462201512977,6.9422821054688],[79.847390426169,6.94195000043775],[79.8463308529747,6.93827707693962],[79.8464020183385,6.9382375406264],[79.8471769300777,6.93804776632294],[79.8474338981732,6.9381096290126],[79.8479856941419,6.93295535303188],[79.8478658996983,6.93294280313779],[79.8468352337866,6.93265421668252],[79.8465878739678,6.93256742376364],[79.8464099484841,6.93236780005022],[79.8462927780436,6.93215515739897],[79.8462103247707,6.93184270289101],[79.8461951360099,6.9316192111249],[79.8462298531774,6.93132845484666],[79.8463643822017,6.9307990180415],[79.8459862488141,6.93066359352596],[79.8458287410864,6.93059570226399],[79.8448848369507,6.93030477290711],[79.8435918175868,6.93017547097072],[79.8426996342258,6.93005909922797],[79.8422777451086,6.92999198050479]]]
	]
 }`],
function(message){
	console.log(message)
}, 
function(err){
	console.log(err)
}, 
function(err){
	console.log("closed", err)
}
)

```
Now I'm not getting any errors, but still all the set command detect as "cross" and "outside". Tried set commands:
**Expected**: These command should detect as Inside
`SET fleet truck1 POINT 6.96091024801032 79.8512351859432`

`SET fleet truck1 POINT 6.93065052211949 79.8420055803085`

`SET fleet truck1 POINT 6.93065052211949 79.8420055803085`

**Expected**:  These command should detect as Outside
`SET fleet truck1 POINT 3.84 2.930`

**Comment by fazlul3003** [comment]
Update:

I tried directly in the tile38 cli with following commands, but still still it detect as outside:

FYI: MultiPolygon is taken from the https://tools.ietf.org/html/rfc7946#section-3.1.9

`WITHIN fleet FENCE OBJECT {"type":"MultiPolygon","coordinates":[[[[180.0,40.0],[180.0,50.0],[170.0,50.0],[170.0,40.0],[180.0,40.0]]],[[[-170.0,40.0],[-170.0,50.0],[-180.0,50.0],[-180.0,40.0],[-170.0,40.0]]]]}`

`SET fleet truck1 POINT 40.0 180.0
`

**Comment by tidwall** [comment]
I confirm that there's a problem. I'll investigate further.

**Comment by tidwall** [comment]
I just pushed an update that addresses this issue. Commit dc1cc76

**Comment by tidwall** [comment]
I just released v1.10.1 which includes a fix to this issue.

**Comment by fazlul3003** [comment]
Hi tidwall,

Sorry man, I purposely took time to reply you; because I wanted to confirm the update you've released working fine, Yes I can confirm, it's working fine. THANK A LOT MAN.

I've couple of questions:
1) You have released new version of tile38 and I've already up and running previous version of tile38 in production server. Therefore would it be ok now if I just replaced the .exe files?

2) Currently we cannot execute redis commands in tile38, can you confirm that?

Thanks a lot again.

**Comment by tidwall** [comment]
> You have released new version of tile38 and I've already up and running previous version of tile38 in production server. Therefore would it be ok now if I just replaced the .exe files?

Yes, just replace the existing exe should suffice.

> Currently we cannot execute redis commands in tile38, can you confirm that?

Which commands are not working?

**Comment by fazlul3003** [comment]
Hi tidwall,

Your reply to my other ticket solve the issue, so I'm closing this issue. 

Thanks again for your cooperation
