### ISSUE TITLE
hook problem

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#245]
@tidwall,
I use a SET collection, HOOK way associated with this SET about 400 fences, but a single tile38 service found that only 5000 GPS processing per minute, can give some suggestions to improve processing performance. 
Thanks!

**Comment by tidwall** [comment]
A few things I would consider:

What events are you registering? (eg, enter, exit, cross, inside, outside)
What kind of objects are the fences, and how complex (# of line segments) are they? 
Are the GPS objects simple points?
How many GPS objects are you processing per second?

**Comment by huangpeizhi** [comment]
@tidwall ,
- register enter/exit event
- complex polygons , fence 400
- GPS track of the vehicle, GPS point
- vehicle 40,000 or less

**Comment by huangpeizhi** [comment]
GPS 200,000/min

**Comment by tidwall** [comment]
Seem like a reasonable number of point/sec. 
Would it be possible to see a fews examples of the geofence polygons? 
Also what kind of server hardware are you running, if you don't mind?

**Comment by huangpeizhi** [comment]
Ok,

i ran 60 TILE38 instances on this machine. 
[fences.txt](https://github.com/tidwall/tile38/files/1621062/fences.txt)
 

- Server

CPU: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz  40cores

processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
stepping        : 1
microcode       : 0xb000021
cpu MHz         : 1937.343
cache size      : 25600 KB
physical id     : 1
siblings        : 20
core id         : 12
cpu cores       : 10
apicid          : 57
initial apicid  : 57
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bogomips        : 4804.94
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

MEMORY: 128G

# free
              total        used        free      shared  buff/cache   available
Mem:      131742140     5260216   122557400       24692     3924524   125743684
Swap:      20971516       77932    20893584

**Comment by tidwall** [comment]
Thanks for providing the fence information. Your geofence polygons are pretty complex, but I think I found a way to help speed the operations up.

Let me know if this helps.

**Comment by huangpeizhi** [comment]
@tidwall , This is indeed a great help to me, thanks.

**Comment by huangpeizhi** [comment]
@tidwall, 
Tested, now, the server now launched a total of 30 TILE38 instances, the overall server load about 80%, all TILE38 service can handle 350,000 GPS per minute, using about 3,000 complex fences.
Now I can meet my performance requirements， thanks!!
:+1:

**Comment by huangpeizhi** [comment]
Now up to 400 complex fences, a single TILE38 service can process 300,000 GPS data per minute

**Comment by tidwall** [comment]
I’m glad it’s working better. 👍
