### ISSUE TITLE
GeoJSON Point in Polygon searches?

### ISSUE THREAD

**Issue by rbastian** [tidwall/tile38#25]
Hi - 

I'm having trouble getting something simple to work: I want to test to see if a GeoJson Point is inside a GeoJson Polygon:

Here is the polygon definition:

```
SET cities tempe OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
{"ok":true,"elapsed":"8.463753ms"}
```

Here is the query for a point inside the Polygon (Tempe lat/lon from Google) that I expect to work but does not:

```
WITHIN cities OBJECT { "type": "Point", "coordinates": [ -111.9400, 33.4255] }
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"65.084µs"}
```

I also tried INTERSECTS:

```
INTERSECTS cities OBJECT { "type": "Point", "coordinates": [ -111.9400, 33.4255] }
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"12.298599ms"}
```

If I query with the entire Polygon, it does work:

```
INTERSECTS cities object {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
{"ok":true,"objects":[{"id":"tempe","object":{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.895,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}}],"count":1,"cursor":0,"elapsed":"11.765324ms"}
```

**Comment by tidwall** [comment]
WITHIN and INTERSECTS cannot be used with points, only polygons or boundaries. This is a limitation of Tile38. But there are workarounds.

It is possible to use your point if it's represented as a polygon:

```
INTERSECTS cities OBJECT { "type": "Polygon", "coordinates": [[[ -111.9400,33.4255],[ -111.9400,33.4255],[ -111.9400,33.4255],[ -111.9400,33.4255]]] }
```

Or you can use the BOUNDS keyword:

```
INTERSECTS cities BOUNDS 33.4411 -111.9787 33.4411 -111.9787
```

Finally you can use the NEARBY and use a small sub-meter value:

```
NEARBY cities POINT 33.4411 -111.9787 0.0001
```

Tile38 should support the Point type for INTERSECTS and WITHIN. I filed a bug #26. 

Thanks for reporting this.

**Comment by rbastian** [comment]
NEARBY with a distance of 0 also works:

```
NEARBY cities POINT 33.4255 -111.94 0
{"ok":true,"objects":[{"id":"tempe","object":{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.895,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}}],"count":1,"cursor":0,"elapsed":"10.386782ms"}
```

**Comment by tidwall** [comment]
Well that's even better. Thanks for the tip and for reporting this issue.

**Comment by tidwall** [comment]
I finally got around to fixing this issue. You can now issue an INTERSECTS on a point:

```
INTERSECTS cities OBJECT { "type": "Point", "coordinates": [ -111.9400, 33.4255] }
```

Though it's not possible to do a WITHIN because a within search find all objects that are fully contained inside of an object. And in your case that a Polygon cannot be fully inside a Point.

Let me know if you run into any problems and thanks for finding this bug.

**Comment by windrunner99** [comment]
This does not seem to work anymore. Running this result in:

```
INTERSECTS cities OBJECT { "type": "Point", "coordinates": [ -111.9400, 33.4255] }
(error) invalid data
```
Was this revered in a following release?

**Comment by tidwall** [comment]
@windrunner99 

In 1.19.3 the behavior of the tile38-cli was changed in order to fix a bug. https://github.com/tidwall/tile38/commit/66af8ab094703aebf621dba1349c327892041c3d

It now requires that when an arguments has a space, like the geojson in your example, it must be encapsulated in quotes.

```
INTERSECTS cities OBJECT '{ "type": "Point", "coordinates": [ -111.9400, 33.4255] }'
```
