### ISSUE TITLE
Feature request: Support RENAME

### ISSUE THREAD

**Issue by mannol** [tidwall/tile38#251]
Consider the following:

- Have a key 'key' with X records
- Want to replace the records in the key
- Have to:
  `DROP key`
  `SET key foreach X`

Problem:
- All reads from key 'key' will fail or return undefined values

Solution:
- Implement atomic `RENAME keyOldName keyNewName`
- Now, we can replace the key atomically with:
  `SET tempKey foreach X`
  `RENAME tempKey key`

P. S. Thanks for this awesome software!

**Comment by tidwall** [comment]
Thanks for the suggestion. I'll definitely consider a RENAME command.
