### ISSUE TITLE
Can we use PGET?

### ISSUE THREAD

**Issue by fazlul3003** [tidwall/tile38#252]
Hi tidwall,

Can we use something like PGET? for example I wanted to get all trucks within the fleet where the id contain specific prefix.

i.e 
`SET fleet truck:123 POINT 33.5123 -112.2693`

`PGET fleet truck:*`

Thanks

**Comment by tidwall** [comment]
Hi fazlul3003,

The SCAN + MATCH will perform this operation

```
SCAN fleet MATCH truck:*
```

**Comment by fazlul3003** [comment]
Hi tidwall,

Thanks, the command line is working fine.

Thanks
