### ISSUE TITLE
Making 2 different objects on 2 different devices and detecting nearby?

### ISSUE THREAD

**Issue by AA1452** [tidwall/tile38#253]
I would like to use tile38 as my default geofence for an app that detects when 2 users are near each other. From what knowledge I have gathered, I'm guessing the process is to put both objects into the same server, then using a nearby query. If this is right, can someone point me to an example that shows this? Don't quite understand how to do it just from reading the documentation.

**Comment by ElectroCamel** [comment]
Yes, you have to create two ids in tile38 by using the `set` command, then you probably want to use a [roaming geofence](http://tile38.com/topics/roaming-geofences/).

**Comment by AA1452** [comment]
Ok that makes sense, thank you! I had one more question as well.  How can I use a mySQL or other database such as Firebase as a tile38 server/database? I don't think simply pointing to it's address and port will work?

**Comment by ElectroCamel** [comment]
Tile38 already has its own server and database, I'm not really sure I understand what you mean by "use another DB as a tile38 server/db"
You can directly query tile to get your users locations, and if you have the need to save them to an SQL database you'd have to manually handle it (i.e. have a PHP page which both queries the DB via mysqli and tile38 via HTTP, websockets or telnet ([HTTP](http://tile38.com/topics/network-protocols/#http) would be the easiest in PHP)

**Comment by AA1452** [comment]
Sorry for the vague question, what I meant was, the tile38 server I'm running is on my local machine; how do I create objects from a device that is not on the same network as the server(local), and still have them go to the server. Can I create a server using Cloud services and have the client code create the objects to that server? Again, I apologize, I'm new to server side programming and really appreciate the help.

**Comment by ElectroCamel** [comment]
You have to expose your locally-run tile38 server to the Internet, by setting your firewall and your router's port forwarding rules to allow traffic on port tcp/9851. If you do not want to do that, there are many server hosting services available (Google Cloud Platform offers a 1-year, 300$ credit [trial](https://console.cloud.google.com/freetrial) along with a [free tier](https://console.cloud.google.com/free))

Once you have a server you can reach remotely, all you have to do is send HTTP request to it directly by your client or from a PHP page which also handles SQL as said above (the choice is yours, depending on your project's structure)

**Comment by AA1452** [comment]
@ElectroCamel That makes much more sense! Now if I want to use a server hosting service, would I use a virtual machine to set up the tile38 server? In other words, how can I setup specifically a tile38 server on a hosting service, because the only way I know how to start one is to use the .exe file?

**Comment by ElectroCamel** [comment]
Yeah, a VM is the most convenient choice. I didn't have any luck trying to get tile38 to run on Google's App Engine, but it runs just fine in Compute Engine.

**Comment by AA1452** [comment]
@ElectroCamel Thank you so much for your help, I really appreciate it. :)

**Comment by ElectroCamel** [comment]
Happy to help! If you don't have any further questions, please close the issue ;)
