### ISSUE TITLE
GeometryCollection doesn't work

### ISSUE THREAD

**Issue by mleone20** [tidwall/tile38#261]
After sending this very big command to the server it doesnt respond anymore.

> SET world2cities V29ybGRUZXJyaXRvcnktYmE= OBJECT {"type":"GeometryCollection","geometries":[{"type":"MultiPolygon","coordinates":[[[[14.7314428,40.7455511],[14.7327098,40.745681500000003],[14.7343438,40.745766600000003],[14.73522,40.745821900000003],[14.7363108,40.745835100000001],[14.7373639,40.745899600000001],[14.7379216,40.745727700000003],[14.738478300000001,40.745560400000002],[14.739202199999999,40.7454793],[14.7399477,40.7453656],[14.7413481,40.744800599999998],[14.7427692,40.744783699999999],[14.743513800000001,40.745192099999997],[14.7443755,40.745995200000003],[14.745463900000001,40.746512500000001],[14.7463978,40.746884399999999],[14.7473183,40.747486600000002],[14.7483006,40.748229700000003],[14.748677300000001,40.748814000000003],[14.7490165,40.749400100000003],[14.750141299999999,40.749771500000001],[14.751184,40.7500839],[14.7522834,40.750632099999997],[14.7525022,40.750697700000003],[14.7537617,40.751053300000002],[14.754481699999999,40.751773399999998],[14.7555341,40.752512899999999],[14.756514299999999,40.752913900000003],[14.7573306,40.753300699999997],[14.757828,40.753671799999999],[14.7581091,40.754603000000003],[14.7583894,40.755430599999997],[14.7582676,40.756305400000002],[14.758571,40.757509900000002],[14.7590184,40.758405699999997],[14.7597503,40.759107200000003],[14.7604948,40.759596500000001],[14.7614775,40.7597679],[14.762732400000001,40.760006599999997],[14.7639627,40.760440000000003],[14.765087899999999,40.760694200000003],[14.766568299999999,40.760880999999998],[14.767527299999999,40.761017500000001],[14.7679651,40.761135000000003],[14.768132599999999,40.761009600000001],[14.7684415,40.760476500000003],[14.7688579,40.760091099999997],[14.769688,40.759689399999999],[14.7708277,40.759384599999997],[14.7713006,40.759266400000001],[14.771824799999999,40.7585379],[14.7724554,40.7576106],[14.773321299999999,40.7573151],[14.773970500000001,40.757179899999997],[14.7741516,40.757142199999997],[14.7746013,40.757050200000002],[14.7746592,40.757112900000003],[14.774716099999999,40.757190399999999],[14.7748966,40.757436200000001],[14.774949100000001,40.757508000000001],[14.775357400000001,40.758149099999997],[14.776221100000001,40.758195700000002],[14.776471000000001,40.758172899999998],[14.777097599999999,40.758115699999998],[14.777999899999999,40.757795799999997],[14.778625,40.757356000000001],[14.778891700000001,40.757287400000003],[14.7797907,40.757075700000001],[14.780088299999999,40.757101499999997],[14.7811418,40.757178799999998],[14.7820065,40.757252399999999],[14.7829652,40.757199700000001],[14.784323300000001,40.757068400000001],[14.7844742,40.757053399999997],[14.7855615,40.756979100000002],[14.787005300000001,40.756821000000002],[14.7880159,40.756522500000003],[14.788132900000001,40.756489700000003],[14.788338899999999,40.756539500000002],[14.788903700000001,40.756675899999998],[14.789446999999999,40.756806099999999],[14.7907718,40.757549599999997],[14.7914143,40.757975399999999],[14.791491499999999,40.758026600000001],[14.7915986,40.758097499999998],[14.7920862,40.757757900000001],[14.792393199999999,40.757783000000003],[14.792430100000001,40.757739299999997],[14.7926179,40.757517100000001],[14.792703100000001,40.757416300000003],[14.7929897,40.756740200000003],[14.7933352,40.756119699999999],[14.793881900000001,40.755669099999999],[14.794593799999999,40.755093100000003],[14.794702300000001,40.754376499999999],[14.7957944,40.753673399999997],[14.7971945,40.752972700000001],[14.7982291,40.751957400000002],[14.7981015,40.751419200000001],[14.7979299,40.750689700000002],[14.7981745,40.750398300000001],[14.7986247,40.750155100000001],[14.7993124,40.749787300000001],[14.799693700000001,40.749205500000002],[14.8002997,40.748400799999999],[14.8009649,40.747953199999998],[14.801156600000001,40.747367400000002],[14.801536,40.7467811],[14.802119599999999,40.746306099999998],[14.8022522,40.745444300000003],[14.8025369,40.744993299999997],[14.803474700000001,40.744761500000003],[14.8045162,40.745024000000001],[14.805035500000001,40.745168800000002],[14.8055571,40.745313500000002],[14.806623,40.745151700000001],[14.807524300000001,40.7444761],[14.808534099999999,40.743713900000003],[14.809483500000001,40.7430314],[14.8102801,40.742032399999999],[14.8107212,40.741186499999998],[14.8115404,40.740303400000002],[14.811602600000001,40.739278599999999],[14.8118532,40.738244299999998],[14.812484400000001,40.737010599999998],[14.813080599999999,40.7359273],[14.8140771,40.735201799999999],[14.8154299,40.734507800000003],[14.8168408,40.733810800000001],[14.8179797,40.733073599999997],[14.819214199999999,40.732372099999999],[14.8196885,40.731605399999999],[14.8200444,40.731353400000003],[14.8203303,40.7309518],[14.8202845,40.730436500000003],[14.8201543,40.729920999999997],[14.8201923,40.729482500000003],[14.8207849,40.728732399999998],[14.8209898,40.727736399999998],[14.821145400000001,40.727129900000001],[14.82136,40.726988499999997],[14.820650199999999,40.726736299999999],[14.8201654,40.726544799999999],[14.8193725,40.726400400000003],[14.818601900000001,40.726272899999998],[14.817395700000001,40.725865800000001],[14.8163202,40.725321600000001],[14.815327,40.724746199999998],[14.8150174,40.724494999999997],[14.814569799999999,40.724131800000002],[14.814192200000001,40.723462300000001],[14.813992900000001,40.723238299999998],[14.8133534,40.7229016],[14.812489599999999,40.722459100000002],[14.8118648,40.722189100000001],[14.811438799999999,40.721918100000003],[14.8111218,40.721123900000002],[14.8109413,40.721029600000001],[14.8107072,40.720906300000003],[14.810243099999999,40.721277499999999],[14.8100051,40.721851000000001],[14.8094378,40.7224602],[14.8087474,40.722895700000002],[14.8078948,40.7232178],[14.806874000000001,40.7234944],[14.806104700000001,40.723483700000003],[14.8043906,40.723187600000003],[14.8030533,40.722904],[14.8019035,40.722939500000003],[14.8010518,40.723009500000003],[14.800731900000001,40.722644500000001],[14.8004245,40.722293999999998],[14.7996924,40.7221148],[14.798995100000001,40.721834899999998],[14.7985931,40.721193599999999],[14.7978714,40.7210319],[14.797279,40.721201299999997],[14.7968163,40.721296600000002],[14.796117799999999,40.721529799999999],[14.7957026,40.721865800000003],[14.795170499999999,40.721928599999998],[14.7940787,40.722222199999997],[14.793153999999999,40.722651300000003],[14.792384500000001,40.722910599999999],[14.792122300000001,40.723126399999998],[14.792002399999999,40.723542000000002],[14.7917179,40.724037899999999],[14.7911831,40.724307899999999],[14.7904953,40.724621599999999],[14.7901636,40.725034299999997],[14.789876899999999,40.725359300000001],[14.7888927,40.725615900000001],[14.788122899999999,40.726023699999999],[14.7878969,40.726282599999998],[14.7872696,40.726246699999997],[14.7865138,40.725965100000003],[14.7860055,40.7256486],[14.7848101,40.725474699999999],[14.7836246,40.725210199999999],[14.78262,40.724959200000001],[14.781590700000001,40.724713899999998],[14.781130900000001,40.724588400000002],[14.7808463,40.724512699999998],[14.7801011,40.7239966],[14.779108600000001,40.723321800000001],[14.778387199999999,40.722840400000003],[14.7778203,40.722706899999999],[14.776861200000001,40.722732499999999],[14.77623,40.722899200000001],[14.776066,40.7229435],[14.775883800000001,40.722982700000003],[14.7757357,40.723014399999997],[14.7755712,40.723049600000003],[14.775271800000001,40.723113900000001],[14.7746209,40.723061100000002],[14.773959,40.7232743],[14.773293499999999,40.723478700000001],[14.7725954,40.723504800000001],[14.7721198,40.723938199999999],[14.7717759,40.724441599999999],[14.771725200000001,40.7248807],[14.7717957,40.725385799999998],[14.7717372,40.725982799999997],[14.7715783,40.7266659],[14.771304499999999,40.7272873],[14.7711244,40.728007499999997],[14.7713473,40.728522900000002],[14.772186700000001,40.7290524],[14.7722316,40.729290900000002],[14.7722924,40.7296142],[14.772313499999999,40.7297212],[14.7722529,40.729820500000002],[14.772064200000001,40.7301298],[14.772028199999999,40.730190499999999],[14.772278999999999,40.730627599999998],[14.7724163,40.7308637],[14.7724609,40.731685200000001],[14.7721751,40.732244100000003],[14.771758500000001,40.732719600000003],[14.7709513,40.733304699999998],[14.770571500000001,40.7336344],[14.770403999999999,40.734089900000001],[14.770273599999999,40.734436899999999],[14.7701365,40.734757600000002],[14.769854799999999,40.735416600000001],[14.7693192,40.7360556],[14.7686682,40.736173800000003],[14.767875800000001,40.735965999999998],[14.767141000000001,40.735800300000001],[14.766158799999999,40.735809000000003],[14.7649875,40.735615699999997],[14.764691900000001,40.735157899999997],[14.7638403,40.7349575],[14.7633312,40.735118],[14.762624199999999,40.735394999999997],[14.7625148,40.735420699999999],[14.7623113,40.735464399999998],[14.762259,40.735475600000001],[14.761836300000001,40.735611499999997],[14.761665600000001,40.735674099999997],[14.7612424,40.735825800000001],[14.7609136,40.735971599999999],[14.760858799999999,40.735995799999998],[14.760703700000001,40.736071099999997],[14.760508400000001,40.736173100000002],[14.7604375,40.7362082],[14.7601409,40.7363626],[14.7596623,40.7367171],[14.759463200000001,40.736864599999997],[14.7588588,40.737205400000001],[14.758608600000001,40.7373574],[14.7580749,40.737676700000002],[14.758003199999999,40.737720799999998],[14.7571239,40.738201400000001],[14.7562725,40.738491600000003],[14.7558276,40.738495899999997],[14.7553831,40.738504599999999],[14.755236200000001,40.738448900000002],[14.754603400000001,40.738188000000001],[14.753576600000001,40.737755300000003],[14.753467300000001,40.737709199999998],[14.7522723,40.737480900000001],[14.7513004,40.737507000000001],[14.750353,40.737576900000001],[14.749359,40.7373385],[14.748211899999999,40.736860200000002],[14.746816000000001,40.736497900000003],[14.745810499999999,40.736151999999997],[14.745623699999999,40.735504200000001],[14.7456861,40.734573900000001],[14.7456067,40.733817199999997],[14.7449923,40.733348300000003],[14.744426000000001,40.732759999999999],[14.7435981,40.732310699999999],[14.7425449,40.7323363],[14.7413819,40.732709399999997],[14.7411083,40.733447699999999],[14.7406551,40.734212999999997],[14.7399042,40.734957100000003],[14.738638699999999,40.735137299999998],[14.737383400000001,40.735042300000003],[14.7363979,40.735320999999999],[14.7355187,40.735959000000001],[14.734391499999999,40.736541799999998],[14.7331348,40.736843],[14.732068399999999,40.7370041],[14.732382100000001,40.738644899999997],[14.732307799999999,40.739337200000001],[14.732151200000001,40.739975100000002],[14.7318412,40.740490200000004],[14.7314963,40.740840400000003],[14.731351800000001,40.7413338],[14.7309231,40.742007800000003],[14.7302813,40.742638399999997],[14.730301499999999,40.743560100000003],[14.7308556,40.744144599999998],[14.7312691,40.744668599999997],[14.731407799999999,40.745282799999998],[14.7314428,40.7455511]]]]}]}

Instead, if i send this command using the tile38-cli it works.

The function i'm using is quite simple:
i have a StreamWriter and a StreamReader and it's something like this:

```
Writer.WriteLine(command);
var response = Reader.ReadLine();
```

The POINT, BOUNDS, NEARBY and the others commands work with no problems.
Can anyone help me?

**Comment by tidwall** [comment]
I'm super sorry about the late response. Is this something that you still need help with? 

At first glance it appears that you are sending the server a raw command as a space delimited string. But the server expects the command to be in the [redis protocol](https://redis.io/topics/protocol) format. I recommend using one of the [client libraries](https://github.com/tidwall/tile38#client-libraries).

**Comment by mleone20** [comment]
Hi! Thanks for the replay, even the super late ;)
I think i was using a very old version of the server because after the upgrade to the last version it's working

**Comment by tidwall** [comment]
👍 Glad to hear.
