### ISSUE TITLE
use within or scan command only return 100 results by default.

### ISSUE THREAD

**Issue by pujian1984** [tidwall/tile38#265]
use within or scan command only return 100 results by default.
but if i use limit command, for example limit 1000,we can get all result.
how to get all result?
thank you very much.

**Comment by tidwall** [comment]
Hi @pujian1984,

100 results is the default limit, if you want more you'll need to use LIMIT. If you want all results, then I recommend using huge number such as 100000000. A number that's much larger than the total objects in the collection.

**Comment by sixstone-qq** [comment]
Hey @tidwall , I just stumbled upon this default limit :innocent: I haven't seen that as documented.

Could you document it in https://tile38.com/commands/within and/or https://tile38.com/commands/scan and/or https://tile38.com/commands/intersects?

Thank you very much for this amazing software :hugs:

**Comment by tidwall** [comment]
@sixstone-qq I'm happy to hear you like the software!
I just pushed an update to the documentation site. 
Thanks for reporting.

**Comment by Vladimir-Kuchinskiy** [comment]
@tidwall I am wondering, is there any engineering reason behind such a default limitation, or it is just such an API design that you decided to have ?

**Comment by tidwall** [comment]
@Vladimir-Kuchinskiy Just an API design the made sense to me at the time. I didn't want the results to be unbounded, and 100 seemed like a pretty good default.
