### ISSUE TITLE
Embeddable?

### ISSUE THREAD

**Issue by rucuriousyet** [tidwall/tile38#266]
Is there any way this could easily be integrated into another Go program to be used in an embedded fashion? I am working on a game server which will require very low latency for location queries, ideally Tile would be part of the server itself...

**Comment by tidwall** [comment]
I think it's possible but easy. There're a few different components that work in sync to make up the system. 

If all you need to create collections of points and such, the controller/collection package is a good start. If you need to persist data and have a network layer then things get complicated fast.

#140 might be helpful.

**Comment by rucuriousyet** [comment]
Thanks, I'll dig into that.

-sent from my OnePlus X

**Comment by tidwall** [comment]
FYI, I moved all of the internal packages into the "pkg" directory. 

I'm closing this issue for now, but feel free to reopen if you have further question.

Thanks!
