### ISSUE TITLE
Runtime Error  1.10.0  1.10.1 

### ISSUE THREAD

**Issue by gmonk63** [tidwall/tile38#269]
Versions 1.10.0 & 1.10.1 compile fine on RPI3 with go version 1.10  but  error out with the following 

127.0.0.1:9851> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11dfc]

goroutine 20 [running]:
sync/atomic.addUint64(0x12cfc03c, 0x1, 0x0, 0x0, 0xc0000000)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/tidwall/tile38/controller.(*aint).add(0x12cfc03c, 0x1, 0x12de6040)
	/tmp/tile38.K2QF/go/src/github.com/tidwall/tile38/controller/atomic.go:12 +0x30
github.com/tidwall/tile38/controller.ListenAndServeEx.func6(0x12de6040)
	/tmp/tile38.K2QF/go/src/github.com/tidwall/tile38/controller/controller.go:254 +0x160
github.com/tidwall/tile38/controller/server.handleConn(0x12de6040, 0x12b0c7a0, 0x12d88528, 0x12b0c7b0, 0x12d88530, 0x1)
	/tmp/tile38.K2QF/go/src/github.com/tidwall/tile38/controller/server/server.go:93 +0x60
created by github.com/tidwall/tile38/controller/server.ListenAndServe
	/tmp/tile38.K2QF/go/src/github.com/tidwall/tile38/controller/server/server.go:80 +0x1b4
127.0.0.1:9851> 

version 1.9 works without issue

**Comment by tidwall** [comment]
Is the RPI3 running 32bit linux?

**Comment by gmonk63** [comment]
Yes it is running rasbian 32bit

**Comment by tidwall** [comment]
OK. I think I know what might be the cause. 
I have a 64bit and 32bit RPI3 in my lab so I should be able to fix it from my side. 
I'll keep you posted.

**Comment by gmonk63** [comment]
Awesome thanks for the quick response...

**Comment by tidwall** [comment]
I just pushed an update to master that should fix the issue. Please give it a test and let me know. Thanks!

**Comment by gmonk63** [comment]
Works great !! Thank you .. If your ever in the North Phoenix area I owe you a beer :)

**Comment by tidwall** [comment]
Glad it worked out. I’d love to hear about your PI solution. Over beers of course. 🍺
