### ISSUE TITLE
missing documentation about performance

### ISSUE THREAD

**Issue by cloudspeech** [tidwall/tile38#27]
This looks like a great project and especially (dynamic) geofencing is super-interesting. 

However, I didn't find any documentation on **performance**. To take one example of interest, if
one stored a set of 1 million moving points in tile38 representing people in a large country, and then issued a dynamic geofencing query on that set, what is the memory usage and what latency can we expect?

To answer such questions, it would be helpful to have performance (time+memory) comments per query type/operators, maybe big-O-notation hints related to the underlying algorithms, and hints on scalability, the various limits affecting it etc.

Even a subset of such documentation would be very helpful.

**Comment by tidwall** [comment]
Thanks for the suggestion. I agree that this would be very helpful. I added it to our roadmap.

**Comment by tidwall** [comment]
I'm consolidating request into one issue at #54
