### ISSUE TITLE
Attribution for the R-Tree code

### ISSUE THREAD

**Issue by mourner** [tidwall/tile38#271]
Hi @tidwall,

I've noticed that most of the R-tree code in this project is ported from https://github.com/mourner/rbush — would you be so kind as to include some kind of attribution for it?

Thank you!

**Comment by tidwall** [comment]
Absolutely, and I just want to say that you do excellent work. Your RBush logic helped boost Tile38's overall performance by about 20%. Thanks a ton!

I added a note to the README and made sure the ported files match with your original notices. If this does not suffice, please let me know.

**Comment by mourner** [comment]
Fantastic, thank you! This is more than enough — a simple link in the source code would suffice. :) You can remove the cited licenses if you want.
