### ISSUE TITLE
Preserve Docker image tag history

### ISSUE THREAD

**Issue by gechr** [tidwall/tile38#272]
Currently there's a single dynamic image tag (`latest`) which points to the most recent version.

Would it be possible to also tag images with the actual static version to allow us to pin to specific versions? Example: https://hub.docker.com/r/library/consul/tags/

**Comment by tidwall** [comment]
Should be possible.

**Comment by tidwall** [comment]
Tile38 is now tracking tags.
https://hub.docker.com/r/tile38/tile38/tags/

**Comment by tidwall** [comment]
This issue has been addressed. Thanks!
