### ISSUE TITLE
Fantastic !!

### ISSUE THREAD

**Issue by abhit011** [tidwall/tile38#274]
@tidwall 
Its a fantastic tool 🥇 

I have been developing something like the same using GeoRadius Redis commands, then on one day while grepping something on internet found tile38.. Its worth an applaud .
 
Need to know few things before I start picking for my product. 

1. I have huge traffic, the no of ID's will be close to 500K and at any sec there would be close to 10k/Sec SET of Various ID's getting inserted with respective location coordinates, Can it handle that load ? How to enable it in a distributed way ?

2. Simultaneously I will be having close to 100K Geofences  to monitor the traffic inside/Outside  ? And these will be keep on increasing  ?

3. I need to group Geofences at Global Level and at Group level, like pool of ID's will belong to set of Geofences and those pool of ID's inside/outside movement should happen on the assigned Geofnces only rather than whole Global Set of Geofences. 
If at any point I need to get the Haversine distance of an ID with its assigned Group of geofences , how it can be done ?

Courtesy
Abhi
!wq

**Comment by abhit011** [comment]
Any replies ?

**Comment by tidwall** [comment]
Hi @abhit011, 

Tile38 doesn't have specific limits built into it. The performance is mostly bound by the server hardware. Like Redis, the database is in-memory and data is stored in tree-like structures. So if you have lots of data, you will need lots of ram. 

Much depends on the spatial complexity of your objects. Simple points are pretty small and we can fit a million of them in less than a 500MB. Geofences are typically polygons so each vertex counts as a point, and this can add up. Additional data like IDs and fields are on top of the spatial data.

The number of operations per second will depend on your network and CPU. I would say 10k/sec is no problem, but I recommend that you try it in your environment.

There's no limit on the number of geofences, but the complexity of the geofence and the type of event notifications can affect performance. For example, if you are only watching for ENTER and EXIT events is easier on the system than if you watch for all events (OUTSIDE,ENTER,INSIDE,EXIT,CROSS). 

I hope this information helpful.

**Comment by abhit011** [comment]
Thanks @tidwall .. anyplace where it mentions about starting tile38 it in distributed way ?

**Comment by tidwall** [comment]
There's nothing specifically built into Tile38 that addresses distributing a dataset over multiple server instances. Tile38 is a single node environment.

Distributing geo data can sometimes be tricky and there're a number of strategies. A common way that I've seen is to break the dataset up into geographical regions and store each regions on separate servers.

There's no turnkey solution that I'm aware of, so you'll probably have to get a little creative.

**Comment by tobilg** [comment]
@tidwall Thanks for the insights! 

Regarding scaling, is my understanding correct that when using the leader/follower mechanism, one could use a load balancer in front of the different Tile38 nodes to achieve scaling at least for the read operations?

**Comment by tidwall** [comment]
@tobilg That's correct. I should have mention it in my prior comment. Thanks!

**Comment by abhit011** [comment]
@tidwall 
Need to ask if tile38 single threaded like Redis ? 
I am making some architectural changes at my stack ... 

If its a single threaded like Redis , then I will always pump data to tile38 i.e "set points" using a single thread only. That thread will send exodus of data to each tile38 instance and those each instances would be receiving specific geography "set points" only , in that case I am distributing the load among n tile38 instances. 

GeoFences in my case are always static, i need to just create them once. But the number of geofences are in millions. 
I wont be storing complex polygon figures but rather would be storing just a bounding box.. Hope it can handle and yes there would be hooks huge too.. Hooks end point would be Kafka.. 

Hope it can handle the load ?

**Comment by abhit011** [comment]
@tidwall ??

**Comment by tidwall** [comment]
@abhit011 

Tile38 is multithreaded. All client connections are independent from one another. It uses locking for multiple readers and a single writer. Thus as many read-only command, like INTERSECTS, can be executed at the same time, but commands like SET and DEL are one at a time.

Keeping the Geofences small will help with performance.

**Comment by abhit011** [comment]
@tidwall 
I have set close to 41K + hooks in one tile38 node..
its serer info gave
`{"ok":true,"stats":{"aof_size":27551063,"avg_item_size":0,"heap_released":0,"heap_size":234086464,"http_transport":true,"in_memory_size":0,"max_heap_size":0,"mem_alloc":234086464,"num_collections":0,"num_hooks":41473,"num_objects":0,"num_points":0,"num_strings":0,"pid":33052,"pointer_size":8,"read_only":false},"elapsed":"0s"}
`But the RAM is close to 500+ MB , why right now I am not doing any set points and stuffs. but then why RAM is 500 + MB ?

**Comment by tidwall** [comment]
@abhit011 

The `heap_size` shows 223 MB being used. Is the OS reporting the 500+ MB?

**Comment by abhit011** [comment]
@tidwall 
Its OS reported...

**Comment by tidwall** [comment]
With Go processes, it's often that the OS reports more memory that what application uses. This isn't usually a problem, as that memory will eventually be reclaimed. 

You can also try the Tile38 commands `GC`, which will forces the process to attempt to clear unused memory. Though it might not affect what the OS is reporting.

**Comment by tidwall** [comment]
I'm closing this issue for now. Feel free to reopen if needed. Thanks.
