### ISSUE TITLE
MQTT ?

### ISSUE THREAD

**Issue by gmonk63** [tidwall/tile38#279]
Would it be possible to add MQTT as a webhook?  this way any endpoint interested in the data could subscribe to the stream.

SETHOOK warehouse mqtt://brokeraddress  -t topic -u username -p password  NEARBY fleet FENCE POINT 33.5123 -112.2693 500

**Comment by tidwall** [comment]
I think MQTT was added a while back. #155 

But I just realized that there's no documentation for it at http://tile38.com/commands/sethook/

🤦

**Comment by gmonk63** [comment]
Thanks for the link..  Its working well. Its it possible to retrieve the hook id  in the response ?  When i setup two hooks say one for Mesa Dr & Brown   and  a second for Mesa Dr & University the only way i would know is based on coordinates but it would be easier if could just get the id 

Thanks
