### ISSUE TITLE
[Question] Nearby filter

### ISSUE THREAD

**Issue by sweco-semtne** [tidwall/tile38#280]
Hi,
I'm trying to understand the nearby / knn function. 
Is it possible to provide a filter similar to the rbush knn filter function?

```
knn(tree, x, y, [k, filterFn, maxDistance])

tree: an RBush tree
x, y: query coordinates
k: number of neighbors to search for (Infinity by default)
filterFn: optional filter function; k nearest items where filterFn(item) === true will be returned.
maxDistance (optional): maximum distance between neighbors and the query coordinates (Infinity by default)
```
Basically I have properties on the objects and I would like the NEARBY to give me the n closest with a given property. 
I'm thinking that MATCH is used after the KNN has obtained the result?

Thanks for a great product btw!

**Comment by tidwall** [comment]
Interesting. This sounds like something that needs to be fixed and similar to #199.

**Comment by tidwall** [comment]
I just pushed a fix to the master branch.

**Comment by sweco-semtne** [comment]
Thanks! I’ll try it out. And once again, fantastic work!

**Comment by tidwall** [comment]
You’re welcome and thanks for the kind words. :)
