### ISSUE TITLE
Not receiving http webhooks

### ISSUE THREAD

**Issue by tobilg** [tidwall/tile38#285]
I create a geofence with a webhook with the node-tile38 module like this:

```javascript
    let meta = { field: 'val1', field2: 'val2'};
    let opts = {
        point: [33.5123, -112.2693],
        radius: 10000
    };
    tileClient.setHook('testhook0', 'http://localhost:5656/webhook', meta, 'nearby', 'fleet', opts).then((result) => {
        console.log(JSON.stringify(result));
    }).catch((err) => {
        console.lof(JSON.stringify(err));
    });
```

When I create a key with a location within the geofence like this

```javascript
    tileClient.set('fleet', 'truck1', [33.5123, -112.2693]).then((result) => {
        console.log(JSON.stringify(result));
    }).catch((err) => {
        console.log(JSON.stringify(err));
    });
```

I don't receive a webhook POST request to the given webhook, as I assumed I would do... What could have gone wrong? Thanks!

**Comment by tobilg** [comment]
I verified that both the geofence as well as the key are written to Tile38. Sorry to not mention that above.

**Comment by tidwall** [comment]
Are you seeing any errors with the setHook call?

**Comment by tobilg** [comment]
No, both calls are going through smoothly. Here's the output from Tile38:

```bash
127.0.0.1:9851> hooks * 
{"ok":true,"hooks":[{"name":"testhook0","key":"fleet","endpoints":["http://localhost:5656/webhook"],"command":["NEARBY","fleet","FENCE","POINT","33.5123","-112.2693","10000"]}],"elapsed":"64.2µs"}
127.0.0.1:9851> get fleet truck1
{"ok":true,"object":{"type":"Point","coordinates":[-112.2693,33.5123]},"elapsed":"943.5µs"}
```

**Comment by tobilg** [comment]
Is there a way to check on the server side (logs?) whether the webhook is triggered or not?

**Comment by tidwall** [comment]
There isn't a log (though there probably should be). Messages generally get sent immediately. If there's a hiccup with delivery then the message gets queued to queue.db and Tile38 tries again asap.

There's a built-in http-webhook tester that I use for diagnostics:

```sh
$ tile38-server --webhook-http-consumer-port 5656
```

All this does is create a webhook listener and print the notification to the console.

**Comment by tidwall** [comment]
Actually if start tile38-server with `-vv` you'll see notification delivery log messages such as:

```
2018/03/14 09:58:32 [DEBU] Endpoint send ok: 5: http://localhost:5656/webhook: <nil>
```

**Comment by tobilg** [comment]
Thanks for the fast replies! I started the server with `-vv` and now I actually see the error:

```bash
2018/03/14 17:23:08 [DEBU] Endpoint connect/send error: 1: http://localhost:5656/webhook: Post localhost:5656/webhook: dial tcp localhost:5656: connect: connection refused
```

It seems to be the problem that I was running it in Docker Compose, and localhost is pointing to the container of Tile38 if it isn't run in host networking mode I guess. Strangely, I see connection refused problems when running it in host networking mode from my node app when I try to connect to it then via `localhost:9851`, which *should* work IMO. Seems to be a Docker for Mac problem though.

**Comment by tobilg** [comment]
BTW, it seems there is no exponential backoff strategy in place, or am I wrong?

**Comment by tidwall** [comment]
The server will eventually give up on a message after too long, around a minute or so.

**Comment by Lokeshjilli** [comment]
@tidwall Is there any way to check on the logs whether the web-hook is triggered or not? since i am not able trigger the webhook.

**Comment by iwpnd** [comment]
> Actually if start tile38-server with `-vv` you'll see notification delivery log messages such as:
> 
> 
> 
> ```
> 
> 2018/03/14 09:58:32 [DEBU] Endpoint send ok: 5: http://localhost:5656/webhook: <nil>
> 
> ```

see above

**Comment by Lokeshjilli** [comment]
Hi @iwpnd,

Yeah, I started tile38 server with tile38-server -vv but i am not able see any logs.
in my case i am using amazon SQS endpoint.  I am able to set the data in tile38 collection for that created hook but I want o see why hook is not triggered

**Comment by iwpnd** [comment]
What do you mean you're not _able_ to see any logs? If you don't see anything, your hooks are not not triggering.

You can test your setup locally and eliminate the possibility that your hooks don't fire because of a falsely setup with the [use of channels](https://tile38.com/topics/geofencing).

**Comment by Lokeshjilli** [comment]
What do you mean you're not able to see any logs? If you don't see anything, your hooks are not not triggering.
         I mean, yeah hooks are not triggering, I want to know what is the reason for that - is there any way to check the logs?
         Using channels, its working fine. I have tested it

**Comment by iwpnd** [comment]
Your server is emitting logs of you start it with the `-vv` flag.

**Comment by Lokeshjilli** [comment]
@iwpnd below are the logs listed when I start server with -vv, but hook is not triggering when breach happens.

2023/12/15 11:37:13 [INFO] Server started, Tile38 version 1.32.1, git c494fe54
2023/12/15 11:37:13 [DEBU] Geom indexing: QuadTree (64 points)
2023/12/15 11:37:13 [DEBU] Multi indexing: RTree (64 points)
2023/12/15 11:37:13 [INFO] Ready to accept connections at [::]:9851
2023/12/15 11:37:13 [INFO] AOF loaded 274 commands: 0.00s, 107075/s, 15 MB/s
2023/12/15 11:37:20 [DEBU] Opened connection: 127.0.0.1:61283

**Comment by iwpnd** [comment]
I suggest you open another issue, tell us what you want to do and provide some example code for anybody to reproduce. If you do not see any log when entering a hook - from my experience - it always comes down to a wrong setup. 
If it were anything else the hook manager would throw an error that it cannot send the message. Take the latter with a grain of salt as I have never used SQS with tile38 and do not have the time to look into the SQS client right now.

**Comment by Lokeshjilli** [comment]
Ok, i will open issue and provide you some example to start with. Thank you @iwpnd

**Comment by NaveenDA** [comment]
I encountered an issue and later realized that I was running Tile38 inside a Docker container while using http://localhost:3000 as the webhook URL. The problem was that the container couldn’t access the host machine’s localhost.
