### ISSUE TITLE
Writes to disk

### ISSUE THREAD

**Issue by gmonk63** [tidwall/tile38#286]
Just wondering how often tile38 writes to disk.  With this being embedded in the RPI I was curios as to how harsh it would be on the SD card.

Thanks

**Comment by tidwall** [comment]
It writes to disk after every write command, such as SET, DEL, etc. Though all disk writes are sequential and Tile38 leaves the fsync up to the OS, so it shouldn't be too big of a deal assuming you have an sdcard with good write performance. 

If the writes are too harsh on the disk then you may want to increase the linux buffer cache size.

**Comment by gmonk63** [comment]
once again thank you for the quick reply
