### ISSUE TITLE
WITHIN returns thousansd..  INTERSECTS returns nothing...

### ISSUE THREAD

**Issue by fils** [tidwall/tile38#295]
Example code:
https://github.com/earthcubearchitecture-project418/garden/blob/master/spatialtesting/simpleClient/simpleclient.go

The line 92
```
reply, err := redis.Values(c.Do("INTERSECTS", "p418", "CURSOR", "0", "LIMIT", "50000", "OBJECT", geowithin))
```
returns nothing..
the line 93
```
reply, err := redis.Values(c.Do("WITHIN", "p418", "CURSOR", "0", "LIMIT", "50000", "OBJECT", geowithin))
```
returns thousands..

if I understand it..  INTERSECTS should always be a super set (or at least equal to) WITHIN.

The geometry object is defined in the function at line 24.

Any obvious reason these two commands result in this behavior?

Running tile38 in docker using the latest image from about 5 days ago
```
fils@xps:~/Project418/gleaner$ docker images | grep -i tile
tile38/tile38            latest              e03153b68c0c        5 days ago          33.2 MB
```

**Comment by tidwall** [comment]
Hi Douglas, 

You're correct, INTERSECTS should return at least the same number of results as WITHIN.

I'm not seeing any issues on my side, I tried your code with random points. I did noticed that your example code doesn't accept points as results so I added this to the switch statement at Line 204:

```go 
case "Point":
	g, err := geojson.UnmarshalGeometry(rawGeometryJSON)
	if err != nil {
		log.Printf("Unmarshal feature error for %s with %s\n", val0, err)
	}
	f := geojson.NewFeature(g)
	f.SetProperty("URL", val0)
	fc.AddFeature(f)
	break
```

Now it's returning my test points.

But I'd like to try it against some of your data. If possible could you attach some of the test data that's causing the problems?

Thanks!

**Comment by tidwall** [comment]
I found the issue and I pushed a fix to the master branch. 
Thanks for letting me know.

**Comment by fils** [comment]
@tidwall   great news..  thanks!
FYI..  did the AOF file work to send you the data?  Didn't know if that was a working approach or not.

Thanks again!

**Comment by tidwall** [comment]
You're welcome.

I used your AOF file and it help very much.

The bug had to do with objects being wrapped in Features and then further wrapped in a FeatureCollection and the resulting boolean value for the intersection function was being transposed. I discovered that the same problem existed for the GeometryCollection type. 😬
