### ISSUE TITLE
Can the disk be not written？

### ISSUE THREAD

**Issue by zhangfeng158** [tidwall/tile38#297]
I want the local disk to do no writing. No AOF is produced.
While prohibiting AOF, it doesn't mean that it doesn't write to disk anymore.

**Comment by zhangfeng158** [comment]
In our application scenario, data are real-time, and do not need recovery and persistence.
Can you provide a switch to disable the persistence capability.

**Comment by tidwall** [comment]
I just pushed an update to the master branch that allows for disabling the AOF file.

**Comment by zhangfeng158** [comment]
Thanks very much
