### ISSUE TITLE
DELHOOK always returning true even if hook doesn't exist

### ISSUE THREAD

**Issue by tobilg** [tidwall/tile38#299]
I just recognized that Tile38 is always returning a `true` message when trying to delete a non-existing `HOOK` via 

```bash
127.0.0.1:9851> DELHOOK sodifhsoif
{"ok":true,"elapsed":"2.909µs"}
```

I'd like to suggest to change that to sending an "not found" error. Would that make sense?

**Comment by tidwall** [comment]
It does makes sense but I'm worried that changing at this point might break existing client implementations.

**Comment by tobilg** [comment]
Ok, that makes sense to me.
