### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by rse** [tidwall/tile38#3]
When one lets tile38-server listening on not just 127.0.0.1 one needs authentication. For this tile38-server should perhaps support a config file with users/passwords pairs and tile38-cli should have options to supply username/password during connect. Optimally, the connection between tile38-cli and tile38-server should be SSL/TLS encrypted so that the password is not transmitted unprotected. Or at least a hash of the password should be transmitted only.

**Comment by agborkowski** [comment]
+1

**Comment by tidwall** [comment]
Hello @rse, I totally agree. Currently Tile38 is designed to run in a trusted environment, and it should not be exposed directly to the internet or other networks that are untrusted. There should be a layer in the middle such as a web application that mediates access. In the case of HTTP or WebSockets that could be Nginx or Haproxy, but most often a custom application. Each of which could include it's own SSL and authentication support.

But that being said, I do intend on adding a lightweight protected-mode and authentication in the next update. At the start this will be quite simple and likely resemble the [Redis Security](http://redis.io/topics/security) model. 

By default Tile38 will only accept connections from the loopback interface. 
Unless one of these three are true:
1. A hostname (`-h` flag) is specified. 
2. `protected-mode` is explicitly turned off. This will be a config option and/or `--protected-mode no` flag.
3. An auth password is defined.

I'm hoping that this will cover most network security requirements moving forward.

Let me know your thoughts.

**Comment by tidwall** [comment]
I added this feature to the latest commit. But I have `protected-mode` set to`no` by default for now.

For now use this command.
```
./tile38-server --protected-mode yes
```
