### ISSUE TITLE
Special hook

### ISSUE THREAD

**Issue by giksa** [tidwall/tile38#30]
I'm using Tile38, but i have a problem.
I will try to explain it with an example application:
This is an app that let you communicate with the first person near you but this feature is a communication with the opposite sex, so for example i have a person (male) that is looking for someone (woman) and in the application i set a static geofence (i need it static) with a radius of 150m that detect if a woman is inside the area.
When a woman enters to the area the man is notified, but i have this problem:

* The man is looking for a woman in a radius of 150m, and there is no one.
* Another man, closer to the first man (10m) is also looking for a woman, but again, there is no one.
* A woman enters to the area.

In this case, both men are notified and i want that just the first (time based) man looking for a woman receives the notification and the other man needs to wait until another woman enters to the area.

**How can i do it?**

I was thinking severals methods to do it in the code, but in every case i have problems with two instances doing the same thing (hook receives two notification, one for every man, so the backend will do the same operation for every man) for example:

* The woman enters
* The resources get notified (two men)
* I update a field of the men, with the user id (woman) that is looking for
* I have to query all the users (man) that are looking for the same user (woman). To send the notification to the older one looking for the woman.

In this case, maybe one of the two resources that are executing the same operation in the same time, hasn't updated the field, this could be the first man, so the second man will detect there is no other man looking for that woman so will get notified, but when the resource for the first man detect the two men, the resource will also detect that this user is the older one and will get notified. **So, the both men are notified**.

**Comment by tidwall** [comment]
If I am understanding your problem correctly. You have:

- Two Men. Let call them `M1`, `M2`.
- Two Women. `W1`, `W2`
- One 150km WebHook Geofence. `G1`

When `W1` or `W2` enter `G1` you would like `M1` xor `M2` to be notified once.

Is this correct?

Also I'm assuming that this is a mobile application that the each participating man and women have on their phone.

**Comment by giksa** [comment]
`M1` start to looking for a woman at 10:00AM with a Geofence `G1`
`M2` start to looking for a woman at 10:30AM with a Geofence `G2`

When this happen (`M1` and `M2` waiting for a Woman), I want that when `W1` enters just `M1` get notified.

Why just `M1`? Because he start to looking for a Woman before `M2`

After `M1` gets notified, the `G1` is deleted and the `M2` with `G2` will continue looking for a woman.

Graphical example:
![sin titulo-3](https://cloud.githubusercontent.com/assets/19378835/17283593/3581580e-5780-11e6-8df9-c84d5bf4fa2e.jpg)

**Comment by tidwall** [comment]
Is this is a mobile application that each **participating** man and women have on their phones?

===

Is `W1` being detected by `G1` and `G2`?
Does both `G1` and `G2` send the notifications correctly?

If so, each geofence notification should contain look something like:
```json
{
    "command": "set",
    "detect": "inside",
    "hook": "G1",
    "time": "2016-03-20T09:37:49.567854293-07:00",
    "key": "users",
    "id": "W1",
    "object": {
        "type": "Point",
        "coordinates": [-112.2695, 33.4626]
    }
}
```

So you have the timestamp, the hook name (`G1`), and the id (`W1`). This should be all you need from Tile38.  At this point your application server must decide on the what to do with the data.

If something is not working correctly, please let me know.

Thanks
