### ISSUE TITLE
AMQP error message

### ISSUE THREAD

**Issue by tobilg** [tidwall/tile38#301]
When trying to implement topic-based routing with RabbitMQ and Tile38, I'm seeing the following error message:

```bash
Endpoint connect/send error: 48: amqp://guest:guest@127.0.0.1:5672/webhook-events?type=topic&route=hook.http: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'webhook-events' in vhost '/': received 'direct' but current is 'topic'"
```

I'm pretty confident I set up the exchange correctly:

![alt text](https://i.imgur.com/u6A0hpv.png)

I don't understand where the `received 'direct' but current is 'topic'` is coming from unfortunately. Do you happen to have an idea? Thanks!

**Comment by tobilg** [comment]
Thanks for the fast response! I think it’d be great to be able to set all these parameters via the endpoint query string, as outlined in the docs.

**Comment by tidwall** [comment]
Sounds good. I'll see what I can do. Thanks

**Comment by tidwall** [comment]
I just pushed an update that allows for setting each of the paramaters.

**Comment by tobilg** [comment]
Thanks a lot! Is the Docker image „latest“ tag built automatically? 

I guess there will be another release soon as well? That’d be great 😀👍🏻

**Comment by tidwall** [comment]
It does build automatically, but it tracks the latest version, not the master branch. 

In this case latest -> v1.12.0. 

I may need to figure out a better approach. Is it normal for docker latest tag to track the master branch?

**Comment by tobilg** [comment]
I’d say it is a common practice to have latest point to master. Other people might disagree though... 😀

**Comment by tobilg** [comment]
@tidwall is this change in the current `latest` Docker image? The exchange seems still to be set to `direct` even when specifying `topic` in the endpoint URI... Thanks!
