### ISSUE TITLE
Who uses Tile38?

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#306]
I’d like to gather a list of projects/companies using Tile38, for the [tile38.com](http://tile38.com) website.

Let me know if your project/company uses Tile38 and wouldn't mind being mentioned on the website. Include a logo with a link to the project if you have one. A short description on how you use Tile38 and how it has helped you is also welcome.
 
Thanks!!

**Comment by contra** [comment]
![image](https://user-images.githubusercontent.com/425716/39166291-e1b94ca4-4756-11e8-9af4-71ed01a274b2.png)

https://stae.co/

We use tile38 to do geography based data partitioning for cities - we were previously doing this in PostGIS which was taking 8 seconds. Tile38 brought this down to ~100ms which allows us to ingest data faster.

**Comment by abhit011** [comment]
@contra that's a great improvement, If possible  can I know also how many nodes you are running of Tile38 and what's the load per second and other details etc? 

Abhi

**Comment by contra** [comment]
@abhit011 Between 4 and 16 tile38 nodes depending on load - we do roughly 10 to 15K intersections per second on tile38.

**Comment by abhit011** [comment]
thanks @contra for sharing info ... There is strange thing, there were complex polygon , i have changed all those complex polygon into bounding boxes .. I have set close to 41K + hooks in one tile38 node.. 
its serer info gave 
`{"ok":true,"stats":{"aof_size":27551063,"avg_item_size":0,"heap_released":0,"heap_size":234086464,"http_transport":true,"in_memory_size":0,"max_heap_size":0,"mem_alloc":234086464,"num_collections":0,"num_hooks":41473,"num_objects":0,"num_points":0,"num_strings":0,"pid":33052,"pointer_size":8,"read_only":false},"elapsed":"0s"}`
But the RAM is close to 500+ MB , why right now I am not doing any set points and stuffs. but then why RAM is 500 + MB ?

Abhi
