### ISSUE TITLE
Is SCAN with ROAMING removed?

### ISSUE THREAD

**Issue by dbathily** [tidwall/tile38#315]
Hi,

According to this issue #96, adding `scan:*` to the roaming command should work. But I have an `invalid argument 'scan:'*`. Is this feature removed or replaced by something else?

Regards,
Didier

**Comment by tidwall** [comment]
Sounds like the syntax or format error. Could you share the entire command that you're using?

**Comment by dbathily** [comment]
Yes, `nearby people fence roam people peopleID 500 scan:*`

**Comment by tidwall** [comment]
It looks like you need a space between `scan` and `:`.

```
NEARBY people FENCE ROAM people peopleID 500 SCAN :*
```

**Comment by dbathily** [comment]
You are right, thank you
