### ISSUE TITLE
How to use the command 'AOF pos'?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#32]
I have started a Leader and a Follower,then send command 'aof 0' to the Leader,it does not work……

**Comment by tidwall** [comment]
Hi @icewukong 

The "AOF pos" command will download the append-only file starting at the byte position specified. The connection is kept open and downloading will continue until you close the connection. 

This command should not be called directly. 

If you are wanting to setup a leader/follower please look at the topic on [Replication](http://tile38.com/topics/replication). The only command you need to make a server a follower is [FOLLOW](http://tile38.com/commands/follow).

**Comment by icewukong** [comment]
I has already  setup a leader/follower. I want to send the data from the pos of append-only file to follower,what should I do?

**Comment by icewukong** [comment]
If the master / slave relationship is established,then the connection is broken again, and it is necessary to send a 'AOF pos' command to the follower to implement the synchronization again?

**Comment by tidwall** [comment]
When the leader/follower connection is broken, the follower will automatically reestablish a new connection. Once connected, the follower will send an AOFMD5 an then AOF to catch up to the follower. 

This is all automated in the background. You shouldn't need to send any commands.

**Comment by icewukong** [comment]
Oh,understand!
Thanks for answering!!!
