### ISSUE TITLE
EVAL command not working

### ISSUE THREAD

**Issue by PascalSavage** [tidwall/tile38#322]
Hello im using version 1.12.2 of tile38 and trying to run this code

```python
import redis

def test_tile38():
	client = redis.Redis(host="127.0.0.1", port=9851)
	result = client.execute_command('SET fleet truck POINT 33.32 115.423')
	print result
	print client.execute_command('EVAL \'return tile38.call(\"GET\", \"fleet\", \"truck\", \"POINT\")\' 0')

if __name__ == '__main__':
	test_tile38()
```
**Here is output from console:**

run python connect.py
OK
Traceback (most recent call last):
  File "connect.py", line 13, in <module>
    test_tile38()
  File "connect.py", line 10, in test_tile38
    print client.execute_command('EVAL \'return tile38.call(\"GET\", \"fleet\", \"truck\", \"POINT\")\' 0')
  File "/home/osboxes/.local/lib/python2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/osboxes/.local/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/osboxes/.local/lib/python2.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: invalid argument 'tile38.call("GET",'

**I tryed on linux and windows. I always get error like  invalid argument 'tile38.call("GET",'**

I get this error even when i try to type it directly into tile38-cli
127.0.0.1:9851> EVAL 'return tile38.call("GET", "fleet", "truck1", "POINT")' 0
(error) invalid argument 'tile38.call("GET",'

**Comment by tidwall** [comment]
Hi @PascalSavage 

Try to put the Tile38 args into separate params:

```
import redis
def test_tile38():
    client = redis.Redis(host='127.0.0.1', port=9851)
    result = client.execute_command('SET', 'fleet', 'truck', 'POINT', '33.32', '115.423')
    print result
    print client.execute_command('EVAL', 'return tile38.call(\"GET\", \"fleet\", \"truck\", \"POINT\")', '0')

if __name__ == '__main__':
    test_tile38()
```

**Comment by PascalSavage** [comment]
Thank you @tidwall it works. 

Im fine with this solution but if anyone knows how can i get it to work in tile38-cli too can still comment though. It has to do something with escaping special characters like space or quotes. 

Problem with cli:
**127.0.0.1:9851> EVAL 'return tile38.call("GET", "fleet", "truck1", "POINT")' 0
(error) invalid argument 'tile38.call("GET",'**
