### ISSUE TITLE
detect when key modified?

### ISSUE THREAD

**Issue by predmond** [tidwall/tile38#324]
Is it possible to detect when objects in a key are modified?

I am (continually) inserting points into a key with an expiry of 1 hour. I would like to be able to get the BOUNDS of the key every time it changes.

Currently I just run through all the keys but this is slow. Is there a better way?

Maybe the lua scripting can be used for this? I can't find any docs on the scripting..

**Comment by tidwall** [comment]
Perhaps this can be done with geofencing. You could use a `INTERSECTS FENCE` that encompasses the entire world and receive notifications for all objects.

```
INTERSECTS key FENCE BOUNDS -90 -180 180 90
```

This will fire an event for any changes to the key, including when a key is deleted/expired. Then you would need to call the `BOUNDS key` after each event.

**Comment by s32x** [comment]
@predmond We'll be closing this issue since it's been a few months since we've heard from you. Hopefully, the above comment has solved your issue. If not, please feel free to re-open!
