### ISSUE TITLE
Possible KNN Search bug

### ISSUE THREAD

**Issue by pmaseberg** [tidwall/tile38#326]
I was running a NEARBY command like

NEARBY lightning LIMIT 4 OBJECTS POINT 34.3 -91.1

Which uses the KNN Search as I understand. Everything seemed to be working fine. The dataset I am using is lightning bolt data and I set a TTL for it, so it is changing over time. I am came in the next day and ran the same query and things got wired.

At times I got a count of 0 but still have one object returned. At other times I got count of 0 and no objects at all. If I moved the lat, lon around it would work correctly, but around that one spot I keep see this odd behavior. 

If I put a radius in the query it worked fine. I finally just restarted tile38 and it started working correctly again.

I know this is not the most helpfully report as I cannot recreated it, but I want to at least report it in cause someone else has seen it.

**Comment by tidwall** [comment]
Thanks for reporting. I'll investigate on my side. If this issue happens again and/or you have any ideas around reproducing please let me know.

**Comment by pmaseberg** [comment]
So this bug happened again. Below is an example of a number of cases that show what I am seeing. I still don't know how to recreate the issue, but a restart of tile38 fixed it again.

`
127.0.0.1:9851> NEARBY lightning LIMIT 1 OBJECTS POINT 34.7794 -97.9123
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"61.196µs"}
127.0.0.1:9851> NEARBY lightning LIMIT 2 OBJECTS POINT 34.7794 -97.9123
{"ok":true,"objects":[{"id":"4c0255ee-6fc9-47ca-9ad0-a9f049134559","object":{"type":"Point","coordinates":[-97.8933,34.7711,1528397295]}}],"count":1,"cursor":0,"elapsed":"106.064µs"}
127.0.0.1:9851> NEARBY lightning LIMIT 3 OBJECTS POINT 34.7794 -97.9123
{"ok":true,"objects":[{"id":"4c0255ee-6fc9-47ca-9ad0-a9f049134559","object":{"type":"Point","coordinates":[-97.8933,34.7711,1528397295]}}],"count":1,"cursor":0,"elapsed":"97.849µs"}
127.0.0.1:9851> NEARBY lightning LIMIT 4 OBJECTS POINT 34.7794 -97.9123
{"ok":true,"objects":[{"id":"4c0255ee-6fc9-47ca-9ad0-a9f049134559","object":{"type":"Point","coordinates":[-97.8933,34.7711,1528397295]}},{"id":"562cef61-1f39-4ef3-ac19-3a933d80ccf3","object":{"type":"Point","coordinates":[-97.9376,34.7676,1528397178]}}],"count":2,"cursor":0,"elapsed":"83.688µs"}
127.0.0.1:9851
127.0.0.1:9851> NEARBY lightning LIMIT 1 OBJECTS POINT 3.7794 -9
{"ok":true,"objects":[{"id":"2ed6b164-a81f-4b9a-815d-614ab39d071e","object":{"type":"Point","coordinates":[-8.7342,4.4586,1528405419]}}],"count":1,"cursor":1,"elapsed":"70.686µs"}
NEARBY lightning OBJECTS POINT 34.7794 -97.9123 2000
{"ok":true,"objects":[{"id":"4c0255ee-6fc9-47ca-9ad0-a9f049134559","object":{"type":"Point","coordinates":[-97.8933,34.7711,1528397295]}}],"count":1,"cursor":0,"elapsed":"57.95µs"}
`

**Comment by tidwall** [comment]
You mentioned that you have a TTLs on the points and I'm wondering if something might be haywire with kNN operations on TTL objects. 

Does your data/appendonly.aof file contain the SET+EX operations? And if so would you mind sharing that file with me? 

Perhaps I can reproduce the behavior on my side.

**Comment by pmaseberg** [comment]
Here is a test case to show the issue

SET k i2 EX 20 POINT 1 1
SET k i1 EX 1000 POINT 2 1
NEARBY k LIMIT 1 POINT 0 0

Keep running the NEARBY. After 20s it returns 0 items (2nd to last line) . After a bit it starts to work correctly again.

Note: I have the EX set to three hours with my real data and it does not seem to fix itself as fast as this example does.

`
127.0.0.1:9851> SET k i2 EX 20 POINT 1 1
{"ok":true,"elapsed":"16.446µs"}
127.0.0.1:9851> SET k i1 EX 1000 POINT 2 1
{"ok":true,"elapsed":"16.461µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"83.821µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"296.329µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"41.835µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"36.013µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"37.758µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"35.392µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i2","object":{"type":"Point","coordinates":[1,1]}}],"count":1,"cursor":1,"elapsed":"63.174µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"22.899µs"}
127.0.0.1:9851> NEARBY k LIMIT 1 POINT 0 0
{"ok":true,"objects":[{"id":"i1","object":{"type":"Point","coordinates":[1,2]}}],"count":1,"cursor":1,"elapsed":"33.454µs"}
`

**Comment by tidwall** [comment]
Your example helped me find the bug. Thanks!
