### ISSUE TITLE
intersection accuracy issue

### ISSUE THREAD

**Issue by contra** [tidwall/tile38#328]
```
tile38-cli 'set boundaries earth object {"type":"MultiPolygon","coordinates":[[[[-179.9999,-89.9999],[-179.9999,90],[180,90],[180,-89.9999],[-179.9999,-89.9999]]]]}'
tile38-cli 'intersects boundaries ids object {"type":"Point","coordinates":[30.60718818389558,-96.3446728545963]}'
```

Returns 0 results. All data in this region works fine, except for this specific spot fails to match the earth polygon. Very strange.

**Comment by tidwall** [comment]
The behavior looks correct because the Y coordinate "-96.3446728545963" is outside of the earth's boundary (-90/+90).

**Comment by contra** [comment]
@tidwall Ah I missed that - not sure how google maps does it but they seem to show the right location for those coordinates. I'll have to add something that pins coordinates to earth (`Math.max(coord, 90)`)

**Comment by tidwall** [comment]
It does makes sense to pin the location... something I should consider.

**Comment by contra** [comment]
@tidwall I guess that asks a more fundamental question - is tile38 just for earth, or any coordinate system? I could see it being useful to configure the coordinate system, with default being WGS84 (earth, meters) and have tile38 enforce it (this would have been an error). Maybe somebody at NASA wants to use it for mars in the future - wouldn't rule it out.

**Comment by tidwall** [comment]
It's designed for earth, but it could (mostly) work for other coordinate systems too.

I think the exception is the NEARBY command, which uses the haversine operation, and expects earth's radius of `6371e3` meters. Mars is about half that (`3389e3`). So the user would need to adjust the distance prior to calling NEARBY .

```sh
NEARBY mars_fleet 33 -115 1000
```
This would need to be sent over as:

```sh
NEARBY mars_fleet 33 -115 1880    # 1000*6371e3/3389e3 
```

Having a configuration option to change the radius of the sphere could solve this problem.

**Comment by contra** [comment]
How about something like this to change the coordinate reference system?

```sh
CONFIG SET crs urn:ogc:def:crs:OGC:1.3:CRS84 # earth, meters (default)
CONFIG SET crs urn:ogc:def:cs:EPSG::6402 # mars
```

This would control the radius as well as error on invalid data outside the system min/max (and other things in the future).

GeoJSON already fleshed most of this out as a part of their spec, so I stuck with using URNs in the example as that seems standard: http://geojson.org/geojson-spec.html#coordinate-reference-system-objects

Which I guess is another unanswered question: If I add geojson with some CRS specified, should tile38 convert it to the CRS it is configured for? Right now AFAIK tile38 ignores that field and will act like everything is WGS84 (earth, meters, degrees).

**Comment by tidwall** [comment]
> If I add geojson with some CRS specified, should tile38 convert it to the CRS it is configured for?

The spec you reference is old. GeoJSON has officially removed the "crs" member.

https://tools.ietf.org/html/rfc7946#appendix-B.1

Moving forward GeoJSON only supports `urn:ogc:def:crs:OGC::CRS84`

https://tools.ietf.org/html/rfc7946#section-4

I want to try to keep as close to the spec as possible. But that being said, there's no reason we can't have a system-wide CRS modifier. It can default to WGS84, but use a different formula when `CONFIG SET crs` is specified.
