### ISSUE TITLE
Hope add a values fencing

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#33]
If Tile38 have a mechanism that can set a range of monitoring would be the best. For example,  the client sent the "fset" command to set the values of  a field can also bind a hook, specifically, if a truck‘s speed reaches a certain value,tile38 will  trigger a values fencing event.

**Comment by tidwall** [comment]
This is possible by using the `WHERE` clause for your fence. 

```
NEARBY trucks FENCE WHERE speed 25 +inf POINT 33.54 -115.67 1000
```

This will only trigger an event when the `speed` field of an object is 25+

For more information check out http://tile38.com/commands/intersects/#search-options

**Comment by icewukong** [comment]
Awesome! it's good idea. 
Thanks!
