### ISSUE TITLE
Implement UnmarshalJSON for pkg/geojson Object

### ISSUE THREAD

**Issue by sixstone-qq** [tidwall/tile38#330]
Hello there,

We are starting to use Tile38 and BuntDB projects and we love them. So firstly, I'd like to thank you for your work here. It's really appreciated.

I find a little strange to have `marshalJSON` function to match `enconding/json` interface in `github.com/tidwall/tile38/pkg/geojson.Object` but not the other way around `unmarshalJSON`. This will help a lot when embedding GeoJSON objects in other structs and loading data from a JSON file.

So take this example:
```go
import "github.com/tidwall/tile38/pkg/geojson"

type MyPrettyStruct struct {
    ID  string `json:"id"`
    ...
    FeatureCollection *geojson.FeatureCollection
}

var s MyPrettyStruct
err := json.Unmarshal(jsonBlob, &s)
```
As of today, we are doing so by extending the object using `ObjectJSON`:
```go
func (s *MyPrettyStruct) UnmarshalJSON(b []byte) (err error) {
	obj, err := geojson.ObjectJSON(string(b))
	if err != nil {
		return err
	}
        s.FeatureCollection = &(obj.(geojson.FeatureCollection))
        return nil
}
```
This would be a great addition to this library.

**Comment by tidwall** [comment]
Hi, This seems reasonable. I originally never intended the GeoJSON package to be used outside of the Tile38 server binary, but it seems low hanging enough. 

Thanks for the suggestion.

**Comment by sixstone-qq** [comment]
@tidwall yeah. I used to use other GeoJSON library but your suggestion for one question in BuntDB want me to use it along with BuntDB :).

Again, congratulations for these great projects!

**Comment by tidwall** [comment]
Thanks! 

I'll probably need to move the GeoJSON package into it's own library at some point, just to keep the API sane.

**Comment by tidwall** [comment]
We recently moved the GeoJSON package into it's own project.

https://github.com/tidwall/geojson

I moved this issue to https://github.com/tidwall/geojson/issues/6
