### ISSUE TITLE
 Regression bug : kafka messages publication

### ISSUE THREAD

**Issue by Nicoreb** [tidwall/tile38#333]
Hello,

I’m using the tile38’s webhook functionality to publish geofenced search to Kafka.
I detected a regression bug due to an update of sarama library : 
[sarama issue](https://github.com/Shopify/sarama/issues/816)

I have the following  message when tile38 is trying to send message to Kafka :
2018/06/28 13:45:06 [DEBU] Endpoint connect/send error: … : kafka: invalid configuration (Producer.Return.Successes must be true to be used in a SyncProducer)

All informations to fix this bug are detailed in the [sarama issue](https://github.com/Shopify/sarama/issues/816).
Thank you in advance for your response.

**Comment by tidwall** [comment]
Hi @Nicoreb, 

Thanks for letting us know. 

I'm not sure what steps we should take to solve this issue and I'm trying to parse the problem. Is this something that needs to be changed in Tile38 or do we need to pull a different version of the Sarama package?

**Comment by Nicoreb** [comment]
Hi @tidwall,

I just done a pull request. I tested it and it work for me. It was just a SyncProducer configuration problem due to a sarama backwards incompatible change.

**Comment by tidwall** [comment]
Thanks for the PR. I'm a little behind right now, but I'll review and merge asap.

**Comment by AnkushKhanna** [comment]
Hello, @Nicoreb thank you for the fix. @tidwall : when can we accept this merge? We are running in the same problem.

**Comment by tidwall** [comment]
Hi Ankush, I plan on having this merged by end of week.

**Comment by tidwall** [comment]
Sorry for the delay on this PR and thanks for your patience.
