### ISSUE TITLE
Accessing Tile38-cli via Docker install? 

### ISSUE THREAD

**Issue by EdwardDeaver** [tidwall/tile38#338]
Hello I'm not too familiar with Docker and I need to access the Tile38-cli to test some things. 

To start the server: docker run -p 9851:9851 tile38/tile38

But how do I access tile38-cli?

**Comment by tobilg** [comment]
Try docker run -it tile38/tile38 tile38-cli

**Comment by EdwardDeaver** [comment]
Hi Tobilg,

I have 2 ssh windows open. One is running the tile38 server via docker and the other the cli.

When I run `docker run -it tile38/tile38 tile38-cli`

I get `Could not connect to Tile38 at 127.0.0.1:9851: Connection refused`

**Comment by tobilg** [comment]
Probably it’s easier to just attach to the running Server Container. Otherwise you‘ll have to use host networking on the CLI Container and specify the host ip address to connect to

**Comment by OuYangResume** [comment]
> 要将tile38-cli的docker实例连接到同一台计算机上tile38-sever的docker实例，请执行以下操作：
> 
> ```
> docker run -p 9851:9851 tile38/tile38
> ```
> 
> ```
> docker run --net=host -it tile38/tile38 tile38-cli
> ```
> 
> 将`-net=host`本地主机公开给docker环境。

记得是打开两个ssh

**Comment by SvenDowideit** [comment]
For reference, using `--net=host` means your tile38 is accessible by anyone on your network (cafe wifi, yay), so the longer and more secure route, is to make a private network for tile38, and to use it

its a 3 step process, but can be worth knowing:
```
$ docker network create tile38
872c3a5db19d1b1f3156ac9f206c37b185a1a1e637e29758ccf1a86363e1c856
docker run --net=tile38 -it --rm --name tile38 tile38/tile38 

   _______ _______
  |       |       |
  |____   |   _   |   Tile38 1.19.5 (0490734) 64 bit (amd64/linux)
  |       |       |   Port: 9851, PID: 1
  |____   |   _   | 
  |       |       |   tile38.com
  |_______|_______| 

2020/02/20 03:46:18 [INFO] Server started, Tile38 version 1.19.5, git 0490734
2020/02/20 03:46:18 [INFO] AOF loaded 0 commands: 0.00s, 0/s, 0 bytes/s
2020/02/20 03:46:18 [INFO] Ready to accept connections at [::]:9851

```
and then to access it (starting a new container that only runs the client):
```
$ docker run --net=tile38 -it tile38/tile38 tile38-cli -h tile38
tile38:9851> 
```
OR (re-using the server container)
```
$ docker exec -it tile38 tile38-cli
127.0.0.1:9851> 
```
```
