### ISSUE TITLE
FATAL unexpected EOF

### ISSUE THREAD

**Issue by gmonk** [tidwall/tile38#339]
I have been getting a lot of these error with 1.12.3   I have to delete the AOF and reload my webhooks.  What would cause this ?

**Comment by tidwall** [comment]
I'd like to reproduce the error. Would it be possible to get the output in the terminal and copy of your AOF file?

**Comment by gmonk** [comment]
[tille38_error.zip](https://github.com/tidwall/tile38/files/2225994/tille38_error.zip)

**Comment by gmonk** [comment]
I think this maybe more due to a corrupt SD card I noticed some other weird things going on.  I started with  a fresh SD and will let you know if it happens again
