### ISSUE TITLE
How to query the envelope of all elements of a key

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#34]
Hi, tidwall:
In order to quickly locate the data within a key, I need to know the minimum bounding rectangle of all the objects in this key. What shall I do?
R tree indexs should store this information, but I did not find such an interface.

**Comment by tidwall** [comment]
Great suggestion. There is currently no way to do this. But you are right that it should be possible. Tile38 uses a hybrid R-tree / Quadtree. It would just need to scan the top level elements for the bounds.

I'll need to investigate a bit, and I'll keep you posted.

**Comment by tidwall** [comment]
I just added the `BOUNDS` command which returns the minimum bounding rectangle for all objects in a key.

```
BOUNDS trucks
```

Please let me know if this works for you. Thanks.

**Comment by icewukong** [comment]
I have tested it. This command is available. Thank you!

**Comment by tidwall** [comment]
You're welcome and I'm glad it to be of help. 👍
