### ISSUE TITLE
Enablement of MQTT certificates (e.g. for usage with AWS IoT Core Broker)

### ISSUE THREAD

**Issue by tobilg** [tidwall/tile38#340]
Currently, the MQTT endpoints can be configured with the [following parameters](https://github.com/tidwall/tile38/blob/master/pkg/endpoint/endpoint.go#L78):

* Host
* Port
* QueueName
* Qos
* Retained

What is missing is that one can specify certificates as well, which are necessary for the usage with AWS IoT Core Broker for example:

* cacert (The filename of the CA certificate to verify the peer)
* cert (The client certificate filename)
* key (The private key filename)

There are some sample implementations, e.g. 

* https://github.com/eclipse/paho.mqtt.golang/issues/72#issuecomment-295019307

**Comment by tidwall** [comment]
Some examples: 
https://github.com/eclipse/paho.mqtt.golang/issues/72#issuecomment-295019307

**Comment by tidwall** [comment]
Please verify that this works for you.

The new options are `cacert`, `cert`, `key`
