### ISSUE TITLE
Running tile38-server detached

### ISSUE THREAD

**Issue by EdwardDeaver** [tidwall/tile38#345]
Is it possible to run tile38 detached (no console output, only in the background)? I'm currently it on a server and I need it to run in the background. 

I've tried:
`./tile38-server &`
`Python: subprocess.Popen(["./tile38-server"], stdin=None, stdout=None, stderr=None, close_fds=True, shell=False)
 `

**Comment by EdwardDeaver** [comment]
Found out how to do it. 

How to:

`nohup ./tile38-server &`

**Comment by tidwall** [comment]
Also, in caseyou need zero stdout/stderr output to the `nohup.out` file:

```bash
nohup ./tile38-server -q &
```

**Comment by EdwardDeaver** [comment]
Thank you tidwall!
