### ISSUE TITLE
GeoJSON example fails

### ISSUE THREAD

**Issue by aaronpk** [tidwall/tile38#346]
attempting to use the sample GeoJSON from https://tile38.com/topics/object-types/#geojson fails:

```
127.0.0.1:9851> SET city tempe OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
Invalid argument(s)
```

It's not clear to me what exactly the problem is. I was actually trying to set a FENCE with a GeoJSON object but it was failing, then I discovered that even basic operations with GeoJSON objects were failing as well.

**Comment by tidwall** [comment]
Hi Aaron,

I'm not seeing the problem on my side.

```
~ $ tile38-cli
127.0.0.1:9851> SET city tempe OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
{"ok":true,"elapsed":"20.391µs"}
```
I'm running tile38-cli and tile38-server v1.12.3 on my MacBook. What version and platform are you running and I'll try to reproduce the issue.  Thanks.

**Comment by aaronpk** [comment]
I'm on OSX 10.12.6 running tile38 v1.12.3. But this was my mistake! Looks like this error is coming from redis-cli rather than the tile38 server. I was assuming the protocol was compatible enough that I could connect to tile38 from redis-cli. It worked for most of what I was testing, but not this.

What I'm actually trying to do is use the PHP Redis client to set these geofences, but that is failing as well. I'm wondering if the PHP Redis client is failing the same way as well. I just get back a "false" when running `rawCommand` from the client. Is there a trick to getting Redis clients to work with these kinds of values?

**Comment by aaronpk** [comment]
Ah thanks! That works in redis-cli now.

I'm currently using the PHP Redis extension. 

I just tried with Predis, and that gave me a more helpful error:

```
ERR invalid argument 'OBJECT'
```

**Comment by aaronpk** [comment]
Sorry, I should clarify what I'm actually doing now. Here's the command I'm trying to run:

```
SETHOOK test http://example.com/ NEARBY group FENCE OBJECT {...}
```

**Comment by tidwall** [comment]
Are you using the `[rawCommand](https://github.com/phpredis/phpredis#rawcommand)` like:

```php
$redis->rawCommand('SET', 'city', 'tempe, 'OBJECT', '{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}')
```
Their README says:

> A method to execute any arbitrary command against the a Redis server

**Comment by aaronpk** [comment]
yep, `rawCommand` in Redis and `executeRaw` in Predis.

I get the `ERR invalid argument 'OBJECT'` error from tile38-cli as well. Am I not understanding the SETHOOK method? I thought that it accepted any type of geometry not just POINTS like the [examples](https://tile38.com/commands/sethook/).

**Comment by aaronpk** [comment]
ahhh that makes sense! That would be a helpful example to include on https://tile38.com/topics/geofencing/ Thanks!

**Comment by tidwall** [comment]
Good input. Thanks :)
