### ISSUE TITLE
JSET cannot be used to append points to linestrings

### ISSUE THREAD

**Issue by brncsk** [tidwall/tile38#348]
Consider the following use case where I'm trying to append coordinate pairs to a linestring:

```
SET traces test OBJECT {"type": "Feature", "geometry": {"type": "LineString", "coordinates": [[0, 0], [1, 1]]}}
> {"ok":true,"elapsed":"80.864µs"}
JSET traces test geometry.coordinates.0.-1 [2,2]
> (error) Position has an invalid value
```

Which boils down to `JSET` interpreting `[2,2]` as a string:

```
JSET traces test properties.testprop.-1 [2,2]
JGET traces test properties.testprop
> {"ok":true,"value":"[\"[2,2]\"]","elapsed":"57.387µs"}
```

Would it be possible to expose SJSON's `SetRaw` somehow to overcome this limitation?

**Comment by brncsk** [comment]
Ah, okay, digging a bit revealed this undocumented gem in json.go:

https://github.com/tidwall/tile38/blob/07be59e3004d0d8ab25071687ecc4cefd723d5ce/pkg/controller/json.go#L138-L143

which basically allows me to do the following:

```
JSET traces test geometry.coordinates.-1 [2,2] raw
```

Thanks :).

**Comment by tobilg** [comment]
Nice find! If you like, you can create a docs PR...

**Comment by brncsk** [comment]
On second thought: how do I file a docs PR? I just realized `[RAW]` is there in the official docs, see: https://tile38.com/commands/jset/ but there is no related example below.

There is another undocumented flag called `str` as well, that's neither listed as such nor is there an example.

**Comment by tobilg** [comment]
The repo of the documentation can be found at 
https://github.com/tile38/tile38.github.io

**Comment by brncsk** [comment]
https://github.com/tidwall/tile38/pull/349
https://github.com/tile38/tile38.github.io/pull/19
