### ISSUE TITLE
Suggest a clear description of the tile38's default spatial data mathematical reference's parameters

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#35]
I suggest a clear description of the tile38's default spatial data mathematical reference's parameters, so that the client will convert other ellipsoidal reference data to the default data reference system,and submit data. otherwise, it is prone to error when the lenth of arc is converted to meters.
Although this error is not great. :)

**Comment by tidwall** [comment]
Thanks for the suggestion.

WGS84 is the only reference coordinate system that Tile38 uses, and all distances are in meters. I wanted to keep the API as simple as possible and felt that this would provide for the broadest range of applications.

Do you recommend that I state this more clearly on README and Tile38.com website? Is there anything specific that you think should be noted?

**Comment by icewukong** [comment]
I mean you can emphasize the distances refers to two points on a spherical surface distance, not plane distance.
If the two projection coordinates of the distance need to be converted to WGS84 under the arc distance.
Because I made such a mistake and I don't want other people to make the same mistake!    :)

**Comment by tidwall** [comment]
Ahh I understand now. Good point and I agree. This is something I'll work on doing. Thanks.
