### ISSUE TITLE
Growing of queue.db

### ISSUE THREAD

**Issue by temporaryaccount** [tidwall/tile38#351]
We are planning to have lots of firing hooks and it seems that queue.db is only growing which can become a problem for us.

What exactly is the function of queue.db and why is it necessary? Can it be disabled (like the AOF) without affecting the hooks?

Thanks.

**Comment by tidwall** [comment]
The queue.db is used to store the geofence notifications that are ready for delivery. When a notification fails to be received by an endpoint, the queue is used to try again soon after. This allows for network hiccups without losing events. 

The queue.db will automatically shrink in the background from time to time. It shouldn't grow too big unless you have a lot of failing endpoints. And even then the events will expire after a minute or so of no delivery.

Unfortunately it can't be disabled without risking loss of event data.

**BUT** I did just push an update 7efa55f that allows for specifying a custom path for the queue.db file, or it can be used keep the database in memory.

So you could do:

```
$ tile38-server --queuefilename :memory:
```

to get the behavior that you want.

**Comment by temporaryaccount** [comment]
If it automatically shrinks and the shrinking really works then I think that will do, thank you. Perhaps a configuration option to define when exactly to shrink it (the interval, or the size threshold) could help a bit, as an enhancement idea.

Thanks again. Should I close the issue?

**Comment by s32x** [comment]
@temporaryaccount I got it! If you need any more help please feel free to re-open this issue.
