### ISSUE TITLE
Subscribe and Psubscribe

### ISSUE THREAD

**Issue by gmonk** [tidwall/tile38#355]
Trying to review the documentation for the above commands  and I'm getting 404 not found

**Comment by temporaryaccount** [comment]
Also pdelchan, setchan, chans, delchan

**Comment by tidwall** [comment]
I just pushed the updates to the tile38.com website. Please try again.

**Comment by s32x** [comment]
All should be good now! All of the pages in question are 200ing now. Sorry for the trouble! If there seems to be an issue again please feel free to re-open!
