### ISSUE TITLE
[FATA] unexpected EOF

### ISSUE THREAD

**Issue by hmarcelodn** [tidwall/tile38#363]
Our pod is failing in Kubernetes due to the error below. We have an AOF file of ~270MB.

```
   _______ _______
  |       |       |
  |____   |   _   |   Tile38 1.12.2 (d5af91c) 64 bit (amd64/linux)
  |       |       |   Port: 9851, PID: 1
  |____   |   _   |
  |       |       |   tile38.com, patreon.com/tidwall
  |_______|_______|

2018/09/25 14:02:57 [INFO] Server started, Tile38 version 1.12.2, git d5af91c
2018/09/25 14:03:11 [INFO] AOF loaded 1299952 commands: 14.15s, 91845/s, 33 MB/s
2018/09/25 14:03:11 [FATA] unexpected EOF
```

Is there something related to the file size? I had renamed the AOF file and it worked. I believe it has problems trying to restore itself when restarted.

**Comment by tidwall** [comment]
An "unexpected EOF" error indicates that the AOF file is incomplete. 

> Is there something related to the file size?

File size shouldn't matter. It's not unusual to have AOF that are many GBs. 

> I had renamed the AOF file and it worked. I believe it has problems trying to restore itself when restarted.

Did everything work before you renamed the file?

**Comment by tidwall** [comment]
As long as the `appendonly.aof` file is in the data directory, the data will reload when Tile38 restarts.

**Comment by hmarcelodn** [comment]
Yes we needed that working back inmmediately so we renamed the file to avoid this. I reviewed the appendonly.aof file and it seems correct, it does not seem to be trunked at all. 

```
OBJECT
$50
{"coordinates":[-95.43665,42.7114],"type":"Point"}
*5
$3
SET
$5
intel
$14
vHOunha0rJ7OVR
$6
OBJECT
$51
{"coordinates":[-73.96506,40.63469],"type":"Point"}
*5
$3
SET
$5
intel
$14
WoA1Mit7cpGVvn
$6
OBJECT
$51
{"coordinates":[-90.20197,38.65481],"type":"Point"}
*5
$3
SET
$5
intel
$14
DuzcPj5Kko5CgA
$6
OBJECT
$51
{"coordinates":[-84.25197,39.77665],"type":"Point"}
```

**Comment by tidwall** [comment]
I'm assuming that there's an `\r\n` at the end of the file, but otherwise it looks good to me. If you want to zip of the file and share it with me, I can try to load it on my side.

**Comment by hmarcelodn** [comment]
@tidwall it really seems to be corrupt https://s3.amazonaws.com/tile38-appendfiles/backappendonly how can this be possible ?

**Comment by tidwall** [comment]
There are a bunch of zero bytes at the end of the file you provided.


![image](https://user-images.githubusercontent.com/1156077/46035752-aa641000-c0b8-11e8-9175-f3bc6b5d53dd.png)


I'm not sure how it happened. I've never seen anything like that before.

**Comment by hmarcelodn** [comment]
Yes that was really weird. Now I have a new AOF file. I will clean this thing up later and merge with the current one then try to restore this.

**Comment by hmarcelodn** [comment]
Fixed by removing these stuff and adding \n\r. Closing the issue so far.
