### ISSUE TITLE
"linestring intersect" problems

### ISSUE THREAD

**Issue by CAIJUNYI** [tidwall/tile38#365]
In `/pkg/geojson/poly/intersects.go`
```
// IntersectsLineString detect if a point intersects a linestring
func (p Point) IntersectsLineString(exterior Polygon) bool {
	for j := 0; j < len(exterior); j++ {
		if raycast(p, exterior[j], exterior[(j+1)%len(exterior)]).on {
			return true
		}
	}
	return false
}
``` 
`exterior` is assumed as a linestring whose head and tail are not connected. If `j` refers to the last point of the linestring, `(j+1)%len(exterior)` will refer to the head of the linestring. In this case, the point might intersects the tail-head line which does not actually exist, and the code might lead to wrong results.

**Comment by tidwall** [comment]
Nice catch! I have this and #364 corrected in an internal branch that I'll be pushing in the coming days. 

It includes an overhaul of the geometry library which also addresses #291, #359, #360, #361, #362, #364, #365
