### ISSUE TITLE
Add a GUI?

### ISSUE THREAD

**Issue by FGRibreau** [tidwall/tile38#37]
Hello !

Would you be interested that we ([Redsmin](https://redsmin.com)) promote tile38 as a compatible server for our online real-time administration and monitoring service?

As for as I can see Tile38 already handles *scan* command, if only it could implement the `type` and `info` command, you would get a GUI and monitoring/alerting for free :)

**Comment by tidwall** [comment]
Hi, 

I can add those commands. Which sections/fields from `INFO` does Redsmin require?

**Comment by FGRibreau** [comment]
The best way is to connect it to Redsmin but from the top of my mind:

- info needs a `redis_version` and the info commands must be able to respond to `info all` and `info commandstats` and `info cluster` (even if its empty)
- some of monitored info keys are:

```
uptime_in_seconds
connected_clients
client_longest_output_list
client_biggest_input_buf
blocked_clients
used_memory
used_memory_rss
used_memory_peak
used_memory_lua
mem_fragmentation_ratio
rdb_changes_since_last_save
rdb_last_save_time
rdb_last_bgsave_time_sec
rdb_current_bgsave_time_sec
aof_rewrite_in_progress
aof_rewrite_scheduled
aof_last_rewrite_time_sec
aof_current_rewrite_time_sec
total_connections_received
total_commands_processed
instantaneous_ops_per_sec
rejected_connections
sync_partial_full
sync_partial_ok
sync_partial_err
repl_backlog_size
repl_backlog_histlen
expired_keys
evicted_keys
keyspace_hits
keyspace_misses
pubsub_channels
pubsub_patterns
latest_fork_usec
aof_delayed_fsync
connected_slaves
master_last_io_seconds_ago
master_link_down_since_seconds
used_cpu_sys
used_cpu_user
cluster_slots_assigned
cluster_slots_ok
cluster_slots_pfail
cluster_slots_fail
cluster_known_nodes
cluster_size
cluster_current_epoch
cluster_my_epoch
cluster_stats_messages_sent
cluster_stats_messages_received
```

but you don't need to implement each of them, however if you implement one just use the same unit type as Redis itself :)

**Comment by tidwall** [comment]
Sounds good. I'll see what I can do. Thanks!

**Comment by FGRibreau** [comment]
Hello @tidwall,

I just saw that you closed this issue, is the "info" command working?

**Comment by tidwall** [comment]
I recently added the INFO command and is should be working. I also made a minor change moments ago to address an issue with the command.
