### ISSUE TITLE
how to store extra data in Hooks - grpc

### ISSUE THREAD

**Issue by pratikidea** [tidwall/tile38#372]
I want to store some small data with hooks command. how to do that?

**Comment by tidwall** [comment]
The [`SETHOOK`](https://tile38.com/commands/sethook/) command allows for optional `META` fields. 

For example:

```
SETHOOK hook1 http://my.endpoint.com/ META field1 value INTERSECTS ...
```

Now `field1` will be stored with the hook.

**Comment by tidwall** [comment]
I hope this information helped. Please feel free to reopen if needed.
