### ISSUE TITLE
EXPIRE triggering del for all hooks regardless of point interaction

### ISSUE THREAD

**Issue by lt** [tidwall/tile38#374]
I currently have approximately 12000 hooks set to detect enter and exit only and report to an AMQP endpoint

Setting a key with a point that is outside of all fences, and then expiring the key generates ~12000 messages. I wasn't expecting to receive messages for fences that the point had not entered (If the point had entered a fence, I'd understand the del in place of an exit)

Is this working as intended?

```
cli 1:
NEARBY people FENCE DETECT enter,exit POINT 50 0 5000

cli 2:
SET people alice POINT 0 0
EXPIRE people alice 1
```

**Comment by tidwall** [comment]
Yes, it's working as intended. By default all geofences send off notifications when an object is updated or deleted. 

It's possible to ignore those notifications by explicitly setting the `COMMANDS` options to `set`.

```
NEARBY people FENCE COMMANDS set DETECT enter,exit POINT 50 0 5000
```

That being said, I can absolutely see the case for not sending `del` notifications for objects that have not previously interacted with the geofence. It makes sense to me.

**Comment by tidwall** [comment]
I hope this information helped. Please feel free to reopen if needed.
