### ISSUE TITLE
Detect inside on polygon object webhook

### ISSUE THREAD

**Issue by EdwardDeaver** [tidwall/tile38#375]
Hello,

I have this polygon webhook fence 

` SETHOOK QueueTest amqp://guest:guest@localhost:5672/warehouse WITHIN fleet object  {"type":"Polygon","coordinates":[[[-75,40],[-73,40],[-73,30],[-75,30],[-75,40]]]}`

How should I specify 'DETECT inside' for this hook? The command produces an error if I add it after 'object'.

**Comment by tidwall** [comment]
Hi Edward, The `DETECT inside` should be placed prior to the `OBJECT` param.

**Comment by s32x** [comment]
Hey @EdwardDeaver, Looks like the last comment helped you get your hooks working so I'm going to go ahead and close this issue. If not feel free to re-open!
