### ISSUE TITLE
Facing an issue with the within command 

### ISSUE THREAD

**Issue by epsilon-akshay** [tidwall/tile38#380]
INTERSECTS area circle 1.2379 101.2823 100 is returning the area required 
but WITHIN area circle 1.2379 101.2823 100 is not returning any area, although the circle lies inside the area.

**Comment by tidwall** [comment]
Hi Akshay, are you still running into problems with this issue? 

Your INTERSECTS and WITHIN queries will both return objects from the specified `area` collection when those respective objects intersect or are fully within the circle.

Are there objects in the `area` that should be returned that are not?

**Comment by tidwall** [comment]
I'm closing this issue for now. But feel free to reopen if needed. Thanks.
