### ISSUE TITLE
WebHooks in tile38 Docker container

### ISSUE THREAD

**Issue by EdwardDeaver** [tidwall/tile38#383]
So I've decided to start using the tile38 docker instance but I'm having an issue having my amqp(rabbtmq) hooks registering with the localhost instance of Rabbitmq. 
The tile38 instance is not communicating to my rabbitmq instance on the localhost. 

I'm starting the docker image using docker-py: 

`container = client.containers.run('tile38/tile38',detach=True, ports={'9851/tcp': 9851})` 

The hook is setup like this: 

`tile38ClientOBJ.execute_command('SETHOOK', "TryTestingDocker",amqp://guest:guest@localhost:5672/warehouse, 'WITHIN', 'fleet', 'DETECT', 'inside', 'object', jsonDropOfPolygon)`

This works when tile38 is running on the localhost.

I suspect the issue is Docker is stopping the container from accessing the host system, but I don't know enough about Docker networking to debug this.

**Comment by tobilg** [comment]
I guess you‘ll have to run the Container with the —networking host flag

**Comment by stevelacy** [comment]
@EdwardDeaver What is your OS? The networking is drastically different if you are on macos

**Comment by EdwardDeaver** [comment]
@stevelacy  Amazon Linux

**Comment by EdwardDeaver** [comment]
Update:

So I did docker command:
`docker run --network="host" tile38/tile38
`
Then I used the tile38cli: 
`docker run --net=host -it tile38/tile38 tile38-cli
`
To run: 
`SETHOOK QUEUETEST amqp://guest:guest@localhost:5672/warehouse NEARBY fleet FENCE POINT 900 900 50
`
` SET fleet truck1 POINT 900 900`

Then I checked the rabbitmq queues:
` sudo rabbitmqctl list_queues
`
Warehouse queue showed up. So I think there are a few things wrong with my code but the networking host was a big part of fixing it. 

Thank you @stevelacy and @tobilg

**Comment by stevelacy** [comment]
Sounds good.

@tidwall Want me to add a docker and or kubernetes example for the docs?

**Comment by LeonardoBonacci** [comment]
A somewhat (docker) related question. I run tile38 as part as of a docker-compose setup. 
To create a kafka webhook I now manually open a tile38-cli (docker run --net=host -it tile38/tile38 tile38-cli) to execute the SETHOOK command.

All works well, but does anyone have suggestions on how to somehow automatically execute a SETHOOK on start-up? 

If preferred, I can make this a separate github question/issue.

Last but not least: I've started working on a kafka-tile38 sink connector. It's still in its initial phase dealing mostly with my specific use-case. Soon I'll make it more generic and more robust. If anyone has the ambition to create an official connector it's free to use or fork. 

https://github.com/LeonardoBonacci/kafka-connect-tile38-sink

**Comment by stevelacy** [comment]
@LeonardoBonacci use the `depends_on` config option for docker-compose and run the sethook command in a container that exits when complete with code 0.

https://docs.docker.com/compose/compose-file/#depends_on

**Comment by LeonardoBonacci** [comment]
Hi @stevelacy thanks for your quick response. 
I'm about to give it a try and wondered whether with container you mean a tile38-cli container?

**Comment by stevelacy** [comment]
yes
