### ISSUE TITLE
Request: Add server version to SERVER command

### ISSUE THREAD

**Issue by stevelacy** [tidwall/tile38#384]
Right now we are sending `/server` requests to our kubernetes tile38 cluster to determine AOF size. We would also like to confirm that the tile38 version update release went through by sending the `SERVER` request from our monitoring daemon without checking the logs directly.

Request: Add `"version": "<server version>"` to the output of `SERVER`

I can add this feature

**Comment by tidwall** [comment]
Make sense to me. I would be happy to accept a PR.
