### ISSUE TITLE
LDFLAGS for setting version during build changed on golang 1.11

### ISSUE THREAD

**Issue by stevelacy** [tidwall/tile38#386]
When running `make` on golang `1.11.2` the version always ends up as `0.0.0`.
I checked the LDFLAGS and the flag that worked was: 
`export LDFLAGS="-X github.com/tidwall/tile38/core.Version=1.14.1"` 
instead of: 
`export LDFLAGS="-X github.com/tidwall/tile38/pkg/core.Version=1.14.1"`

This is potentially a breaking change as I have not tested it on go pre 1.11

**Comment by tidwall** [comment]
That was a big oversight. Thanks for reporting. I just pushed a fix and full release.
