### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by charlieuk2k** [tidwall/tile38#388]
This looks really interesting.

I'm assuming I can feed this with X/Y 'hit's' and it will be able to tell me how many hits I had in the geofence area.

The X/Y's, could I use grok formatted and then pipe to tile38?

**Comment by starboy** [comment]
Position updates can be made via the Redis Protocol using x/y coordinates or geojson. As long as your message to Tile38 matches that in the documentation then yes, you should be able to pipe them to Tile38. I'm unfamiliar with Grok so I can't answer for certain but I would suggest you go over the documentation here - https://tile38.com/commands/set/

**Comment by charlieuk2k** [comment]
Thanks
