### ISSUE TITLE
Restoring 'WITHIN' when tile38 starts returns fatal error

### ISSUE THREAD

**Issue by jiuweigui** [tidwall/tile38#389]
Hi.

I have a weird problem with the latest tile38. I can create a location entry and tie it to a geofence and when i write a location the fence is triggered as expected. However if I stop and start tile38 (when using storing data persistently) I get an error regarding 'WITHIN': [FATA] invalid argument 'WITHIN'.

As the fence has been added correctly and it has been functioning, I would assume restoring it from disk would also work. However for some reason it doesn't. I've reproduced this on images tagged 1.14.0 and 1.14.3.

As a minor thing I also noticed that at least the latest tile38 docker images all have version 0.0.0 and git 0000000.

**Comment by jiuweigui** [comment]
Hmm on second thought maybe this is some sort of issue with my build/provisioning scripts. Apologies.

**Comment by tidwall** [comment]
As a side note there was an issue with loading AOF files in 1.14.0 that was fixed in 1.14.1 that sounds similar.

If you happen to run into this issue again please let me know. 

Thanks
