### ISSUE TITLE
Have you deployed this to heroku or AWS?

### ISSUE THREAD

**Issue by steve21124** [tidwall/tile38#4]
if you do, do you have https://devcenter.heroku.com/articles/deploying-go or procfile?

**Comment by tidwall** [comment]
I have not deployed on heroku, but I have tested on AWS. And I have deployed on Digital Ocean. I don't currently have a procfile. Sorry :(

**Comment by steve21124** [comment]
thanks. how about docker? do you have one for digital ocean?

**Comment by tidwall** [comment]
I installed Tile38 directly on the server. I'm quite familiar with Docker and it shouldn't bee too difficult to assemble a Dockerfile. Though I have not tested it.

**Comment by mozinator** [comment]
I use this for deploying tile38

Dockerfile
```
FROM phusion/baseimage:0.9.18

CMD ["/sbin/my_init"]
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8
RUN groupadd -r tile38 && useradd -m -g tile38 tile38
RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q git build-essential
RUN curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.6.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
RUN mkdir -p /gopath /goroot
ENV GOPATH=/gopath
ENV PATH=$PATH:$GOPATH/bin
RUN git clone https://github.com/tidwall/tile38.git /tile38
RUN cd /tile38 && make && make install

RUN mkdir /etc/service/tile38
ADD tile38.sh /etc/service/tile38/run
RUN chmod +x /etc/service/tile38/run

VOLUME ["/data"]

EXPOSE 9851
```

tile38.sh
```
#!/bin/bash
set -e

chown -R tile38 /data

exec sudo -u tile38 /usr/local/bin/tile38-server -d /data -h 0.0.0.0 -p 9851
```

**Comment by tidwall** [comment]
@mozinator thanks for sharing your Dockerfile.

**Comment by mpseay** [comment]
Hey guys, I noticed mention of docker. Hope you don't mind if I append to this thread. I'm currently trying to get tile38 up and running in a docker container:

Dockerfile 
`FROM golang

RUN git clone https://github.com/tidwall/tile38.git /go/src/github.com/tile38
RUN cd /go/src/github.com/tile38 && make

VOLUME ["/data"]

ENTRYPOINT /go/src/github.com/tile38/tile38-server

EXPOSE 9851`

I've got a truncated docker-compose file:
`    freeza:
        image: company/freeza
        ports:
            - "4001:8081"
        depends_on:
            - tile38
        links:
            - tile38
        env_file:
            - ./dockerlocal.env
    tile38:
        image: company/tile38
        ports:
            - "9851:9851"`

When I try to run these, for some reason I'm unable to connect. This compose file is much larger than this with connected services. I wasn't sure if you ran into this if you have tried tile38 with docker?

`[michaelseay trunks] (dev)$ docker-compose up --build
Starting trunks_tile_1
Recreating trunks_freeza_1
Attaching to trunks_tile_1, trunks_freeza_1
tile_1    |
tile_1    |    _______ _______
tile_1    |   |       |       |
freeza_1  | 2016/05/03 04:21:25 unable to fill pool: dial tcp [::1]:9851: getsockopt: connection refused
tile_1    |   |____   |   _   |   Tile38 1.1.4 (b5b4f92) 64 bit (amd64/linux)
tile_1    |   |       |       |   Port: 9851, PID: 5
tile_1    |   |____   |   _   |
tile_1    |   |       |       |   tile38.com
tile_1    |   |_______|_______|
tile_1    |
tile_1    | 2016/05/03 04:21:25 [INFO] Server started, Tile38 version 1.1.4, git b5b4f92
tile_1    | 2016/05/03 04:21:25 [INFO] AOF loaded 0 commands: 0.00s, 0/s, 0 bytes/s
tile_1    | 2016/05/03 04:21:25 [INFO] The server is now ready to accept connections on port 9851
trunks_freeza_1 exited with code 1`

**Comment by tidwall** [comment]
Hi @mpseay, 

We don't currently have an official docker image but we do plan on publishing one together in the near future.

Tile38 does run in a docker container. I haven't seen the error that you mention, but I'm not too familiar with docker-composer. This is a Dockerfile that I'm currently using. It's based on the lastest tar.gz release as opposed to the git repo. 

```
FROM debian:wheezy

RUN apt-get update \
    && apt-get install -y curl \
    && curl -L https://github.com/tidwall/tile38/releases/download/1.1.4/tile38-1.1.4-linux-amd64.tar.gz -o tile38-1.1.4-linux-amd64.tar.gz \
    && tar xzvf tile38-1.1.4-linux-amd64.tar.gz \
    && rm tile38-1.1.4-linux-amd64.tar.gz \
    && apt-get remove -y curl && apt-get autoremove -y

VOLUME ["/data"]
ENTRYPOINT /tile38-1.1.4-linux-amd64/tile38-server
EXPOSE 9851
```

I wish I could help more.

**Comment by mpseay** [comment]
Awesome, I'll be on the look out. In the meantime I'll see if I can figure this out and I'll update the thread if I can get it functioning! Thanks!

**Comment by mpseay** [comment]
Quick Update: Turns out the issue was my own :( My connection details in my service container was trying to access localhost rather than the docker host. Problem solved!

**Comment by tidwall** [comment]
@mpseay Glad to hear you found a solution. I hope Tile38+Docker works out well for your project.

**Comment by mozinator** [comment]
I just want to share that I have been using tile38 for a couple of months in production now. It works great!

**Comment by tidwall** [comment]
@mozinator That great to hear! If it's not asking too much, could you share your use case? I would love to hear how Tile38 is helping you or your organization.

**Comment by mozinator** [comment]
@tidwall I developed an app meant for people who dont have nautical charts or safety equipment on their boats. The app has an nautical chart in it, and you can see other ships on it in real-time.
That last part is made possible due to tile38 👍

**Comment by tidwall** [comment]
@mozinator  Very cool! Sounds like a super useful app. 
Thanks for sharing!

**Comment by gordysc** [comment]
If you want a super slim version of this, here's a Dockerfile for Alpine (3.4):
```
FROM alpine:3.4

ENV TILE38_VERSION 1.5.0
ENV TILE38_DOWNLOAD_URL https://github.com/tidwall/tile38/releases/download/$TILE38_VERSION/tile38-$TILE38_VERSION-linux-amd64.tar.gz

RUN apk update \
    && apk add ca-certificates \
    && update-ca-certificates \
    && apk add openssl \
    && wget -O tile38.tar.gz "$TILE38_DOWNLOAD_URL" \
    && tar -xzvf tile38.tar.gz \
    && rm -f tile38.tar.gz \
    && mv tile38-$TILE38_VERSION-linux-amd64/tile38-server /usr/local/bin \
    && rm -fR tile38-$TILE38_VERSION-linux-amd64

EXPOSE 9851
CMD ["tile38-server"]
```

Image size is about 19.57 MB

**Comment by tidwall** [comment]
@gordysc This looks good. I think could work as the template for the official image.

**Comment by gordysc** [comment]
@tidwall The only addition we'd probably want to make is the mount point for data that's persisted to disk, so that can be done on an SSD outside the Docker container.  I haven't taken a look yet, but is there a flag to dictate where to persist data on disk? We'd probably want to have that be mounted to the volume: /data

**Comment by tidwall** [comment]
@gordysc Yes. There a `-d` flag that allows for specifying a data directory.

**Comment by gordysc** [comment]
@tidwall Beautiful! So just a few things to get this left to make this happen:

1. Creating an official Dockerhub repo
2. Adding automatic builds (https://docs.docker.com/docker-hub/builds/)
3. Adding logic to support the `-d` flag.

**Comment by tidwall** [comment]
@gordysc OK. I'll take care of this and keep you posted. Thanks.

**Comment by tidwall** [comment]
@gordysc I have the automatic builds enabled and create an automated build at https://hub.docker.com/r/tile38/tile38 which points to this project. I included master/latest and tags.

**Comment by gordysc** [comment]
@tidwall will follow up with another PR this evening to update documentation/formatting for Dockerhub

**Comment by tidwall** [comment]
@gordysc Is it possible to have custom dockerhub formatting? It looks like they pull in the Github README which has a mix of HTML and markdown.

**Comment by gordysc** [comment]
@tidwall No, but you can have a README specifically for Dockerhub.  You just have to isolate it w/ the Dockerfile in a separate directory.  The PR above should allow you to adjust the formatting and content you put on Dockerhub independently of your Github's main README

**Comment by davidmurdoch** [comment]
@steve21124 were you ever able to deploy to Heroku?

**Comment by imraxy** [comment]
can someone share how to host on Heroku? Please

**Comment by s32x** [comment]
Due to the fact that Heroku uses an [Ephemeral Filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem), persisting any database data on a Heroku Dyno (outside of using an add-on) is detrimental. With this system, Heroku Dynos are periodically rebooted and will lose both their Tile38 memory AND AOF file that would have been written to disk.

Currently, and for the foreseeable future, there is no way to persist an AOF anywhere other than disk making Heroku the wrong place to host Tile38. The above Dockerfile may help run it temporarily but you will not be able to retain your data for long. Perhaps there will be a Tile38 Heroku add-on in the future which would be the ideal use case on heroku, however until then we recommend running the database elsewhere.

**Comment by s32x** [comment]
If there's interest in a Heroku Add-on thumbs up this comment!

**Comment by tidwall** [comment]
I'm closing this issue for now. As @s32x mentioned above, due to the ephemeral nature of there's no open way to get Tile38 integrated with Heroku. At least not without some type of business support and/or creating a SaaS. 

If someone has other ideas, feel free to reopen and add to this issue.

Thanks.

**Comment by helenamerk** [comment]
Has anyone tried running tile38 on ecs? Any best practices? 

Spun it up through ecs with the docker image, but running in to an issue. Using the node driver, which uses the redis RESP protocol.

To connect my other ecs services to my tile38 service, I set up an ALB, only to realize after hours of debugging later, that load balancers do not support the RESP protocol 😞. The only way to connect to my instances was to find the ip of specific instances, which change with new deployments. 

While testing, also been running into this issue that shuts down the tile38 service:
<img width="1485" alt="tile38 index out of range" src="https://user-images.githubusercontent.com/7145275/82981398-d546eb80-9fa0-11ea-81e4-6dbb4eb2a20c.png">

It looks to be similar to the index out of range error reported here -- am I doing something wrong? Tile38 tends to disconnect, and eventually throw the error.  (https://github.com/tidwall/tile38/issues/247)
