### ISSUE TITLE
Using redis-rb, how do you interface with Tile38?

### ISSUE THREAD

**Issue by jegodwin** [tidwall/tile38#40]
Sorry if this is a dumb question...just a little lost on how to interact w/ the tile38-server via redis-rb. I've got as far as starting the the tile38-server and then connecting to the server & port using redis-rb, but then I'm lost. What syntax should I use to do something like setting a point?

Redis-rb docs say this for setting a key: `redis.set("mykey", "hello world")`
So I tried: `redis.set("fleet", "truck", "point", "33.5123 -112.2693")` (didn't worK)
..and, stuff like `redis.set("fleet", "truck", point: "33.5123 -112.2693")`.

**Comment by tidwall** [comment]
Not a dumb question. 

You should be able to call any Tile38 command using `redis.call()`. Forgive me, my ruby is not very good., but something like this should work:

```ruby
redis.call(["set", "truck", "point", "33.5123", "-112.2693"])
# or possibly
redis.call([:set, "truck", "point", "33.5123", "-112.2693"])
```

Let me know if this works for you.

**Comment by jegodwin** [comment]
Hmmm. I tried that and although I'm not getting an error, it doesn't seem to be setting anything; I'm not getting a response back from the server. 😕

**Comment by tidwall** [comment]
The code isn't overly clear to me, but here's the function signature to the `call` function.  https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L84-L96


Not sure if makes a difference, but I actually had an error in my syntax. I forgot the `fleet` key.
```ruby
redis.call(["set", "fleet", "truck", "point", "33.5123", "-112.2693"])
```


Is the server saving the `set` command? You can check with telnet.

```
$ telnet host 9851
get fleet truck
```

**Comment by jegodwin** [comment]
I get `-1` when i telnet and type `get fleet truck`.

I'll play with it some more this weekend and see where I get. Thanks for your help. This could be a great addition for our new startup.

**Comment by tidwall** [comment]
"-1" means "not found". So I guess the set calls were doing nothing. 

Let me know if there's anything I can do. Thanks for your interest in the project.

**Comment by tomquas** [comment]
i couldn't get redis/redis-rb to work together with tile38 either. what _worked_ for me was amakawa/redic:
``` ruby
require 'redic'
r = Redic.new 'redis://127.0.0.1:9851'
r.call 'set', 'fleet', 'truck', 'point', '23.4', '11.2'
r.call 'keys', '*'
r.call 'get', 'fleet', 'truck'
```

**Comment by tidwall** [comment]
@tomquas Thanks for the suggestion. I added redic to the README.
