### ISSUE TITLE
received a live command that was not QUIT

### ISSUE THREAD

**Issue by belek** [tidwall/tile38#405]
Hi, at first thanks for this great service!
Currently I have a problem with checking Geofence feature.  When I set new locations I got an error:
`[ERRO] received a live command that was not QUIT`
Please could you explain what is am I doing wrong?

Initing client:  
```go
tile38Client := redis.NewClient(&redis.Options{
	Addr: *tile38URL,
})
ping, err = tile38Client.Ping().Result()
if err != nil {
	log.Fatalf("failed to ping tile38: %v", err)
}
log.Printf("Connected to tile38: PING %s", ping)
```

Now I want to setup geofencing:  
```go
fenceCMD := redis.NewStringCmd("NEARBY", "fleet", "FENCE", "POINT", 33.462, -112.268, 6000)
tile38Client.Process(fenceCMD)
fenceResult, err := fenceCMD.Result()
if err != nil {
	log.Fatalf("failed to set geofencing: %v", err)
}
log.Println(fenceResult)
```

And check it by setting new locations:  
```go
setLocationCMD := redis.NewStringCmd("SET", "fleet", "bus", "POINT", 33.460, -112.260)
tile38Client.Process(setLocationCMD)
setLocationResult, err := setLocationCMD.Result()
if err != nil {
	log.Fatalf("failed to set locations: %v", err)
}
log.Println(setLocationResult)
```

The application log:  
```
{"level":"info","msg":"Connected to tile38: PING PONG","time":"2019-01-30T19:52:38+06:00"}
{"level":"info","msg":"OK","time":"2019-01-30T19:52:38+06:00"}
{"level":"fatal","msg":"failed to set locations: EOF","time":"2019-01-30T19:52:38+06:00"}
exit status 1
```

Tile38 log:
```
╰─$ docker run --rm --name tile38 -p 9851:9851 tile38                                                                                                                            2 ↵

   _______ _______
  |       |       |
  |____   |   _   |   Tile38 1.15.0 (f638904) 64 bit (amd64/linux)
  |       |       |   Port: 9851, PID: 1
  |____   |   _   |
  |       |       |   tile38.com
  |_______|_______|

2019/01/30 13:52:35 [INFO] Server started, Tile38 version 1.15.0, git f638904
2019/01/30 13:52:35 [INFO] AOF loaded 0 commands: 0.00s, 0/s, 0 bytes/s
2019/01/30 13:52:35 [INFO] Ready to accept connections at [::]:9851
2019/01/30 13:52:38 [INFO] live 172.17.0.1:49166
2019/01/30 13:52:38 [ERRO] received a live command that was not QUIT
2019/01/30 13:52:38 [INFO] not live 172.17.0.1:49166
```

**Comment by belek** [comment]
@tidwall, hey, sorry, could you have a look on this issue and help to figure out what is wrong? Thanks!

**Comment by s32x** [comment]
When you setup the geofence and run `NEARBY fleet FENCE POINT 33.462 112.268 6000` you're effectively converting that connection to a live stream which only recieves updates on the fence. This is how you're supposed to recieve geofence updates. Once the stream is set, the only command that should be sent back from the client is to close the connection (IE: QUIT command that you're seeing in the error). To send further commands to tile38 (such as point updates) you should use a completely seperate connection. 

Currently, since we have implemented pubsub and geofence channels the recommended approach would be to instead create a geofence channel, subscribe to it in a seperate goroutine and perform point updates on a seperate thread. Below is an example of this:

```go
package main

import "github.com/go-redis/redis"

func main() {
	// Create your redis client
	rc := redis.NewClient(&redis.Options{Addr: ":9851"})
	defer rc.Close()

	// Create the channel that will enable us to subscribe for geofence
	// notifications
	rc.Do("SETCHAN", "warehouse", "NEARBY", "fleet", "FENCE", "POINT", 33.462,
		-112.268, 6000)

	// Subscribe on the above created channel
	println("SUBSCRIBING TO GEOFENCE MESSAGES")
	pubsub := rc.PSubscribe("warehouse")
	defer pubsub.Close()

	// Concurrently subscribe and listen for geofence messages
	go func() {
		// Loop over all messages that come over the connection
		println("LISTENING FOR GEOFENCE MESSAGES")
		for {
			msg, _ := pubsub.ReceiveMessage()
			println(msg.Payload)
		}
	}()

	// Set the bus point that will trigger a geofence message
	println("SETTING BUS POINT")
	rc.Do("SET", "fleet", "bus", "POINT", 33.460, -112.260).String()

	// Delete the pubsub channel
	rc.Do("DELCHAN", "warehouse")
}
```
Output:
```
SUBSCRIBING TO GEOFENCE MESSAGES
SETTING BUS POINT
LISTENING FOR GEOFENCE MESSAGES
{"command":"set","group":"5c51f2c0f5ec4e4f349fd036","detect":"inside","hook":"warehouse","key":"fleet","time":"2019-01-30T11:53:52.75706-07:00","id":"bus","object":{"type":"Point","coordinates":[-112.26,33.46]}}
```

Hopefully this helps! We'll be sure to update the geofence documentation on the website to further elaborate on this. Let me know if you need anymore help!

**Comment by tidwall** [comment]
@s32x Thanks for the thorough answer.

@belek 

Thanks for your patience. When possible, I recommend using the pub/sub style of geofencing.

Please let us know if you have any further questions.

Also, make sure to join our a [slack channel](https://join.slack.com/t/tile38/shared_invite/enQtMzQ0OTEwMDUxMzc5LTc0NTJjZmM3YjFhOGZiZGU2NDNjOWEwM2Q5ZWE3MzFiYWZkZDIyN2U2ZmUzZDBmODU0MjI1ZjQ0N2Y1M2I1NTg). You can often get questions answered much quicker.

**Comment by tidwall** [comment]
This issue looks resolved, but feel free to reopen if needed. Thanks.
