### ISSUE TITLE
To evaluate how much memory tile38 will use

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#41]
Before loading the AOF file in tile38, is there a relatively conservative and simple method to evaluate how much memory tile38 will use ?

In addition, in order to reduce memory fragmentation, do you have any suggestion on the design of GeoJSON ?

**Comment by tidwall** [comment]
> Before loading the AOF file in tile38, is there a relatively conservative and simple method to evaluate how much memory tile38 will use ?

Every object comprises of at least:
- Object Header: 16-bytes
- R-Tree Pointer: 16-bytes

Then there's the actual data such as:
- Point Object (Lat/Lon): 16-bytes
- LineString: (Point*N)
- Polygon: (LineString*N)
- Etc..

So the smallest object is a Point which will take at least 48 bytes to store. 

> In addition, in order to reduce memory fragmentation, do you have any suggestion on the design of GeoJSON ?

Tile38 stores GeoJSON in a binary format, and any variation of the same fields are stored identically. For example:

```json
{
  "type": "Point",
  "coordinates": [10,10]
}
```

and 

```json
{"coordinates": [10,10],"type":"Point"}
```

are the same as far as Tile38 is concerned.  Both formats use the same amount of data.

I hope this information helps, and let me know if you have any additional questions.

**Comment by tidwall** [comment]
I would also like to add that you can always check the memory usage with the `SYSTEM` command.

**Comment by tidwall** [comment]
One more thing. If you are on a low-memory system, you can compile for 32-bits and save some memory. 

From the command line:

```bash
$ GOARCH=386 make
```

The pointer sizes will be 32bits and this will save about 8 bytes per object.

**Comment by icewukong** [comment]
I get it，thank you :)
