### ISSUE TITLE
MQTT topic in webhook url is wrong "tile38/device/test" becomes "tile38"

### ISSUE THREAD

**Issue by pstuifzand** [tidwall/tile38#410]
Hi,

I was trying out MQTT webhooks and found that the topic from the url is split in the slashes. When I use this url `mqtt://mosquitto:1883/tile38/township/0931?qos=1`, the topic becomes tile38, while it should be `tile38/township/0931`.

-- Peter

**Comment by tidwall** [comment]
I agree and we'll get it changed right away. 
Thanks for reporting this issue.
