### ISSUE TITLE
SERVER command in script

### ISSUE THREAD

**Issue by 1995parham** [tidwall/tile38#411]
Is there any way for calling `SERVER` command in the Lua script? I am using the following command in Lua script:
```lua
tile38.call('SERVER')
```
and get the following error:
```
ERR unknown command 'SERVER'
```

**Comment by rshura** [comment]
Looks like an oversight, should be an easy change to make it work.

**Comment by 1995parham** [comment]
Yes, you are right. I think I correct it and create a pull request for it.
