### ISSUE TITLE
use ’where in‘ command，tile38 return ‘(error) invalid argument BOUNDS’

### ISSUE THREAD

**Issue by pujian1984** [tidwall/tile38#414]
`WITHIN AisRealtime  WHERE utc 1550807030895 +inf WHEREIN mmsi 1234567 123 BOUNDS 30.583100441498317 111.23073577880861 30.68014451934492 111.46522521972656`
tile38 return：
`(error) invalid argument 'BOUNDS'`
how to use wherein command？thank you

**Comment by rshura** [comment]
First thing after `WHEREIN` should be a number of values to follow. You should instead  `1` between `mmsi` and 1234567

**Comment by srimaln91** [comment]
I have experienced the same issue time ago. It would be better if we can mention this explicitly in the documentation.
