### ISSUE TITLE
Does tile38 use CPU's single core?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#42]
Does tile38 use CPU's single core? The source code does not seem to set the use of multi-core, if set to multi-core, whether it can enhance the performance of it?

**Comment by tidwall** [comment]
Yes. All cores should be used by default. You can use the GOMAXPROCS environment variable to control this.

**Comment by icewukong** [comment]
I ask so many questions, thank you for your patience！

**Comment by tidwall** [comment]
No worries. I appreciate the feedback. :)
