### ISSUE TITLE
Neraby with match

### ISSUE THREAD

**Issue by nithinkota** [tidwall/tile38#421]
NEARBY fleet match man* distance POINT  13.0257553 77.6672509 130000

When i run the above query  i am getting all the records which are less than that distance by neglecting the match query.  

{"ok":true,"objects":[
{"id":"banaswadi","object":{"type":"Point","coordinates":[
77.6557162,13.0193145]},"distance":1440.2965125250248},
{"id":"manyata","object":{"type":"Point","coordinates":[77.618843,13.052758]},"distance":6042.691334891891}
,{"id":"silkboard","object":{"type":"Point","coordinates":[77.65618,12.88597]},"distance":15589.645317174029},
{"id":"mandya","object":{"type":"Point","coordinates":[76.90493,12.52926]},"distance":99406.68801523448}],
"count":4,"cursor":0,"
elapsed":"0s"}

I need to get records which are matched with  'man*' within that distance only.
Please look into this once.Thank you

**Comment by tidwall** [comment]
Thanks for reporting this issue. I just released a hotfix.
