### ISSUE TITLE
Make creation of SQS queue optional

### ISSUE THREAD

**Issue by tobilg** [tidwall/tile38#427]
If I read the [code](https://github.com/tidwall/tile38/blob/master/internal/endpoint/sqs.go#L92) correctly, currently it's always attempted to create a SQS Queue.

I'd suggest to either make this optional (via an additional parameter), or skip this completely. Reason: When running in AWS, the policies would need to be defined upfront.

**Comment by tidwall** [comment]
I added this to PR #430

**Comment by tidwall** [comment]
@tobilg This one is fixed, but I wanted to double check with you before closing.

**Comment by tobilg** [comment]
Yes, thanks again!
