### ISSUE TITLE
Webhook Client.Timeout

### ISSUE THREAD

**Issue by tesujiro** [tidwall/tile38#428]
I am using tile38 server for my private project, Webhook timeout sometimes.
> 2019/03/09 07:49:47 [DEBU] Endpoint connect/send error: 1: http://127.0.0.1:8080/hook: Post http://127.0.0.1:8080/hook: net/http: request canceled (Client.Timeout exceeded while awaiting headers)  

I wrote a simple program to reproduce it.
[webhook timeout](https://gist.github.com/tesujiro/d782f68ae36f2cd7676f7d97a36c1353)
In my environment ( Tile38 1.16.1 + redigo / MacBook Pro Mojave 10.14.3 ) this program reproduce the failure 100%, and took goroutine stack traces.
[Tile38-server stack trace](https://gist.github.com/tesujiro/7c107ea7c3d54d00ae08b9f13c5c19b1)

There is a lock chain between goroutines ,but I have no idea to fix it.

- (h *Hook) manager() locks h.cond.L on tile38/internal/server/hooks.go: 569
- (server *Server) handleInputCommand() locks server.mu on tile38/internal/server/server.go: 945, and in (h *Hook) Signal() waits for h.cond.L released on tile38/internal/server/hooks.go: 560
- (server *Server) handleInputCommand() wait for server.mu released on tile38/internal/server/server.go: 968

**Comment by tidwall** [comment]
Thanks for providing the code to reproduce and also the stack trace! I'll give it a whirl and see what I can do. Stay tuned!

**Comment by tidwall** [comment]
I'm seeing the issue from my side. I'm still investigating a solution.

**Comment by tidwall** [comment]
Though I do see that the messages end up getting delivered.

**Comment by tesujiro** [comment]
Thanks for your support.
I tried to write a sequence diagram.
<img width="764" alt="SequenceDiagram" src="https://user-images.githubusercontent.com/7157116/54463815-a5566280-47b7-11e9-81ab-1ac9734bfd93.png">
There is a deadlock. The root cause maybe that the hook manager locks h.cond.L while sending webhook request.

**Comment by tidwall** [comment]
I see. It appears that Tile38 is blocking while waiting for an OK from your http handler. I'll see about making a change that avoids that block.

**Comment by tidwall** [comment]
I just pushed a fix. Your research helped. Thanks!

**Comment by tesujiro** [comment]
Thank you!
Webhook performance will also be better.

**Comment by tidwall** [comment]
Oh yes! This is a very good update.
