### ISSUE TITLE
Nearby Returning results outside the range Point -> Linestring

### ISSUE THREAD

**Issue by owaaa** [tidwall/tile38#43]
First of all, this is a really cool project. I like that is very fast. I was doing some testing and computed distances for each of my matches returned by tile38 (point to linestring). I'm doing a nearby search with 1km and still getting some items over 74km away. Looking at the code it looked like was doing an intersection so I would of thought that it would work or is this bounding box based?

tested Tile38 1.1.4
Geojson in error -> http://bl.ocks.org/d/6d5b8a53c7a055d880f41dacf1d46297

```
curl --data "nearby Infrastructure/Pipelines point 33.5 36.3833 1000" 192.168.99.100:9851
{"ok":true,"objects":[{"id":"1FuHkvZ5KENLF-nV3SUxgR8FVSRJIXFcUUidKRyaM_1251_LineString","object":{"type":"LineString","coordinates":[[35.380068,33.569721],[35.841426,32.365757],[42.115382,33.606739]]}}],"count":1,"cursor":0,"elapsed":"100.212µs"}
```

**Comment by tidwall** [comment]
Hi Andrew, 

I just pushed an update that fixes this problem.

It appears that the linestring was being treated like a polygon causing the first and last points of the linestring to be closed off. Then the center point of the radius was being reported as inside of the polygon. 

Let me know if this helps or if you have any questions.

Thanks for reporting this issue!
