### ISSUE TITLE
Is it possible to restrict geofences to a specific entity?

### ISSUE THREAD

**Issue by stcktrce** [tidwall/tile38#434]
Let's say i have a entity named `alpha` that was added using `SET fleet alpha POINT x y`

would it be possible to restrict a geofence to only trigger when `alpha` enters the geofence? We currently handle this within our application, but it'd be great if we could offload this into tile as well.

**Comment by tidwall** [comment]
Yes. The `MATCH` keyword provided a pattern for filtering objects by their IDs.


In your case:

```
NEARBY fleet FENCE DETECT enter,inside,exit MATCH alpha POINT 52.7563395 -0.8838196 200
```

will match exactly on `alpha`. But, you can also do something like `MATCH truck:*` which will match on everything that has the `truck:` prefix.
