### ISSUE TITLE
UNSUBSCRIBE channel

### ISSUE THREAD

**Issue by githubfr** [tidwall/tile38#448]
I can use the SUBSCRIBE channel command. But how can i unsubscribe?
Thank you very much.

**Comment by tidwall** [comment]
I just pushed a fix. The UNSUBSCRIBE command was missing.

So now, if you call something like `SUBSCRIBE fleet` or `PSUBSCRIBE fleet:*`, you'll call `UNSUBSCRIBE fleet` or PUNSUBSCRIBE fleet:*` respectively.

Also the `QUIT` command will unsubscribe from all channels and close the connection. Or, you can just close the tcp socket from the client side and the channels will gracefully close automatically.
