### ISSUE TITLE
Nearby result showing field data incorrectly

### ISSUE THREAD

**Issue by AnshulJain1985** [tidwall/tile38#453]
Hi

I am facing an issue with nearby when data is showing correctly but the fields values are showing in every object for last one only.

SET fleet truck1 FIELD speed 90 FIELD age 30 POINT 33.5224 -112.2793
SET fleet truck2 FIELD speed 60 FIELD age 23 POINT 33.5225 -112.2795
SET fleet truck3 FIELD speed 70 FIELD age 26 POINT 33.5226 -112.2796
SET fleet truck4 FIELD speed 80 FIELD age 27 POINT 33.5227 -112.2797

127.0.0.1:9851> NEARBY fleet where age 26 +inf POINT 33.462 -112.268 60000
{"ok":true,"fields":["speed","age"],"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2793,33.5224]},"fields":[80,27]},{"id":"truck3","object":{"type":"Point","coordinates":[-112.2796,33.5226]},"fields":[80,27]},{"id":"truck4","object":{"type":"Point","coordinates":[-112.2797,33.5227]},"fields":[80,27]}],"count":3,"cursor":0,"elapsed":"79.403µs"}

If you see above result looks correct, but speed and age fields value is showing of last object truck4 only although the values are different.
Is there something I am missing or doing incorrectly.

Please help.

**Comment by melbania** [comment]
Hi @AnshulJain1985 and @tidwall,

I think I’ve found the source of the bug and have a fix on my local machine. I just need to write up some tests, and then I can submit a PR soon if that’s okay.

**Comment by tidwall** [comment]
Thanks @melbania! Please submit your PR when ready and I'll review.

**Comment by AnshulJain1985** [comment]
Thanks @melbania for the update.

**Comment by tidwall** [comment]
Just merged. I'll push a new version shortly.

**Comment by tidwall** [comment]
The latest release includes this fix. Thanks @AnshulJain1985 and @melbania
