### ISSUE TITLE
Tests of "OUTPUT json" are reporting elapsed time

### ISSUE THREAD

**Issue by melbania** [tidwall/tile38#456]
Related to #453: I am trying to test for correct json output when doing a search, and the command "OUTPUT json" returned '{"ok":true,"elapsed":"368ns"}', which includes elapsed time, a quantity that will vary with each test.

Is it possible to have the tests that include setting the output to json not report elapsed time?

**Comment by tidwall** [comment]
Makes sense. I'll push an update momentarily.
