### ISSUE TITLE
Nearby command 's where conditions how to express equal?

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#46]
I use the FIELD clause in the set command. 
SET name id Field routecode abc Field stationid 123456 POINT lat lon
which "routecode" value is string

NEARBY FenceXY where routecode 69030 POINT 23.135278 113.325000 100.000000 
where conditions how to express equal?

**Comment by tidwall** [comment]
`FIELD routecode abc` is not allowed because fields can only be numbers. 

The WHERE requires two values "min" and "max". 
To search for equality on a single value you can do this:
`WHERE routecode 69030 69030`

**Comment by huangpeizhi** [comment]
Using where condition and using match conditions, which performance is good？

**Comment by tidwall** [comment]
Sorry for not getting back to you sooner. Both WHERE and MATCH have a similar performance O(n).
