### ISSUE TITLE
Intersect with multiple objects

### ISSUE THREAD

**Issue by AnshulJain1985** [tidwall/tile38#469]
I want to detect multiple geofences enter exist. As per documentation Objects do support but I am not able to implement it.

I tried multiple ways to implement it but it is not working. Can you please help me here if I am doing something wrong here.

INTERSECTS test FENCE DETECT enter,exit **OBJECTS [{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]**
(error) invalid argument '[{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]'

127.0.0.1:9851> INTERSECTS test FENCE DETECT enter,exit **OBJECTS {"type":"Point","coordinates":[-149.831200065,61.1181799835]} {"type":"Point","coordinates":[-149.832280073,61.1170899589]}**
(error) invalid argument '{"type":"Point","coordinates":[-149.831200065,61.1181799835]} {"type":"Point","coordinates":[-149.832280073,61.1170899589]}'

127.0.0.1:9851> INTERSECTS test FENCE DETECT enter,exit **OBJECT {"type":"Point","coordinates":[-149.831200065,61.1181799835]} OBJECT {"type":"Point","coordinates":[-149.832280073,61.1170899589]}**
(error) invalid data

**Comment by melbania** [comment]
Hi @AnshulJain1985,

Your third try is really close. If you want to detect entries and exits for multiple geofences, Tile38 wants you to provide the geofence objects as either a FeatureCollection or a GeometryCollection using the 'OBJECT' command as follows:

```
INTERSECTS test FENCE DETECT enter,exit OBJECT {"type": "FeatureCollection","features": [{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]}
```

or

```
INTERSECTS test FENCE DETECT enter,exit OBJECT {"type": "GeometryCollection","geometries": [{"type": "Point","coordinates": [-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]}
```

I was able to successfully detect entries and exits for these geofences after setting up and subscribing to a channel using the above INTERSECTS commands, similar to how the docs explain the process at https://tile38.com/topics/geofencing/.

### OBJECT vs. OBJECTS
The 'OBJECTS' option is not for defining multiple objects, rather it is an output format option (see the "Output Formats" section at https://tile38.com/commands/intersects/ ... which is, in my opinion, in need of some good example documentation. It is the default format used by NEARBY, WITHIN, INTERSECTS, and SCAN, and so is not needed if you want objects reported in your results. You could opt for POINTS, BOUNDS, or HASHES, though, if you would rather have that information reported back to you, like so:

```
INTERSECTS test FENCE DETECT enter,exit POINTS OBJECT {"type": "FeatureCollection","features": [{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]}
```

which, upon exit/entry, would report something similar to

**"point":{"lat":61.1181799835,"lon":-149.83120006}**

as the last key:value item in the event log, or 

```
INTERSECTS test FENCE DETECT enter,exit BOUNDS OBJECT {"type": "FeatureCollection","features": [{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]}
```

which, upon exit/entry, would report something similar to

**"bounds":{"sw":{"lat":61.1181799835,"lon":-149.831200065},"ne":{"lat":61.1181799835,"lon":-149.831200065}}**


as the last key:value item in the event log, or 

```
SETCHAN testing3 INTERSECTS test FENCE DETECT enter,exit HASHES 7 OBJECT {"type": "FeatureCollection","features": [{"type":"Point","coordinates":[-149.831200065,61.1181799835]},{"type":"Point","coordinates":[-149.832280073,61.1170899589]}]}
```

which, upon exit/entry, would report something similar to

**"hash":"bdv7ww0"**

as the last key:value item in the event log.

The COUNT output format option does not work in this context, though. When I tested it, my channel did not report any entries or exits at all. I'm going to recommend that Tile38 probably ought to throw an error if it is included in a geofencing query at all, or at least it should not "turn off" event reporting!

Hope that helps!

**Comment by AnshulJain1985** [comment]
Hi @melbania 
Let me give it a try. Thanks for your quick response.

Regards
Anshul

**Comment by kevinjbradshaw** [comment]
How did it go? I believe I have a similar use case, but not 100% sure...looking to test a point against a collection of geofences, and have all it is within returned. Would this approach work? Thank you in advance.

**Comment by AnshulJain1985** [comment]
yes, it work without any issue.
