### ISSUE TITLE
How to make better use of TILE38 in this business？

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#47]
There is a scene in the business, the use of real-time GPS data of the device to simulate multiple real-time access to the fence, the message can be triggered at each access（out/in）.

GPS data generated by the terminal about tens of thousands, each terminal every 10 seconds to produce a GPS message; and the fence is relatively static definition（Hundreds of thousands of）.

How to use TILE38 to achieve such a scene more concise it?

Thanks!

**Comment by tidwall** [comment]
Hi huangpeizhi,

Sorry, but I'm not fully understanding your question.

Are you asking if Tile38 can handle a static Geofence with 100,000+ points, and 10,000+ messages every 10 seconds?

Yes. A modest Tile38 server should handle this load.

**Comment by huangpeizhi** [comment]
Business description as shown in Figure， :)

![huang](https://cloud.githubusercontent.com/assets/19602075/18342982/f5c41788-75e3-11e6-915c-87b2699cab32.jpg)

**Comment by tidwall** [comment]
100,000 fences is a lot for one server. Are you planning to use [webhooks](http://tile38.com/commands/sethook/)?

**Comment by icewukong** [comment]
Hi tidwll,huangpeizhi
use `NEARBY stations FENCE ROAM bus * 20`
In this way can solve this problem?

**Comment by huangpeizhi** [comment]
I try use the SETHOOK command to create 100000+ webhook, but point to a HTTP endpoint. :)

**Comment by huangpeizhi** [comment]
![h](https://cloud.githubusercontent.com/assets/19602075/18382071/05aafc1a-76b2-11e6-8de2-a5be33e683d3.jpg)

this kind of way can't handle this kind of scene.

**Comment by huangpeizhi** [comment]
25,000,000+/day

Can provide DEL HOOK *  method? 

The number of POST method to send  >  the number of HOOKS than the actual number of triggers
：）

**Comment by tidwall** [comment]
Sure I can add a new command that accepts a pattern. How about `PDELHOOK *`?

**Comment by huangpeizhi** [comment]
Very grateful!

Currently SETHOOKS only HTTP (S) and DISQUE two ways, and this in two ways, each HOOK are based on the establishment of a new connection.
I do not know, it is due to too many connections caused by slow processing? Or TILE38 processes each trigger mechanism FENGS cause?
Or whether there are ways to provide the use of a single TCP connection ENDPOINT.

**Comment by tidwall** [comment]
Yes. Each HOOK may have it's own connection. This may be too slow for your project.

I could create a single TCP endpoint such as HTTP/2, Websockets, gRPC, or Fasthttp. Is there a specific technology that you would prefer?

**Comment by huangpeizhi** [comment]
Thank you very much to provide this feature, I want to use gRPC way.

**Comment by tidwall** [comment]
Sounds good. Let me look into this.

**Comment by huangpeizhi** [comment]
hi, tidwall:

I simply added in the TILE38 using REDIS single connection pool HOOK, HOOK TRIGGER trigger output the ENTER and EXIT events to REDIS LIST, and CPU use is very high(Use of a 32-core CPU machines, Intel(R) Xeon(R) CPU   E7520  @ 1.87GHz)

![huang](https://cloud.githubusercontent.com/assets/19602075/18431498/ab159da4-790f-11e6-9867-f784a817fb97.jpg)

**Comment by huangpeizhi** [comment]
![cpu](https://cloud.githubusercontent.com/assets/19602075/18431898/b9803da2-7911-11e6-9f8e-9ee98563b4db.jpg)

**Comment by tidwall** [comment]
I would like to reproduce this issue.

Could you provide an example of the [SET](http://tile38.com/commands/set/) command that you are using?
And also an example of the [FENCE](http://tile38.com/topics/geofencing/) command?
About how many SET calls per second? 
And also how many FENCES do you have open at once?

Thanks

**Comment by tidwall** [comment]
I pushed a huge update (3b99a6276eaa40a1baa79093818ce198214e04c9) yesterday to the master branch . It includes GRPC support and the PDELHOOK command.  Also HTTP hooks use a one connection per endpoint and support HTTP/2.


PDELHOOK example:
```
PDELHOOK *
```
will delete all hooks, and:
```
PDELHOOK station:*
```
Will delete all hooks that begin with `station:`

GRPC example:
```
SETHOOK station:10012 grpc://host:9876 NEARBY bus FENCE POINT 33.5 -115.5 1000
```
Will create a webhook that sends messages over GRPC.  You can find the proto file at "/hservice/hservice.proto".

**Comment by huangpeizhi** [comment]
thanks very much！

The situation I tested yesterday was
1. Initialize the fence, using the command: 
   SETHOOK fenceId redis://host:port/queuename NEARBY BUSXY FENCE DETECT enter,exit POINT lat lon radius
   note: about 1000 fence, the fenceId of each fence is unique.
2. Update BUSXY Set realtime, using the command:
   SET BUSXY terminalId POINT lat lon
   note: 450/s GPS info, about 12000+ terminals, the terminalId of each terminal is unique.

redis://host:port/queuename is I simply add a single connection that can be written to REDIS LIST

Because of the test server, there are other applications in the run, I am ready to re install a new test server today, testing gRPC and FENCE inbound/outbound.

Thank you very much for your help!

**Comment by huangpeizhi** [comment]
Because of the previous test CPU too high, today I divided the BUSXY into a number of small collection of categories, and then related to the different HOOK FENCE, now CPU reduced to 30%.

**Comment by tidwall** [comment]
Thanks for sharing this. How is the GRPC performance?

**Comment by huangpeizhi** [comment]
Hi, tidwall

I recently tested in the case of Fence 100000+, how many keys in the collection and how many updates to be able to handle the test on the test machine.

1. I first chose a line of terminal GPS information, gps record 60/minute, execute command SET BUSXY 931491 POINT 23.067500 113.340556

![image](https://cloud.githubusercontent.com/assets/19602075/18612546/b60815e6-7d8f-11e6-8cf0-1cd7d7ebbb71.png)

![image](https://cloud.githubusercontent.com/assets/19602075/18612549/c0e358ea-7d8f-11e6-87bb-f1ece3a91f95.png)

2. gps record 3000/minute, execute command SET BUSXY 931491 POINT 23.067500 113.340556

![image](https://cloud.githubusercontent.com/assets/19602075/18612553/d57d61b0-7d8f-11e6-9487-de5507f745c4.png)

![image](https://cloud.githubusercontent.com/assets/19602075/18612554/ddb6fcec-7d8f-11e6-9cfd-a6f587093a6e.png)

3. gps record 500/minute

![image](https://cloud.githubusercontent.com/assets/19602075/18612561/0286cfac-7d90-11e6-9039-cb3293fc345e.png)

4 gps record 250/minute 

![image](https://cloud.githubusercontent.com/assets/19602075/18612575/6344347e-7d90-11e6-89c5-4540c5ee64c5.png)

5. gps record 196/minute 

![image](https://cloud.githubusercontent.com/assets/19602075/18612607/295caac4-7d91-11e6-82c1-43b6e7196def.png)


Only 1 cases can be handled properly, 2-5 can not be processed to complete.

**Comment by huangpeizhi** [comment]
Test machine :
2 cpu 4 core   Intel(R) Xeon(R) CPU E5520  @ 2.27GHz

**Comment by huangpeizhi** [comment]
Test Result:
Fence 100,000 - Set update 100/min
Fence 10,000 - Set update 350/min

**Comment by tidwall** [comment]
This seems too slow.  

I have some ideas on how to speed up Tile38 quite a bit, but I would like to reproduce the benchmarks above on my development computer.

Could you provide the steps to reproduce your results?

**Comment by huangpeizhi** [comment]
- prepare stable GPS data source, data real-time written to REDIS LIST.
- define a fixed number of fences, associated with fixed TILE38 KEY collection, trigger the ENTER and EXIT event.
- print out the trigger event.
- first define the 100000+ fence, at a rate of 3000 per minute GPS data source to a REDIS LIST, program a goroutine will write GPS to gochannel, another goroutine data set into the fence on the KEY, observing REDIS can in the queue data processing is completed, if not, reduce the number of fence or real-time GPS message number.

**Comment by tidwall** [comment]
Thanks. I'll see what I can do.

**Comment by tidwall** [comment]
Hi @huangpeizhi, 

Is this issue still valid?

**Comment by tidwall** [comment]
Hi @huangpeizhi, I'm closing this for now. I think that most of the concerns in this issue have been resolved. If not, please open a new issue and I'll help. Thanks!
