### ISSUE TITLE
Add tile38-benchmark to the Dockerfile

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#470]
The `tile38-benchmark` command should be included in the Dockerfile.

**Comment by skyritsis** [comment]
Is there an ETA on the addition of benchmark on the Docker image?

**Comment by snmad** [comment]
@skyritsis  the below dockerfile will build the tile38-benchmark


FROM alpine:3.8

ENV TILE38_VERSION 1.17.3
ENV TILE38_DOWNLOAD_URL https://github.com/tidwall/tile38/releases/download/$TILE38_VERSION/tile38-$TILE38_VERSION-linux-amd64.tar.gz

RUN addgroup -S tile38 && adduser -S -G tile38 tile38

RUN apk update \
    && apk add ca-certificates \
    && update-ca-certificates \
    && apk add openssl \
    && wget -O tile38.tar.gz "$TILE38_DOWNLOAD_URL" \
    && tar -xzvf tile38.tar.gz \
    && rm -f tile38.tar.gz \
    && mv tile38-$TILE38_VERSION-linux-amd64/tile38-benchmark /usr/local/bin 

ENTRYPOINT [ "tile38-benchmark" ] 
CMD ["-h", "IPADDRESS"]
