### ISSUE TITLE
Switch to golang modules

### ISSUE THREAD

**Issue by sbsends** [tidwall/tile38#473]
Pls consider switching to golang modules. It will only take a few minutes.

**Comment by tidwall** [comment]
Are you running into a compilation issue?

**Comment by lmolas** [comment]
Go modules is the standard golang way for managing dependencies now.

**Comment by stevelacy** [comment]
"if it ain't broke..."
Not sure what actually improves this project by switching, I know it's the new (over one year old) hot stuff... but deps does still work.

**Comment by lmolas** [comment]
Yes you are right but if it works it takes 5 minutes to switch. You can give it a try.

**Comment by tidwall** [comment]
I've tried a few months ago but gave up because it was super tedious. The conversion was taking up way too much of my time. 

I'm not 100% convinced that moving to Go modules is needed for a project like this as dep does a good job vendoring for source compatibility.

**Comment by tidwall** [comment]
I moved to Go modules. I don't recommend telling people that it'll only a few minutes though.
