### ISSUE TITLE
Complexity of WHERE for object fields in a collection

### ISSUE THREAD

**Issue by skyritsis** [tidwall/tile38#480]
Is there an estimate, based on the implementation of WHERE, of what the time complexity is for ranged searches on FIELDS? Do you use some separate kind of indexing for the FIELDS apart from the rtree and btree for the IDs?

**Comment by tidwall** [comment]
Linear time complexity. WHERE does not work additional indexes. It just filters over the results.

**Comment by skyritsis** [comment]
Thank you very much for the answer. Have a nice day.
