### ISSUE TITLE
Pipeline Issues (python client)

### ISSUE THREAD

**Issue by owaaa** [tidwall/tile38#49]
I haven't been able to get pipelines to work (using Python Client). In #14 it appears that this should be supported?

My code looks something like 

```python

pipe = self.r.pipeline()
        for item in items:
            id = item['id']
            geojson = item['geometry']
            pipe.execute_command("set", "key", id, "object", geojson)
pipe.execute()
```
Tile38 reports [ERRO] Protocol error: unbalanced quotes in request

Thoughts?

Redis client is redis==2.10.5

Individual execute_commands directly against the client, "non-pipelined" work great, I just want to speed up bulk loads. Thanks

**Comment by tidwall** [comment]
I would like to reproduce this issue on my side.

About how many messages are your sending at one time? And roughly how large is each geojson?

**Comment by owaaa** [comment]
I had about 1000 set commands. I tried batching to a low number (10) but having a different issue now. The call to pipe.execute() hangs on the very first attempt and never returns. I'm not sure if this is an issue with the python redis client or if something else is going on. I also tried turning off transaction for the pipeline

**Comment by tidwall** [comment]
I think I found the issue. I'm working up a fix now and I'll keep you posted.

**Comment by tidwall** [comment]
I found the issue and pushed an update to the master branch. If possible, please verify on your side. Pipelining should be working now. 

Please note that Tile38 does not support the `MULTI` command, which is how Redis handles transactions. Make sure that transactions are disabled with your client.

**Comment by owaaa** [comment]
I verified via the master branch. Thanks!
