### ISSUE TITLE
Nearby with keys regular expression

### ISSUE THREAD

**Issue by AnshulJain1985** [tidwall/tile38#492]
Hi

I need to search for nearby points under all keys.
I tried to use it using * but is not working as it works with KEYS command.

NEARBY comp:* POINTS POINT 25.1859673 55.262186 1600

Can you please let me know is there any way to do that.

**Comment by tidwall** [comment]
Hi, sorry about the delay in responding to this question. 

The NEARBY command does not accept patterns. Only one collection per command.

You'll need to send Tile38 the KEYS command first, like `KEYS comp:*` and then perform the NEARBY on each collection.

**Comment by AnshulJain1985** [comment]
Thanks Josh. I have done the same implementation for this.
