### ISSUE TITLE
JGET returns invalid JSON when JSET sends strings that look like numbers

### ISSUE THREAD

**Issue by spierepf** [tidwall/tile38#493]
```
$ telnet localhost 9851
Trying ::1...
Connected to localhost.
Escape character is '^]'.
JSET user 901 name 0236
+OK
jget user 901
$13
{"name":0236}
JSET user 901 name "0236"
+OK
jget user 901
$13
{"name":0236}
```
The trouble is that `{"name":0236}` is not strictly valid JSON and is rejected by the Jackson parser (https://github.com/FasterXML/jackson)

Is there syntax that will force JSET to treat the value as a string?

**Comment by tidwall** [comment]
Thanks for reporting this. Until this issue is fixed, as a workaround, I recommend using the RAW or STR options. The RAW option puts raw json, as is, into the field. The STR option converts the value to a valid json string, no matter what it is.

```
JSET user 901 name '"0236"' RAW
JSET user 901 name 0236 STR
``

**Comment by spierepf** [comment]
Sorry, I should have seen that in the docs. Thanks!
