### ISSUE TITLE
hooks not sending to endpoint

### ISSUE THREAD

**Issue by neterror** [tidwall/tile38#495]
Hello,
I  configure 2 hooks that publish to MQTT when geofence event occurs. Initially the event is triggered, but after setting the position of different objects the hooks stop sending to the endpoints until the server is restarted. The steps to reproduce:
- start the server with -vv

- SETHOOK group1_1570208078328 mqtt://localhost:8131/geofence/group1/qos=0/retained=0 nearby group1 FENCE POINT 43.22628 27.93916 272.0
- SETHOOK group2_1570208105580 mqtt://localhost:8131/geofence/group2/qos=0/retained=0 nearby group2 FENCE POINT 43.23135 27.98594 473.0
- set group1 car1 POINT 43.23223 27.99981  
The above works as expected. MQTT event is published
- set group2 car2 POINT 43.23135 27.98594
Works as expected. MQTT event is published

But after 3-4 repetitions of the set group commands the hooks stop working. On the terminal is observed only queued hook messages:
2019/10/04 20:29:26 [DEBU] queued hook: 265
2019/10/04 20:29:56 [DEBU] queued hook: 266
  ... 
My environment is Centos 7, master branch of tile38, go version go1.13 linux/amd64

**Comment by neterror** [comment]
The problem seems to be in the file mqtt.go line 98, after conn.conn.Publish(...) there is t.Wait(). The hook goroutines block forever at that Wait(). 
I think what happens is that:
- The MQTT protocol do not allow 2 clients with the same name. At line 86 it is fixed always to tile38
- When the first hook is activated, it establishes connection with the broker with ClientID tile38
- When the second hook is activated it establishes connection with the same ClientID 
- After some short time of publishing to both channels the broker (tried both mosquitto and emqtt) starts disconnecting the clients. I can see TCP RST from it with wireshark, reconnection attempts from paho. I also enabled paho debug logs and I can see a lot of error messages.
- At that point Wait after Publish is block.
I changed the clientId to be unique for each connection and it seems to work fine.

**Comment by tidwall** [comment]
This issue should be resolved with your recent PR #496 and the added `WaitTimeout`.

**Comment by Lokeshjilli** [comment]
Hi, 
I configure hook that publish to MQTT when geofence event occurs, event is not triggered.

Hook:

SETHOOK test_hook mqtt://localhost:1883/geofence WITHIN fleet FENCE DETECT enter,exit object '{"type": "Polygon","coordinates":[[[-122.51953125, 37.78265474565738],[-122.39044189453125,37.81032643553476],[-122.35679626464844,37.72565098865453],[-122.49343872070312,37.67947293019486],[-122.51953125,37.78265474565738]]]}'

set fleet MA1FW2DDUP3A15402 point 37.75822994194451 -122.45773315429688
set fleet MA1FW2DDUP3A15402 point 37.65495972930227 -122.45498657226562

**Comment by iwpnd** [comment]
Test if your geofence works in [this](https://tile38.com/topics/geofencing) basic example. If it does, start your tile38 server with `-vv` and see if tile38 can actually connect to the provided endpoint.

**Comment by Lokeshjilli** [comment]
I can see, hook is triggered. But the data is null (mqtt://localhost:1883/geofence: <nil>)

@iwpnd adding the response from tile38 server terminal.

2023/12/05 14:03:36 [DEBU] queued hook: 1
2023/12/05 14:03:36 [DEBU] Endpoint send ok: 1: mqtt://localhost:1883/geofence: <nil>
2023/12/05 14:05:31 [DEBU] queued hook: 2
2023/12/05 14:05:32 [DEBU] Endpoint send ok: 2: mqtt://localhost:1883/geofence: <nil>

**Comment by Lokeshjilli** [comment]
Hi, 
Thank you @iwpnd , its working fine.
