### ISSUE TITLE
MATCH clause problem

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#50]
scan FenceXY cursor 0 match 00010/13/00010002*
{"ok":true,"fields":["routeid","routesubid","stationid","ordernumber"],"objects":[{"id":"00010/13/00010002","object":{"type":"Point","coordinates":[113.223213,23.078522]},"fields":[427,840811,10003314,2]}],"count":1,"cursor":0,"elapsed":"70.87µs"}

scan FenceXY cursor 0 match 00010/13*
{"ok":true,"fields":["routeid","routesubid","stationid","ordernumber"],"objects":[],"count":0,"cursor":0,"elapsed":"75.706µs"}

why?

![image](https://cloud.githubusercontent.com/assets/19602075/18336781/c869d92a-75bc-11e6-93c4-e4d80728c23f.png)

**Comment by huangpeizhi** [comment]
tile38  version is 1.4.1

**Comment by tidwall** [comment]
You found a bug. Tile38 uses "path.Match" for matching, and it has problems with the slash '/' character will. Can you use ':' instead?

**Comment by huangpeizhi** [comment]
ok, thanks!
