### ISSUE TITLE
WHEREEVAL issues

### ISSUE THREAD

**Issue by vthorsell** [tidwall/tile38#500]
Hi,

I can not get WHEREEVAL to work with NEARBY, even with your examples. By doing this:

`SET fleet truck1 POINT 33.5123 -112.2693`
`FSET fleet truck1 speed 16 wheels 8`

Now running:
`scan fleet`
Produces:
`{"ok":true,"fields":["speed","wheels"],"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]},"fields":[16,8]}],"count":1,"cursor":0,"elapsed":"36.073µs"}`

And then running this as an example:
`NEARBY fleet WHEREEVAL "return FIELDS.wheels > ARGV[1] or (FIELDS.length * FIELDS.width) > ARGV[2]" 2 8 120 POINT 33.462 -112.268 6000`

I always get the following error:
`(error) invalid argument 'FIELDS.wheels'`

I'm running TILE38 1.18.0 on Ubuntu 16.04.6 LTS (installed according to your instructions).

Any pointers how to solve this? Even running (if this is related):

`EVAL "return 1 + 1" 0`
gives me:
`(error) f_e451dbd41c4a000fb21587ce00594aa1cbeba72a at EOF:   unterminated string\n`

**Comment by rshura** [comment]
Are you running commands with `tile38-cli`? If so, can you try running the same commands with `redis-cli`?  On ubuntu, you can install it by `apt-get install redis-tools`, and then run:

``redis-cli -h HOST -p 9851 NEARBY fleet WHEREEVAL "return FIELDS.wheels > ARGV[1] or (FIELDS.length * FIELDS.width) > ARGV[2]" 2 8 120 POINT 33.462 -112.268 6000```

**Comment by vthorsell** [comment]
Hi again,

Yes I was testing from `tlie38-cli`.

I did the same procedure again, meaning emptied the current "fleet" and added "truck1" again.

Running from `tile38-cli`:
`scan fleet`

Result:

`{"ok":true,"fields":["speed","wheels"],"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]},"fields":[16,8]}],"count":1,"cursor":0,"elapsed":"33.618µs"}`

Testing with `WHEREEVAL` from `tile38-cli`:
`NEARBY fleet WHEREEVAL "return FIELDS.wheels > ARGV[1] or (FIELDS.length * FIELDS.width) > ARGV[2]" 2 8 120 POINT 33.462 -112.268 6000`

Result:

`(error) invalid argument 'FIELDS.wheels'`

Testing `EVAL` from `tile38-cli`:

Result:

`(error) f_e451dbd41c4a000fb21587ce00594aa1cbeba72a at EOF:   unterminated string\n`

Now testing with `redis-cli` instead:

`redis-cli -h 127.0.0.1 -p 9851 NEARBY fleet WHEREEVAL "return FIELDS.wheels > ARGV[1] or (FIELDS.length * FIELDS.width) > ARGV[2]" 2 8 120 POINT 33.462 -112.268 6000`

Result:

`(error) ERR f_6f690171fff82d1105b0b25ba48b475951d2a42c:1: attempt to compare string with number
stack traceback:
	f_6f690171fff82d1105b0b25ba48b475951d2a42c:1: in main chunk
	[G]: ?`

Testing `EVAL` with `redis-cli`:
`redis-cli -h 127.0.0.1 -p 9851 EVAL "return 1 + 1" 0`

Result:

`(integer) 2`

**Comment by rshura** [comment]
So what happens here is that `tile38-cli` does not properly quote the arguments.  Therefore, if the argument has a space within it, like the text of the script, tile38-cli treats it as the next argument.  Hence the `invalid argument` error. This has been a long standing issue with tile38-cli. Not sure if @tidwall intends to fix it.

Meanwhile, both `redis-cli` and all other good redis clients correctly treat arguments with spaces. So this is strictly a `tile38-cli` issue.

I'll correct the docs to include `tonumber` conversion into the examples.  The `length` and `width` part of the example will only work if the truck object has `length` and `width` fields.  Hope it all makes sense :-)

**Comment by tidwall** [comment]
I just pushed an update that fixes the bad quote issue.
