### ISSUE TITLE
STATS command  input/output be careful!

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#51]
127.0.0.1:9851> STATS FenceXY
{"ok":true,"stats":[{"in_memory_size":6813930,"num_objects":104830,"num_points":104830}],"elapsed":"57.39µs"}

127.0.0.1:9851> STATS  FenceXY             # note: 2 spaces
{"ok":true,"stats":[null,{"in_memory_size":6813930,"num_objects":104830,"num_points":104830}],"elapsed":"135.822µs"}

**Comment by tidwall** [comment]
Is this with the tile38-cli command?

**Comment by huangpeizhi** [comment]
yes  :)

**Comment by huangpeizhi** [comment]
yes  :)

**Comment by tidwall** [comment]
Thank you for finding this bug 👍
