### ISSUE TITLE
Distinguish between zero values and no value

### ISSUE THREAD

**Issue by pdrum** [tidwall/tile38#512]
**Describe the bug**
Tile fields treat 0 values and no values of fields as the same. I think this is not the expected. So there is no way to know if a value is never set or is set to 0.

behavior.
**To Reproduce**
If you run `SET fleet truck1 FIELD age 0 POINT 33.5123 -112.2693` and then fetch the point with `GET fleet truck1 WITHFIELDS`, the result looks like 

```py
[b'{"type":"Point","coordinates":[-112.2693,33.5123]}']
```

**Expected behavior**
IMHO what should get returned is:

```py
[b'{"type":"Point","coordinates":[-112.2693,33.5123]}', [age', b'0']]
```

**Comment by tidwall** [comment]
This is by design. 

It's mention in the documentation. https://tile38.com/commands/intersects/#fields

> The object field values are grouped together in a list per object. Due to the way Tile38 organizes field memory, it’s possible to see zero values for fields that have not been set. It’s recommended to treat all nonexistent or omitted fields as having the value of zero. Check out this [Github issue](https://github.com/tidwall/tile38/issues/169#issuecomment-295280587) for more information.
