### ISSUE TITLE
SETCHAN freezes when coordinate is Geojson

### ISSUE THREAD

**Issue by duartejc** [tidwall/tile38#513]
**Describe the bug**
When registering a channel in tile38-cli and coordinates are Geojson format the cli didn't respond to the command. 
 
**To Reproduce**
1 - Init Tile38-CLI;
2 - Register a channel with `SETCHAN buildingTiakiwai WITHIN traffic FENCE DETECT enter,exit,cross OBJECT {"type":"Polygon","coordinates":[[[174.77801,-41.27632],[174.77800,-41.27686],[174.77881,-41.27688],[174.77883,-41.27634],[174.77801,-41.27632]]]}` 

**Expected behavior**
Cli returning a success message.

**Comment by tidwall** [comment]
I'm unable to reproduce. 

When I enter the same command I get back an 'OK' response.

```
{"ok":true,"elapsed":"37µs"}
```

**Comment by duartejc** [comment]
More context:

I'm running from **master**, on a Linux machine. Up to date branch. 

![image](https://user-images.githubusercontent.com/583437/70532409-c1641600-1b35-11ea-9cef-77391cd2e347.png)

![image](https://user-images.githubusercontent.com/583437/70532520-fa9c8600-1b35-11ea-8546-c0777df2e6d5.png)

*the command line is complete, I promise ;)

![image](https://user-images.githubusercontent.com/583437/70532654-3e8f8b00-1b36-11ea-8215-ec154c47a015.png)

Cursor keeps blinking indefinitely and no result is shown. 

I tested both on Docker containers (on my machine and on an AWS instance) and install from code.

**Comment by duartejc** [comment]
I just confirmed the bug occurs on versions above 1.19.0.
Now I'm running successfully from tag 1.18.0

Thank you!

**Comment by jose-lpa** [comment]
I am running version 1.19.2, straight away from fresh Docker pull, and I can confirm this is happening.

![Screenshot from 2019-12-11 16-03-29](https://user-images.githubusercontent.com/2226098/70637876-e341c380-1c2f-11ea-857e-a349130a237e.png)

...and it hangs.

**Comment by tidwall** [comment]
I just push a hotfix moments ago. Thanks for reporting!

**Comment by duartejc** [comment]
Welcome... Thanks for your project!

**Comment by jose-lpa** [comment]
Good job. Many thanks, @tidwall :+1:
