### ISSUE TITLE
GRPC webhook not firing. 

### ISSUE THREAD

**Issue by naveenchlsn** [tidwall/tile38#514]
**Describe the bug**
I have set up a grpc hook for receiving geofencing responses from tile38. But Tile 38 is not publishing the same. 

**To Reproduce**

```SETHOOK warehouse6 grpc://localhost:8081/ NEARBY fleet FENCE POINT  33.462 -112.268 6000```

```SET fleet bus POINT 32.460 -112.260```

GRPC endpoint is not being hit.  

**Expected behavior**
GRPC webhook is fired. 
**Logs**
No logs to share. Please let me know where we can get error logs for issue in firing. 

**Operating System (please complete the following information):**
 - OS: [Mac OS]
 - Version [10.14.5]

**Additional context**
I have used the following [proto](https://github.com/tidwall/tile38/blob/master/internal/hservice/hservice.proto) to generate GRPC service.

**Comment by tidwall** [comment]
> No logs to share. Please let me know where we can get error logs for issue in firing.

For verbose logs use the `-vv` flag at startup. 

```
$ tile38-server -vv
```

This will pump out messages for each geofence success of failure.

**Comment by naveenchlsn** [comment]
Thanks for the quick response on this.  I am able to resolve this.
