### ISSUE TITLE
Need help in understanding geofencing internals. 

### ISSUE THREAD

**Issue by naveenchlsn** [tidwall/tile38#515]
1. Can we set TTL on a geofence in tile38? 
2. Can check if a geofence is created already in tile38, and ingest data to tile 38 only if the geofence is present. 
3. How can we check if a geofence is created? 
4. How do we delete a geofence? I think we can drop the collection but will it delete other metadata when the geofence is created. ?

**Comment by tidwall** [comment]
> Can we set TTL on a geofence in tile38?
Yes, there's an EX option for the SETHOOK command. See https://tile38.com/commands/sethook/
> Can check if a geofence is created already in tile38, and ingest data to tile 38 only if the geofence is present.
Yes, you can check if the geofence is already in the system with the HOOKS command, and then follow it up with a SET command. See https://tile38.com/commands/hooks/
> How can we check if a geofence is created?
Yes, with the HOOKS command.
> How do we delete a geofence? I think we can drop the collection but will it delete other metadata when the geofence is created. ?
Yes, you can delete a geofence using DELHOOK. See https://tile38.com/commands/delhook/
Geofences and collections are separate things in Tile38. A geofence can track any collection, existing or not existing. So deleting a collection or deleting a geofence does not affect the other.
