### ISSUE TITLE
About lettuce

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#52]
hi,tidwall
I was a little white,there is a problem need to consult you.
I want to send some instructions through the lettuce to tile38,
But I can't find the call in the lettuce source.For example,
                  redis.call(["set", "fleet", "truck", "point", "33.5123", "-112.2693"])
Looking forward to your reply，thank you

**Comment by tidwall** [comment]
Hi GameFreedom,

You will want to the the `redis.dispatch` interface. 
Please see the page on [Custom commands](https://github.com/mp911de/lettuce/wiki/Custom-commands)

**Comment by GameFreedom** [comment]
Thank you for your help.
With your help, I tried out

**Comment by GameFreedom** [comment]
I'm sorry, I have a question.
After I set the password, how to access.
I tried the following several ways：(password:1234)
1.           "redis://1234@localhost:9851"
2.           First send command with AUTH,Then send my query
These methods are not working.
Should excuse me I how to operate?

**Comment by GameFreedom** [comment]
As follows, does not contain the 'within‘ in ‘CommandType’:
                RedisClient redisClient = RedisClient.create("redis://localhost:9851");
		StatefulRedisConnection<String, String> redis = redisClient.connect();
		RedisCommand<String, String, String> command = new Command<>(
				CommandType.GET, new StatusOutput<>(codec), new CommandArgs<>(
						codec).addValues("fleet","truck1"));
		ReactiveCommandDispatcher<String, String, String> dispatcher = new             ReactiveCommandDispatcher<>(command,
				redis, false);
		Observable<String> observable = Observable.create(dispatcher);
		String res = observable.toBlocking().first();
		System.out.println(res);
If that is not able to use this command

**Comment by tidwall** [comment]
Sorry, but I'm not sure how to use lettuce to send a WITHIN command.

I recommend that you create an issue at https://github.com/mp911de/lettuce/issues/new
