### ISSUE TITLE
Consolidate order of Latitude and Longitude

### ISSUE THREAD

**Issue by KBassford** [tidwall/tile38#524]
**Is your feature request related to a problem? Please describe.**
When inputting GeoJSON and reading the output of server FENCE notifications, the Longitude is listed first, followed by Latitude.  When issuing a SET command the order is reversed (Latitude followed by Longitude).  This inconsistency can be quite frustrating and lead to problems for those who are not familiar with this module or to the wider problem that has plagued GIS software (see https://macwright.org/lonlat/ and http://docs.geotools.org/latest/userguide/library/referencing/order.html for backgrond).  To be honest, I didn't even notice until Josh pointed out that setting a Polygon object was opposite the SET command, and therefore my code would never work.

**Describe the solution you'd like**
Well, since GeoJSON, ArcGIS and most Redis services require Longitude followed by Latitude, it would seem to be the most logical way to go.

**Describe alternatives you've considered**
You could also do as GeoTools does and add a property that sets the output format (X,Y or Y,X).  Or you could require keywords (Lon, Lat), though that could get messy.

**Additional context**
N/A

**Comment by tidwall** [comment]
I don’t consider this an issue. The documentation clearly shows the order of the lat/lon parameters. https://tile38.com/commands/set/

Beside swapping the arguments would be a breaking change.
