### ISSUE TITLE
Server notifications through the Tile38-cli are via STDERR.

### ISSUE THREAD

**Issue by KBassford** [tidwall/tile38#526]
**Describe the bug**
As the title states, subscribed server notifications via Tile38-cli use STDERR, not STDOUT as would be the norm.  That is why the Geofence tutorial works, because the terminal window receives both STDERR and STDOUT which appear exactly the same to the user.

**To Reproduce**
Using a Redis client, define a Geofence.
Then using GO to SUBSCRIBE ...
```
	go func() {
		subscribe := "SUBSCRIBE " + channel
		pcmd = exec.Command(cli, subscribe)
		pcmd.Stdout = os.Stdout
		err = pcmd.Start()
		if err != nil {
			fmt.Println("Failed Subscribe:", err)
			return
		}
		fmt.Println(subscribe, ":", output(buffer))
	}()
```

Issue several SET commands to simulate an object passing through your Geofence.
You will see nothing.

Now add "pcmd.Stderr = os.Stderr" under the line "pcmd.Stdout = os.Stdout" and rerun, you see output now.

**Expected behavior**
Output should be reported via STDOUT.

**Logs**
(Since you get nothing when the problem is present ...)

**Operating System (please complete the following information):**
 - OS: Ubuntu Linux
 - Version 16.04 (AWS tailored)

**Additional context**
NOTE: This may be why Redis clients don't report SUBSCRIBed channels (Issue #525)!?

**Comment by tidwall** [comment]
I designed the `tile38-cli` to be used from the command-line terminal, not to be executed from inside an application like the way you are showing. You should be using a proper client like [redigo](https://github.com/gomodule/redigo).

**Comment by KBassford** [comment]
This does not address the basic problem.  All output should be via STDOUT.

**Comment by tidwall** [comment]
I understand that it's an inconvenience for you to have to redirect stderr, but it really isn't a bug with the software. Whether the tile38-cli outputs to stdout or stderr makes no difference because I never designed tile38-cli to be executed as a child process from an application.
