### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by KBassford** [tidwall/tile38#527]
**Is your feature request related to a problem? Please describe.**
Took me almost 3 weeks to write a program that I should have been able to do in an afternoon due to limited examples, the bugs I have previously reported, and undocumented features like the fact that if one enters a GeoJSON object, it is required that ALL whitespace in the GeoJSON object be eliminated (Don't know whether this is true for files being directly input and read in, but it sure is true of the command line.)

**Describe the solution you'd like**
Maybe a user Wiki would be a good solution?  That way you are not responsible for having to find every instance that may confuse a user.  Besides, personal experience has taught me that I, as an author, am the worst judge of what I should, and should not document.  (Never edit your own work, get someone else that does not have the same familiarity with the code/subject as you do.  A fresh/different set of eyes.)

**Describe alternatives you've considered**
Code generated (think GoDoc).

**Additional context**
Things that stumped/confused me ...

- As noted above, ALL whitespace must be eliminated from GeoJSON prior to being place upon the command line.
- Order of Lat and Lon will constantly switch back and forth in your code.  Be cognizant of the order when parsing responses and issuing commands.
- Server output uses STDERR, not STDOUT as one would expect.
- When using a Geofence (at least a Polygon object for a fence), either the "cross" parameter does not work, or maybe it requires one to be sitting exactly on the border itself, or maybe one uses the "cross" parameter with intersecting objects that are larger than a point ("cross" actually means intersect)?  Since I can't get it to output anything in my application, I can't tell which of the above is true.  I can however verify that "enter", "exit", "inside", and "outside", alone and in any combination all work for polygons.

**Comment by tidwall** [comment]
The documentation project for Tile38 is at [tile38/tile38.github.io](https://github.com/tile38/tile38.github.io). 

There you can file issues or provide pull requests to the tile38.com website, such as missing commands or adding more examples. I recommend filing one issue at a time. 

Also, there is a [wiki](https://github.com/tidwall/tile38/wiki) for this project which includes examples for how to use Tile38 with various clients specific to some programming languages. If you would like to modify or add an entry, please file an issue to this [tidwall/tile38](https://github.com/tidwall/tile38) project with a complete code example.
