### ISSUE TITLE
 a few questions

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#53]
hi, tidwall
1. when using the HOOKS or KEYS command, the results can provide a number of HOOK or KEY display?
2. for what reason, HOOK collection can not be seen through the KEYS command?
3. when I set the KEY expiration date, when the KEY expires, Will affect the results of FENCE event?

thanks ：)

**Comment by tidwall** [comment]
Hi huangpeizhi

> when using the HOOKS or KEYS command, the results can provide a number of HOOK or KEY display?

If you are using a Redis client, then the results are encoded as a [RESP](http://redis.io/topics/protocol) Array.  Redis Arrays begin with `*` and then the number of items;

```
*6\r\nkey1\r\nkey2\r\n
```

> for what reason, HOOK collection can not be seen through the KEYS command?

Hook and Keys are kept in separate structures. The don't share the same keyspace.

> when I set the KEY expiration date, when the KEY expires, Will affect the results of FENCE event?

Yes, when a key expires a DEL is issued and it propagates through the FENCE was a "del" event.

**Comment by huangpeizhi** [comment]
thanks!

When the amount of KEY or HOOK is more, it is necessary to divide the KEY or HOOK into smaller classes to reduce unnecessary associations.

In this case, TILE38 is for a long time to run the service, need to do as much as possible not to restart the operation, which requires the operation of the state, the KEY or HOOK to maintain the work, the proposed consideration:
- DROP key command, consider the fuzzy match.
- Increase RENAME key command, because sometimes it takes time to prepare the contents of the key collection, but also not affect the original KEY set.

**Comment by tidwall** [comment]
I'm closing this issue for now. Thanks for the suggestions and your help.
