### ISSUE TITLE
Tile38 - Geofence around a Volume

### ISSUE THREAD

**Issue by mayanagarwal** [tidwall/tile38#531]
The Tile38 website says ([link](https://tile38.com/topics/geofencing/)): 
A geofence is a virtual boundary that can detect when an object enters or exits the **area**. This boundary can be a radius or any search **area** format, such as a bounding box, GeoJSON object, etc. 

Also, the [Set](https://tile38.com/commands/set/) documentation says that the Z coordinate is application-specific such as elevation, or a timestamp, etc..

What I was trying to figure out was a way to **geofence a volume** and not an area. Somehow giving it a GEOJSON with a height variable and tile38 distinguishes inside which zone it is based on height even if the latitude & longitude is the same for the 2 zones.

`{
         "type":"Feature",
         "properties":{
            "id":12345,
            "name":"Zone1"
         },
         "geometry":{
            "type":"MultiPolygon",
            "coordinates":[
               [[[
                        144,
                        -37,
                        17
                     ],
                     [
                        144,
                        -38, 17
                     ],
                     [
                        145,
                        -37, 17
                     ],
                     [
                        145,
                        -38, 17
                     ],
[
                        144,
                        -37, 17.99
                     ],
                     [
                        144,
                        -38, 17.99
                     ],
                     [
                        145,
                        -37, 17.99
                     ],
                     [
                        145,
                        -38, 17.99
                     ]
                  ]]]
         }
}`
`{
         "type":"Feature",
         "properties":{
            "id":12346,
            "name":"Zone2"
         },
         "geometry":{
            "type":"MultiPolygon",
            "coordinates":[
               [[[
                        144,
                        -37, 18
                     ],
                     [
                        144,
                        -38, 18
                     ],
                     [
                        145,
                        -37, 18
                     ],
                     [
                        145,
                        -38, 18
                     ],
[
                        144,
                        -37, 18.99
                     ],
                     [
                        144,
                        -38, 18.99
                     ],
                     [
                        145,
                        -37, 18.99
                     ],
                     [
                        145,
                        -38, 18.99
                     ]
                  ]]]
         }
}`

For example, I run a command `SET testing point1 POINT 144.5 37.5 17.5` it should give me an output that it is inside Zone 1 and outside Zone 2.

I have a workaround for this. I am Adding L18/ L17 as the prefix for the filename and my Tils38 querries on a webhook for that level. But would love to have the feature in Tile38.

**Comment by tidwall** [comment]
Tile38 is designed for 2D geo coordinates [-180,-90] to [180,90]. The z coordinate is allowed for objects, but there are limitations for geofencing and queried, as you have discovered. It looks like you found a decent workaround. This is similar to how others are adding timestamps to objects, and later filtering on time ranges.

Another option is to use the `FIELD` option; `SET testing obj1 FIELD zmin 18 FIELD zmax 19 ...`.  Then query using the `WHERE` option; `INTERSECTS testing WHERE zmin 18 19 WHERE zmax 18 19 ...`
