### ISSUE TITLE
geojson parser fails

### ISSUE THREAD

**Issue by tomquas** [tidwall/tile38#536]
**Describe the bug**
Am trying to use the geojson syntax from the example. Parsing fails.

**To Reproduce**
127.0.0.1:9851> SET city tempe OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}
Invalid argument(s)

same for a simple example:
127.0.0.1:9851> SET cities x OBJECT {"type": "Point", "coordinates": [1.2, 2.1]}
Invalid argument(s)

**Operating System (please complete the following information):**
 - OS: amd64/linux on docker
 - Version 1.19.5

**Comment by tomquas** [comment]
uh, my fault: forgot the enclosing quotes:

127.0.0.1:9851> SET city tempe OBJECT '{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]}'
OK

that said, i am a total copy-paste fan when it comes to learning from tutorials... maybe the docs need an update? ;)

**Comment by tidwall** [comment]
Thanks for point that out. I filed a bug on the docs repo.

**Comment by tidwall** [comment]
I updated the documentation with the added ticks around the geojson.
