### ISSUE TITLE
DEL-eting inexisting `id` does not return an error

### ISSUE THREAD

**Issue by adioanca-rpma** [tidwall/tile38#549]
**Describe the bug**
deleting an inexistent `id` should, IMO, return error

**To Reproduce**
127.0.0.1:9851> set toll-gates 6 OBJECT {"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.8950,33}
{"ok":true,"elapsed":"65.36µs"}
127.0.0.1:9851> get toll-gates 6
{"ok":true,"object":{"type":"Polygon","coordinates":[[[-111.9787,33.4411],[-111.8902,33.4377],[-111.895,33.2892],[-111.9739,33.2932],[-111.9787,33.4411]]]},"elapsed":"22.763µs"}
127.0.0.1:9851> get toll-gates 7
(error) id not found
127.0.0.1:9851> del toll-gates 7
{"ok":true,"elapsed":"2.625µs"}
127.0.0.1:9851> del toll-gates 6
{"ok":true,"elapsed":"7.683µs"}
127.0.0.1:9851> get toll-gates 6
(error) key not found
127.0.0.1:9851> get toll-gates 7
(error) key not found
127.0.0.1:9851> 

**Expected behavior**
`DEL` should return an error. The workaround is to make a `GET` and skip deletion on error.
I need this behaviour to respond with success/error to a microservice requesting this.

**Logs**
N/A

**Operating System (please complete the following information):**
 - OS: Linux
 - Version: latest

**Additional context**
Don't know if `DEL` should always return `ok`. No documentation is available on deleting inexistent key/ids.

**Comment by tidwall** [comment]
I agree it's a confusing behavior, but passive deletes are by design. Changing it at this point would break current implementations.

The tile38-cli used JSON output by default which always returns a `"ok":true` response.

But with using RESP output (which is the default when connecting from a Redis client) you will receive the number of objects deleted.

For example:
```
tile38-cli> OUTPUT resp
OK
tile38-cli> SET toll-gates 6 POINT 33 -115
OK
tile38-cli> DEL toll-gates 6
(integer) 1
tile38-cli> DEL toll-gates 7
(integer) 0
```

One thing we could do is add an additional field to the JSON response so it could look like:
```
tile38-cli> OUTPUT json
{"ok":true,"elapsed":"312ns"}
tile38-cli> SET toll-gates 6 POINT 33 -115
{"ok":true,"elapsed":"40.186µs"}
tile38-cli> DEL toll-gates 6
{"ok":true,"count":1,"elapsed":"4.087µs"}
tile38-cli> DEL toll-gates 7
{"ok":true,"count":0,"elapsed":"1.14µs"}
```

What do you think?



``

**Comment by adioanca-rpma** [comment]
Hi,

Thanks for proposed solutions.

I'm using `node-tile38` library so adding `count: 0/1` would require changes to it.
Doing a `get` folowed by a `del` is an acceptable solution, so I'll close this issue.

Thank you for this great product that you've made available for us all!
