### ISSUE TITLE
About Pipeline

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#55]
HI,
Recently, I am using Lettuce channel model,
But tile38 seems doesn't work.I want to ask you, whether tile38 support channel model?
And then, there is a problem, Lettuce with dispitch tile38 operation, then the jedis is in what way?
I hope you can help me

**Comment by tidwall** [comment]
Tile38 does support pipelining as of [1.4.2](https://github.com/tidwall/tile38/releases/tag/1.4.2).

**Comment by tidwall** [comment]
Hi GameFreedom. Were you able to solve the problem?
