### ISSUE TITLE
About attribute query

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#56]
Hi,
I have a question about the attributes of the query.
‘GET’ is similar to the 'where' in the SQL statement?
I want to pass the ‘where’ condition to check the properties of the node containing the attribute value

**Comment by huangpeizhi** [comment]
[#46](https://github.com/tidwall/tile38/issues/46)

**Comment by GameFreedom** [comment]
Hi,
I want to ask is the attribute query, not range queries

**Comment by tidwall** [comment]
Are you wanting to get an attribute from a GeoJSON object?

Unfortunately Tile38 does not currently support queries on a GeoJSON attributes.

**Comment by GameFreedom** [comment]
ok,thanks
