### ISSUE TITLE
Cannot work Nearby as concurrently using graphql-go

### ISSUE THREAD

**Issue by vishnutm** [tidwall/tile38#560]
@tidwall 
Currently, try to perform Nearby function in driver detail in a concurrent manner. I currently use the graphql-go method to fetch the APIs.

**_current Nearby function_**

![Screenshot from 2020-05-17 00-07-23](https://user-images.githubusercontent.com/30982642/82127589-67e1d080-97d2-11ea-8ae4-040387691336.png)

**My go-routine method (Resolve function)**

`func GetNearbyUser() *graphql.Field {
	return &graphql.Field{
		Type: graphql.NewList(types.NearbyType),
		Args: graphql.FieldConfigArgument{

			"latitude": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.Float),
			},

			"longitude": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.Float),
			},

			"collection": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.String),
			},

			"radius": &graphql.ArgumentConfig{
				Type:         graphql.Float,
				DefaultValue: 2000.00,
			},
		},

		Resolve: func(params graphql.ResolveParams) (interface{}, error) {

			ch := make(chan []types.NearbyLocation)

			go func() {
				var Lat = params.Args["latitude"].(float64)
				var Long = params.Args["longitude"].(float64)
				var radius = params.Args["radius"].(float64)
				var collection = params.Args["collection"].(string)
				response, _ := tile38.Nearby(collection, Lat, Long, radius)
				ch <- response
			}()

			return func() interface{} {

				return <-ch
			}, nil

		},
	}
}`

**Error Result**

query : `query {nearbyUser(collection:"driver",latitude:8.55652,longitude:76.872894,radius:2000){latitude,longitude,id}}`

  
![Screenshot from 2020-05-16 23-14-40](https://user-images.githubusercontent.com/30982642/82127749-97450d00-97d3-11ea-88c6-cf32663662f3.png)
![Uploading Screenshot from 2020-05-16 23-14-30.png…]()

**Comment by tidwall** [comment]
The error you are getting does not appear to be related to Tile38. I'm unfamiliar with graphql. 

You appear to be running into some type of Go syntax error. 


Perhaps your Resolve function should be something like:

```go
Resolve: func(params graphql.ResolveParams) (interface{}, error) {
	return func() (interface{}, error) {
		var Lat = params.Args["latitude"].(float64)
		var Long = params.Args["longitude"].(float64)
		var radius = params.Args["radius"].(float64)
		var collection = params.Args["collection"].(string)
		resp, err := tile38.Nearby(collection, Lat, Long, radius)
		return resp, err
	}, nil
}
```

You may want to ask this question on a graphql-go forum.

**Comment by vishnutm** [comment]
@tidwall, Thank you for your valuable suggestion
