### ISSUE TITLE
Crashes under go1.14 runtime

### ISSUE THREAD

**Issue by rshura** [tidwall/tile38#562]
This is the runtime issue we encountered the hard way, through crashes of tile38:
https://github.com/golang/go/issues/37688

The issue manifests with tile38 if the query contains `TIMEOUT` and `WHEREVAL` and the timeout gets triggered (query does not finish within the allotted timeout). After such queries, the next GC cycle crashes the server, exactly like the issue above.

Rebuilding with go1.14.3 fixed the issue for us. We can reliably crash 1.14 runtime and not crash with 1.14.3 runtime on the same code.

**Comment by rshura** [comment]
There's nothing to fix in tile38 for this, but all the released binaries should not be built with go 1.14.

**Comment by tidwall** [comment]
Yikes. That's good to know. 
I just made sure that the official Docker releases will be 1.14.3+
