### ISSUE TITLE
Field names and values order doesn't match for JSON output

### ISSUE THREAD

**Issue by ipsusila** [tidwall/tile38#569]
The order of field names and field values doesn't match for `SCAN` query with JSON output. Try the following in `tile38-cli`

```bash
>SET fleet truck1 FIELD speed 90 FIELD age 21 POINT 33.5123 -112.2693
>SCAN fleet match truck*
{"ok":true,"fields":["age","speed"],"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]},"fields":[90,21]}],"count":1,"cursor":0,"elapsed":"170.4µs"}
```

Reformated JSON output is shown below:

```json
{
    "ok": true,
    "fields": ["age", "speed"],
    "objects": [{
        "id": "truck1",
        "object": {
            "type": "Point",
            "coordinates": [-112.2693, 33.5123]
        },
        "fields": [90, 21]
    }],
    "count": 1,
    "cursor": 0,
    "elapsed": "170.4µs"
}
```

As shown above, the field names order is `["age", "speed"]` and the field values order is `[90, 21]`. 
Tried both for version [1.21.1](https://github.com/tidwall/tile38/releases/tag/1.21.1) and `master` branch.

**Comment by tidwall** [comment]
I found the issue and fixed it. It seems to have occurred specifically with JSON output. RESP output and other retrieval commands did not encounter this problem.
