### ISSUE TITLE
FR: support 'monitor' command

### ISSUE THREAD

**Issue by tomquas** [tidwall/tile38#571]
**Is your feature request related to a problem? Please describe.**
when debugging redis interactions, it's of tremendous help to start a separate terminal session with

$ redis-cli monitor

and trace commands. i'd love to see this support in tile38, too.

**Describe the solution you'd like**
$ tile38-clie monitor

**Describe alternatives you've considered**
app logging - too much additional, repetitive effort

**Additional context**
[none]

**Comment by tomquas** [comment]
wow, i'm impressed. thank you.

**Comment by tidwall** [comment]
You're welcome.

**Comment by larsw** [comment]
Excellent, but noticed that "MONITOR" is not available when doing tab completion in `tile38-cli`.
