### ISSUE TITLE
Need More Information in Tile38 geofence notification 

### ISSUE THREAD

**Issue by monaadelrabea66** [tidwall/tile38#577]
In Our Project we send location of object every 1 sec and need to validate its location if is inside or outside geofence
for Example 

SETCHAN test_eventId_zoneId_chan INTERSECTS test_eventId FENCE POINTS OBJECT {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"zone_id":"zone_1"},"geometry":{"type":"Polygon","coordinates":[[[39.546661376953125,22.89262280727798],[39.469757080078125,22.829351851270825],[39.48760986328125,22.743256140281986],[39.61944580078125,22.75085500586733],[39.74578857421875,22.85466376836665],[39.546661376953125,22.89262280727798]]]}},{"type":"Feature","properties":{"zone_id":"zone_2"},"geometry":{"type":"Polygon","coordinates":[[[39.821319580078125,22.768584048597102],[39.711456298828125,22.724257128165284],[39.737548828125,22.622884538527202],[39.49859619140625,22.518900009781632],[39.8419189453125,22.554415740003208],[39.821319580078125,22.768584048597102]]]}},{"type":"Feature","properties":{"zone_id":"zone_3"},"geometry":{"type":"Polygon","coordinates":[[[39.5672607421875,22.774915291708023],[39.48623657226562,22.80403522599119],[39.532928466796875,22.636827710810884],[39.76776123046875,22.568365847961534],[39.796600341796875,22.731857049769385],[39.5672607421875,22.774915291708023]]]}}]}

SUBSCRIBE test_eventId_zoneId_chan

set test_eventId test_unitId_1 POINT 22.80909892750663 39.58786010742187
set test_eventId test_unitId_2 POINT 22.60640442085196 39.77874755859374
set test_eventId test_unitId_2 POINT 22.688785246513845 39.758148193359375
this used commands 
and 
output :
{"command":"set","group":"5f469494741d534ba558f658","detect":"inside","hook":"test_eventId_zoneId_chan","key":"test_eventId","time":"2020-08-26T20:03:51.537092243+02:00","id":"test_unitId_1","point":{"lat":22.80909892750663,"lon":39.58786010742187}}

Its more Helpful if there is information about which geofence that detected in 
as for example i send information for each geofence in feature values: "properties":{"zone_id":"zone_1"},

**Comment by monaadelrabea66** [comment]
@tidwall  .if there is  any implementation for this feature please refer it .

**Comment by tidwall** [comment]
Tile38 is treating your entire FeatureCollection as a single Geofence. You'll need to separate each Feature(Polygon) from the FeatureCollection and use one per geofence channel.

Something like:

```
> SETCHAN test_eventId_zone_1 INTERSECTS test_eventId FENCE POINTS OBJECT {"type":"Polygon","coordinates":[[[39.546661376953125,22.89262280727798],[39.469757080078125,22.829351851270825],[39.48760986328125,22.743256140281986],[39.61944580078125,22.75085500586733],[39.74578857421875,22.85466376836665],[39.546661376953125,22.89262280727798]]]}
> SETCHAN test_eventId_zone_2 INTERSECTS test_eventId FENCE POINTS OBJECT {"type":"Polygon","coordinates":[[[39.821319580078125,22.768584048597102],[39.711456298828125,22.724257128165284],[39.737548828125,22.622884538527202],[39.49859619140625,22.518900009781632],[39.8419189453125,22.554415740003208],[39.821319580078125,22.768584048597102]]]}
> SETCHAN test_eventId_zone_3  INTERSECTS test_eventId FENCE POINTS OBJECT {"type":"Polygon","coordinates":[[[39.5672607421875,22.774915291708023],[39.48623657226562,22.80403522599119],[39.532928466796875,22.636827710810884],[39.76776123046875,22.568365847961534],[39.796600341796875,22.731857049769385],[39.5672607421875,22.774915291708023]]]}
```

Then you can use a `PSUBSCRIBE` to subscribe to all of the channels using a pattern:

```
> PSUBSCRIBE test_eventId_*
```

**Comment by monaadelrabea66** [comment]
@tidwall  Tile38 is treating   FeatureCollection as a single Geofence and that i want it . I want Tile38t to told me if object is Inside at least one of all geofence in FeatureCollection.and it will notify me with one record. 
for ex:i need it to told me  "object is inside geofence zoneId1"
output example i need 
{"command":"set","group":"5f469494741d534ba558f658","detect":"inside","hook":"test_eventId_zoneId_chan","key":"test_eventId","time":"2020-08-26T20:03:51.537092243+02:00","id":"test_unitId_1","point":{"lat":22.80909892750663,"lon":39.58786010742187}, 

"geofence":"zoneId1"}  and this info i already it send it when i set FeatureCollection in properties variable .

**Comment by tidwall** [comment]
I'm sorry but I'm afraid that Tile38 cannot do what you are asking. It is not designed to return the "id" of the child Feature in a FeatureCollection for a geofence notification.

**Comment by monaadelrabea66** [comment]
@tidwall  thanks a lot for your support
