### ISSUE TITLE
DETECT clarification

### ISSUE THREAD

**Issue by feichler-or** [tidwall/tile38#578]
Not sure if this is a bug or working as intended, but I couldn't find any information in the documentation and here at the github project

**Describe the bug**
`SETCHAN` with `DETECT` does not trigger `cross` notifications if used as `DETECT enter,exit,cross`

**To Reproduce**
I tried the following with three terminals:

1. Terminal 1: `SETCHAN test-eec NEARBY fleet FENCE DETECT enter,exit,cross POINT 10.000 10.000 10000`
=> `{"ok":true,"elapsed":"33.476µs"}`
2. Terminal 1: `SUBSCRIBE test-eec`
=> `{"ok":true,"command":"subscribe","channel":"test-eec","num":1,"elapsed":"2.662µs"}`
3. Terminal 2: `SETCHAN test-eecio NEARBY fleet FENCE DETECT enter,exit,cross,inside,outside POINT 10.000 10.000 10000`
=> `{"ok":true,"elapsed":"40.522µs"}`
4. Terminal 2: `SUBSCRIBE test-eecio`
=> `{"ok":true,"command":"subscribe","channel":"test-eecio","num":1,"elapsed":"2.498µs"}`
5. Terminal 3: `SET fleet vehicle_1 POINT 10.0 10.0`
=> Terminal 1 notified with `enter` event
=> Terminal 2 notified with `enter` event
=> Terminal 2 notified with `inside` event
6. Terminal 3: `SET fleet vehicle_1 POINT 0.0 0.0`
=> Terminal 1 notified with `exit` event
=> Terminal 2 notified with `exit` event
=> Terminal 2 notified with `outside` event
7. Terminal 3: `SET fleet vehicle_1 POINT 20.0 20.0`
=> Terminal 2 notified with `cross` event
=> Terminal 2 notified with `outside` event

**Expected behavior**
I expected in step 7 that Terminal 1 would also be notified, as it is a `cross` event for that channel too

**Operating System (please complete the following information):**
Ubuntu 18.04 - tested in docker container `tile38/tile38:1.22.0`

**Additional context**
In the use case I'm currently evaluating I only need the `enter`, `exit` and `cross` events - `outside` and `inside` are not necessary and would create "too much noise" as every point that is either outside or inside creates a new notification and not only changes (e.g. last location outside - notification was generated - next location again outside -> another notification generated)

Any suggestions or clarifications about the `DETECT` mechanics are appreciated

**Comment by schmidp** [comment]
@tidwall hey sorry to bump, it would help us a lot to get some clarification on this issue.

**Comment by tidwall** [comment]
I can reproduce the issue on my side and have fix on my local machine. I have some more testing to do and I'll publish a fix asap. Thanks for reporting and for bumping.

**Comment by tidwall** [comment]
Should be good now.
