### ISSUE TITLE
Can tile38 provide a persistence mechanism similar to RDB redis?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#58]
Can tile38  provide the data in the dump tile38 to the file, and then start another tile38 server, load the dump file, similar to the RDB redis persistence mechanism? I have an application scenario that requires a quick start of a copy of the service, the larger the amount of data, the copy and load the AOF file is too slow.
If I want to achieve this function, what do you suggest?

**Comment by tidwall** [comment]
No, Tile38 only has the AOF file. The AOF file can grow large over time, and the larger the AOF file, the slower the loading time.

There's a background routine that will automatically shrink the AOF file every now and then. 
You can send an AOFSHRINK command which will force the shrink routine to start.

This should make the AOF file smaller, and load a little quicker.

**Comment by icewukong** [comment]
I get, thx.
