### ISSUE TITLE
Bulk SET operations

### ISSUE THREAD

**Issue by greendisc777** [tidwall/tile38#580]
Is there a way to bulk load 100mm points? I'm not seeing anything like redis-cli --pipe.

**Comment by tidwall** [comment]
Sure, Tile38 works with redis-cli --pipe.  Such as:

```
cat data.txt | redis-cli -p 9851 --pipe
```

Where data.txt has a bunch of valid Tile38 commands. It's recommended that the commands in the data file are formatted using Redis protocol as shown at https://redis.io/topics/mass-insert.

**Comment by greendisc777** [comment]
Much better! Thank you!

**Comment by tidwall** [comment]
You're welcome 🙂
