### ISSUE TITLE
Intersect, send custom result to celery(Redis), LUA script?

### ISSUE THREAD

**Issue by mmmcorpsvit** [tidwall/tile38#587]
Hello,

are any way to create custom data send to redis on intersect with some analyze?

I try create dating sevice based at GPS, for example man search women, age 30-45 etc... will be perfect if possible use analyze data at itersect, please help how best way?

**Comment by mmmcorpsvit** [comment]
and how can use gps ccords with ttl?
what time range use?
are possible gps + ttl + timestamp from mobile phone data?

**Comment by tidwall** [comment]
Hi,

Objects can numerical fields:

```
SET people john FIELD age 32 POINT 33.1203 -112.5591
SET people mary FIELD age 36 POINT 33.1203 -112.5591
```

Then filter on the age 30-45 using WHERE:

```
INTERSECTS people WHERE age 30 45 BOUNDS 33 -113 34 -112
```

For man/woman you can use a field `gender` where male is `1` and woman is `2`:

```
SET people john FIELD gender 1 FIELD age 32 POINT 33.1203 -112.5591
SET people mary FIELD gender 2 FIELD age 36 POINT 33.4726 -112.7183
```

Then filter on men age 30-45:

```
INTERSECTS people WHERE gender 1 1 WHERE age 30 45 BOUNDS 33 -113 34 -112
```

**Comment by tidwall** [comment]
> and how can use gps ccords with ttl?

The TTLs in Tile38 are used to automatically expire objects after a specified amount of time. 

For example, to expire (delete from database) after 30 seconds:

```
SET people john FIELD gender 1 FIELD age 32 EX 30 POINT 33.1203 -112.5591
```

**Comment by mmmcorpsvit** [comment]
big th)))
