### ISSUE TITLE
About field

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#59]
Hi,
for example,
1.nearby fleet where speed 70 +inf point 33.462 -112.268 6000.
Condition that speed is more than 70, but I hope speed equal to 70.
2.WHERE speed 70 +inf WHERE age -inf 24
‘Where’ is to use the ‘and’ connection here, I want to use the ‘or’ connection

Excuse me, have this command tile38? How should I write this sentence？

**Comment by tidwall** [comment]
@GameFreedom Sorry for the delay on the response. Unfortunately only AND is available at this time.

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if you have any questions or ideas around this feature.
