### ISSUE TITLE
documentation is poor

### ISSUE THREAD

**Issue by stefanocudini** [tidwall/tile38#590]
hi,

I think this is an extraordinary project and for this I congratulate you

the command list is perfect(although references to redis could be inserted)
and also the Geofencing section is interesting

but the basic documentation should be more extensive, for example it would be useful:
- a glossary with basic terms (key, channel ...)
- general architecture of the project
- a section dedicated to the cli client

I would like to contribute but I lack these bases

best regards
Stef

**Comment by tidwall** [comment]
Thank you for your feedback. We will continue to look into improving the documentation.

**Comment by tidwall** [comment]
Transfered this issue to the documentation website.
