### ISSUE TITLE
Webhook encoding problem

### ISSUE THREAD

**Issue by ahmetagilkaya** [tidwall/tile38#595]
**Describe the bug**
Webhook not support turkish characters.

I work with Turkish characters. I can set Turkish characters successfully. But when i use webhook, turkish characters spoiled.
appendonly.aof file -> Balıkçı Gemisi, Tanımlı değil etc.
kafka webhook result -> Bal�k�� Gemisi, Tan�ml� de�il etc.

How can i solve this situation ?

**Comment by tidwall** [comment]
I'm wondering at point in the process the Turkish characters are getting spoiled. Tile38 or the webhoook endpoint?
Tile38 stores all data locally in UTF8, and sends all webhoook notifications in UTF8.
What encoding does your webhoook require and can it be configured to handle UTF8?

**Comment by ahmetagilkaya** [comment]
@tidwall Thank you for your reply. 
I think there is a problem with encoding in the CommandArgs class of the lettuce library. 
Now I'm using jedis instead of lettuce library. For now, there is no problem.
Thanks.

**Comment by tidwall** [comment]
Thanks for reporting back. I'll close this issue for now but feel free to reopen if needed.
