### ISSUE TITLE
Webhook, cannont sent to self-signed SSL

### ISSUE THREAD

**Issue by mmmcorpsvit** [tidwall/tile38#596]
```
2021/01/26 03:45:57 [DEBU] Endpoint connect/send error: 122: https://192.168.88.239:8000/geo/hook/: Post "https://192.168.88.239:8000/geo/hook/": x509: certificate signed by unknown authority
```

how can disable all https check of ssl ?

**Comment by mmmcorpsvit** [comment]
i try fix, i in correct way? need fix 
https://github.com/tidwall/tile38/blob/93e3a067b7d7cd0ec18ee07afa1edd5061b0efb0/internal/endpoint/http.go

i never before write on go

**Comment by tidwall** [comment]
Tile38 requires trusted certificates for all https endpoints.
I see your endpoint is using port 8000, which is not common with HTTPS/TLS.
Have you tried "http://192.168.88.239:8000/geo/hook/"  (without the "s")

**Comment by mmmcorpsvit** [comment]
for many reason i cannont use plain http (need facebook auth, require https connect on debug too etc...), so this problem(

will be greate add some setting for off security checks, and this can be improve perfomance

**Comment by tidwall** [comment]
Right now Tile38 only works with trusted certificates. 
Perhaps you can create a self-signed cert and CA and install on servers that need it. 
Maybe the [mkcert](https://github.com/FiloSottile/mkcert) tool can help?

**Comment by mmmcorpsvit** [comment]
i little patch code, file: internal/endpoint/http.go:
```go
func newHTTPConn(ep Endpoint) *HTTPConn {
	return &HTTPConn{
		ep: ep,
		client: &http.Client{
			Transport: &http.Transport{
				MaxIdleConnsPerHost: httpMaxIdleConnections,
				IdleConnTimeout:     httpExpiresAfter,
				TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // ignore expired SSL certificates
			},
			Timeout: httpRequestTimeout,
		},
	}
}
```

work fine, this is my first code-try on go-lang, can you please review and add how param please ?

**Comment by tidwall** [comment]
Yes that is a way to do it, but I recommend trying to find a way to add your self-signed and CA certs to your server. That way you won't need to maintain a fork of Tile38.

**Comment by mmmcorpsvit** [comment]
i think perfect way introduce param like --no-check-endpoint-http-ssl-verify
(i develop on windows, use django+self signed ssl on develop pc)
in production can just param for check ssl, this another story

anyway, th for great soft)
if i add param, you accept PR for this future, this ok?

**Comment by tidwall** [comment]
I gotta say no to this one. Sorry.

**Comment by mmmcorpsvit** [comment]
th in any way
