### ISSUE TITLE
Roaming geofence does not pick up FSET commands, but SET fields + current position works

### ISSUE THREAD

**Issue by johnpmayer** [tidwall/tile38#597]
To be clear, I'm not sure what is *intended* behavior, but it would be nice for this to work (or be configurable to work): Imagine a system where one client writes the POINT, but other clients may be responsible for writing other FIELDs, so the workaround of using SET is limited (because SET requires a location, other clients need to first query current position, possible race condition if not done atomically).

**Describe the bug**
Create key1 with some location
Set up a roaming nearby fence on key1
Create key2
SET key2 in range of key1's fence (works, geofence publishes a message)
SET key2 with same position and update a field (works, geofence publishes a message)
FSET key2 any field (**doesn't work, no messages published by geofence**)

**To Reproduce**
TODO - I can create a sequence of commands to reproduce the behavior

Note that FSET does appear to work with non-roaming FENCE.

**Expected behavior**

**Logs**
TODO

**Operating System (please complete the following information):**
 - OS: Mac OS
 - Version: Tile38 1.22.0 (bd572b0) 64 bit (amd64/darwin)

**Comment by tidwall** [comment]
Interesting. That looks like an oversight on my part and should be fixed.

**Comment by johnpmayer** [comment]
Cool. I’ll work on a concrete repro.
