### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by LuisUrrutia** [tidwall/tile38#6]
Hi, i'm trying to install Tile38 with no success.
I set the gopath (/opt/go) and i clone the repo in a src directory, and i run "make test" and show me errors like this:

```
/opt/go/src/_/opt/src/github.com/tidwall/tile38/cmd/tile38-cli (from $GOPATH)
can't load package: package _/opt/src/github.com/tidwall/tile38/cmd/tile38-server: cannot find package "_/opt/src/github.com/tidwall/tile38/cmd/tile38-server" in any of:
        /usr/local/go/src/_/opt/src/github.com/tidwall/tile38/cmd/tile38-server (from $GOROOT)
        /opt/go/src/_/opt/src/github.com/tidwall/tile38/cmd/tile38-server (from $GOPATH)
can't load package: package _/opt/src/github.com/tidwall/tile38/controller: cannot find package "_/opt/src/github.com/tidwall/tile38/controller" in any of:
        /usr/local/go/src/_/opt/src/github.com/tidwall/tile38/controller (from $GOROOT)
        /opt/go/src/_/opt/src/github.com/tidwall/tile38/controller (from $GOPATH)
```

Could you add an explanation step by step please? I'm new with go and I just want to test it.
Thanks u very much

**Comment by tidwall** [comment]
Hi @LuisUrrutia,

Sounds like there may be a problem with the test.sh script. What version of Go do you have installed? `go version`

**Comment by tidwall** [comment]
I've identified the problem and I'm working on a fix now. Thanks @LuisUrrutia!

**Comment by LuisUrrutia** [comment]
Hi again @tidwall, i tried the steps that you describe, but:
<img width="754" alt="captura de pantalla 2016-03-07 a las 4 43 06 p m" src="https://cloud.githubusercontent.com/assets/3771248/13581067/e63273d8-e483-11e5-9bb4-14906526b06e.png">

**Comment by tidwall** [comment]
I made an update earlier a few hours ago that addresses this issue. Did you pull the latest commit?

**Comment by xinuguru** [comment]
I had same trouble with @LuisUrrutia.
I added some environment variables to fix it.
I installed go with homebrew.

GOROOT=/usr/local/Cellar/go/1.6/libexec
GOPATH=~/git/tile38-1.0.4/vendor

**Comment by tidwall** [comment]
@xinuguru Thanks for info. Did you install Go specifically for Tile38, or were you using Go for other projects before?

**Comment by xinuguru** [comment]
@tidwall No. I'm not familiar with go. I never used before.

**Comment by tidwall** [comment]
Ok. Good to know. I'm on a Mac too and never used Homebrew for installing Go. I've alwayed followed the instructions on the Go website. Perhaps there's something different that happens when installing with Homebrew that I'm not aware of. Thanks.

**Comment by tidwall** [comment]
I located and fixed the problem. Thanks for notifying me of the issue @xinuguru
