### ISSUE TITLE
Separate creation/updating of objects

### ISSUE THREAD

**Issue by damariei** [tidwall/tile38#60]
Right now, the `SET` command will either create or update an existing object if it already exists.
This means you cannot reliably know which action will occur.

Potentially, this could be fixed with transactions (i.e first a `GET` to match sure it doesn't exist, then `SET`), but transactions are not allowed either...

**Comment by tidwall** [comment]
Transactions are not currently available. The only guarantee is that you can know if the SET was successful because the OK response. 

Perhaps an update to the SET command would suffice.

We can add the [NX|XX] keywords, possibly add a RETURN keyword.

```
# Set a point only if it does not already exist.
SET fleet truck NX POINT 33 -115 

# Set a point only if it already exist.
SET fleet truck XX POINT 33 -115 

# set a point and return the value that it replaced, or return null.
SET fleet truck RETURN POINT 33 -115
```
Thoughts?

**Comment by damariei** [comment]
Makes sense to me, I was originally going to suggest an `UPDATE` command, but the `NX|XX` convention is more familiar from Redis it seems.

**Comment by tidwall** [comment]
Cool. I think NX|XX is the logical path forward.
