### ISSUE TITLE
Best way to add/query timestamp?

### ISSUE THREAD

**Issue by damariei** [tidwall/tile38#61]
It seems common to add something like a "timestamp" field to objects, and then be able to query for objects within a certain time.

One could use fields but this does not seem ideal as fields are not indexed, example:
`SCAN test WHERE time 1475229282 inf+`

This would have to iterate through each object in key `test`.
The `id` of objects itself is indexed so the time could be put as the id itself, but using only globbing does not allow a range of ids.

I noticed it is possible to add a `Z` dimension to points, but how to query on this?

**Comment by tidwall** [comment]
Hi Dmitri,

You should be able to query on the Z index using WHERE like this:

```
# set point with Z
SET test obj POINT 33 -115 10
# scan on Z
SCAN test WHERE z 10 +inf
```

Tile38 is not fully optimized for three dimensional spatial indexing, so you may not see a big performance gain at this time. It's something that I've been working on, but it's taking some time to complete because it's requiring big changes to the Rtree structures.

I hope to have something in the near future. Sorry for the inconvenience.

**Comment by tidwall** [comment]
I just pushed an update that should address the performance issues with the `Z` field. Assigning a Timestamp to Z will provide very quick lookups.

**Comment by zycbobby** [comment]
Hi, I get into this issue finally and I think I am solving the same problem.

I have checked the source code  in index/rtree/rtree.go

```
func (tr *RTree) Search(minX, minY, minZ, maxX, maxY, maxZ float64, iterator func(data interface{}) bool) {
	// start := time.Now()
	// var count int
	tr.tr.Search([2]float64{minX, minY}, [2]float64{maxX, maxY}, func(data interface{}) bool {
		// count++
		return iterator(data)
	})
	// dur := time.Since(start)
	// fmt.Printf("%s %d\n", dur, count)
}
```

I think the RTree search process does not use minZ and maxZ actually, but tile38 will filter the result during the output process in controller/scanner.go

```
for _, where := range sw.wheres {
			if where.field == "z" {
				if !gotz {
					z = o.CalculatedPoint().Z
				}
				if !where.match(z) {
					return sw.fvals, false
				}
				continue
			}
			var value float64
			idx, ok := sw.fmap[where.field]
			if ok {
				if len(fields) > idx {
					value = fields[idx]
				}
			}
			if !where.match(value) {
				return sw.fvals, false
			}
		}
```

Is it better to do the z filter process in the rtree search?

**Comment by SpyridonLaz** [comment]
any progress on this ?
