### ISSUE TITLE
Memory Leak in Kafka Producer

### ISSUE THREAD

**Issue by iwpnd** [tidwall/tile38#613]
Hi 👋 

**Describe the bug**
We discovered a memory leak in Tile38 Kafka producer.

We are running Tile38 services. 

Service 1:
- 1 leader / x follower
- 600 SET/s
- approx 125.000 objects
- Followers are used to count devices in a polygon with approx 10 req/s

Service 2:
- 1 leader / x follower
- 600 SET/s
- approx 125.000 objects
- 25.000 Kafka hooks
- Followers count devices whenever a device enters/exits a hook

**Expected behavior**
The amount of objects and hooks stays the same, yet the memory usage of the service using Kafka is steadily increasing compared to the service that is not using hooks at all. While I expected memory consumption being higher on the one using Kafka, I don't expect it to grow into OOM.

**Logs**
![Screenshot 2021-06-28 at 13 27 58](https://user-images.githubusercontent.com/6152183/123630853-53199e00-d816-11eb-8a6c-2ccfba589de4.png)
I'm still using [tile38-prometheus sidecar](https://github.com/tile38/tile38-prometheus), let me know if I can provide you with additional information from there.

**Additional Information**
Since the only real difference is the use of Kafka I started to look for a reason with Sarama and found this issue [#1321](https://github.com/Shopify/sarama/issues/1321). If I understood Tile38 `SyncProducer` correctly, you expire the connection after a certain amount of time and create a new one, creating a `new sarama.NewConfig()` in the process. As it turns out this is slowly leaking memory due to `go-metrics`. 

Options seem to [be](https://github.com/Shopify/sarama/issues/1321):
1. disable metrics in the producer entirely [like so](https://github.com/Shopify/sarama/blob/65e4c5f9905926359079cd336942cf8c23fc791e/config.go#L385-L390) if they're not going to be used with Tile38 metrics anyways
2. re-use the config instead of creating a new one
3. use `defer cfg.MetricRegistry.UnregisterAll()` when the connection is closed after TTL

**Operating System (please complete the following information):**
 - OS: Linux
 - Version 1.24.3

**Comment by tidwall** [comment]
I just pushed a PR that addresses this issue.  I went with the `cfg.MetricRegistry.UnregisterAll()` option.

The sarama api feels a little convoluted and I'm honestly not sure the best approach to take. But on the surface it seems like a good idea to try and everything that is attached to the producer after its connection is closed.
