### ISSUE TITLE
Expired points are not being purged in a timely manner

### ISSUE THREAD

**Issue by Neuintown** [tidwall/tile38#616]
**Describe the bug**
Points are being added to a key with a TTL of 10 minutes. After these points have expired, they can no longer be accessed by ID and they do not appear in the results of searches such as `WITHIN`. These expired points do however appear when `SCAN`ing the key they were added to, and can be `DELETE`d by ID. They also appear to be counted when running `STATS` on their key.

**To Reproduce**
- every 5 seconds ~50 objects are added to key "a"
  - each object has a TTL of 10 minutes
  - each object contains a unique ID that is 28 alphanumeric characters long, and includes dashes (-)
  - each object contains one point and a JSON block of about 15 properties
  - new objects may replace existing objects if their IDs match, and if so the TTL of 10 minutes is refreshed
-  objects are added to Tile38 by a Java application through the Lettuce REDIS library (https://github.com/lettuce-io/lettuce-core)
```
@Command("SET ?0 ?1 EX ?3 OBJECT ?2")
String set(String key, String id, String geoJson, long expirySeconds);
```

**Expected behavior**
Points are purged upon expiry and and no longer appear when running `SCAN`. They no longer contribute to in-memory size.

**Logs**
Nothing noteworthy in the standard logs, just the periodic `AOFSHRINK`.

**Operating System (please complete the following information):**
 - OS: Linux 3.10.0-1062.el7.x86_64 \# 1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 GNU/Linux
 - Version: Docker Hub tile38/tile38:1.12.1 and 1.24.3

**Additional context**
There are several other processes contacting the Tile38 container periodically:
- every 5 minutes, `AOFSHRINK` is run
- every 5 seconds 0-400 GeoJSON objects (arrays of points) are added to a separate key "b" with a TTL of several hours
- objects are periodically removed from "b" and given their own unique key containing the associated object from key "b"
  - the TTL of the object in these keys is the remaining TTL from when they were in key "b"
  - these unique keys are left to expire, and they do appear to be getting purged correctly
- every 5 seconds over 10k points with a 2 hour TTL are added to a separate key "c", the majority replace existing points
- points are periodically removed from "c", typically before they have a chance to expire

**Comment by tidwall** [comment]
I was able to reproduce the problem.

Here's a test program that show the issue in action:

```
https://gist.github.com/tidwall/b0d87956d8488a0b0e902f367babc439
```

**Comment by tidwall** [comment]
I just pushed a fix.

**Comment by Neuintown** [comment]
The fix is working great, thanks for getting this done so quickly!

**Comment by tidwall** [comment]
No problem. Thanks for reporting the issue!
