### ISSUE TITLE
Potential Replace Bug Corrupting the Index

### ISSUE THREAD

**Issue by umpc** [tidwall/tile38#62]
This may be out of the scope of tile38, but I wanted to at least mention it here for the author or incase someone else runs into this:

I've often noticed that when replacing previously inserted Feature objects, they disappear from the index, or corrupt the index entirely, but the item (id and obj), replaces correctly with the new value each time. This never happens with a small dataset. The dataset where I've noticed it to occur has around 1,025,000 points, spanning the globe.

This means that a replaced obj can be accessed using the appropriate id, but cannot be queried for using Nearby.

Also strange: The index corruption appears to occur predictably when the collection is written to 'too quickly.' That's just my immediate assessment from what I have observed.

```
package main

import (
    "fmt"
    "encoding/json"
    "strconv"
    "time"
    "math/rand"

    "github.com/tidwall/tile38/controller/collection"
    "github.com/tidwall/tile38/geojson"
)

func main() {
    geoindex := collection.New()

    for i := 0; i < 3; i++ {

        for lng := float64(-180); lng < 180; lng += 0.25 {
            for lat := float64(-90); lat < 90; lat += 0.25 {

                objBytes, _ := json.Marshal(map[string]interface{}{
                    "type": "Feature",
                    "geometry": map[string]interface{}{
                        "type": "Point",
                        "coordinates": []interface{}{lng,lat},
                    },
                    "properties": map[string]interface{}{
                        "randomNumber": rand.New(rand.NewSource(time.Now().UnixNano())).Float64(),
                    },
                })
                obj, _ := geojson.ObjectAuto(objBytes)

                id := strconv.FormatFloat(lng, 'f', -1, 64) + strconv.FormatFloat(lat, 'f', -1, 64)

                // Simulate problem on a small scale by calling insert twice, which writes too quickly.
                geoindex.ReplaceOrInsert(id, obj, nil, nil)

                objBytes2, _ := json.Marshal(map[string]interface{}{
                    "type": "Feature",
                    "geometry": map[string]interface{}{
                        "type": "Point",
                        "coordinates": []interface{}{lng,lat},
                    },
                    "properties": map[string]interface{}{
                        "randomNumber": rand.New(rand.NewSource(time.Now().UnixNano())).Float64(),
                    },
                })

                obj2, _ := geojson.ObjectAuto(objBytes2)
                geoindex.ReplaceOrInsert(id, obj2, nil, nil)
            }
            
        }
    
        // Shows that obj exists under its id. obj gets updated correctly, each time.
        obj, _, _ := geoindex.Get("-6115.25")
        fmt.Printf("Get %v: %v\n", i, obj)

        // But obj cannot be found using the index after the first insert iteration.
        geoindex.Nearby(0, 0, 15.335, -61.0043, 80467.2,
            func(_ string, obj geojson.Object, _ []float64) bool {
                fmt.Printf("Nearby %v: %v\n", i, obj)
                return true
            },
        )
    }
}
```

I wanted to ask here first, before looking into this possibly later this week. I'll update this if I figure out what's going on here. Maybe this is an obvious mistake to someone else, but I'm not sure how it would be.

**Comment by tidwall** [comment]
@umpc Thanks for reporting this. 

I can confirm the issue on my side.  I'll need to investigate further and I'll keep you posted.

**Comment by tidwall** [comment]
@umpc I just pushed an update to master that corrects this problem on my side. Please let me know if this works for you.

**Comment by umpc** [comment]
@tidwall The update fixed the issue. 👍 

I tested the index in the project where I discovered it and it worked there as well.

Thank you for your swift responses and for the fix!

**Comment by tidwall** [comment]
You're welcome and thank you for the thorough bug report.
