### ISSUE TITLE
z coordinate disfunct for object parameter

### ISSUE THREAD

**Issue by tomquas** [tidwall/tile38#622]
**Describe the bug**
follow instructions at https://tile38.com/commands/set#z-coordinate
while replacing 'nearby 1' with 'nearby fleet'

while set..point seems to initialize the z coordinate and nearby will find it,
set..object will be not be found the nearby command

**To Reproduce**
see above

**Expected behavior**
tile38 should initialize the z coordinate field from geojson points; not sure how to solve this for polygons though

**Operating System (please complete the following information):**
 - OS: Linux / Mac OS
 - Version 1.25.2

**Comment by tidwall** [comment]
> tile38 should initialize the z coordinate field from geojson points

It seems to be working for me. For example, `SET fleet truck1 POINT 10 15 30` followed by `GET fleet truck1` returns:

```
{"type":"Point","coordinates":[15,10,30]}
```

**Comment by tomquas** [comment]
```
127.0.0.1:9851> drop fleet
{"ok":true,"elapsed":"21.7µs"}
127.0.0.1:9851> SET fleet truck1 POINT 33.5123 -112.2693 115
{"ok":true,"elapsed":"82µs"}
127.0.0.1:9851> NEARBY fleet WHERE z -15 130 POINT 33 -115 1000000
{"ok":true,"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123,115]}}],"count":1,"cursor":0,"elapsed":"54.5µs"}

# so far so good; now for the issue:

127.0.0.1:9851> drop fleet
{"ok":true,"elapsed":"28.9µs"}
127.0.0.1:9851> {et truck1 OBJECT {"type":"Point","coordinates":[33.5123,-112.2693,115]}
{"ok":true,"elapsed":"96.9µs"}
127.0.0.1:9851> NEARBY fleet WHERE z -15 130 POINT 33 -115 1000000
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"29.7µs"}
```

i'd expect the second NEARBY to give the same result as the first one. am i wrong?

**Comment by tidwall** [comment]
The issue appears to be that the the GeoJSON coordinates in your example are inverted.

GeoJSON coordinate ordering must be `[x,y,(z)]`, where x is longitude and y is latitude.

Try `{"type":"Point","coordinates":[-112.2693,33.5123,115]}`.

**Comment by tomquas** [comment]
thank you, that was my fault.
i will submit a PR to the docs project so others may not fall into the same trap.
closed.

**Comment by tomquas** [comment]
hi @tidwall, sorry to bother again, but i came across another curiosity with z-coordinates: when giving different z ranges, results may be missing.

a nearby query with z=0 always succeeds, whereas any other starting value for z returns an empty result.

version: Tile38 1.25.4 (b3c036ac) 64 bit (amd64/linux) / docker image: tile38/tile38:latest

```
$ tile38-cli  "NEARBY" "u" "LIMIT" "2" "WHERE" "z" "0" "1651713886" "NOFIELDS" "OBJECTS" "POINT" "48.13743" "11.57549"
{"ok":true,"objects":[
  {"id":"ejeVqre","object":{"type":"Feature","geometry":{"type":"Point","coordinates":[11.57,48.14,1631717260]}}},
  {"id":"YqVMOkj","object":{"type":"Feature","geometry":{"type":"Point","coordinates":[11.569,48.15,1631717260]}}}],
  "count":2,"cursor":2,"elapsed":"75.9µs"}
$ tile38-cli  "NEARBY" "u" "LIMIT" "2" "WHERE" "z" "120" "1651713886" "NOFIELDS" "OBJECTS" "POINT" "48.13743" "11.57549"
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"120.8µs"}
```

**Comment by tidwall** [comment]
I found the problem. Tile38 was only extracting the Z coordinates from a Point, not a Feature/Point. 

I just pushed the fix. Thanks :)
