### ISSUE TITLE
Clear command in the tile38-cli

### ISSUE THREAD

**Issue by CaioDallaqua** [tidwall/tile38#633]
**Is your feature request related to a problem? Please describe.**
Although not strictly necessary, it would be nice if the tile38-cli had a "clear" command to clean up the console.

![tile38-print](https://user-images.githubusercontent.com/25767779/150695565-6f43f479-83ac-49e1-82f9-2a8e8c75297b.png)

This could improve user's experience of using the cli specially when the database is already populated.

**Describe the solution you'd like**
Something like the "clear" command in the redis-cli.

**Comment by iwpnd** [comment]
Hi @CaioDallaqua, you can use `CTRL+L` to clear your terminal output on unix systems. Not sure about the windows alternative.
