### ISSUE TITLE
The FOLLOW command does not allow passing the auth of the follower

### ISSUE THREAD

**Issue by rave-eserating** [tidwall/tile38#641]
**Describe the bug**
The FOLLOWER command does not allow specifying the leader's auth password, resulting in failure when attempting to follow via the command. This is problematic when the leader is password protected and we want to turn a previous leader into a follower via a script on startup when we say want to check with Redis Sentinel first to determine the leader after a failure.

This is you command definition which shows no argument for leaderauth
`"FOLLOW": {
    "summary": "Follows a leader host",
    "complexity": "O(1)",
    "arguments": [
      {
        "name": "host",
        "type": "string"
      },
      {
        "name": "port",
        "type": "integer"
      }
    ],
    "since": "1.0.0",
    "group": "replication"
  },`

Would be great if you could fix this ASAP as we are standing up a Tile38 Cluster using Sentinel for failover.

**Comment by rave-eserating** [comment]
Apparently you can preset the leaderauth in the leader's config file and it will be used when a FOLLOW command is executed. However it would be good to also to be able to create a follower via a script including specifying the leaderauth

**Comment by iwpnd** [comment]
Use `CONFIG SET leaderauth your-password` prior to `FOLLOW`

**Comment by rave-eserating** [comment]
Thanks @iwpnd , we can close this bug then, however I do suggest the FOLLOW documentation adds this information so that others don't have to figure out how to do it. @tidwall

**Comment by iwpnd** [comment]
Feel free to open a Pr in the [docs](https://github.com/tile38/tile38.github.io).
