### ISSUE TITLE
Expose config and INFO response for slave_priority which is used by Redis Sentinel

### ISSUE THREAD

**Issue by rave-eserating** [tidwall/tile38#642]
We are trying to set-up Redis Sentinel to handle monitoring and automated promotion of a Tile38 "cluster".
We need to be able to prioritize or inhibit a slave from ever becoming elected to leader.
Redis Sentinel has this functionality available. 
A slave can use the config property named 'replica-priority' to set the priority of the slave which is by default set at a priority of 100.
When Sentinel calls INFO on the Redis slave it will return the following: 'slave_priority: 100' or whatever value the slave was set to.

We can set the value to zero which tells Sentinel to never promote the slave. We need to do this to tell a Tile38 follower in another datacenter to not be elected as leader by Sentinel or to at least prioritize it so it is the absolute last choice.

Unfortunately Tile38 has no way to configure this or send back the slave_priority value when INFO is called.

**Describe the solution you'd like**
Add a config option to allow setting the slave priority (follower priority) and expose the value in the INFO response using the property 'slave_priority'

I actually need this functionality sooner than later. I will look in the Tile38 code to see if I can figure out what needs to be added to be able to possibly create a PR.

**Comment by iwpnd** [comment]
Sounds very straightforward to add. I would be happy to contribute if @tidwall wants to see it in v1 still.

**Comment by rave-eserating** [comment]
We actually need this functionality to get our Tile38 cluster to production by the end of August, so anything we can do to move it forward would be great, otherwise I'm going to be forced to create our own forked Tile38 version.

**Comment by iwpnd** [comment]
That sounds like this is your issue.

**Comment by rave-eserating** [comment]
@iwpnd , I'm sorry what do you mean by your last comment? I was simply eluding to the fact that we need this functionality sooner than later and I would prefer it was in an official release. I'm happy to do the work myself and create a pr but I do not know what the release cadence is for Tile38 and if it will be possible to get this fix in within our timeframes. @tidwall perhaps you can answer that.

**Comment by iwpnd** [comment]
> I'm sorry what do you mean by your last comment?

You last comment sounded like a demand, rather than a request in an open source project. If I do you wrong in that regard, I'm sorry.

Tile38 has a `tile38/tile38:edge` and `tile38/tile38:latest` [image](https://hub.docker.com/r/tile38/tile38/tags) that follows `master`. So if you get your PR merged, it is usable independent of the release. 😃

**Comment by tidwall** [comment]
Hi @rave-eserating, 

The change seems pretty straightforward, and I can see others making use of it too.

> I will look in the Tile38 code to see if I can figure out what needs to be added to be able to possibly create a PR.

I recommend starting here:

The file that maintains the server config: https://github.com/tidwall/tile38/blob/master/internal/server/config.go
The function that serves the INFO command: https://github.com/tidwall/tile38/blob/master/internal/server/stats.go#L431

**Comment by rave-eserating** [comment]
@tidwall @iwpnd see https://github.com/tidwall/tile38/pull/643 when you have time to review
