### ISSUE TITLE
is there any way to get the ids only, I mean not return the objects,  when I use intersects or within command 

### ISSUE THREAD

**Issue by whcself** [tidwall/tile38#646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by whcself** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/32793449/181907686-d09f5fc2-8dbd-402a-ade3-f4e97b986f59.png">
just like remove the object part

**Comment by srimaln91** [comment]
It is possible to change the output format. Just set it as `IDS` so it will only return object IDs. You can refer to the documentation below.

https://tile38.com/commands/intersects#output-formats

**Comment by whcself** [comment]
> 

thanks a lot, it worked. I have read this documentation before, but I just did not  get it.

**Comment by whcself** [comment]
> It is possible to change the output format. Just set it as `IDS` so it will only return object IDs. You can refer to the documentation below.
> 
> https://tile38.com/commands/intersects#output-formats

thanks a lot, it worked. I have read this documentation before, but I just did not get it.
