### ISSUE TITLE
Is there a way to load data faster?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#65]
Hi tidwall

I'm thinking about whether there is a quick way to load data.

For an AOF file that executed the shrink command, if you can split the AOF file in logic and load data in parallel with multiple threads, then the speed at which the service is started is faster.

How do you think about it?

**Comment by tidwall** [comment]
I'm not sure if this is possible because the commands in the AOF are stored in order of execution. So they must be played back in exact order for the server to guarantee that it's in an identical state from when the server was shut down.

**Comment by tidwall** [comment]
The latest push to master should speed up loading by about 10%.

**Comment by tidwall** [comment]
I'm closing this issue for now. If you have further questions or thoughts, please feel free to reopen this issue.

We'll continue to investigate further ways to increase performance around data loading.
