### ISSUE TITLE
INTERSECTS does not respond correctly with geometry with an inner ring

### ISSUE THREAD

**Issue by mblackgeo** [tidwall/tile38#664]
**Describe the bug**
Technically a duplicate of #241, but I am still seeing incorrect behavior when running INTERSECTS using a geometry with an inner ring. Consider this example below, where the lines 1,2,3,4 are stored in Tile38 and the query is being run using the green polygon:

![image](https://user-images.githubusercontent.com/18327836/201316141-13e1a697-58b2-4a89-bc9b-0ecdc5e219a4.png)

INTERSECTS matches lines 1, 2, 3, and 4. This is incorrect as line 2 does not intersect. For reference WITHIN only returns line 4, as expected.

**To Reproduce**

* Insert the [lines GeoJSON](https://gist.github.com/mblackgeo/865866ef3c096b60c931b13a33d11214) into Tile38
* Query using the [GeoJSON of the green polygon with an inner ring](https://gist.github.com/mblackgeo/6829b70e757e9de56969e09cd9edf0cc).

**Expected behavior**
Expected that INTERSECTS would only return 1,3,4 in the result.

**Operating System:**
 - OS: Linux
 - CPU: Intel
 - Version: 1.29.1
 - Container: Docker

**Additional context**
Originally raised in #241.

**Comment by iwpnd** [comment]
Hey @mblackgeo 

You are correct. It appears to only check an [intersection with the polygon exterior ring as linestring](https://github.com/tidwall/geojson/blob/b8728ac7d3e1540ffd7a46e056b9f0fc6133bc24/geometry/poly.go#L147) in those cases.

**Comment by tidwall** [comment]
@mblackgeo I pushed a hot fix moments ago. Thanks for reporting.
@iwpnd Thanks for finding the where it's happening.

**Comment by iwpnd** [comment]
🫡

**Comment by tidwall** [comment]
ref: https://github.com/tidwall/geojson/commit/675497e5d23269efaf57b99af9fb73820ed653d4

**Comment by tidwall** [comment]
ref: https://github.com/tidwall/geojson/commit/5d24577b460ba679e824173af4a5ae9ac6419155

**Comment by mblackgeo** [comment]
Thanks for fixing and releasing this so quickly :100: !
