### ISSUE TITLE
Missing "fields" in version 1.30.2

### ISSUE THREAD

**Issue by DucPhan2997** [tidwall/tile38#668]
**Describe the bug**
Missing fields when using JSET to update 

**To Reproduce**
1. _SET sup-gojek test POINT  106.66329051644803 10.769453594179312_
2. _JSET sup-gojek test info dpv_
3. _FSET sup-gojek test info-field 1_
4. _GET sup-gojek test withfields_ -> `{"ok":true,"object":{"type":"Point","coordinates":[10.769453594179312,106.66329051644803],"info":"dpv"},"fields":{"info-field":1},"elapsed":"15.554µs"}`
5. _JSET sup-gojek test info dpvUpdated_
6. _GET sup-gojek test withfields_ -> `{"ok":true,"object":{"type":"Point","coordinates":[10.769453594179312,106.66329051644803],"info":"dpvUpdated"},"elapsed":"15.554µs"}` **Missing fields**

**Expected behavior**
Same the old version (1.29.2), the fields should be returned

**Logs**
Version 1.30.2
![Version 1.30.2](https://user-images.githubusercontent.com/102129426/209794052-2de6f6ca-8c1d-4534-ba3f-55c90530ac1a.png)

Version 1.29.2
![Version 1.29.2](https://user-images.githubusercontent.com/102129426/209794179-14e5940f-c21a-4dff-b853-758ddc7a5cbf.png)

**Operating System (please complete the following information):**
 - OS: Linux
 - CPU: amd64
 - Version: 1.30.2
 - Container: Docker

**Additional context**

**Comment by tidwall** [comment]
Thanks a ton for reporting! 
I pushed a new release that fixes this issue :)
