### ISSUE TITLE
outdated replace usage in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [tidwall/tile38#671]
There is a replace line in go.mod pinning `golang.org/x/text` to `v0.3.7`. However, according to [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059), version of `golang.org/x/text` before `v0.3.8` suffers potential vulnerability. Should it be updated? <br>
<https://github.com/tidwall/tile38/blob/master/go.mod#L118>
```txt
golang.org/x/text => golang.org/x/text v0.3.7
```
Or you may update some direct dependency, say `github.com/xdg/scram`. It will indirectly update the version of `golang.org/x/text` and then the above replace line can be dropped.
```txt
$ go mod why -m golang.org/x/text
# golang.org/x/text
github.com/tidwall/tile38/internal/endpoint
github.com/xdg/scram
github.com/xdg/stringprep
golang.org/x/text/unicode/norm
```
Tips: `github.com/xdg/scram` seems to have been renamed to [`xdg-go/scram`](https://github.com/xdg/scram/blob/master/README.md).

**Comment by tidwall** [comment]
These changes will make it to the next version. Thanks!
