### ISSUE TITLE
No support for batched/bulk calls to tile38 with java-client 

### ISSUE THREAD

**Issue by Mukund2900** [tidwall/tile38#675]
[Pull  #Request](https://github.com/HkMoyun/tile38-client/pull/3)

This is a pull request I have created to support this feature. 
Pretty sure making thousands of request every second is going to be a common use case which people are going to have, just like me. 
I see no support for that in java-clients unlike node where it is much easy to batch the requests.

Also another issue with java client is the maven provided is not supported because it seems to be uploaded to a private repository. 
I have released a version for same which you can refer in my fork. 

Open to suggestions and discussion regarding the same.

**Comment by iwpnd** [comment]
Hi 👋  The java client is not maintained by tile38
