### ISSUE TITLE
Get hooks for a key of moving points to that of a key of Geofences

### ISSUE THREAD

**Issue by Mukund2900** [tidwall/tile38#676]
Is there a way to set hook in tile38 such that it detects movement of members in or out of the geofence. 

`SETHOOK myhook http://10.0.1.5/hook INTERSECTS people FENCE geodata`

Is there a way to define something like this?
Instead of defining hooks on each geofence can we define it on the whole key, like we do it for nearby, so it tells me when members of people key entered any of the geofence in key geodata

**Comment by Mukund2900** [comment]
I have around 5 million geofences so that's why I want to create hooks over keys instead of each fence.

**Comment by iwpnd** [comment]
No you cannot. Each of your 5 million geofences has to have it's own hook right now. Integrate the `SETHOOK/DELHOOK` command in the lifecycle of your geofence, and you're good. Every `SET` of your hook will also create a hook, every `DEL` will delete it along with the geometry.

**Comment by iwpnd** [comment]
> Is there a way to cluster tile38 ? Or scale it horizontally ?
see [replication](https://tile38.com/topics/replication), however that does only work for read actions. 

if you want to scale tile38 leader horizontally, you'll have to take care of how you spatially shard each leader. say leader1 = europe, leader2 = north america.. etcpp you get the idea.

**Comment by Mukund2900** [comment]
Sure got it
Had one more question, does the hook logic applies to Channel as well? We need to create 50million channels to support it?
