### ISSUE TITLE
What is the performance/complexity when we add MATCH and WHERE to a command

### ISSUE THREAD

**Issue by Mukund2900** [tidwall/tile38#677]
Unable to find anywhere in the docs the complexity for MATCH and WHERE commands when added on top of NEARBY/INTERSECT.

I am using it with hooks and I want to understand which one performs better, because I have option to use both. 

I have a key called person. 

`SET person alice FIELD name alice POINT 25.42513145100104 75.63783657767418`

Now while setting hook which one of the following will give better performance -> 

1. `SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS person MATCH alice MATCH bob FENCE DETECT enter,exit GET area test`

2. `SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS person WHERE name 2 alice bobFENCE DETECT enter,exit GET area test`

Also is there any performance benefit of referring the geofence as `GET area test ` v/s defining it directly like -> 

`SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS person WHERE name 2 alice bobFENCE DETECT enter,exit OBJECT {"type":"Polygon","coordinates":[[[75.63783657767418,25.43318147102104],[75.6392084514683,25.43305944145809],........[75.63783657767418,25.43318147102104]]]}`

Which one is a better approach in terms of performance.

**Comment by tidwall** [comment]
MATCH and WHERE add some complexity to a query. Both are linear, and are performed on each potential record. MATCH is probably a little faster than WHERE because it directly performs a comparison operation on the ID, while the WHERE needs to dig into the object fields. Both should be pretty fast in most cases, yet workflows vary so I recommend testing on your side to see which is best of you.

> Also is there any performance benefit of referring the geofence as `GET area test`  v/s defining it directly

No, both will perform the same.

**Comment by Mukund2900** [comment]
@tidwall just had one more question regarding this. Please refer to the following query -> 

`SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS person WHERE name 2 alice bob FENCE DETECT enter,exit OBJECT {"type":"Polygon","coordinates":[[[75.63783657767418,25.43318147102104],[75.6392084514683,25.43305944145809],........[75.63783657767418,25.43318147102104]]]}`

`SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS person WHERE name 2 rob lob FENCE DETECT enter,exit OBJECT {"type":"Polygon","coordinates":[[[75.63783657767418,25.43318147102104],[75.6392084514683,25.43305944145809],........[75.63783657767418,25.43318147102104]]]}`

as you can see the geofence is same in both the case. Does it internally treat it as 2 geofences? Or it keeps the hook on the same geofence? 
If it does not treat it as same geofence i think creating a geofence first and then defining the hooks makes more sense.

**Comment by iwpnd** [comment]
it'll be treated as two geofences and if a devices enters the polygon it'll send two events to kafka
