### ISSUE TITLE
multipolygon support

### ISSUE THREAD

**Issue by uwer** [tidwall/tile38#678]
I think this may have been raised some years ago,
it appears that for type object/geojson under FENCE only simple polygons are allowed, is there a plan to include multipolygons ? i.e. a doughnut?
Cheers

**Comment by iwpnd** [comment]
i am fairly certain that this has been addressed previously in #664. the issue was with one of Tile38 upstream packages.

can you share an example that does not work for you?

**Comment by uwer** [comment]
Thanks Ben,

You are right, looking at your example i can see how it can work.
I used a multipart geometry, changing it to a singlepart did the trick and i was able to add it.
I have to run a few more tests to be sure that it does what i need it to do.

Thank you for your quick reply, great piece of work!
Thanks
Uwe

**Comment by uwer** [comment]
found a work around with existing setup
