### ISSUE TITLE
Issue with intersect when defining detect exit/enter

### ISSUE THREAD

**Issue by Mukund2900** [tidwall/tile38#679]
In the documentation there is this example 
```
$ tile38-cli
localhost:9851> SETCHAN warehouse INTERSECTS fleet WHERE speed 50 +inf FENCE DETECT outside,inside POINT 33.462 -112.268 6000
{"ok":true,"elapsed":"12.988µs"}
```

This does not work, only nearby works. On local we get this error -> 
```
127.0.0.1:9851>  SETCHAN warehouse INTERSECTS fleet WHERE speed 50 +inf FENCE DETECT outside,inside POINT 33.462 -112.268 6000
(error) invalid number of arguments
127.0.0.1:9851> 
```

**Comment by iwpnd** [comment]
if thats in the documentation than its wrong, i believe what you wanna do is use `CIRCLE 1 1 1000`

**Comment by Mukund2900** [comment]
Yeah. I thought #649  this never got merged.

**Comment by Mukund2900** [comment]
@tidwall @iwpnd 
Is there a way to get the commands as well with hooks response? 
`SETHOOK test kafka://127.0.0.1:9092/bbb INTERSECTS vehicles WHERE BUID 1 qaTest WHERE timestamp 1000 1130 FENCE DETECT enter,exit GET area test`

The response is not sending the commands. Basically i want to get this in the response `WHERE timestamp 1000 1130 `
but not getting all the specified commands. 
The reason for this is i need to validate the exit condition. It can happen that the vehicle is inside the geofence but time has passed and now an exit event has triggered. I want to identify this. 
We have a solution for this?
