### ISSUE TITLE
Support the `ROLE` command so that Redis.Sentinel is fully supported. 

### ISSUE THREAD

**Issue by Kilowhisky** [tidwall/tile38#686]
**Is your feature request related to a problem? Please describe.**
Redis Sentinel is a popular way to handle high availability with Redis. It also happens to work with Tile38 except when the Redis client doesn't support the fallback to the `INFO replication` command. This is the case for the `StackExchange.Redis` (C#) a Redis client, Unfortunately this client is the defacto standard client for C# based applications. 

Fortunately the `ROLE` command is a very small command that outputs the same information that `INFO replication` does. 

See bug with StackExchange.Redis. https://github.com/StackExchange/StackExchange.Redis/issues/2461 

**Describe the solution you'd like**
I would like Tile38 to support the `ROLE` command. 

**Describe alternatives you've considered**
I've tried to get the other repo to support the fallback command, but considering the changeover happened LONG ago in the Redis command list they see supporting it as unlikely.

**Comment by tidwall** [comment]
I have no problem adding the `ROLE` command. The output looks cleaner that what `INFO replication` provides so I can see when StackExchange.Redis chose to use it.

**Comment by tidwall** [comment]
The ROLE command has been added to Tile38. It present the basic information that 'INFO replication' would otherwise provide in the format [shown here](https://redis.io/commands/role/).

**Comment by Kilowhisky** [comment]
Works!

**Comment by iwpnd** [comment]
@Kilowhisky can you share how you setup Tile38 with sentinel?

**Comment by Kilowhisky** [comment]
@iwpnd I'll post it up once i get it stable. I keep having random problems where the failover causes the AOF to get corrupted or straight up crashes the followers.

**Comment by samar-sajnani** [comment]
@Kilowhisky did you ever get it stable, I'm seeing issues where tile38 keeps showing redis-sentine going from live to not live and causing issues with RESP initial AOF bulk replication. I also had issues with followers crashing.
