### ISSUE TITLE
Search within MultiPolygon

### ISSUE THREAD

**Issue by LuisUrrutia** [tidwall/tile38#7]
I have GEOJSON objects, in this format:

`{"type":"MultiPolygon","coordinates":[[[[-69.47657387098774,-20.577241016355124],[-69.47743687205649,-20.730774540841214],[-69.47073936300552,-20.729771961542188],[-69.46597958706174,-20.72983009675763],[-69.45877723512393,-20.730084380669112],[-69.44686656121634,-20.730974121623348],[-69.43723371262506,-20.73045672747964],[-69.42880075385169,-20.731381525443332],[-69.41873262589603,-20.731487645905986],[-69.40542652633845,-20.731835767898335],[-69.39577493752837,-20.73263531750617],[-69.38372958341907,-20.730241017367664],[-69.36200202890991,-20.71836987920766],[-69.35253550207952,-20.714973987675318],[-69.33589939397065,-20.71372416190152],[-69.3306638946128,-20.713029501441095],[-69.3191057828514,-20.706789468081535],[-69.31293032540394,-20.70372860854936],[-69.30836410831125,-20.7031495131714],[-69.29004944359707,-20.700036843688718],[-69.27794024100051,-20.696557660221398],[-69.27767269653012,-20.696793024726926],[-69.27732856059063,-20.696990109602993],[-69.27692694816037,-20.697099186283605],[-69.27650612989353,-20.69720829285809],[-69.27612342146159,-20.697317337332464],[-69.2757982302911,-20.697372073560402],[-69.27547277143243,-20.697444881381966],[-69.27509039024032,-20.697569735853595], ...`

I want to know if i can search within this MultiPolygon and what data can i store in (or with) a MultiPolygon. If it can't be done will be a nice feature.

**Comment by tidwall** [comment]
Yes. You can search within a MultiPolygon. Tile38 is designed to support all objects regardless of their complexity or type.

**Comment by LuisUrrutia** [comment]
The syntax will be something like:
`WITHIN key OBJECT (MultiPolygon)`
right?

And if i want to store more data with a MultiPolygon I have to do this:
`SET cities Santiago FIELD code 1 FIELD region Metropolitana OBJECT (geojson)`

But what about if i want to search all the point within the MultiPolygon Santiago in cities key?

**Comment by tidwall** [comment]
Correct, `WITHIN key OBJECT (MultiPolygon)` will search for all objects belonging to `key` that are fully contained with the `MultiPolygon` object.

And right, using the `FIELD` keyword will allow for meta data.

I hope that I understand what you are trying to do. Perhaps you are looking for something like:

```WITHIN key GET cities Santiago```

This will search for everything inside of `key` that is fully contained within the object id Santiago. Using the `GET` keyword get the search to target an object that already exists.

I'm sorry that the documentation for Tile38 is lacking. It's still a work in progress.

Please let me know if this helps or not.

**Comment by LuisUrrutia** [comment]
Yeah! That's what I'm looking for. Don't worry about the doc, i know that is a really new project (or at least a new project for the community) and btw is a really good project, my partners and i are playing with this since a9bbecb969f415435444bc7f54ea3fbe2a91560d and it's awesome!

**Comment by tidwall** [comment]
Great to hear! Thanks so much for your feedback.
