### ISSUE TITLE
PING when loading data has a different behavior on tile38 vs redis

### ISSUE THREAD

**Issue by Kilowhisky** [tidwall/tile38#700]
In standard Redis. If data is being loaded the `PING` command returns the standard "LOADING ..." message. 

In tile38 it just returns PONG. 

I can make a PR to adjust this behavior but i'm not entirely sure of the implications.

**Comment by tidwall** [comment]
After some thought, I'm not sure this change is needed. Since PING is a client only command, I would think it natural that a PING returns a PONG just as long a client can connect. And I worry that changing this may have adverse side-effects for exiting users that expect the existing behavior.

**Comment by Kilowhisky** [comment]
I agree, The main reason for bringing it up is that helm charts like this one i'm trying to use for deployment: https://github.com/bitnami/charts/tree/main/bitnami/redis uses `PING` as its `READINESS` command. A simple script override changes it to `HEALTHZ`. 

Closing...
