### ISSUE TITLE
Panic in tile38 causing server crash due to bug in geojson

### ISSUE THREAD

**Issue by prathik** [tidwall/tile38#714]
**Describe the bug**
If we put a geojson with some polygons having z coordinates and others not having them, then the way geojson currently handles it would head to a panic and the server crash.

Here is the related PR on geojson that would fix the panic (but not the issue)
https://github.com/tidwall/geojson/pull/26

**To Reproduce**

Run the following commands

`> set abc test object {"type":"Polygon","coordinates":[[[0,0],[10,0],[0,10],[0,0]],[[0,0,0],[0,10,0],[10,0,0],[0,0,0]]]}`

`> get abc test`

This leads to tile38-server crashing.

**Expected behavior**

Tile38 should respond with 

```{"ok":true,"object":{"type":"Polygon","coordinates":[[[0,0],[10,0],[0,10],[0,0]],[[0,0,0],[0,10,0],[10,0,0],[0,0,0]]]},"elapsed":"17.224µs"}```

**Logs**

```
panic: runtime error: index out of range [4] with length 4

goroutine 40 [running]:
github.com/tidwall/geojson.appendJSONPoint({0xc000044300?, 0xc000406670?, 0x
105378f?}, {0x30?, 0x0?}, 0xc000002750, 0x4)
        github.com/tidwall/geojson@v1.4.3/object.go:261 +0x168
github.com/tidwall/geojson.appendJSONSeries({0xc000044300?, 0x1?, 0xc0004066
c8?}, {0x217c6d0, 0xc0000cccd0}, 0x2f01878?, 0x4)
        github.com/tidwall/geojson@v1.4.3/object.go:293 +0xe5
github.com/tidwall/geojson.(*Polygon).AppendJSON(0xc000002780, {0x0?, 0x0?,
0x4?})
        github.com/tidwall/geojson@v1.4.3/polygon.go:48 +0x1b9
github.com/tidwall/tile38/internal/server.(*Server).cmdGET(0xc000004300, 0xc
0003140a0)
```

**Operating System (please complete the following information):**
 - OS: MacOS
 - CPU: amd64
 - Version: 1.19.0
 - Container: None

**Additional context**
Draft creating the panic in geojson https://github.com/tidwall/geojson/pull/26

**Comment by tidwall** [comment]
That geometry is invalid. All points in a geometry should have the same number of coordinates.

I pushed a fix to the master branch which will return "invalid coordinates" when trying to SET the geometry

**Comment by prathik** [comment]
@tidwall - thanks! according to geojson spec it's a valid one though (validated with various linters). However, this fix works as well, I'd recommend responding with "invalid coordinates must provide z coordinate for all polygons" or something as such.
