### ISSUE TITLE
FSET does not have a FGET counterpoint

### ISSUE THREAD

**Issue by Kilowhisky** [tidwall/tile38#723]
Its not possible to recover just a field value for a key / id. Meanwhile there is a function that works that way for JSON `JGET`. 

I have found a need for this from time to time, especially when objects contain lots of fields and performance is important.

I can make a PR for this.

**Comment by tidwall** [comment]
I would accept a PR. Are you thinking the command would be like this?

```
FGET key id
```

**Comment by Kilowhisky** [comment]
FGET key id field

Yea. Something like that.
