### ISSUE TITLE
AOFSHRINK

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#73]
hi, tidwall,
In production environment is to use real-time data, update the KEY value of TILE38 system, build AOF large file size, how to clear the AOF file?
Only restart TILE38?

Thanks.

**Comment by huangpeizhi** [comment]
Sometimes, after using the aofshrink command, tile38 failed to start.

![n8df24a9z](https://cloud.githubusercontent.com/assets/19602075/19676964/b7b74022-9ac9-11e6-8f88-c1d775b384f2.png)

**Comment by huangpeizhi** [comment]
The production environment cannot clean the AOF file, this is a real problem.

**Comment by tidwall** [comment]
It would be helpful to compare the AOF before and after of the AOFSHRINK. Is this something that you could share? Maybe in a private email?

**Comment by huangpeizhi** [comment]
tidwall,

thank you for your answer!  i suggest two methods，
- one is AOFCLOSE false|true （default is false）,  can let users decide which action is need to record or distribute， What can be discarded.
- the second is to provide AOFSIZE nmb|ngb, configure an AOF file maximum size.

i tried more than once to execute the AOFSHRINK command and send the results to your email.
thank you for the TILE38 system!

**Comment by huangpeizhi** [comment]
hi, tidwall

I find that I use the LINUX version too low will cause the AOFSHRINK commands to handle the exception。

![1z098el](https://cloud.githubusercontent.com/assets/19602075/19712299/42b2e71c-9b6f-11e6-9b7d-9732bddb9054.png)

**Comment by tidwall** [comment]
Hi huangpeizh1,

Thanks for the suggestions. I'll probably add the ability for AOFSHINK to occur automatically in the background in a future release. I'll keep you posted.

**Comment by huangpeizhi** [comment]
Hi, @tidwall 

Because now I'm using TILE38 as fences in and out of the service, this application is run, so I'd like to know, AOFSHRINK not realize cases, is there any reliable way to clear the AOF log.

thanks!

**Comment by tidwall** [comment]
Hi @huangpeizhi 

I'm looking into this issue today and I'll keep you posted.

**Comment by tidwall** [comment]
I pushed an update to the master branch that addresses this issue. Corruption should no longer happen when issuing an AOFSHRINK command. 

I'm still working on the autoshrink method, but I wanted to get this done first.

Thanks for your patience.

**Comment by huangpeizhi** [comment]
@tidwall 
thanks!

![image](https://cloud.githubusercontent.com/assets/19602075/20913173/88ca495a-bbb0-11e6-85e3-74beade3f3a3.png)

I have configured AOFSHRINK command in CRONTAB , cleaned every hour AOF log, thank you so much for your help！

**Comment by tidwall** [comment]
That's great to hear! Let me know if you run into any problems and thanks a ton for your help.

**Comment by tidwall** [comment]
I'm closing this issue for now. Feel free to reopen if see any further issues.
