### ISSUE TITLE
Invalid JSON created when setting a field to a string value like '000296'. 

### ISSUE THREAD

**Issue by Kilowhisky** [tidwall/tile38#736]
**Describe the bug**
When the OUTPUT is set to JSON and a field was set to a string value like `'000296'`. The tile38 serializer will automatically convert the field into a number and try and output `000296`. This is invalid json though because you cannot have leading 0's in numbers according to the JSON spec. This creates errors with many of the client libraries that utilize `JSON.parse()` (i'm using tile38-ts). 

**To Reproduce**
1. Set output to JSON
2. Set a field to a value of `'000296'`
3. Get the record
4. See that it converted the field to a numerical field with leading zeros.

**Expected behavior**
Strip leading zeros when converting it to a number?

**Logs**

```Tile38Error: Unexpected number in JSON at position 14454```
![image](https://github.com/tidwall/tile38/assets/7075666/9097c26f-0035-4f69-a257-c51682bc67a0)

**Operating System (please complete the following information):**
 - OS: AWS ECS
 - CPU: ???
 - Version: 1.30.2
 - Container: ECS

**Additional context**
I can fix in insertion handler, but invalid JSON should not be created either way...

**Comment by Kilowhisky** [comment]
So this is tied to this issue: https://github.com/tidwall/tile38/issues/719
Turns out, that field is supposed to be "vehicle name". The vehicle just happens to be called '000296'...  

So i'm not sure how to fix this besides moving the "vehicle name" property to under the "properties" object. But i'm not sure if i can do that as that object is currently inserted as a POINT and performance is critical. 

Thoughts?

**Comment by Kilowhisky** [comment]
I'm just going to prepend the field value with `vn:<name>`. Its a hack, but it works.

**Comment by Kilowhisky** [comment]
Turns out `_` is also a valid number character for Go but not for JSON....

![image](https://github.com/tidwall/tile38/assets/7075666/fa77b457-34c3-4732-bfb8-b913cb0d8d3f)

**Comment by tidwall** [comment]
I just pushed an update that will ensure that a numeric field value conforms to JSON.
