### ISSUE TITLE
FSET transforms field names to lowercase

### ISSUE THREAD

**Issue by unendingblue** [tidwall/tile38#741]
**Describe the bug**
The command `FSET` transforms any given field name to lowercase.
`SET`ing a key with fields that have mixed or uppercase names works correctly.

**To Reproduce**
Set an arbitrary key with an uppercase field
`SET user 1 FIELD TEST 123 POINT 90 90`

Get the key
`GET user 1 WITHFIELDS`

> Response
> `{"ok":true,"object":{"type":"Point","coordinates":[90,90]},"fields":{"TEST":123},"elapsed":"19.744µs"}`

Set the field to a new value
`FSET user 1 TEST 987`

Get the key again
`GET user 1 WITHFIELDS`

> Response
> `{"ok":true,"object":{"type":"Point","coordinates":[90,90]},"fields":{"TEST":123,"test":987},"elapsed":"16.374µs"}`

Observe that we now have a new field named "test", instead of the original "TEST" field being updated.

**Expected behavior**
`FSET` should retain the field name's letter casing.

**Additional context**
I don't have experience in Go, but my initial assumption is that the culprit logic is likely this:
https://github.com/tidwall/tile38/blob/51e686279795c608f94f8e8f57443713701694db/internal/server/crud.go#L843-L860

Instead of calling ToLower on 844, it should be called directly on the switched value at 845, similar to how `SET` works.

**Comment by iwpnd** [comment]
Good catch. Can confirm. 👍

**Comment by iwpnd** [comment]
Can also confirm. Let's see whats going on with `wherein` :eyes:

**Comment by tidwall** [comment]
@iwpnd yes please take a look. I don’t recall this being the intended behavior.

**Comment by iwpnd** [comment]
#742 and #743 should resolve this now @tidwall

**Comment by tidwall** [comment]
Ok, I'll review asap.

**Comment by tidwall** [comment]
Fixed and merged!
