### ISSUE TITLE
NOFIELDS doesn't seem to work

### ISSUE THREAD

**Issue by Yugloocamai** [tidwall/tile38#75]
Using tip of master, passing NOFIELDS has no effect.  It always returns all fields.

"SCAN [key] NOFIELDS" returns complete json objects

"NEARBY [key] NOFIELDS POINT 34.018161 -118.278846 10000" also returns complete objects

Perhaps I'm misunderstanding what NOFIELDS is intended to do, but adding or removing NOFIELDS does not change the response payload in any way.

**Comment by tidwall** [comment]
Hi @Yugloocamai, 

The NOFIELDS keyword only works with the fields that where defined using [FSET](http://tile38.com/commands/fset) or [FIELD](http://tile38.com/commands/set/#fields).

Perhaps the IDS keyword is what you are looking for:

```
SCAN key IDS
NEARBY key IDS POINT 34.018161 -118.278846 10000
```
Which returns only the object IDs, the objects are omitted.

**Comment by tidwall** [comment]
@Yugloocamai Let me know if you need further help and thank for your interest in Tile38.
