### ISSUE TITLE
About search and scan

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#76]
Hi,
I found a bug,for example,"http://localhost:9851/set+fleet+truck+string+"1234567890"",
then, I use the "search" query:"http://localhost:9851/search+fleet+match+ * 2 * ", It failed.
By the same token, the “scan“ method.
Look forward to your reply.
Thanks

**Comment by icewukong** [comment]
It seems that the conditions behind the match can't start with a * .
