### ISSUE TITLE
Question: Is it possible to list the names of each collection in an index?

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/tile38#78]
I have a bad habit, particularly during development and debugging, of giving collections names that I then immediately forget.

I have poked around and it's possible to list the names of all the collections in an index the "how" of doing so eludes me.

**Comment by tidwall** [comment]
The command is [KEYS](http://tile38.com/commands/keys/). 

```
KEYS *
```

Will return all collections.

The docs are confusing because collections are sometimes called keys, and objects are sometimes called ids. This is something that I want to clear up at some point.

**Comment by thisisaaronland** [comment]
Perfect, thanks!
