### ISSUE TITLE
GeoJson size

### ISSUE THREAD

**Issue by DefunctExodus** [tidwall/tile38#8]
First let me say this is a very cool project, specifically the geo fencing.

I have not had a ton of time to play around with this let so I figured I may as well just ask, is there a limit to the size of the geojson you support?

I ask this because one of my files is about 200mb give or take.

Thanks

**Comment by tidwall** [comment]
Thanks for the kind words.

The geojson limit is 4GB. But after looking at the code, there is apparently a 16MB limit to the size of a message that can be received by the server. Which actually seems really small. I'll fix this and push an update.
