### ISSUE TITLE
Question: replication

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/tile38#80]
A couple questions about replication:

* Is it possible to determine whether a given is a leader or a follower from one of the "server" commands? If it is I can't seem to figure out how.

* Will a machine follower-iness persist across Tile38 restarts or does it need to told each time?

Thanks,

**Comment by tidwall** [comment]
> Is it possible to determine whether a given is a leader or a follower from one of the "server" commands?

It is always assumed that server is a leader unless the `following` field from the [SERVER](http://tile38.com/commands/server/) command is specified. Also you can check the state of the AOF replication by checking the `caught_up` field on the follower. Finally the `read_only` field will be set to `true` for followers.

- following: When in follow mode, this is the address of the leader.
- caught_up: When in follow mode, this indicates if the server has the same data as the leader.
- read_only: Is true when the server is in readonly mode.

> Will a machine follower-iness persist across Tile38 restarts or does it need to told each time?

Yes. When a server is designated as a follower, that server will continue to follow the leader even after the follower or leader servers are restarted.

**Comment by thisisaaronland** [comment]
Great, thanks!

**Comment by tidwall** [comment]
You're welcome :)
