### ISSUE TITLE
Can tile38 add the cross domain access support ?

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#81]
Because tile38 runs in a independent container, I would like to directly access tile38 in web project, this will appear across the domain problem.

**Comment by tidwall** [comment]
You will need to use the [Websockets](http://tile38.com/topics/network-protocols#websockets) interface or to put it behind a project like [JSONP](https://en.wikipedia.org/wiki/JSONP#Cross-domain_requests_using_a_proxy_server).

**Comment by icewukong** [comment]
thx!

**Comment by tidwall** [comment]
You're welcome!
