### ISSUE TITLE
The precise search

### ISSUE THREAD

**Issue by GameFreedom** [tidwall/tile38#82]
Hi,
For example,
localhost:9851/set+terminal+truck+string+123
I use the 'search' 'approach to precise search：localhost:9851/search+terminal+match+123.
Returns the result is empty.Only when using the '*' number have a result

**Comment by tidwall** [comment]
Thanks for reporting this issue. I pushed a fix to the master branch.

**Comment by GameFreedom** [comment]
Hi,
Now,i find a problem.First,our total data volume is 55 million
1.‘*’ in front .For example, search+A+match+*123,time consuming 30s,it's too slow.
2.Three concurrent queries,CPU with 16 core reach 100 percen

**Comment by tidwall** [comment]
When a pattern begins with a star the entire collection will be scanned. The operation is O(n). 

```sh
*123
```
Starts at the first value and scans all 55 million for matches.

```sh
f*123
```
Jumps to the first value that starts with "f" and scans items for matches. It stops searching upon encountering a value that does not start with "f".

I advise against using the star prefix for huge collections.
