### ISSUE TITLE
Coordinate cross-border judgment

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#83]
I send tile38 coordinates of a cross-border, for example:

`SET fleet truck1 POINT 95.5123 -191.2693 245.0`

Service will not respond. Whether there should be a wrong protection, if I sent out the coordinates, service returns an error.

 I am not sure whether this method is suitable that Tile38 check the coordinates when receiving data.
But  it cannot hinder other operations at least

**Comment by umpc** [comment]
Hi. What is the version of Tile38 that you're using and how are you connecting to the server?

I tried this on [master](https://github.com/tidwall/tile38/tree/master) and I was able to use the included CLI to add the point and then look for it:

```
127.0.0.1:9851> SET fleet truck1 POINT 95.5123 -191.2693 245.0
{"ok":true,"elapsed":"9.407909ms"}
127.0.0.1:9851> get fleet truck1
{"ok":true,"object":{"type":"Point","coordinates":[-191.2693,95.5123,245]},"elapsed":"6.311116ms"}
127.0.0.1:9851> nearby fleet point 95 -190 16000
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"944.819µs"}
127.0.0.1:9851> nearby fleet point 95 -190 64000
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"138.622µs"}
127.0.0.1:9851> nearby fleet point 95 -190 640000
{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"114.656µs"}
127.0.0.1:9851> nearby fleet point 95 -190 6400000
{"ok":true,"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-191.2693,95.5123,245]}}],"count":1,"cursor":0,"elapsed":"792.9µs"}
```

**Comment by icewukong** [comment]
v1.5.2.
I am sorry, I made a mistake, my coordinates are 1.3e98, cause the service no response.
With the increase in the number of coordinates, the time of service impact will be more and more slow, and ultimately will not be able to respond.

In order to avoid this problem, what do you suggest?

**Comment by umpc** [comment]
I can confirm that using ```SET``` with coordinates in scientific notation does hang the server, but isn't hanging inserts or nearby queries in the collection package itself.

I suggest filtering input to only allow valid parameters according to your application's requirements to be used in index queries. That logic goes for any system that accepts untrusted user input.

**Comment by icewukong** [comment]
Thank you for reply！

**Comment by tidwall** [comment]
I pushed a fix that should address this problem with regards to points. 

This issue is a bit more [complicated](https://github.com/tidwall/tile38/blob/master/index/norm.go#L55-L74) for rectangles and as of right now the slowness still exists.
