### ISSUE TITLE
bogus hook endpoint causes server to hang on roaming geofence

### ISSUE THREAD

**Issue by tomquas** [tidwall/tile38#84]
hi, i think i came across an issue which causes the server to hang for good.

Tile38 version 1.5.2, git a38228c on Ubuntu 14.04.5 LTS, Trusty Tahr

i tried to replay the roaming geofences example from http://tile38.com/topics/roaming-geofences/, and this is what happened, from the logs of tile38-cli:

127.0.0.1:9851> sethook myhook https://127.0.0.1/hook nearby people fence roam people * 5000
{"ok":true,"elapsed":"61.198µs"}
127.0.0.1:9851> hooks *
{"ok":true,"hooks":[{"name":"myhook","key":"people","endpoints":["https://127.0.0.1/hook"],"command":["nearby","people","fence","roam","people","*","5000"]},{"name":"sp","key":"fleet","endpoints":["https://127.0.0.1/api/sp/callback"],"command":["NEARBY","fleet","FENCE","detect","inside","POINT","33.5123","-112.2693","5000"]}],"elapsed":"45.109µs"}
127.0.0.1:9851> SET people bob POINT 33.01 -115.01
<<<CLI hangs>>>
^C
trustyvm> tile38-cli
127.0.0.1:9851> delhook myhook
<<<CLI hangs>>>
^C

i had to restart the server before the cli became responsive again.

note: i tried another https endpoint with valid ssl certificate, but same result.

**Comment by tomquas** [comment]
just checked with freshly release 1.5.3, same issue

**Comment by tidwall** [comment]
Hi Tom, 

Thanks a bunch for reporting this. I just pushed a hotfix to the master branch. I'll publish a minor point release shortly.
