### ISSUE TITLE
grpc reconn trigger condition？

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#85]
thanks!

**Comment by tidwall** [comment]
Hi @huangpeizhi,

Could you provide detail on this issue?

**Comment by huangpeizhi** [comment]
sorry，
I look at the code described in the grpc.go， 
grpcExpiresAfter = time.Second * 30

I don't know the connection expires, when new messages, will re-establish the connection with the GPRC server？

thanks!

**Comment by huangpeizhi** [comment]
If 30 seconds is not sending data, GPRC connection is dropped?
If this is the case, can provide a heartbeat approach to maintaining connections?

**Comment by tidwall** [comment]
An idle connection to a grpc endpoint is closed after 30 seconds. A new connection is automatically established when a grpc message is sent to the endpoint. Tile38 handles the all connections is the background.
You should not need to add a heartbeat.

**Comment by huangpeizhi** [comment]
@tidwall , thanks!

**Comment by tidwall** [comment]
You're welcome. :)
