### ISSUE TITLE
Server() method in helper.go Problem

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#86]
hi, tidwall:

While i trying to get service status, call method Server() in  helper.go, Error occurs:
%s invalid character '\x00' looking for beginning of value
 %s invalid character '$' looking for beginning of value

why?

**Comment by tidwall** [comment]
I'll look into this. Would it be possible to provide the error message in its entirety?
Thanks for reporting.

**Comment by huangpeizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/19602075/20456436/aa75d03a-aeb1-11e6-9adf-a755ed521443.png)

![image](https://cloud.githubusercontent.com/assets/19602075/20456441/c8f70416-aeb1-11e6-803a-5a05b82c45fe.png)

Execute the following code will appear above the output problems.

**Comment by tidwall** [comment]
I would like to reproduce this error. Which client library are you using?

**Comment by huangpeizhi** [comment]
https://github.com/go-redis/redis

**Comment by tidwall** [comment]
Thanks for providing the example code. 

> While i trying to get service status, call method Server() in helper.go, Error occurs:
%s invalid character '\x00' looking for beginning of value
%s invalid character '$' looking for beginning of value

Do you know which line number this error is occurring on?

**Comment by huangpeizhi** [comment]
Before using this approach，
![image](https://cloud.githubusercontent.com/assets/19602075/20467851/150449f4-afca-11e6-90dc-1ecaa862649f.png)

Errors caused by m.statTs().
```
func (m *Metrics) Json() string {
	m.statDCL()
	//m.statTS()   

	bs, err := json.MarshalIndent(m, "", "    ")
	if err != nil {
		return err.Error()
	}
	return string(bs)
}

func (m *Metrics) statTS() {
	var err error
	for i, s := range m.s.tile38Conns {
		m.TS[i], err = s.Server()
		if err != nil {
			glog.Warningf("execute tile38 ServerStats failure, %s", err.Error())
		}
	}
}
```

**Comment by tidwall** [comment]
Thanks. This is helpful. I'll try to fix is asap.

**Comment by tidwall** [comment]
I'm unable to reproduce this error. 

One thing to note is that the `github.com/tidwall/tile38/client.Conn` object is not thread safe. I noticed that you are creating a connection in the `initTile38()` function, and then using the connection in both a goroutine and in a the `statTS()` function. It's possible that the read data is being corrupted. If so, this would lead to problem that you are seeing.

I recommend switching to a client library like [redigo](https://github.com/garyburd/redigo), which handles [connection pooling inside goroutines](https://godoc.org/github.com/garyburd/redigo/redis#Pool) very well.

The only caveat is that; if you want to have JSON output, you must include the `OUTPUT JSON` command right away.

**Comment by huangpeizhi** [comment]
@tidwall ， 
Thanks,  Looks like this causes， i changed REDIS use libraries.
