### ISSUE TITLE
Recommendations of the fencing event

### ISSUE THREAD

**Issue by huangpeizhi** [tidwall/tile38#87]
Hi, @tidwall 

In the fencing event, each ENTER and EXIT are belong to the same group, you can consider adding a unique identity in the event of recognition?
This can be avoided, while many fences ENTER/EXIT after the information storage, sorted in order to know each Member of the Group

thanks!

huangpeizhi

**Comment by tidwall** [comment]
> In the fencing event, each ENTER and EXIT are belong to the same group, you can consider adding a unique identity in the event of recognition?

I can add a unique event_id for every such as:

```json
{
  "command":"set",
  "detect":"enter",
  "key":"fleet",
  "id":"bus1",
  "event_id":"8aa68be86f92512a0d7c6804",
  ...
}
```
Would this be helpful?

**Comment by huangpeizhi** [comment]
I want is a set of events that are associated with the identification , in determining the entity in and out of the fence, the ENTER/EXIT event is associated.

![image](https://cloud.githubusercontent.com/assets/19602075/20587205/9b579ea6-b246-11e6-9e0f-97c1a0b23adf.png)

**Comment by huangpeizhi** [comment]
what is it combined of event_id?

**Comment by huangpeizhi** [comment]
what is it combined of event_id?

**Comment by tidwall** [comment]
Sorry for the delayed response. 

I think I understand now. So you would like to have your messages grouped by the "enter"/"exit" events?

Perhaps something like this:

```
{"group_id":"8aa68be86f92","key":"fleet","id":"bus1","detect":"enter",...}
{"group_id":"8aa68be86f92","key":"fleet","id":"bus1","detect":"inside",...}
{"group_id":"8aa68be86f92","key":"fleet","id":"bus1","detect":"inside",...}
{"group_id":"8aa68be86f92","key":"fleet","id":"bus1","detect":"exit",...}

{"group_id":"75a3ef68cc15","key":"fleet","id":"bus1","detect":"enter",...}
{"group_id":"75a3ef68cc15","key":"fleet","id":"bus1","detect":"inside",...}
{"group_id":"75a3ef68cc15","key":"fleet","id":"bus1","detect":"inside",...}
{"group_id":"75a3ef68cc15","key":"fleet","id":"bus1","detect":"exit",...}
```

This is a good idea and I think that it's possible, but I'll need to dig a little deeper before making promises.

**Comment by huangpeizhi** [comment]
Yes, it is.
Because, in practice, many in/out is does not meet the requirements and need to remove certain conditions.

-:)

**Comment by huangpeizhi** [comment]
Hi, @tidwall

Note the same machine multiple tile38 process，tile38 can't produce the same group_id，can refer to mongodb objectid.

**Comment by tidwall** [comment]
I just pushed a build to master that groups with the key "group" and uses the BSON ObjectID format.

Let me know if this works for you.

**Comment by huangpeizhi** [comment]
@tidwall,

Thank you very much, I've put the GROUPID in database, inspection data. 
![image](https://cloud.githubusercontent.com/assets/19602075/20962462/55a347d0-bca4-11e6-9db3-6080965576ce.png)

**Comment by tidwall** [comment]
That's great to hear. Let me know if there's anything you need.

**Comment by huangpeizhi** [comment]
@tidwall ,
Running one day, no problem, i close the issue, if problems are found, then reopen.

thanks!
