### ISSUE TITLE
Secure HTTP Endpoints // Make RESTFUL // CSRF

### ISSUE THREAD

**Issue by Miserlou** [tidwall/tile38#89]
It looks like tile38 is vulnerable to command injection via the browser, as modifications to the database happen over GET rather than POST requests. For example, I can add an iframe to a page with src `localhost:9851/set+fleet+truck3+point+33.4762+-112.10923` and modify the database. This leaves all developers and operators who use tile38 open to a nasty attack. (Related examples: http://bouk.co/blog/hacking-developers/)

I suggest you a) make the API RESTful so that modifications only happen on POST, and b) make sure that the API only accepts requests from the same origin as the calling page along with a CSRF token.

**Comment by tidwall** [comment]
Hi Rich, 

Thanks for the suggestions and for providing the link.

I totally agree with you. I've been intending on deprecating the RESTful APIs in the 2.0 release, but I think this may be cause for doing it sooner.

**Comment by tidwall** [comment]
I have a fix on the roadmap, so I'm closing this issue for now. Please feel free to reopen if you have any question or concerns. Thanks a ton for your help.

**Comment by kirantpatil** [comment]
Hi @Miserlou,

May I know, currently how are you securing the HTTP endpoints ?

Thanks.
