### ISSUE TITLE
Need an example for Websockets

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#90]
Hi,tidwall
When we use the mobile terminal to access the tile38, in a large loop at the same time sent tens of thousands of HTTP requests, TCP tile38 connection is exhausted. 
I would like to use WebSockets to send these requests, so that I can only build one TCP connection to send these http requests. 
Can you give an example of a WebSockets request to be sent through curl?

**Comment by icewukong** [comment]
```
package main

import (
	"fmt"
	"log"

	"golang.org/x/net/websocket"
)

var origin = "http://localhost:9851/"
var url = "ws://localhost:9851/search"

func main() {
	ws, err := websocket.Dial(url, "", origin)
	if err != nil {
		log.Fatal(err)
	}
	message := []byte("+test")
	_, err = ws.Write(message)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Send: %s\n", message)

	var msg = make([]byte, 512)
	m, err := ws.Read(msg)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Receive: %s\n", msg[:m])

	ws.Close() //close connection
}
```
I get the output:
```
Send: +test
Receive: {"ok":false,"err":"invalid number of arguments","elapsed":"0s"}
```
What is the correct parameter?

**Comment by icewukong** [comment]
Only the complete command written to the URL can get the correct results.
`var url = "ws://localhost:9851/get+test+11"`
output：
`Receive: {"ok":true,"object":"22","elapsed":"0s"}`

But each command requires the establishment of a websocket connection, and can not reuse the connection.

**Comment by tidwall** [comment]
Hi @icewukong,

I don't recommend using Tile38 and Websockets. I'm deprecating HTTP and Websocket clients in a future release.

Please use a Redis-compatible library such as [Redigo](https://github.com/garyburd/redigo).

**Comment by icewukong** [comment]
I get it and suggest retain HTTP support！

**Comment by icewukong** [comment]
Hi,@tidwall,

I write a websocket server with golang,and use tile38 client's connection pool to send data with tile38 to solve connection depletion problem.

Thanks your suggestion ！

**Comment by icewukong** [comment]
By the way,about autoshrink AOF,I suggest that you can set a switch to close autoshrink,because I had used characteristics of AOF to realize finding incremental database for a period of time.

If autoshrink can't close,after the new version is updated, the already deployed program of mine will not be able to use again!

**Comment by tidwall** [comment]
> I get it and suggest retain HTTP support！

I understand that HTTP support is very useful for cURL users. I won't remove HTTP and Websocket support completely. I just don't recommend using it and in the future I'm going to require a flag at startup such as:

```
$ tile38-server --http-transport-enabled
```

**Comment by tidwall** [comment]
> By the way,about autoshrink AOF,I suggest that you can set a switch to close autoshrink,because I had used characteristics of AOF to realize finding incremental database for a period of time.

Good point, I'll make sure to have config options to adjust frequency or disable the feature.

references #74

**Comment by icewukong** [comment]
Thank you for your project to give me a lot of help.

**Comment by tidwall** [comment]
You're welcome. I greatly appreciate all of your feedback.

**Comment by juanpabloaj** [comment]
@icewukong another simple example with websockets in browser

Add `truck` in `tile38-cli`

```
set fleet truck1 point 33.5123 -112.2693
```

``` html
<html>
  <head>
    <meta charset="utf-8">
    <title>index</title>
  </head>
  <body>
    <script src="js/socket.js" type="text/javascript" charset="utf-8"></script>
  </body>
</html>
```

``` javascript
var socket = new WebSocket("ws://localhost:9851/scan+fleet");

socket.onmessage = function(event) {
  console.log(event.data);
};

socket.onerror = function(event) {
  console.log(event.data);
}
```

with this you get this output in the browser console

`{"ok":true,"objects":[{"id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]}}],"count":1,"cursor":0,"elapsed":"106.644µs"}`

**Comment by icewukong** [comment]
@juanpabloaj 
Thank your reply,I mean, this way does not play the advantages of websocket,because each command will create a new connection.
My solution is : deploy a websocket server connection service,then web terminal connect this server through the websocket protocol, the service through the connection pool to access tile38, the advantage of this is that multiple commands can establish a TCP connection only.

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if needed. 

Thank you!
