### ISSUE TITLE
CirclePolygon function wrong winding order

### ISSUE THREAD

**Issue by antonioromano** [tidwall/tile38#91]
The polygon returned by the method has winding clockwise, while it should be counterclockwise for any external linear ring in polygons.
Are you sure your is the right behavior?

https://github.com/tidwall/tile38/blob/master/geojson/object.go#L429

**Comment by tidwall** [comment]
You are right. I'll switch it over to ccw order and poke around a bit.

Are you running into an issue related to this with Tile38 or are you using the GeoJSON library externally?

**Comment by antonioromano** [comment]
Both, but we run into the issue using it as a library. I think that is one of the most complete geoJson library for golang.
Thank you very much

**Comment by antonioromano** [comment]
You can fix it by computing the angles counterclockwise, for example like this (line 439):

`for deg := 360.0; deg > 0; deg -= step`

**Comment by tidwall** [comment]
Good tip thanks! I just pushed a fix. Let me know if this works for you.
