### ISSUE TITLE
Deprecate HTTP and Websocket Support

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#92]
For security reasons (#89) I believe that support for HTTP and Websockets should be deprecated. We won't completely remove support, but Tile38 will require a flag at start up such as:

```
$ tile38-server --enable-http-transport
```

reference #89 #90

**Comment by tidwall** [comment]
This should target 2.0 release so we don't break 1.0. Until then, perhaps we should add the `--disable-http-transport` for 1.0.

**Comment by tidwall** [comment]
Perhaps the flag is --http-transport is a better name for the flag. Just a Boolean. It's true by default, at least for version 1.X.

**Comment by m1ome** [comment]
I will do this for 1.* and we can port this to 2.0 when time comes, just switching condition and flag name.

**Comment by tidwall** [comment]
@m1ome thanks for helping with this.

**Comment by m1ome** [comment]
@tidwall you are welcome!

**Comment by john-bonachon** [comment]
if websockets is deprecated, how should we use a Redis client to persist a connection and receive new messages? as far as I know, all clients can send raw RESP commands, but they usually returns response "OK", will you include examples for node_redis or redis-py in the wiki?

**Comment by john-bonachon** [comment]
Ok, seems like a solution would be to use tile38's SETHOOK command, and for example set a redis endpoint which will be put in a PubSub queue. Then it would be possible to subscribe to that queue. 

From a webapp perspective, wouldn't this dance add some overhead or performance issues?
[Tile38 hooks <-> Websocket server (running redis pubsub)] <-> Websocket webclient
