### ISSUE TITLE
Batch SET via http

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#94]
The the I am trying to do is to make batch of commands like
`SET boundies ca_bounds_poly.23197 OBJECT {"type":"MultiPolygon","coordinates":[[[[-122.2823,37.8721],[-122.2733,37.8733],[-122.2731,37.8715],[-122.282,37.8704],[-122.2823,37.8721]]]]}
`
 ... and send them via http interface (<30K lines ~ 12MB)
As the result I get an error:
`{"ok":false,"err":"invalid character 'S' after top-level value","elapsed":"4.383065ms"}`

When I revert to a single mode (1 post = 1 SET) - data is inserted without problem (ignoring performance, for sure)

**Comment by tidwall** [comment]
HTTP is not the best protocol for mass insertion. I don't think the Tile38 HTTP implementation supports more than one command per request. Sounds like this is too slow for your use case.

The other option is use the Redis protocol, which is what Tile38 uses natively. Every command is formatted like:
```
*<args><cr><lf>
$<len><cr><lf>
<arg0><cr><lf>
<arg1><cr><lf>
...
<argN><cr><lf>
```

So the command:

```
SET boundies ca_bounds_poly.23197 OBJECT {"type":"MultiPolygon","coordinates":[[[[-122.2823,37.8721],[-122.2733,37.8733],[-122.2731,37.8715],[-122.282,37.8704],[-122.2823,37.8721]]]]}
```

would look like:

```
*5
$3
SET
$8
boundies
$20
ca_bounds_poly.23197
$6
OBJECT
$142
{"type":"MultiPolygon","coordinates":[[[[-122.2823,37.8721],[-122.2733,37.8733],[-122.2731,37.8715],[-122.282,37.8704],[-122.2823,37.8721]]]]}
```

Each line ending must be `<cr><lf>`.

For more information see https://redis.io/topics/mass-insert

**Comment by amorskoy** [comment]
Thanks @tidwall 
I will try to master method mentioned. I want to avoid lowe level Redis TCP socket usage - but now I got direction. 
Thanks

**Comment by jchamberlain** [comment]
I know this is an old issue, but what's the recommended CLI way of using RESP? I don't see a `--pipe` option in `tile38-cli`, and `redis-cli` just says "Error reading replies from server" when I try piping to Tile38.
