### ISSUE TITLE
Contributing with Jetbrains IDE

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#97]
Seems to be too stupid question, but, anyway...
I was able to build Tile38 Go project and run it.

Now my target is run Debug in IntelliJ Idea with Go plugin. 
Despite different FAQ's on this topic present, I was not able to run Tile38 server's main.go via IDE:

"go get" was performed to retrieve exteral imports into GOPATH (/var/www/GO/deps)

Here is IDE's output in run and debug (same):

`GOROOT=/opt/go
GOPATH=/opt/go:/var/www/GO/deps
/opt/go/bin/go build -o "/tmp/Server Appgo" /var/www/GO/tile38/cmd/tile38-server/main.go
# command-line-arguments
cmd/tile38-server/main.go:81: cannot use s (type *"google.golang.org/grpc".Server) as type *"github.com/tidwall/tile38/vendor/google.golang.org/grpc".Server in argument to hservice.RegisterHookServiceServer
cmd/tile38-server/main.go:81: cannot use hserver literal (type *hserver) as type hservice.HookServiceServer in argument to hservice.RegisterHookServiceServer:
	*hserver does not implement hservice.HookServiceServer (wrong type for Send method)
		have Send("golang.org/x/net/context".Context, *hservice.MessageRequest) (*hservice.MessageReply, error)
		want Send("github.com/tidwall/tile38/vendor/golang.org/x/net/context".Context, *hservice.MessageRequest) (*hservice.MessageReply, error)`

**Comment by tidwall** [comment]
Hi @amorskoy,

Strange. Tile38 is completely vendored so it shouldn't be looking for external dependencies.

I think it's generally not advised to have the GOROOT in the GOPATH. What happens if you remove the `/opt/go` from GOPATH? Such as:

```
GOPATH=/var/www/GO/deps
```

**Comment by amorskoy** [comment]
Hi @tidwall 
I was able to run Debug under IntelliJ Ide, but for that purpose I had to reorganize an IDE project a little bit:

`mkdir Tile38Project/src/github.com/tidwall
 cd Tile38Project/src/github.com/tidwall
git clone https://github.com/amorskoy/tile38
`

And then I have imported Tile38Project dir as Go project, removed GOROOT from libs, add Tile38Project as the only library dir.

Now I am able to debug, life will go easier

**Comment by tidwall** [comment]
Very cool. I think I'll give it a spin to see how the debugging works.
