### ISSUE TITLE
JSET, JGET, JDEL commands does not work

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#98]
Hi,@tidwall
Whether these commands have been completed?
I tested it, found that the data has not been written to the AOF file, the data can not be queried out.
JSET, JGET, JDEL commands support geojson? I mean, if this can deal with the geometry and attribute data in geojson, respectively?

**Comment by tidwall** [comment]
> I tested it, found that the data has not been written to the AOF file, the data can not be queried out.

Thanks for finding this bug. I pushed a fix to the master branch.

> Whether these commands have been completed?

The commands are very new and they're intended to manage user-defined JSON documents. They are complete and should be ready to use.

> JSET, JGET, JDEL commands support geojson? I mean, if this can deal with the geometry and attribute data in geojson, respectively?

Yes. But it's important to note that while JSET and JDEL can be used to modify an existing geojson object value, the `SET` and `DEL` should be used to create new objects or delete existing ones. JGET can be used to query any object type, geojson or user-defined json.

For example (using redis-cli):

```
> SET fleet truck1 POINT 33 -115
OK
> JGET fleet truck1 coordinates
"[-115,33]"
```

JSET can be used to set a value of an existing geojson object:

```
> SET fleet truck1 POINT 33 -115
OK
> JSET fleet truck1 coordinates.1 33.5
OK
> JGET fleet truck1 coordinates
"[-115,33.5]"
```

Hope this information helps. Please let me know if you have any further questions. I appreciate any feedback you can provide.

**Comment by icewukong** [comment]
Expect:
```
  JSET user 901 name Tom
  JGET user 901
  > '{"name":"Tom"}'
```
Although the data is written to the aof, JGET command did not query out the results:
`{"ok":true,"value":"","elapsed":"0s"}`

**Comment by tidwall** [comment]
Thanks. I just pushed a fix.

**Comment by icewukong** [comment]
Support search command？
I mean, like "where clause", query in a KEY.

**Comment by tidwall** [comment]
At the moment there's only the ability to query one document value at a time. But I plan on adding full indexes and searching like SummitDB https://github.com/tidwall/summitdb#json-documents

**Comment by icewukong** [comment]
That would be wonderful   :)
