### ISSUE TITLE
SETHOOK and DEL event

### ISSUE THREAD

**Issue by amorskoy** [tidwall/tile38#99]
I believe, that it would be nice idea to have event subscription mask setup during **SETHOOK**

Currently **del**, **drop** and **set** events causes hook to fire.

In my case I am using ~20000 web hooks, and **del** is not interested. Moreover, it produce unneccessary traffic to endpoint.

I would be nice to specify that 'set' is the only interesting event during **SETHOOK** declaration

**Comment by tidwall** [comment]
Sure, this is doable.

**Comment by tidwall** [comment]
I just pushed an update that adds the `COMMANDS` keyword. It works like the `DETECT` keyword.

```
NEARBY fleet FENCE COMMANDS set,del POINT 33 -115 10000
```

Will only send **set** and **del** commands. 

```
NEARBY fleet FENCE COMMANDS set POINT 33 -115 10000
```

Will only send **set** commands. 

When the COMMANDS keyword is not provided, all notifications are sent.

Let me know if this works for you.

**Comment by amorskoy** [comment]
Nice job @tidwall  - thanks - It will be super useful for my Tile38 demo tomorrow.
Hope to join your dev process soon

**Comment by tidwall** [comment]
That's great to hear! Thanks a bunch for your help and good luck with tomorrow's demo.
